### PR TITLE
Add BaseHMC kwargs to nuts

### LINKED ISSUE #1940: Nuts doc string is incomplete

### PR DESCRIPTION
**Pull request by aseyboldt**
Fixes #1940.

### CODE REVIEW

**Comment by twiecki** [comment]
While we're at it, might want to add the appropriate ones to `HamiltonianMC` as well.

**Comment by aseyboldt** [comment]
done

**Comment by twiecki** [comment]
Thanks!

**Comment by rahuldave** [comment]
Thanks for this! Will make understanding the NUTS sampler args much easier for my students!

**Comment by twiecki** [comment]
Kinda unfortunate that the doc-string is not displayed correctly in sphinx: http://pymc-devs.github.io/pymc3/api.html#pymc3.step_methods.hmc.nuts.NUTS

**Comment by aseyboldt** [comment]
Looks like the docstring of `__init__` doesn't show up I'll have a look tomorrow (and maybe check the relevant pep about what should go where). The doc for `LKJCholeskyCov` seems to be a bit messed up, too.

**Pull request merged**
