### PR TITLE
Changed PytTensor import alias to pt in PyMC overview

### LINKED ISSUE #7411: Include README example in docs homepage
### Description

https://github.com/pymc-devs/pymc?tab=readme-ov-file#linear-regression-example

⬇️

https://www.pymc.io/projects/docs/en/stable/learn.html

### PR DESCRIPTION
**Pull request by Krupakar-Reddy-S**
## Related Issue

- [x] Closes #7411 
- [x] Related to #7446 

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7452.org.readthedocs.build/en/7452/

### CODE REVIEW

**Comment by Krupakar-Reddy-S** [comment]
@twiecki I have made the changes in one commit, but still the diff is too large :(

**Comment by twiecki** [comment]
> @twiecki I have made the changes in one commit, but still the diff is too large :(

Yeah I think you need to start fresh. make a new branch from main, make that one change, and submit a new PR and abandon this branch.

**Comment by Krupakar-Reddy-S** [comment]
I have done that, I deleted the branch made a new one from main but with the same name

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
OK it's probably fine.

**Comment by twiecki** [comment]
Thanks!

**Pull request merged**
