### PR TITLE
Vonmises moments

### PR DESCRIPTION
**Pull request by Domenico89**
Add moments and tests for the below distributions as part of #5078:
-pymc.distributions.continuous.VonMises

### CODE REVIEW

**Comment by Domenico89** [comment]
The curren tests should work fine, but if I use np.arange(5) as mu in line 446 ,f or example, I get as a result array([ 0.,  1., 2.,  3., -2.28318531]), which is not what I would expect. I couldn't figure out where -2.2831853 is coming from. Other strange numbers appear when I run the test for np.arange(k) with k>4.

**Comment by ricardoV94** [comment]
> The curren tests should work fine, but if I use np.arange(5) as mu in line 446 ,f or example, I get as a result array([ 0., 1., 2., 3., -2.28318531]), which is not what I would expect. I couldn't figure out where -2.2831853 is coming from. Other strange numbers appear when I run the test for np.arange(k) with k>4.

Seems like it is just mirroring around `+-np.pi`? Are you testing the moment with a transformed distribution?

**Comment by ricardoV94** [comment]
All tests are passing except for a pre-commit issue. I added a commit fix it with the bot, so make sure to merge from here if you want to do anything with this branch.

I guess you were seeing the effects of the CircularTransform?
```python
with pm.Model() as m:
  x = pm.Vonmises("x", np.arange(4))  
  y = pm.Vonmises("y", np.arange(4), transform=None)
```

The moment of `x` will by default be on the Circular scale, whereas that of `y` will not. We are testing with the second case, when we call this line:

https://github.com/pymc-devs/pymc/blob/1d337ca57d0fa348e67b73c05e7c678220c31612/pymc/tests/test_distributions_moments.py#L90

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Thanks @Domenico89, everything seemed to be working in our tests here.

Let me know if you find issues that need to be fixed or if my hunch above was correct.

**Comment by Domenico89** [comment]
> Thanks @Domenico89, everything seemed to be working in our tests here.
> 
> Let me know if you find issues that need to be fixed or if my hunch above was correct.


ah, ok. Sorry if took this long, I am new with the base code. Thanks for the hunch!

**Pull request merged**
