### PR TITLE
Bump PyTensor to 2.9.1

### PR DESCRIPTION
**Pull request by michaelosthege**
**What is this PR about?**
Updating to the latest PyTensor version, because I'm looking forward to a bugfix in the release after, and I want things to go smooth =)

After major complications due to (unnoticed) broken release pipelines on the PyTensor side, it appears that the upgrade actually was comparably smooth with only a minor typing issue.

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- Updated PyTensor 2.8.11→[2.9.1](https://github.com/pymc-devs/pytensor/releases/tag/rel-2.9.1)

## Maintenance
- Turned off `*.tar.bz2`-only installations because PyTensor 2.9.1 is no longer available from `.tar-bz2` artifacts. This _may_ break caching in GitHub Actions.

### CODE REVIEW

**Comment by michaelosthege** [comment]
image

**Comment by twiecki** [comment]
Also requires pre-commit (and rtd?)

**Comment by michaelosthege** [comment]
> Also requires pre-commit (and rtd?)

I did a Ctrl+H for 2.8.11..
Also checked again, but pre-commit config and rtd don't specify PyTensor versions 🙂

**Comment by twiecki** [comment]
> Updated PyTensor 2.8.11→[2.8.12](https://github.com/pymc-devs/pytensor/releases/tag/rel-2.8.12)

**Comment by michaelosthege** [comment]
We might be running into problems with our environment creation settings:
I can `mamba create -n pttest -c conda-forge pytensor=="2.9.1"` just fine locally, but in CI it says `nothing provides requested pytensor 2.9.1**` on all three OS.

The only difference w.r.t. 2.8.11 I can spot is that [2.8.11 was available as `*.tar.bz2` artifacts on conda-forge](https://anaconda.org/conda-forge/pytensor/files) but 2.9.1 is only available as `*.conda` artifacts.

IIRC there's something about the conda caching forcing us to install from `*.tar.bz2` artifacts; currently looking for the respective lines in the yamls...

**Review by twiecki — APPROVED** [review]

**Pull request merged**
