### PR TITLE
UserWarning if doing predictive sampling with models containing Potentials

### LINKED ISSUE #3865: Forward sampling functions should warn that they ignore Potential in a model
## Description of your problem
As discussed [here](https://discourse.pymc.io/t/how-to-limit-a-geometric-discrete-distribution-in-a-range/4537/8?u=alexandorra) with @junpenglao, it seems like `sample_posterior_predictive` cannot account for a `Potential` in a model with `Geometric` likelihood:
```python
with pm.Model() as m_bike:
    a = pm.Normal("a", 0.0, 0.5)
    bT = pm.Normal("bT", 0.0, 0.2)

    p = pm.math.invlogit(a + bT * bike_data["temp_std"])

    bike_count = pm.Geometric('bike_count', p, observed=bike_data["count"])
    pm.Potential('constraint', tt.switch(bike_count > 1100, -np.inf, 0.))

    trace_bike_poisson = pm.sample(1000, tune=2000, random_seed=RANDOM_SEED)
    post_samples = pm.sample_posterior_predictive(
        trace_bike_poisson, random_seed=RANDOM_SEED
    )

idata = az.from_pymc3(trace=trace_bike_poisson, posterior_predictive=post_samples)
az.plot_ppc(idata);
```
This samples perfectly, but the constraint was not applied to PP samples:
Capture d’écran 2020-03-10 à 21 27 48
The data come from Kaggle’s [bike-sharing demand](https://www.kaggle.com/c/bike-sharing-demand) contest.

## Versions and main components

* PyMC3 Version: Master
* Theano Version: 1.0.4
* Python Version: 3.7.6
* Operating system:OS X
* How did you install PyMC3: pip

### PR DESCRIPTION
**Pull request by ricardoV94**
As discussed in https://github.com/pymc-devs/pymc3/issues/3865

Do we want tests for the Warning?

### CODE REVIEW

**Review by michaelosthege — COMMENTED** [review]
Looks good! A simple test would be great.

**Review by AlexAndorra — APPROVED** [review]
Nice, thanks @ricardoV94 ! I agree with @michaelosthege that a simple test would be nice.
Also, this should probably be added to `fast_sample_posterior_predictive` too: https://github.com/pymc-devs/pymc3/blob/1769258e459e8f40aa8a56e0ac911aa99e7f67de/pymc3/distributions/posterior_predictive.py#L156

**Comment by ricardoV94** [comment]
> Nice, thanks @ricardoV94 ! I agree with @michaelosthege that a simple test would be nice.
> Also, this should probably be added to `fast_sample_posterior_predictive` too:
> 
> https://github.com/pymc-devs/pymc3/blob/1769258e459e8f40aa8a56e0ac911aa99e7f67de/pymc3/distributions/posterior_predictive.py#L156

Nice catch!

I added some tests, do you think they are an overkill?

**Review by michaelosthege — CHANGES_REQUESTED** [review]
The tests are overkill in the sense that they will add unnecessarily lots of runtime.
Instead of calling `pm.sample()` which will be a complete overkill in terms of compute, it would be better to use `az.InferenceData.from_dict` and manually create a "trace" using `numpy.random`.

**Comment by ricardoV94** [comment]
> The tests are overkill in the sense that they will add unnecessarily lots of runtime.
> Instead of calling `pm.sample()` which will be a complete overkill in terms of compute, it would be better to use `az.InferenceData.from_dict` and manually create a "trace" using `numpy.random`.

Agreed! By any chance, do you know if there is any test already doing something like this?

**Comment by michaelosthege** [comment]
> Agreed! By any chance, do you know if there is any test already doing something like this?

It doesn't looks like that's the case so far. Many tests probably _could_.

You can inspect the existing trace to find out which variables you'll need. Something along the lines of

```
for vname in trace.varnames:
    print(f"vname is shape {trace[vname].shape}")
    print(trace[vname])
```

**Comment by AlexAndorra** [comment]
I guess you can also take some cues from [ArviZ test suite](https://github.com/arviz-devs/arviz/tree/master/arviz/tests) -- we do stuff like that IIRC, and we also have built-in datasets

**Review by michaelosthege — APPROVED** [review]

**Review by AlexAndorra — APPROVED** [review]
All good, thanks @ricardoV94 🍾

**Comment by AlexAndorra** [comment]
BTW @ricardoV94, do you have an email address I can contact you on please?

**Comment by ricardoV94** [comment]
@AlexAndorra you can find my work email in this page: https://cognitivescience.ceu.edu/people/jose-vieira

**Pull request merged**
