### PR TITLE
More work on SMC

### PR DESCRIPTION
**Pull request by ColCarroll**
This is two incremental changes:
-- the `paripool` function is simplified
-- the `stage` argument used to be possibly an int, string, or `None`.  Now it is consistently an int.

### CODE REVIEW

**Comment by twiecki** [comment]
Looks like a great refactoring.

@hvasbath can you help review this?

**Comment by ColCarroll** [comment]
hacking away a few minutes a day -- happy for input, but I can ping hvasbath when I change the actual sampler for a review (`test_smc` and `test_step_exact` have been super helpful!)

Trying to factor out all the I/O into `smc_text.py` so that `smc.py` reads a little more cleanly.

**Comment by twiecki** [comment]
I looked over it and it looks fine, we can merge.

**Comment by hvasbath** [comment]
@ColCarroll thats a great idea of having -1 instead of final. Why didnt I think of it myself ...
I refactored the i/o part in the beat repo already there it is a function init_stage starting at line 542 in smc.py .
https://github.com/hvasbath/beat/blob/master/src/smc.py
If you want to have a look. I was not sure whether this would be good to have like this in pymc3 so we could simply use it as well like this if you prefer?

**Pull request merged**
