### PR TITLE
Add README example to docs

### LINKED ISSUE #7411: Include README example in docs homepage
### Description

https://github.com/pymc-devs/pymc?tab=readme-ov-file#linear-regression-example

⬇️

https://www.pymc.io/projects/docs/en/stable/learn.html

### PR DESCRIPTION
**Pull request by Krupakar-Reddy-S**
## Description
Added the example from pymc REAME.md to the pymc_overview notebook in learn section of docs as case study 0.

## Related Issue

- [x] Closes #7411 
- [x] Related to #7411

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7446.org.readthedocs.build/en/7446/

### CODE REVIEW

**Comment by Krupakar-Reddy-S** [comment]
image

After updating there are empty bars before output tables, these correspond to weird `Output ()` in the notebook rendered in github.

image

please advice on how to fix this :)

**Comment by twiecki** [comment]
Hm, now looking at this, I'm not sure what this example provides in addition to example 1 (sorry)... @OriolAbril what are your thoughts here?

**Comment by twiecki** [comment]
Another idea would be to put that example on the welcome page: https://www.pymc.io/welcome.html

**Comment by Krupakar-Reddy-S** [comment]
> Hm, now looking at this, I'm not sure what this example provides in addition to example 1 (sorry)... @OriolAbril what are your thoughts here?

I felt the same as there was an very detailed motivating example before this.
ok then i will put it up on the home page.

**Comment by twiecki** [comment]
While we're here, do you want to change the imports `at` to `pt` (pytensor)?

**Comment by Krupakar-Reddy-S** [comment]
> While we're here, do you want to change the imports `at` to `pt` (pytensor)?

Sure :)
Also what version of pymc to use here, i have used `5.15.1` for my previous changes or is there a specific standard for the docs notebooks?

**Comment by twiecki** [comment]
The most recent one ideally but it doesn't matter too much here.

**Comment by Krupakar-Reddy-S** [comment]
I have raised the PR [here](https://github.com/pymc-devs/pymc.io/pull/98) to add the example to the welcome page.
I will raise for the import name change here :)

**Comment by twiecki** [comment]
Thanks for your patience :).

**Pull request closed without merging**
