### PR TITLE
WIP: bugfix and improvement in getting_started notebook

### LINKED ISSUE #1029: issue on Metropolis with Theano0.8.0rc1 (master of 20160319) and Pymc3 (master of 20160319) getting_started.ipynb' on Windows
Hi,

I get the following error on getting_started.ipynb. As I'm new to the module and it's on Python3.4.4 64bit/mingwpy/windows7/latest Theano trunk/no gpu (only cgohlke numpy-mkl), it may or may not be a new error, a bad user error, a Theano error; or a pymc3 error:

```
from pymc3 import Metropolis 

with disaster_model:
    step1 = NUTS([early_rate, late_rate])

    # Use Metropolis for switchpoint, and missing values since it accommodates discrete variables
    step2 = Metropolis([switchpoint, disasters.missing_values[0]] )

    trace = sample(10000, step=[step1, step2])
```

```
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:

TypeError: expected type_num 9 (NPY_INT64) got 7

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-19-7d2f5d9a03b4> in <module>()
      7     step2 = Metropolis([switchpoint, disasters.missing_values[0]] )
      8 
----> 9     trace = sample(10000, step=[step1, step2])

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in sample(draws, step, start, trace, chain, njobs, tune, progressbar, model, random_seed)
    147         sample_func = _sample
    148 
--> 149     return sample_func(**sample_args)
    150 
    151 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in _sample(draws, step, start, trace, chain, tune, progressbar, model, random_seed)
    156     progress = progress_bar(draws)
    157     try:
--> 158         for i, strace in enumerate(sampling):
    159             if progressbar:
    160                 progress.update(i)

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\sampling.py in _iter_sample(draws, step, start, trace, chain, tune, model, random_seed)
    238         if i == tune:
    239             step = stop_tuning(step)
--> 240         point = step.step(point)
    241         strace.record(point)
    242         yield strace

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\compound.py in step(self, point)
     12     def step(self, point):
     13         for method in self.methods:
---> 14             point = method.step(point)
     15         return point

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\arraystep.py in step(self, point)
    116         bij = DictToArrayBijection(self.ordering, point)
    117 
--> 118         apoint = self.astep(bij.map(point))
    119         return bij.rmap(apoint)
    120 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\step_methods\metropolis.py in astep(self, q0)
    123             q = q0 + delta
    124 
--> 125         q_new = metrop_select(self.delta_logp(q, q0), q, q0)
    126 
    127         if q_new is q:

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\gof\link.py in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\theano\compile\function_module.py in __call__(self, *args, **kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

TypeError: expected type_num 9 (NPY_INT64) got 7
Apply node that caused the error: AdvancedIncSubtensor1{no_inplace,set}(TensorConstant{[   4    5..   0    1]}, Subtensor{int64:int64:}.0, TensorConstant{[39 83]})
Toposort index: 7
Inputs types: [TensorType(int64, vector), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(111,), (2,), (2,)]
Inputs strides: [(8,), (4,), (8,)]
Inputs values: ['not shown', array([0, 0]), array([39, 83], dtype=int64)]
Outputs clients: [[Elemwise{Composite{Switch((i0 * GE(i1, i2)), ((Switch(i3, i4, (i1 * i5)) - scalar_gammaln((i6 + i1))) - i7), i4)}}(Elemwise{ge,no_inplace}.0, AdvancedIncSubtensor1{no_inplace,set}.0, TensorConstant{(1,) of 0}, InplaceDimShuffle{x}.0, TensorConstant{(1,) of -inf}, Elemwise{log,no_inplace}.0, TensorConstant{(1,) of 1}, Elemwise{Composite{Switch(GE(i0, i1), i2, i3)}}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-a2c400c3581a>", line 14, in <module>
    disasters = Poisson('disasters', rate, observed=disaster_data)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\distributions\distribution.py", line 25, in __new__
    return model.Var(name, dist, data)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 272, in Var
    var = ObservedRV(name=name, data=data, distribution=dist, model=self)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 544, in __init__
    data = as_tensor(data, name,model,distribution.dtype)
  File "D:\WinPython\basedir34\buildQt5\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\pymc3\model.py", line 512, in as_tensor
    missing_values)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

### PR DESCRIPTION
**Pull request by fonnesbeck**
There were several errors in the import statement for the S&P500 data that are fixed here. However, the S&P500 example is still problematic. The warning "this step can take up to 5 minutes on an old PC" is a big understatement; on my "modern" MacBook Air, the model does not even get started after 15 minutes of wall time. I'm not sure this is a great advertisement for PyMC3, let alone in a "getting started" notebook. Moreover, I wonder if we should be recommending using `find_MAP` to get initial values, given how rarely it works as a strategy for initializing an MCMC run. 

Thoughts?

Closes #1029

### CODE REVIEW

**Comment by springcoil** [comment]
Yeah it's not a great advertisment. Should we use ADVI here to find a starting point?

**Comment by fonnesbeck** [comment]
I wonder if this is even the correct dataset. There are almost 4000 values and it is not even a table with headers and dates, as the notebook suggests. Can you check this @twiecki?

**Comment by twiecki** [comment]
Taking a look.

**Comment by springcoil** [comment]
This looks good to me. I think this is the right approach Thomas.

**Comment by twiecki** [comment]
I changed it to use `pandas-datareader` to download the data from yahoo finance and use ADVI to initialize NUTS. Sampling is pretty fast now (~2 mins on my machine). I also added some text describing how ADVI is good for init, compared to find_MAP.

**Comment by springcoil** [comment]
Needs a rebase obviously before being merged - great work @twiecki and @fonnesbeck

**Comment by twiecki** [comment]
Rebased.

**Comment by springcoil** [comment]
Needs another rebase right?

**Comment by fonnesbeck** [comment]
That should do it. I also added a conditional import for the pandas data loader that pip-installs it if its not already installed.

**Comment by rshpeley** [comment]
Your github web docs should also be updated,
  [http://pymc-devs.github.io/pymc3/notebooks/getting_started.html](url)

Nice tutorial, btw!

**Comment by twiecki** [comment]
Should be updated.

**Pull request merged**
