### PR TITLE
OPVI+SVGD

### PR DESCRIPTION
**Pull request by ferrine**
This PR ports SVGD to OPVI framework

### CODE REVIEW

**Comment by ferrine** [comment]
Inference fails in a strange way

**Comment by ferrine** [comment]
I figured out what was going on. Optimizer has improper learning rate. Fixing it (set adagrad, lr=1e-3) gives good visual results on simple problem. I also use current implementation at work and it performs 1.7 times faster. I'll merge after sanity check test.

**Comment by twiecki** [comment]
@ferrine We should probably remove the existing SVGD implementation then, no?

**Comment by ferrine** [comment]
Yes, without any doubt

**Comment by ferrine** [comment]
I wonder if aevb is theoretically available for svgd

**Comment by ferrine** [comment]
Ready for review

**Comment by ferrine** [comment]
I'll merge this after #1985  as it is needed here. 
I also did some kind of refactoring in this PR because svgd did not fit architecture.

**Pull request merged**
