### PR TITLE
Improve error message for empty models

### PR DESCRIPTION
**Pull request by aseyboldt**

### CODE REVIEW

**Comment by fonnesbeck** [comment]
LGTM. Do we have a test that affirms that models with no free variables always have `ndim=0`.

**Comment by aseyboldt** [comment]
If I read the failing tests right, then that is not the case. There seems to be something up with discrete parameters.

On June 14, 2017 4:33:56 PM CEST, Chris Fonnesbeck <notifications@github.com> wrote:
>LGTM. Do we have a test that affirms that models with no free variables
>always have `ndim=0`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pymc-devs/pymc3/pull/2293#issuecomment-308450575

-Adrian

**Comment by aseyboldt** [comment]
Turns out `model.ndim` was broken...

**Comment by junpenglao** [comment]
Is this ready to merge?

**Pull request merged**
