### PR TITLE
remove bpic and dic

### LINKED ISSUE #2756: Remove BPIC and DIC
These were deprecated in #2754 , and should be removed after the next release (3.3).

### PR DESCRIPTION
**Pull request by aloctavodia**
Close #2756

### CODE REVIEW

**Comment by ColCarroll** [comment]
Love it - will merge when tests pass.

**Comment by aloctavodia** [comment]
I forgot to remove dic from one example!

**Comment by junpenglao** [comment]
You mean the one in GLM-logistic.ipynb right?

**Comment by aloctavodia** [comment]
that's right!

**Pull request merged**
