### PR TITLE
NegativeBinomial distribution sample generator wrapper

### PR DESCRIPTION
**Pull request by fearghuskeeble**
Per #3864 I added a wrapper for the generating samples in NegativeBinomial. This is already used in ZeroInflatedNegativeBinomial and other distributions which require operations on the scipy arguments. 

Also fixed an error typo in sampling.

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks! Why wasn't this caught by a test? Can we add one that would have caught it?

**Comment by ColCarroll** [comment]
Posterior predictive tests are not at all comprehensive. Adding a test would be nice if @fearghuskeeble has time.

**Comment by rpgoldman** [comment]
Please test on both `sample_posterior_predictive` and `fast_sample_posterior_predictive`.  You'll see examples of testing both in the existing tests (I think in `test_sampling`).

**Comment by fearghuskeeble** [comment]
I'm not clear as to the relevance of posterior predictive sampling here.

In terms of the prior sampling, the testing is unfortunately a little opaque to me but I will have a look...

**Comment by lucianopaz** [comment]
@twiecki, it wasn't caught because there are no tests that try to sample from the prior when one of the distribution parameters is a scalar and the other is a vector.

@fearghuskeeble, take a look at test_distributions_random.py. The tests there are structured in a relatively obscure way, so I recommend you just look at how we added [a single extra test for the categorical distribution](https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_distributions_random.py#L470-L484) and follow that pattern to add test in the [negative binomial's test class](https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_distributions_random.py#L437-L439).
Oh, and don't forget to add a line in the release notes.md fine at the project's root under maintenance.

**Comment by fearghuskeeble** [comment]
@lucianopaz I looked back at #3509 and added a test to your nested sampling class.

**Review by lucianopaz — APPROVED** [review]
Great work! I can't merge this from my phone but I'll do it once I get a chance to log into my computer

**Comment by twiecki** [comment]
Thanks @fearghuskeeble!

**Pull request merged**
