### PR TITLE
some small changes to make advi respect theano.config.floatX

### PR DESCRIPTION
**Pull request by Spaak**
And thereby improve GPU compatibility.

### CODE REVIEW

**Comment by twiecki** [comment]
Looks good to me. @taku-y?

@Spaak Does ADVI run on the GPU with this?

**Comment by taku-y** [comment]
@twiecki looks good to me. Ready to merge.

**Comment by Spaak** [comment]
@twiecki actually I don't know yet, I was making these changes primarily to manage memory usage by keeping everything `float32`. I don't have a GPU on which to test, maybe in the coming months.

**Comment by twiecki** [comment]
@Spaak ok, thanks.

**Comment by Spaak** [comment]
@twiecki Was able to verify; yes, ADVI now runs on the GPU. Titan X Pascal ~150 it/s vs Xeon E5-1650 v3 ~10 it/s. Minibatch ADVI also runs on the GPU (~90 it/s, whereas it used to be faster than non-minibatch on CPU). I presume the speedup with minibatch is more modest because of the copying of data back and forth to GPU.

**Comment by twiecki** [comment]
@Spaak This is the first time we've seen a speed-up when using the GPU, very exciting!

**Comment by twiecki** [comment]
Did you try NUTS on the GPU?

**Comment by Spaak** [comment]
Yes, NUTS seems to work, but only when I have `theano.config.optimizer = None`, both `fast_run` and `fast_compile` result in errors (different ones). Because of `optimizer=None` there is no speedup over CPU. Some of the errors I'm getting could be due to my own code. I will try out some more to get NUTS (and/or maybe Metropolis to start with) working on GPU either in the next few days or January 2017.

**Comment by twiecki** [comment]
@Spaak Which branch are you running for NUTS on the GPU? I think the `use_theano_float_type2` branch is not functional currently.

**Pull request merged**
