### PR TITLE
Clarified 0-based indexing requirement for OrderedLogistic and OrderedProbit

### LINKED ISSUE #7422: DOC: Slightly more clarification about the expected target value indexing of pymc.OrderedLogistic
### Issue with current documentation:

While it is possible to deduce that OrderedLogistic expects the observed values to have the typical 0-based indexing as in regular Python, based on the documentation's example:
`y = np.concatenate((1*np.ones(n1_c),
                    2*np.ones(n2_c),
                    3*np.ones(n3_c))) - 1`
the initial line of the documentation `Useful for regression on ordinal data values whose values range from 1 to K as a function of some predictor...` makes it seem like the encoding should be "1,2,3,...K". This can be confusing for users, as this can result in `logp=-inf` error, which does not intuitively trace back to the source of the error here.

### Idea or request for content:

Make it clearer that the target values ("observed") should be 0-based, like in regular Python. Similar change could also be made for OrderedProbit.

### PR DESCRIPTION
**Pull request by kdotmanoj**
…dProbit in discrete.rst

## Description

This pull request updates the discrete.rst documentation to clarify the requirement for 0-based indexing in the OrderedLogistic and OrderedProbit distribution entries. This addition aims to help users understand that these distributions expect 0-based indexing for their input data, which is crucial for correct implementation and usage

## Related Issue

- [x] Closes #7422 
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7457.org.readthedocs.build/en/7457/

### CODE REVIEW

**Comment by kdotmanoj** [comment]
@twiecki can you please review this :)

**Review by twiecki — APPROVED** [review]

**Comment by kdotmanoj** [comment]
Hi @twiecki,

Thank you for reviewing the PR! I wanted to check if you know when it might be merged.

Thanks!

**Comment by twiecki** [comment]
Thanks!

**Comment by ricardoV94** [comment]
This shouldn't be in `discrete` but in the docs of the OrderedLogistic/Probit functions. 
image

Also as https://github.com/AllenDowney mentioned the description of the distributions are themselves wrong: https://github.com/pymc-devs/pymc/blob/d31301279776888c1540bfba890cba38ea250637/pymc/distributions/discrete.py#L1192

**Pull request merged**
