### PR TITLE
Fixes to DP mixture notebook

### PR DESCRIPTION
**Pull request by fonnesbeck**
DP mixture notebook now runs reasonably well.

### CODE REVIEW

**Comment by twiecki** [comment]
LGTM. Note that earlier I was talking about the dependent density regression one, however.

**Comment by fonnesbeck** [comment]
Why was this reverted? The models had not converged in the original version.

**Comment by lucianopaz** [comment]
I think because it conflicted with the rerun notebooks PR, #3397. Maybe it can be re applied now.

**Comment by twiecki** [comment]
I think the other PR already fixed this NB.

**Pull request merged**
