### PR TITLE
Mixture docs update

### PR DESCRIPTION
**Pull request by ericmjl**
I was getting errors with mixture distributions because I didn't see the new `.dist(...)` syntax. Following chat with @junpenglao, I am putting in this PR to add an example to the Mixture distribution docs. Please let me know if the wording or example needs to be changed, happy to make them.

### CODE REVIEW

**Comment by junpenglao** [comment]
Thanks! Could you add also an example for the second use case `iterable of one-dimensional PyMC3 distributions the component distributions`
Also could you please remove the irrelevant part the PR (replacing images)?

**Comment by ericmjl** [comment]
@junpenglao not a problem!

Did have a question though - I've never done a removal of commits before. Is it `git revert {hash}` to remove it? Or are you referring to a squashing of a commit?

**Comment by junpenglao** [comment]
Maybe merge with master? I have no idea actually...

**Comment by ColCarroll** [comment]
This is The Coward's Path, but I would copy the relevant changes, close this PR, and start a new one.

**Comment by junpenglao** [comment]
As xkcd put it:
image

**Comment by ColCarroll** [comment]
Separately, [ImgBot](https://github.com/dabutvin/ImgBot) looks super cool and I'm not against including those changes in a separate PR, though we don't ship the docs folder on pypi/conda, so it might not be worth the effort to save ~30kb on the size of the git repo.

**Comment by ericmjl** [comment]
I think I figured it out! It's a:

- `git rebase -i HEAD~X` where `X` is the number of commits. Alternatively `git rebase -i --root` to go back to beginning.
- Then use the interface to squash a bunch of commits.

I'll get it done in a short bit.

**Comment by ericmjl** [comment]
Ugh, defeated by git... I'm going to take @ColCarroll's path, a path that I've tread many times...

**Pull request closed without merging**
