### PR TITLE
Make init argument to sample case-insensitive

### PR DESCRIPTION
**Pull request by fonnesbeck**
Having "MAP" and "NUTS" be lower case here where it is upper case everywhere else is confusing. So as not to break things, the easiest approach is to make the input case-insensitive.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Confusing failures. `init` should never be a dict, according to the docstring.

**Comment by ColCarroll** [comment]
looks like the 3rd argument used to be `start`, so I'd guess a positional argument was used where a keyword argument should have been

**Comment by ColCarroll** [comment]
you got a lot of them -- looks like `pymc3.tests.test_examples.TestLatentOccupancy` is still breaking.

Good to catch all these!  I think `pylint` catches this sort of thing?  hope to have cycles this weekend to help thomas merge 3.1, then merge the pylint changes, which should make adding new code a bit easier.

**Comment by fonnesbeck** [comment]
I'll keep chipping away. 

We should probably use keyword arguments throughout our tests in order to keep this sort of thing from happening.

**Comment by fonnesbeck** [comment]
`test_bad` is an odd test. Short chains don't *necessarily* have a large Rhat, so I'm not sure we need a test for that.

**Comment by ColCarroll** [comment]
The point of `test_bad` is to verify that not all chains have a small Rhat -- I think such a test is important to sanity check the RHat implementation.

**Comment by fonnesbeck** [comment]
Maybe best to use known, fixed non-convergent traces for that rather than obtaining random samples.

**Comment by fonnesbeck** [comment]
I made the initial values for the means in the test case to be quite far from their true values, so it should guarantee `test_bad` evaluates as expected.

**Comment by fonnesbeck** [comment]
Very bizarre that this still fails (or rather, doesn't fail) given how it is initialized. Will take a closer look.

**Comment by twiecki** [comment]
Also need to rebase, perhaps that fixes this.

**Comment by fonnesbeck** [comment]
I just  keep getting circular merges here. Not sure what's happening. Going to close this and try again on the new master.

**Pull request closed without merging**
