### PR TITLE
Added notebook and data for LGCP tutorial

### LINKED ISSUE #4084: Adding doc notebook for log Gaussian Cox process
I've written a short tutorial on the LGCP and its marked Poisson process extension per the discussion here: https://discourse.pymc.io/t/cox-process-in-pymc3/389/2. The notebook can be viewed [here](https://github.com/ckrapu/pymc3/blob/master/docs/source/notebooks/log-gaussian-cox-process.ipynb). It requires a small CSV data file with a few hundred lines. I'm not aware of any specific checklist for doc notebooks so I followed these guidelines:

* Use Jupyter settings for high-resolution images (e.g. `%config InlineBackend.figure_format = 'svg'
`)
* Included required dataset so that it can be loaded using `pm.get_data`
* Added a watermark and authorship statement
* Ran with most recent PyMC3 version

One potential issue is that the entire run time is ~5 hours since part of the model involves a latent GP with 350 points in space. I didn't try using ADVI in this notebook. Additional feedback / suggestions would be greatly appreciated!

### PR DESCRIPTION
**Pull request by ckrapu**
This PR refers to issue https://github.com/pymc-devs/pymc3/issues/4084 and adds a new notebook showing how to fit a log Gaussian Cox process using a discrete grid approximation. It also includes an extension to model marked points. A small dataset is included as well.

### CODE REVIEW

**Comment by junpenglao** [comment]
LGTM overall, some nitpicks: could you change the nested for-loop count with a `plt.hist2d`? it should simplify the code a bit.

**Comment by ckrapu** [comment]
> LGTM overall, some nitpicks: could you change the nested for-loop count with a `plt.hist2d`? it should simplify the code a bit.

I didn't realize there was an easy way to do it in 2D. Good idea! I've made the update.

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
This is a super nice advanced use-case of GPs, thanks @ckrapu !
I think there are just a few tweaks or precisions missing, as I wrote below. It shouldn't be too long to add and feel free to ask if anything is unclear 😉

**Comment by ckrapu** [comment]
<p>Yeah, I missed the rest of that statement.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4087/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ckrapu** [comment]
<p>Agreed - now that I think about it, a SD of 10 on log scale is way too wide. I'm not sure how to pick the length scale, though. I've tried using <code>HalfNormal(sd=100)</code>  and various settings for an inverse-Gamm prior. None of those seemed to help cut down on the convergences. The rule of thumb I was taught was to make sure that the upper bound is less than the largest interpoint distance. Any ideas here?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4087/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ckrapu** [comment]
<p>Got it!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4087/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ckrapu** [comment]
<p>This part didn't have to be expressed in a roundabout way; I cleaned that up.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4087/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Much clearer indeed, thanks!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4087/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Thanks for the changes @ckrapu, this looks really neat now!

> I'm not sure how to pick the length scale, though. I've tried using HalfNormal(sd=100) and various settings for an inverse-Gamm prior. None of those seemed to help cut down on the convergences. Any ideas here?

Yeah, that's always (very) tricky... `HalfNormal(sd=100)` seems already very wide, given that you exponentiate it. I think going with Gamma or InvGamme is indeed much safer, in addition to giving you more leeway to incorporate domain knowledge. I'm curious about any advice on this from the very knowledgeable @fonnesbeck and @bwengals !

Prior pred checks with spaghetti plots and ribbon plots can also be useful -- I'm doing exactly that [in a NB](https://github.com/AlexAndorra/pollsposition_models/blob/test-gp-popularity/popularity/gp-raw-econ.ipynb) right now; the code is still very messy and WIP, but hopefully this can help you 🤷‍♂️ There are also prior choices in [the Mauna Loa NB](https://docs.pymc.io/notebooks/GP-MaunaLoa.html).
Notice though that your changes already sped up the sampling by a factor of 2+!

> The rule of thumb I was taught was to make sure that the upper bound is less than the largest interpoint distance.

Yeah but even that isn't that great IIUC, as 1) it picks priors based on the observed data, and 2) maybe future data _can_ inform larger interpoint distance.

**Comment by MarcoGorelli** [comment]
Hi @ckrapu - a new CI check has been added, before your next commit could you fetch and merge upstream/master? I'm pretty sure it will still pass, this is just to be sure

**Comment by ckrapu** [comment]
> Thanks for the changes @ckrapu, this looks really neat now!
> 
> > I'm not sure how to pick the length scale, though. I've tried using HalfNormal(sd=100) and various settings for an inverse-Gamm prior. None of those seemed to help cut down on the convergences. Any ideas here?
> 
> Yeah, that's always (very) tricky... `HalfNormal(sd=100)` seems already very wide, given that you exponentiate it. I think going with Gamma or InvGamme is indeed much safer, in addition to giving you more leeway to incorporate domain knowledge. I'm curious about any advice on this from the very knowledgeable @fonnesbeck and @bwengals !
> 
> Prior pred checks with spaghetti plots and ribbon plots can also be useful -- I'm doing exactly that [in a NB](https://github.com/AlexAndorra/pollsposition_models/blob/test-gp-popularity/popularity/gp-raw-econ.ipynb) right now; the code is still very messy and WIP, but hopefully this can help you 🤷‍♂️ There are also prior choices in [the Mauna Loa NB](https://docs.pymc.io/notebooks/GP-MaunaLoa.html).
> Notice though that your changes already sped up the sampling by a factor of 2+!
> 
> > The rule of thumb I was taught was to make sure that the upper bound is less than the largest interpoint distance.
> 
> Yeah but even that isn't that great IIUC, as 1) it picks priors based on the observed data, and 2) maybe future data _can_ inform larger interpoint distance.

I spoke too soon about the priors. Those changes helped a ton with the marked model as you pointed out.

**Comment by ckrapu** [comment]
> Hi @ckrapu - a new CI check has been added, before your next commit could you fetch and merge upstream/master? I'm pretty sure it will still pass, this is just to be sure

Yup! Done.

**Comment by MarcoGorelli** [comment]
@ckrapu looks like some of the imports are out of order, can you make the following change please?

```diff
+    "from itertools import product\n",
+    "\n",
     "import arviz as az\n",
     "import matplotlib.pyplot as plt\n",
     "import numpy as np\n",
     "import pandas as pd\n",
-    "import pymc3 as pm\n",
-    "\n",
-    "from itertools import product"
+    "import pymc3 as pm"
```
? 

Or, just run `isort` via `nbqa` from the command-line, see the [style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style):

```
nbqa docs/source/notebooks/log-gaussian-cox-process.ipynb --treat-comment-as-code '# %%' --lines-between-types 1 --nbqa-mutate
```

**Comment by AlexAndorra** [comment]
@MarcoGorelli is there a way to enforce this automatically in the GH action when the committer hasn't run nbqa (or, later, Black) on the NB?

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli is there a way to enforce this automatically in the GH action when the committer hasn't run nbqa (or, later, Black) on the NB?

As in, can we get the GitHub Action to _push_ to the file? Maybe...I know that pre-commit's author is working on a paid product that would allow for that, but there may be a way to do this without it, I'll look into it

**Comment by MarcoGorelli** [comment]
> > @MarcoGorelli is there a way to enforce this automatically in the GH action when the committer hasn't run nbqa (or, later, Black) on the NB?
> 
> As in, can we get the GitHub Action to _push_ to the file? Maybe...I know that pre-commit's author is working on a paid product that would allow for that, but there may be a way to do this without it, I'll look into it

@AlexAndorra looks like it's not ready yet https://pre-commit.ci/ ...hopefully it'll be available for free for open source projects. In the meantime I guess we can ask contributors to run this themselves, or a maintainer can add a commit to their branch

**Comment by AlexAndorra** [comment]
> As in, can we get the GitHub Action to push to the file?

Yes, as in: contributor pushes to PR --> GH action _checking_ imports/Black on NB fails --> GH action _runs_ `nbqa` itself and then pushes the changes automatically. In other words, all the formatting / style is taken care of automatically 🎉 

> looks like it's not ready yet https://pre-commit.ci/ ...hopefully it'll be available for free for open source projects

That'd be so awesome!

> In the meantime I guess we can ask contributors to run this themselves

Definitely -- that's already what we do so it's actually no change

**Comment by ckrapu** [comment]
The import order is fixed. Should we assume that the import order desired by `nbqa` is the default moving forward?

**Comment by MarcoGorelli** [comment]
Thanks for updating! 

> the import order desired by `nbqa`

just to be clear - it's `isort` that determines the import order, `nbqa` is just a little adapter which will let it run on Jupyter Notebooks (instead of Python files)

**Comment by AlexAndorra** [comment]
> Should we assume that the import order desired by nbqa is the default moving forward?

Yep, but this was already the case (see the [style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style)) -- the only difference is that now it's checked automatically in CI 😉

**Review by AlexAndorra — APPROVED** [review]
Merging now, as we gave it a few days 🎉 Thanks @ckrapu for this nice addition to the docs!

**Comment by ckrapu** [comment]
This may be a dumb question, but I don't see a thumbnail for this notebook in the gallery. Did I forget to set something with this PR?

**Comment by twiecki** [comment]
@ckrapu it should be the last plot of the NB. @ColCarroll?

**Comment by MarcoGorelli** [comment]
@ckrapu are you referring to the "Gaussian Process" section here https://docs.pymc.io/nb_examples/index.html ?

If so, it seems that "conditional-autoregressive-model" is also missing

**Comment by ckrapu** [comment]
Yup - I thought that putting its name in `docs/source/notebooks/table_of_contents_examples.js` would automatically place it in the gallery.

**Pull request merged**
