### PR TITLE
start private API section

### PR DESCRIPTION
**Pull request by OriolAbril**
Starts a private api section and fills an example page.
Still not sure what should be documented there and the goal is not to add more things,
only to show how it is done so other people can take over.
Related to #5539

+ [x] what are the (breaking) changes that this PR makes? **None**
+ [x] important background, or details about the implementation: see above
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

### CODE REVIEW

**Comment by michaelosthege** [comment]
Maybe move `ARCHITECTURE.md` from the root level into the new section?

Also, linking this because it's related: https://github.com/pymc-devs/pymc/wiki/PyMC3-Internals-(for-devs)

**Comment by OriolAbril** [comment]
> Maybe move ARCHITECTURE.md from the root level into the new section?

I'll always agree to moving files from random markdown files in github to the documentation. I see both more related to the developer guide (and therefore to #5346) than to this page that would be only API docs so that we can reference private functions in the developer guide, in the architecture... as links and get to their api page with nice docstring, the [source] section. The hope would be that it would help both developers and new contributors.

**Review by michaelosthege — APPROVED** [review]

**Comment by michaelosthege** [comment]
@OriolAbril shall we merge this one before we start getting git conflicts?

Only maintainers could push to this branch. So having this on `main` will make it easier for everybody to contribute.

**Comment by OriolAbril** [comment]
Sounds good, I didn't merge because I was focused on other things, merging now

**Pull request merged**
