### PR TITLE
Render `DifferentialEquation` Documentation

### PR DESCRIPTION
**Pull request by Dpananos**
Solves #3848.  `DifferentialEquation` docs should be rendering now.

### CODE REVIEW

**Comment by ColCarroll** [comment]
Thanks, @Dpananos! I can probably push these live tomorrow morning unless someone (@rpgoldman?) objects. A quick glance at the [release-notes](https://github.com/pymc-devs/pymc3/blob/master/RELEASE-NOTES.md) seems like we have not changed too many apis?

**Comment by ColCarroll** [comment]
(objections are fine, they just mean I will have to be a little careful force pushing to the docs branch, and try to get only the new stuff)

**Comment by Dpananos** [comment]
Yea, push them tomorrow.  I built the docs before making the pr, but if something goes wrong just let me know.

**Comment by ColCarroll** [comment]
Getting a funny traceback. I am running 

```bash
$ cd docs/source
$ make html
```
and getting the error below. Running just 
```python
> import arviz as az
> az.load_arviz_data('radon')
```
(which seems to throw the error below) does fine. I am running this on master, with ArviZ on master (`0.7.0`), and Sphinx `2.4.4`. 

Here is the error:
```python
>>>-------------------------------------------------------------------------
Exception in /home/pete/projects/pymc3/pymc3/stats/__init__.py:docstring of pymc3.stats.bfmi at block ending on line 43
Specify :okexcept: as an option in the ipython:: block to suppress this message
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-282e0ea03c40> in <module>
      1 import arviz as az
----> 2 data = az.load_arviz_data('radon')
      3 az.bfmi(data)

~/projects/arviz/arviz/data/datasets.py in load_arviz_data(dataset, data_home)
    231                 "again, or please open an issue.".format(file_path, checksum, remote.checksum)
    232             )
--> 233         return from_netcdf(file_path)
    234     else:
    235         if dataset is None:

~/projects/arviz/arviz/data/io_netcdf.py in from_netcdf(filename)
     23     ``az.rcParams["data.load"]``.
     24     """
---> 25     return InferenceData.from_netcdf(filename)
     26 
     27 

~/projects/arviz/arviz/data/inference_data.py in from_netcdf(filename)
    126         """
    127         groups = {}
--> 128         with nc.Dataset(filename, mode="r") as data:
    129             data_groups = list(data.groups)
    130 

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -101] NetCDF: HDF error: b'/home/colin/arviz_data/radon.nc'
<<<-------------------------------------------------------------------------
```

**Comment by Dpananos** [comment]
Of course it couldn't have been that easy.

I rebuilt the docs this morning.  I'm not getting that error when I `make html`.  Let's roll it back.  Can you make a fork of my branch and try making the docs again?

**Comment by rpgoldman** [comment]
I just built from master and I didn't get an error.

**Comment by ColCarroll** [comment]
must be my setup :grimacing: does one of you feel ok force pushing to the `gh-pages` branch? (https://github.com/pymc-devs/pymc3/tree/gh-pages)

**Comment by Dpananos** [comment]
I do not feel OK force pushing that.

**Comment by rpgoldman** [comment]
@ColCarroll Mine may have diverged.  This is what I have:

```
nbsphinx==0.5.1
sphinx-autobuild==0.7.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
```

Also, why do we have to force push, instead of just pushing?

**Comment by ColCarroll** [comment]
Here's mine, matches on the major/minor, at least

```
nbsphinx==0.5.1
sphinx-autobuild==0.7.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
```

I think it is because we don't care about history for the docs (in theory, can go back and rerun them), and don't want to bother with diffs.

**Comment by rpgoldman** [comment]
I see: I was not using arviz on master.  When I rerun with Arviz on master, I also get an error, but not the same one:

```
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<class 'netCDF4._netCDF4.Dataset'>, '/Users/rpg/src/arviz/arviz/data/_datasets/non_centered_eight.nc', mode='r', kwargs={'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 243, in __del__
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 217, in close
  File "/Users/rpg/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<class 'netCDF4._netCDF4.Dataset'>, '/Users/rpg/src/arviz/arviz/data/_datasets/centered_eight.nc', mode='r', kwargs={'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 243, in __del__
  File "/Users/rpg/.virtualenvs/pymc3/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 217, in close
  File "/Users/rpg/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable

```

> I think it is because we don't care about history for the docs (in theory, can go back and rerun them), and don't want to bother with diffs.

And no one is actually checking out `gh-docs`, so it doesn't matter that we are force pushing?

**Comment by ColCarroll** [comment]
Any chance you have a version of arviz where it worked? 0.7.0 on pypi didn't work for me...

re `gh-docs`: exactly.

**Comment by rpgoldman** [comment]
I seem to have been doing this with 0.6.1 when it worked -- I got Arviz from PyPi into my virtual environment and had forgotten to update.

**Comment by rpgoldman** [comment]
@ColCarroll 

Note also that my error above is not a fatal error -- the doc building (`make html`) still ran to completion.

I wonder if it's related, though, because it's some kind of xarray input error, and yours is also a netcdf error.

**Comment by rpgoldman** [comment]
There's a typo here:

```
make_node(self, y0, theta)¶
Create a “apply” nodes for the inputs in that order.
```
Should that be 'an "apply" node' (i.e., singular instead of plural)?

Also, what's the return type?

**Comment by ColCarroll** [comment]
I don't see where the `make_node` is coming from? 

Hrm... I tried 0.6.1 with the same error, in a fresh environment. Lemme try nuking the build directory too.

**Comment by rpgoldman** [comment]
In the docstring for `perform` the `Return` part of the docstring is in the summary line, but it should be in a separate "Returns" header.

**Comment by Dpananos** [comment]
I don't even see a doc string for that method.  Why is it showing up in the docs?

**Comment by rpgoldman** [comment]
> I don't even see a doc string for that method. Why is it showing up in the docs?

I think it's because you are automagically generating docs for all of the methods of the class `pymc3.ode.DifferentialEquation`

**Comment by Dpananos** [comment]
Am I doing that in the `ode.rst` file?  I'm not super familiar with sphinx or rst.  I tried to emulate some other files so it is quite probable I'm doing something wrong in `ode.rst`.

**Comment by rpgoldman** [comment]
@Dpananos I'm not an expert myself, but I think the following documents all the members of `DifferentialEquation`.  This will skip private ones with `_` prefix, but document all the others. For more details, see here: http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

It may be that you want to just remove the `:members:` line if you don't have any members you want documented.  Otherwise, per the above, you can specify them explicitly.

```
.. automodule:: pymc3.ode
   :members: DifferentialEquation
```

**Pull request merged**
