### PR TITLE
Use SMC like other samplers

### PR DESCRIPTION
**Pull request by aloctavodia**
This PR make it possible to use SMC in a way that is closer to other samplers.

```python
pm.sample(draws=2000, chains=200, step=pm.SMC())
```
Passing `pm.SMC()` is mandatory because there is no easy way to auto-assign the SMC sampler. 
I would like to run more tests tomorrow, just to be sure I did not broke something. BTW, it would be nice to drop the _experimental warning_ from SMC for next release (3.5).

### CODE REVIEW

**Comment by aloctavodia** [comment]
Remaining Travis errors unrelated to this PR :-)

**Comment by junpenglao** [comment]
LGTM - @michaelosthege could you please have a look? Given that there are some similarity between DEmetropolis and SMC maybe there are some room for further refactoring (in another PR of course).

**Comment by hvasbath** [comment]
You made some real progress to smoothing the SMC sampler out to get into the more common pymc3 feeling! Thats great! @aloctavodia  . I am sorry that I havent been more active with contributing the last monthes.

**Comment by aloctavodia** [comment]
@hvasbath I am glad you like it. Don't worry, we are all trying to do our best within our time constraints.

**Comment by michaelosthege** [comment]
I've been away without internet since Thursday, so I just had the first chance to look at it.
There are quite a lot of code style changes in the diff, but from what I can see from sampling.py, the change is focused on the user experience, but in the background SMC continues to use the text-based backend for inter-chain-communication, right?
There might be some potential to align SMC and DEMetropolis in terms of inter-chain-communication, but I'm too unfamiliar with SMC to tell if this is even desireable(?).  But as @junpenglao said this would definitely be something for another PR.

**Comment by junpenglao** [comment]
@michaelosthege Thanks for having it a look.

Good to merge after resolving the conflicts.

**Comment by aloctavodia** [comment]
You are right @michaelosthege, this PR basically make a few change in `sampling` and `SMC` class focused on user-experience. Thanks for the input, I need to read about DEMetropolis.

**Comment by twiecki** [comment]
Thanks @aloctavodia!

**Comment by hvasbath** [comment]
No need to worry about inter chain communication, as it exists only in the serial part of the code. But in DEMetropolis you have it in the parallel sampling of the chains like in parallel tempering if I am not completely wrong? So DEM and SMC are quite different in this respect. However, it might be worth it to look into the new parallel sampler from @aseyboldt to replace the current pool ... wich would make the includion to pm.sample even smoother?

**Comment by twiecki** [comment]
I shouldn't have merged this:
```

self = <pymc3.tests.test_smc.TestSMC object at 0x7f78ba764890>, n_jobs = 1
stage = 0
    @pytest.mark.parametrize(['n_jobs', 'stage'], [[1, 0], [2, 6]])
    def test_sample_n_core(self, n_jobs, stage):
        step_kwargs = {'homepath': self.test_folder, 'stage': stage}
        with self.ATMIP_test:
            mtrace = pm.sample(draws=self.samples,
                               chains=self.chains,
                               cores=n_jobs,
                               step = pm.SMC(),
                               step_kwargs=step_kwargs)
    
        x = mtrace.get_values('X')
        mu1d = np.abs(x).mean(axis=0)
>       np.testing.assert_allclose(self.muref, mu1d, rtol=0., atol=0.03)
E       AssertionError: 
E       Not equal to tolerance rtol=0, atol=0.03
E       
E       (mismatch 25.0%)
E        x: array([0.5, 0.5, 0.5, 0.5])
E        y: array([0.532979, 0.482611, 0.480073, 0.501302])
pymc3/tests/test_smc.py:62: AssertionError
```

**Comment by junpenglao** [comment]
Hopefully this is just a numerical glitch.

**Comment by twiecki** [comment]
Seems that way, I restarted the two failing jobs and it finished fine now.
Should probably set the seed there.

**Pull request merged**
