### PR TITLE
Posterior predictive sampling

### PR DESCRIPTION
**Pull request by stevenmanton**
Adding posterior predictive check code from [this tutorial](http://pymc-devs.github.io/pymc3/posterior_predictive/). Also, I tweaked the `draw_value` function to avoid theano function compilation during each iteration of sampling. I welcome a discussion regarding API, docs, testing, etc.

### CODE REVIEW

**Comment by twiecki** [comment]
This looks great, thanks! Can you change the pymc3 example notebook to use this new functionality?

**Comment by stevenmanton** [comment]
Will do. I actually noticed there's a bug in the function and in the notebook. Basically, it looks like the code won't generate the correct shape of the observed variable. I'll figure it out and fix it and resubmit.

**Comment by stevenmanton** [comment]
Ok, I realized that the `sample_ppc` function would generate posteriors, but the posteriors wouldn't necessarily have the same size as the observed data. It's easy to default the size to that of the observed data, but there are actually cases when it's nice to generate posterior samples of different sizes.

I ended up just adding a `size` kwarg to the `sample_ppc` function and updated the notebook to use this new function.

**Comment by twiecki** [comment]
That's odd with the `size` kwarg. I remember we discussed this over at https://github.com/pymc-devs/pymc3/pull/784. @mwibrow do you mind taking a look at this PR?

**Comment by mwibrow** [comment]
@twiecki not a problem. I suspect some of my tests have been a bit 
abstract and not very representative of what might actually happen in a 
real analysis. Will look in to it.

**Comment by mwibrow** [comment]
I think the problem is because the distributions themselves have no idea whether they are observed or not and therefore have no access to the size of the observed data. As the `random` method in the `run_ppc` command from the tutorial linked by @stevenmanton  is called like this

```
obs.distribution.random(point=param)
```

there is no way the `random` method can know what the shape of the observed data is. One solution may be to explicitly add a `random` method to the `ObservedRV` class in `model.py` which will pass the required shape if the 'size' parameter is not supplied:

```
def random(self, point=None, size=None):
        return self.distribution.random(point=point, size=size or self.tag.test_value.shape)
```

With this addition, sampling from an observed variable would/should then be done like this.

```
var.random(point=param, size=size)
```

This change seems to be working so far with the `sample_ppc` in the PR, so by default if no `size` is specified, the shape of the observed data is used.

**Comment by stevenmanton** [comment]
Yep, @mwibrow explains what's going on well.

It's rather easy to default to the size of the observed variable, but there are potential downsides to this approach as well. For instance, I use this function for a model with a gaussian random walk variable for weekly data from, say, 2013 to 2015. To predict 2016, I can modify the trace to used a fixed value of the walk variable repeated for each week. In the current implementation of the PR, no size parameter needs to be passed and the output of `sample_ppc` has the correct size. If instead `sample_ppc` defaulted the size argument to the size of the observed variable, I would get an error unless I explicitly passed a size. (Because there are more weeks in 2013 through 2016.)

Now maybe this use case (modifying the trace) is far less common and shouldn't be weighed as much as the normal use cases. In any case, that's the reasoning behind why I didn't specify a default for size.

**Comment by stevenmanton** [comment]
Also, it seems more correct to say that this function is sampling from the posterior predictive distribution and so should be called `sample_ppd`. I would consider sampling from the ppd a _part of_ standard posterior distribution checks. Would you guys agreed?

**Comment by fonnesbeck** [comment]
These appear to specifically be posterior predictive checks because they are generating samples that correspond to the values of the observed variables only. This function can't be used to draw samples for arbitrary input variable values, which you would expect from a posterior predictive distribution. So I would keep the name as is. If any change, I would recommend a slightly more descriptive name, such as `post_pred_check`.

**Comment by fonnesbeck** [comment]
I notice that the resulting values are lists of arrays. Since every sample will be the same shape, we should probably return a multidimensional array instead.

**Comment by stevenmanton** [comment]
@fonnesbeck thanks for taking a look! I like the idea of returning an ndarray instead of list. One corner case might be if there is an observed matrix rather than vector. Is this possible?

Also, can you explain more your comment about only calling the function on observed variables? It seems like you could call it on any variable, since under the hood you're just calling `var.distribution.random`, which all variables (even unobserved) define. Am I understanding that correctly? I don't really see a compelling reason for doing so, but it seems possible. Maybe doing some bootstrap sampling for estimating the variance of an estimator?

**Comment by twiecki** [comment]
@stevenmanton So what happens currently? Just a single value gets drawn? I do think the use-case with the random-walk is relevant, but not the most common one so I think it'd be better to default to sampling with the same shape but allow for passing of a different argument.

**Comment by fonnesbeck** [comment]
@stevenmanton If I'm understanding the code correctly, it is drawing values that correspond to the observed values, so if you, say, were running a regression model y ~ x where there were 10 observations, you would get 10 distributions from `sample_ppc`, one for each observation. This explicitly makes them posterior predictive checks, and not general samples from the posterior predictive distribution. This function would not give you, for example, imputed values or potential future observations without generalizing the function, right?

**Comment by stevenmanton** [comment]
@twiecki Currently, if all the dependent/ancestor variables are scalar, the produced ppc will also be scalar unless a size is specified. This is because of what @mwibrow explained.

I agree that this should not be the default. I can simply make the size default to the observed variable size, but that would mean I'd have to specify a size the random walk case I described (whereas now I do not have to). If I can think of a clever way to handle both cases without passing a size parameter, I'll do so and recommit. Otherwise I'll default size to the observed variable size and require the size kwarg for other sizes.

**Comment by stevenmanton** [comment]
@fonnesbeck Thanks for the interesting discussion. You're right at the limit of my understanding of Bayesian statistics, but I think you're probably right regarding not sampling from the posterior predictive distribution. You still can use `sample_ppc` to sample from non-observed variables, say a latent variable in a model, which may be pretty useful at times. I just wanted to make the distinction that the function isn't limited to observed variables.

**Comment by fonnesbeck** [comment]
Right, I just noticed the `vars` default argument. You are certainly sampling from the posterior predictive distribution, but only for at points established by the data inputs in the model.

**Comment by stevenmanton** [comment]
This size thing seems tricky. There are a bunch of different use cases to handle for if we're trying to be intelligent about automatically choosing the appropriate size parameter.

For example, if the observed variable were to return a scalar from `random`, then passing the size of observation seems reasonable. But what value do you use to get the size? If you use `tag.test_value`, then if you update the observed data via a shared variable, then `tag.test_value` doesn't reflect the size of the data. You could try `shared_var.shape.eval()`, but I've had this fail on me as well. (For example, if there's a missing data variable.)

If the observed variable were to return a vector from `random`, then passing a `size` parameter seems to make `random` actually return a matrix. You could pass `None` to `random` and get the correct shape, but then how do you distinguish from the case when it returns a scalar unless you actually call `random`, look at the shape, and then decide whether or not to pass size.

These two cases are illustrated in the [example notebook](https://pymc-devs.github.io/pymc3/posterior_predictive/).

Thoughts? I seem to think that passing a size option, while maybe a bit cumbersome, is the safest and most intuitive option.

**Comment by stevenmanton** [comment]
How do we feel about merging this pull request? It seems the issue with the `size` argument isn't fully resolved (in the sense that it doesn't automatically choose the size likely intended by the user), but as long as the API doesn't change, might we be able to add that later? I feel like the function as-is is pretty useful and still quite sensible. I'd like to work on adding other features :-)

**Comment by twiecki** [comment]
@stevenmanton Fair enough. I'll merge this.

**Comment by twiecki** [comment]
Merged with https://github.com/pymc-devs/pymc3/commit/305ac4550c41831b9140853bfe1536d01b7b38c6. Thanks for the contribution!

**Pull request closed without merging**
