### PR TITLE
Fixed inconsistency of advi and opvi include_transformed param

### LINKED ISSUE #2102: Inconsistent api in ADVI and OPVI
This is a small thing, but `opvi.Approximation.sample` and `advi.sample_vp` use the keyword argument `hide_transformed`, while `stats.summary`, `stats.df_summary`, and a few of the plotting functions use the keyword argument `include_transformed`.  We should standardize on just one.

I have a preference for `include_transformed`, since it avoids double negatives (which are awkward in English).

### PR DESCRIPTION
**Pull request by denadai2**
Fixes #2102

### CODE REVIEW

**Comment by denadai2** [comment]
I add a note: I just removed the inconsistency on the code BUT sometimes the transformed variables are included, sometimes no. Shouldn't we check also the consistency of default values of this parameter?

**Comment by twiecki** [comment]
Thanks @denadai2. Where is the inconsistency? In the examples?

**Comment by twiecki** [comment]
Oh for the default parameters, yes, it seems like we'd want consistency there. Although I can see cases where for sampling we want default yes, but for display we do not. Is there a pattern?

**Comment by denadai2** [comment]
If sampling = yes and display=no, it's ok! :))

**Pull request merged**
