### PR TITLE
Implement missing values and automatic log-likelihoods derivations

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR makes the changes necessary for missing value-related functionality.

A key component to this functionality is the ability to derive log-likelihood graphs for non-`RandomVariable` graphs.  More specifically, this PR extends the scope of `pymc3.distributions.logp.logpt` into graphs corresponding to expressions like `Y[idx] = data` (e.g. `aesara.tensor.set_subtensor(Normal("Y")[idx], data)`).

Further down this path, we'll implement log-likelihoods for arbitrary sums, differences, indexing with random variables, etc.  These `logpt` features will&mdash;for instance&mdash;automate the construction of discrete mixtures defined by simple expressions like `Normal("X") * I + Normal("Y") * (1 - I)` where `I = Bernoulli("I", p)`, or `aesara.tensor.stack([X, Y])[I]`, etc.

### CODE REVIEW

**Comment by brandonwillard** [comment]
All right, this PR has missing values implemented, but it doesn't add any missing values variables to the `Model` objects; instead, missing values are automatically sampled within the log-likelihood functions that contain them.

To summarize, when a log-likelihood is created for an observed random variable, `rv_var`, with missing values given by the indices `mask` and observed data `data`, the observations variable used in the resulting log-likelihood graph, `obs`, are equal to something like 
```python
obs = copy(rv_var)
obs[~mask] = data
```
and the result is `logpt(rv_var, data)`.  See [here](https://github.com/brandonwillard/pymc3/blob/f306a64049cf7505bc26131539913d519edfb308/pymc3/distributions/logp.py#L278).

**Comment by brandonwillard** [comment]
@pymc-devs/core-devs, do we want to go forward with this missing values approach?  I believe it differs from the original approach in terms of the values used for imputation.

**Comment by ricardoV94** [comment]
> Further down this path, we'll implement log-likelihoods for arbitrary sums, differences, indexing with random variables, etc. These `logpt` features will—for instance—automate the construction of discrete mixtures defined by simple expressions like `Normal("X") * I + Normal("Y") * (1 - I)` where `I = Bernoulli("I", p)`, or `aesara.tensor.stack([X, Y])[I]`, etc.

How would you indicate you want to condition your mixture on observations, or that you want to marginalize the bernoulli variable?

**Comment by brandonwillard** [comment]
> How would you indicate you want to condition your mixture on observations, or that you want to marginalize the bernoulli variable?

We could provide a `Distribution`-like interface for that (e.g. `Observed(at.stack([X, Y])[I], data)`).  For that matter, we could add an `observed` keyword to `Deterministic`, although I think the word "deterministic" doesn't really apply well in this scenario.

**Comment by brandonwillard** [comment]
As an example, I just pushed a `logpt` implementation for `*Subtensor*` `Op`s (i.e. indexing).  With that, we can automatically derive log-likelihoods for terms like `Y[I]`.  

See [this test](https://github.com/brandonwillard/pymc3/blob/f326c955dd3a570ec680fd7ba15836fd1d601753/pymc3/tests/test_logp.py#L140) for a complete example of a basic "switching" model.

Next, I can implement a lift rewrite for `*Subtensor*` `Op`s applied to `Joins` and that would allow us to define nearly arbitrary discrete mixtures and switching models via terms like `at.stack([X, Y])[I]`.

**Pull request merged**
