### PR TITLE
Adding coords, dims, and some optimizations to numpyro-based sampler

### PR DESCRIPTION
**Pull request by zaxtax**
This is further work to make the output of `sample_numpyro_nuts` indistinguishable from the default sampler output.

Any feedback on how to test coords and dims from @OriolAbril and @ricardoV94 is more than welcome!

Also interested in what the inference library field should be for this xarray? Should I use numpyro or pymc?

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
> Also interested in what the inference library field should be for this xarray? Should I use numpyro or pymc?

I guess Numpyro?

**Comment by twiecki** [comment]
Or maybe `pymc-numpyro`?

**Comment by zaxtax** [comment]
I think it's good to merge either way. But it might be worth somewhere else discussing whether it should be `pymc`, `numpyro`, or `pymc-numypro` and if it's `pymc-numpyro` what version to put there. The version of `pymc` or the version of `numpyro` or some concatenation of those.

**Comment by twiecki** [comment]
This is great, thanks @zaxtax!

What are your experiences with this sampler?

**Comment by twiecki** [comment]
We've also been meaning to add the blackjax sampler, any interest in working on this?

**Comment by zaxtax** [comment]
> This is great, thanks @zaxtax!
> 
> What are your experiences with this sampler?

The numpyro sampler has in my experience been consistently the most performant sampler. If you can use it it's always worth it to do so. I'm curious what the plan is with integrating jax-based samplers. Is the goal to have blackjax, tfp, and numpyro? Or just include blackjax?

**Comment by twiecki** [comment]
Good to know. Probably just blackjax, tfp nuts didn't work well.

**Comment by zaxtax** [comment]
Alright. In that case there needs to be some work on blackjax since it's noticeably slower than numpyro. I don't see any reason there should be any difference between them, but it would be silly to drop numpyro support until blackjax is roughly as performant.

**Comment by ricardoV94** [comment]
> Alright. In that case there needs to be some work on blackjax since it's noticeably slower than numpyro. I don't see any reason there should be any difference between them, but it would be silly to drop numpyro support until blackjax is roughly as performant.

We are not planning to drop numpyro, the idea was to have both options, if they both work. 

What kind of model are you basing your performance comparisons upon?

**Comment by zaxtax** [comment]
I was using non-centered eight schools, following the examples in:

https://github.com/blackjax-devs/blackjax/blob/main/notebooks/use_with_numpyro.ipynb
https://docs.pymc.io/en/v3/pymc-examples/examples/diagnostics_and_criticism/Diagnosing_biased_Inference_with_Divergences.html

**Comment by twiecki** [comment]
> Alright. In that case there needs to be some work on blackjax since it's noticeably slower than numpyro.

That's good to know. CC @rlouf

**Comment by rlouf** [comment]
We're aware of performance issues with the warmup, which should be solved with a design change that @junpenglao is working on. Sampling itself should take about the same time.

**Comment by rlouf** [comment]
@ricardoV94 suggested I
open a PR with a blackjax sampler for PyMC, which I will do once the `AeHMC` NUTS sampler is finalized.

**Comment by twiecki** [comment]
That'd be awesome @rlouf.

**Comment by zaxtax** [comment]
> We're aware of performance issues with the warmup, which should be solved with a design change that @junpenglao is working on. Sampling itself should take about the same time.

That's really neat. What's the best way I can help?

**Comment by twiecki** [comment]
@zaxtax I think you can go ahead an start on adding blackjax similar to how numpyro is in here while @rlouf finishes up `aehmc`.

**Pull request merged**
