### PR TITLE
Default VonMises  kappa to 1.0 and fix math notation in doc

### PR DESCRIPTION
**Pull request by williambdean**
**What is this PR about?**
This PR fixes the default value concern raised in the issue [here](https://github.com/pymc-devs/pymc/issues/6418). The docs are also adjusted. 

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- None

## New features
- VonMises without args will allow sampling

## Bugfixes
- pm.draw, pm.sample... will now produce sample with defaults / no args in VonMises distribution

## Documentation
- The math will render now. Defaults now updated

## Maintenance
- ...

### CODE REVIEW

**Comment by wd60622** [comment]
I didn't see any tests for checking the samples of the VonMises distribution. The tests that I did see provided a kappa all that were not the prior default (None)

If there is a place someone feels appropriate to add an additional test, let me know.

**Review by ricardoV94 — APPROVED** [review]
I suggest we don't need a test for this one, I don't think we test default parameters anywhere else

**Comment by wd60622** [comment]
New docs

von-mises-new-docs

**Comment by ricardoV94** [comment]
Thanks @wd60622 !

**Pull request merged**
