### PR TITLE
add analytics

### PR DESCRIPTION
**Pull request by OriolAbril**
Adds google analytics to docs following the guidance on sphinx faq: https://www.sphinx-doc.org/en/master/faq.html and configures it to use pymc code

### CODE REVIEW

**Review by ColCarroll — APPROVED** [review]
LGTM, leaving open for a bit in case others want to comment.

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Where can we view them?

**Comment by OriolAbril** [comment]
logging to https://analytics.google.com from the pymc gmail account. There are two "properties", one for pymcon and another for docs. We have to rebuild and push docs for the changes to be effective here though

**Comment by rpgoldman** [comment]
Hmmmm..... Are we sure that this won't break our docs if readers disable Google Analytics from their browser? I routinely do this, because it seems nosy and I don't understand it.

**Comment by OriolAbril** [comment]
do https://numpy.org and https://pandas.pydata.org work for you with google analytics disabled?

**Pull request merged**
