### PR TITLE
Move IO operations into `smc_text.py`

### PR DESCRIPTION
**Pull request by ColCarroll**
Pretty big refactor -- tried to move all the file I/O out of `smc.py` and into `smc_text.py`.  This changed the sampling algorithm at some point that I couldn't find, so I changed the hardcoded samples too (`test_smc.py` still passes, the samples don't look obviously wrong, and the experimental warning is still there).   There was also a problem with `calc_covariance` not returning matrices that was fixed.

Next up should be actually reviewing the algorithm.

### CODE REVIEW

**Comment by twiecki** [comment]
LGTM.

**Comment by hvasbath** [comment]
Awesome refactoring! There it was actually really visible what a programming noob I still am ... Not sure in which way this could have affected the algorithm. Have to check longer ... However I am surprised that calc_covariance can ever return a 1-d array- when is that the case?

**Comment by ColCarroll** [comment]
Thanks -- this is a good way for me to learn more about this!  

The covariance was sometimes just a number, and needed to be a `1x1` matrix.

**Comment by hvasbath** [comment]
Ah that means you have only one RV size 1 to sample over? If not, there must be a problem somewhere else.

**Pull request merged**
