### PR TITLE
Chain transformation

### PR DESCRIPTION
**Pull request by junpenglao**
Add chain transformation, with additional tests for distributions that are by default using transform.

### CODE REVIEW

**Comment by twiecki** [comment]
This is great stuff! Can you add an example to the docs?

**Comment by junpenglao** [comment]
Will work on it.

**Comment by fonnesbeck** [comment]
You should (at least briefly) update the docs to describe this. The API QuickStart would probably be the best place.

**Comment by fonnesbeck** [comment]
The API QuickStart would probably be the best place.

**Comment by junpenglao** [comment]
> The API QuickStart would probably be the best place.

I was looking at the doc and thinking maybe changing http://docs.pymc.io/prob_dists.html is also an option?
My idea would be changing the title of the page:
Probability Distributions --> Random Variable and Probability Distributions
As it is more accurate.

And then add `Transformation of variable` before auto transformation, and different transformation after `Auto-transformation` (the logic is besides auto-transformation you can also specify transformation)

**Comment by twiecki** [comment]
That sounds like a good spot.

**Comment by junpenglao** [comment]
I follow @fonnesbeck's suggestion at the end - will change the `Probability Distributions` session in another PR.

**Comment by twiecki** [comment]
"For example, we can combining the ordered transformation and logodd transformation to create 2D RVs that satisfy $x_1, x_2 \sim \text{Uniform}(0, 1) \space and \space x_1&lt; x_2$"
->
"For example, we can combine the ordered transformation and logodd transformation using `Chain` to create 2D RVs that satisfy $x_1, x_2 \sim \text{Uniform}(0, 1) \space and \space x_1&lt; x_2$"

**Comment by twiecki** [comment]
It's a good one!

**Pull request merged**
