### PR TITLE
Histogram: use only free RVs from trace

### PR DESCRIPTION
**Pull request by ferrine**
While experimenting I found that TransformedRVs are quite different from regular ones and Histogram fails on them. This PR fixes the problem

P.S. according to conventions I switched to memoize usage in one property

### CODE REVIEW

**Comment by twiecki** [comment]
LGTM.

**Comment by ferrine** [comment]
What's up with coveralls?

**Comment by twiecki** [comment]
Not sure, I restarted the build.

**Comment by ferrine** [comment]
Doesn't help

**Comment by ferrine** [comment]
I've merged. It's coveralls problems, not ours

**Pull request merged**
