### PR TITLE
Speed up to DIC and BPIC

### LINKED ISSUE #2487: DIC method taking hours
Hello,
I'm using the DIC function in a model with 10'000 iterations and 3 chains. It takes hours (~3) to compute the DIC and I found the problem is at this line https://github.com/pymc-devs/pymc3/blob/3232e160dfc728546c4dcedfc0a195831bcd1cf4/pymc3/stats.py#L119.

I tried to parallelize it, but it seems it doesn't parallelize easily. Can you help me?

### PR DESCRIPTION
**Pull request by denadai2**
Fixes #2487

### CODE REVIEW

**Comment by springcoil** [comment]
LGTM. 

Can someone explain to me why this is a significant speed up?

**Comment by ColCarroll** [comment]
This is maybe a bad design choice, but 

https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L156 

makes the `logp` look like an attribute, when it actually puts together a function based on the current state of the model.  In this case the underlying state is not changing, so the function can be calculated just once, then reused.

I say _maybe_ a bad design choice because it makes the code way more readable, and is only a problem when `logp` is computed in an inner loop without updating the model, as it is here.

**Comment by springcoil** [comment]
What would be the solution then? If this is a bad design choice?

**Comment by junpenglao** [comment]
@springcoil we also have more discussions here: https://github.com/pymc-devs/pymc3/issues/2480

**Comment by ColCarroll** [comment]
There's sort of three metrics at odds:  performance for changing input, performance for static input, and ease of use.  There are three approaches I can think of that address these to various amounts --
The "safe" option is to make this an honest function call -- not as easy to use, but performant in any situation.  Something like:

```
logp = model.get_logp()
logp(pt)
```

The current and previous APIs are super easy to use, but only performant in one of the two situations:  the old API used a call to `memoize` which does great in this situation, but terrible if the state keeps changing.

The current design is super maintainable, does terrible if the state stays constant, and great if the state keeps changing.

I haven't looked too closely, but I think it would be super brittle to optimize all three of those concerns, since you would probably have to track when state is changing.

**Comment by springcoil** [comment]
I'd agree that it's really hard to optimize all three of those concerns. It's kinda a multi-objective optimization problem - so difficult :) 

As a prejudice - I'd aim for ease of maintainability and for handling situations were state is changing (because that's often the main use case for users in my understanding), and just accept that this is a negative part of the design for when state needs to be constant. 

Maybe this needs to be written up somewhere in the documentation - or is this sufficient? 

@twiecki @fonnesbeck @ferrine ?

**Comment by junpenglao** [comment]
We should put it in the API quick start http://docs.pymc.io/en/latest/notebooks/api_quickstart.html where model.logp is called.

**Comment by junpenglao** [comment]
Thanks for the fixed @denadai2 ;-)

**Comment by denadai2** [comment]
@junpenglao np!

**Pull request merged**
