### PR TITLE
Fix docker image build

### LINKED ISSUE #5974: Docker image GH action build is broken
Made a new release, got this error:
`The workflow is not valid. .github/workflows/docker-image.yml (Line: 30, Col: 9): Unexpected value 'tags'`

Recently added through https://github.com/pymc-devs/pymc/pull/5966

### PR DESCRIPTION
**Pull request by symeneses**
**What is this PR about?**

It fixes #5974. 
In the local test, the step was working but it looks like the indentation of `tags` is wrong.

...

**Checklist**
+ [ ] Explain important implementation details 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## Bugfixes / New features
- ...

## Docs / Maintenance
- ...

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
@michaelosthege had some ideas of how to test this.

**Comment by michaelosthege** [comment]
@twiecki please review & merge #5976 first. We don't want to trigger the test pipelines all the time.

@symeneses once that's merged please rebase onto `main` and also include the changes I did in #5975.

**Comment by michaelosthege** [comment]
@symeneses that other PR is merged now, so you could rebase now & start testing the steps right in the PR.
Let me know if you have time (or not) then we can decide whether to proceed here, or over in #5975 :)

**Comment by symeneses** [comment]
> @symeneses that other PR is merged now, so you could rebase now & start testing the steps right in the PR. Let me know if you have time (or not) then we can decide whether to proceed here, or over in #5975 :)

I can test now. I will add the changes from #5975

**Comment by symeneses** [comment]
It looks like it's working now,[ it failed in my fork ](https://github.com/symeneses/pymc/actions/runs/2691175769)as I don't have the secrets. 

Let me know if everything is fine to remove the comments.

**Comment by michaelosthege** [comment]
Lookig good! This pipeline run https://github.com/pymc-devs/pymc/runs/7392065463?check_suite_focus=true confirmed the build and test steps.

Now let's uncomment the commented-out sections and then we can sqash-merge

**Review by michaelosthege — APPROVED** [review]
🚀

**Pull request merged**
