### PR TITLE
Strip observed in prior predictive V4

### PR DESCRIPTION
**Pull request by ricardoV94**
Strip observed in prior predictive to replicate old behavior in V3

### CODE REVIEW

**Review by twiecki — DISMISSED** [review]

**Comment by twiecki** [comment]
What was the behavior before this and why didn't a test catch this?

**Comment by ricardoV94** [comment]
The behavior before was to resample the observed variables. There was an open issue about perhaps making this optional: https://github.com/pymc-devs/pymc3/issues/3592

**Comment by ricardoV94** [comment]
I can add a quick test. What do you think?

**Comment by twiecki** [comment]
Great!

**Review by michaelosthege — DISMISSED** [review]

**Comment by ricardoV94** [comment]
I think this test was supposed to capture this behavior but was being used with the wrong values: https://github.com/pymc-devs/pymc3/pull/4524/files#diff-6e6fc11cfc0436b0afd1e8493c54027012f5721bb1cf1139657ea001338a9900

With the changes, it would have failed before this PR.

**Review by michaelosthege — APPROVED** [review]
Well spotted with that test case!

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Indeed - thanks @ricardoV94!

**Pull request merged**
