### PR TITLE
Refactor examples to standard format with a base class

### LINKED ISSUE #1356: Get examples running
The example suite touches a lot of the code that the tests miss (for example, #1355), and `test_examples` is a nice way of running them all, but it isn't run on travis (since it fails in a lot of ways).  

I have started working on getting them running again -- any objections to a `Pymc3Example` class to provide a template for example code?  It seems just requiring a `set_up` and `run` method would help.

### PR DESCRIPTION
**Pull request by ColCarroll**
PR to fix #1356 isn't ready until I refactor the other examples, but wanted to get any comments while it was still easy to change the design.  Each example is an instance of `Pymc3Example`, and there's a dictionary of very rough benchmarks in `__init__.py` that controls what actually gets run in the test suite (I arbitrarily chose 30s as the max time an example can run for).

### CODE REVIEW

**Comment by ColCarroll** [comment]
Updated according to #1356, adding 
- `disaster_model_missing`
- `hierarchical`
- `hierarchical_sqlite`
- `latent_occupancy`
- `rsv`

to the (potential) example test suite.  There are a number of examples that should probably be deleted, and others that might be refactored, but didn't want to make this diff larger than it had to be.  There would also need to be an update to travis to add `test_examples` to one of the test runs.

**Comment by ColCarroll** [comment]
Updated to actually run the examples above in the test suite.  This actually doesn't improve test coverage very much in the rest of the library (34 extra non-example lines are covered!)  It slows down total time for test runs (because more tests), but since it is split in 3, it does not slow total time.  In any case happy to update with any suggested changes (or close this if it isn't wanted!)

Also, since it might be of interest, here are the files with <=80% coverage on master:

```
Name                                     Stmts   Miss  Cover
------------------------------------------------------------
pymc3/backends/ndarray.py                   55      9    84%
pymc3/data.py                                5      1    80%
pymc3/debug.py                               5      2    60%
pymc3/distributions/multivariate.py        191     74    61%
pymc3/distributions/timeseries.py           53     38    28%
pymc3/examples/arbitrary_stochastic.py      19      8    58%
pymc3/examples/disaster_model.py            23      9    61%
pymc3/glm/glm.py                            63     16    75%
pymc3/interactive_sampling.py               59     52    12%
pymc3/plots.py                             345    166    52%
pymc3/step_methods/ATMCMC.py               285    251    12%
pymc3/step_methods/gibbs.py                 40     21    48%
pymc3/step_methods/metropolis.py           149     36    76%
pymc3/step_methods/quadpotential.py         92     31    66%
pymc3/tuning/scaling.py                     64     32    50%
pymc3/variational/advi_minibatch.py        161     36    78%
```

**Comment by twiecki** [comment]
Probably these should have more coverage:

```
pymc3/step_methods/ATMCMC.py               285    251    12%
pymc3/step_methods/gibbs.py                 40     21    48%
pymc3/step_methods/metropolis.py           149     36    76%
pymc3/step_methods/quadpotential.py         92     31    66%
pymc3/tuning/scaling.py                     64     32    50%
pymc3/variational/advi_minibatch.py        161     36    78%
```

As we don't get much better coverage, but I still think it's useful to have some models run, I suggest we use this style on some select models which we move to the test-folder and leave the other ones here and keep the file simple. Eventually, these models should be ported to ipynbs and added to the docs properly.

@ColCarroll What do you think?

**Comment by ColCarroll** [comment]
@twiecki sounds good -- refactored the PR, got rid of examples marked for retirement in #1356, and got rid of those examples that are duplicated in the notebooks section.

**Comment by springcoil** [comment]
Seems there's a conflicting .travis.yml file - is this because of the other changes you made @ColCarroll

**Review by springcoil — CHANGES_REQUESTED** [review]
The only thing that needs fixed is the travis.yml file - otherwise I see no reason why this can't be merged - especially since Thomas already reviewed the other changes.

**Comment by twiecki** [comment]
This is fantastic. Very satisfying to see the test coverage increase, too.

**Pull request merged**
