### PR TITLE
Set joblib to not use most recent version.

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by twiecki** [comment]
OK, I'll merge this to get travis working again.

**Comment by wanjuanzhang** [comment]
Hello, I also had the same problem when using pycm3. Is there any solution?

**Comment by twiecki** [comment]
@wanjuanzhang Downgrade joblib.

**Comment by wanjuanzhang** [comment]
Hello, I have downgraded the joblib, but the program is often unable to run and does not respond.

**Comment by twiecki** [comment]
@wanjuanzhang Alternatively, update to python 3.

**Comment by wanjuanzhang** [comment]
Thank you very much, your suggestion is very useful to me. I have successfully run the program. Have a nice day.

**Comment by twiecki** [comment]
Glad it's working for you.

**Pull request merged**
