### PR TITLE
Add typing to discrete distributions

### PR DESCRIPTION
**Pull request by jessica-writes-code**
**What is this PR about?**
Per #5358 , it would be nice to have type hints for distribution parameters.

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- N/A

## New features
- N/A

## Bugfixes
- N/A

## Documentation
- N/A

## Maintenance
- Add typing for distribution parameters.

### CODE REVIEW

**Comment by canyon289** [comment]
Thanks for contributing to PyMC!

**Comment by jessica-writes-code** [comment]
It seems like the new typing has introduced a mypy error that didn't exist before in `discrete.py`, but exists in several other files -- that the signatures for `dist` in the child classes are incompatible with the parent. I'm not sure there exists a good short-term fix, but I think there are two (probably more) potential long-term fixes:
(1) Adjust signature of `dist` in the `Distribution` class. (This will probably require adjusting how it is called in several places.)
(2) Rename the `dist` method of the `Distribution` class.
My vote is for (1), but I'm happy to work on either, if it would be useful.

(Also, apologies for not commenting on #5358 before starting this. I'll make sure to do that more effectively going forward.)

**Comment by ricardoV94** [comment]
Has this PR been superseded by others?

Not sure who to ping: @OriolAbril ?

**Comment by OriolAbril** [comment]
I have no idea about typing, sorry

**Comment by ricardoV94** [comment]
Sorry, I thought this PR was part of some sprint

**Comment by ricardoV94** [comment]
It seems the type-hints are still missing on main. @jessica-writes-code can you fix the conflicts that have emerged in the PR?

**Comment by jessica-writes-code** [comment]
@ricardoV94 Changes made!

**Review by ricardoV94 — APPROVED** [review]
Looks good to me. Thanks @jessica-writes-code

**Comment by jessica-writes-code** [comment]
@ricardoV94 Mypy check is failing. See my comment from Dec 25. Happy to pursue either option or any alternative you suggest!

**Comment by ricardoV94** [comment]
I am closing this one as a long time has passed. Type hints may already have been improved in the meantime. Feel free to reopen a PR if type hints are still missing. Thanks for the help!

**Pull request closed without merging**
