### PR TITLE
update docstrings in ZeroInflatedPoisson, DiracDelta and OrderedLogistic classes

### PR DESCRIPTION
**Pull request by saurbhc**
**What is this PR about?**
Issue #5459  - Update Docstrings for ZeroInflatedPoisson, DiracDelta and OrderedLogistic classes 

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- None

## Bugfixes / New features
- None

## Docs / Maintenance
- Yes, as per the issue #5459 

#DataUmbrellaPyMCSprint
cc: @reshamas 
cc: @mariyayb

### CODE REVIEW

**Comment by cluhmann** [comment]
The types and spacing look good to me.  You might want to include `:context: close-figs` just after the `.. plot::` as detailed in [the tutorial](https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/docstring_tutorial.html#section-independent-comments).

**Comment by cluhmann** [comment]
This LGTM.  Just need a core dev to approve.

**Review by aloctavodia — APPROVED** [review]
LGTM

**Comment by aloctavodia** [comment]
thanks @saurbhc!

**Pull request merged**
