### PR TITLE
Switch to setup-micromamba action

### PR DESCRIPTION
**Pull request by maresb**
## Related Issue

- [X] Closes #7046
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [X] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7213.org.readthedocs.build/en/7213/

### CODE REVIEW

**Comment by maresb** [comment]
I think the error may be fixed here: https://github.com/pymc-devs/pytensor/pull/678

**Comment by maresb** [comment]
Ah ya, thanks, that's the one!

**Review by twiecki — APPROVED** [review]
Looks much simpler.

**Comment by ricardoV94** [comment]
Do we need https://github.com/pymc-devs/pytensor/pull/678 here?

**Comment by twiecki** [comment]
Worth a try.

**Comment by maresb** [comment]
Ok, rebased.

**Comment by maresb** [comment]
That's weird, maybe it needs to be rerun?

image

I still find GH's UI here weird. I can't find a rerun button for that task. Maybe I need to wait until the whole thing finishes?

**Comment by ricardoV94** [comment]
Yeah, you can only rerun failed runs once everything is done

**Comment by maresb** [comment]
Just started the rerun. Any idea why I can't view logs (see screenshot)? Is this a GH outage?

**Comment by maresb** [comment]
Viewing the CI logs is still really flaky for me, but somehow I was able to get a glimpse of:

```
 _________________ ERROR collecting tests/sampling/test_jax.py __________________
tests/sampling/test_jax.py:30: in <module>
    from numpyro.infer import MCMC
../../../micromamba/envs/pymc-test/lib/python3.12/site-packages/numpyro/__init__.py:6: in <module>
    from numpyro import compat, diagnostics, distributions, handlers, infer, ops, optim
../../../micromamba/envs/pymc-test/lib/python3.12/site-packages/numpyro/distributions/__init__.py:4: in <module>
    from numpyro.distributions.conjugate import (
../../../micromamba/envs/pymc-test/lib/python3.12/site-packages/numpyro/distributions/conjugate.py:9: in <module>
    from numpyro.distributions.continuous import Beta, Dirichlet, Gamma
../../../micromamba/envs/pymc-test/lib/python3.12/site-packages/numpyro/distributions/continuous.py:36: in <module>
    from jax.scipy.linalg import cho_solve, solve_triangular
../../../micromamba/envs/pymc-test/lib/python3.12/site-packages/jax/scipy/linalg.py:18: in <module>
    from jax._src.scipy.linalg import (
../../../micromamba/envs/pymc-test/lib/python3.12/site-packages/jax/_src/scipy/linalg.py:403: in <module>
    @_wraps(scipy.linalg.tril)
E   AttributeError: module 'scipy.linalg' has no attribute 'tril'
```

Then for attempt #2, which I believe was post-rebase, I think I was still seeing the old "filename too long" error. :cry: But I can't access the logs in order to paste them here...

Am I the only one who is having trouble viewing the CI logs?

**Comment by maresb** [comment]
Regarding `scipy.linalg.tril`, see <https://docs.scipy.org/doc/scipy-1.11.4/reference/generated/scipy.linalg.tril.html>:

> **Deprecated since version 1.11.0**: [`tril`](https://docs.scipy.org/doc/scipy-1.11.4/reference/generated/scipy.linalg.tril.html#scipy.linalg.tril) is deprecated in favour of [`numpy.tril`](https://numpy.org/devdocs/reference/generated/numpy.tril.html#numpy.tril) and will be removed in SciPy 1.13.0.

**Comment by maresb** [comment]
> Yeah, you can only rerun failed runs once everything is done

@ricardoV94, here I at least have a "Re-run" link, even though it doesn't appear to have actually triggered a rerun yet.

image

**Comment by ricardoV94** [comment]
@maresb wanna try to revive this one?

**Comment by maresb** [comment]
Eventually! Thanks @ricardoV94 for the ping. Currently I'm waiting for all the the major micromamba v2 bugs to get resolved before touching this sort of thing.

**Comment by maresb** [comment]
@lucianopaz, would you be interested in helping me revive this?

There are still issues with micromamba v2, but I think there's a decent chance that they won't be problematic here.

**Comment by maresb** [comment]
Supersedes #7580

**Review by lucianopaz — APPROVED** [review]
LGTM!

**Pull request merged**
