### PR TITLE
DOCS: Bayesian Logistic Regression example

### PR DESCRIPTION
**Pull request by springcoil**
I based this example on J. Benjamin Cook, and include a link to his original version.

I included a bit of model selection which can be worked on and reviewed.

cc @jonsedar @AustinRochford @twiecki for review.

### CODE REVIEW

**Comment by jonsedar** [comment]
Nice use of glm to make life easy on the modelspec! Some thoughts:
- It could be nice to have some plots of distributions of the input features - just to get a handle on them.
- I'm not sure any *IC measurement is that useful by itself, would you want to try a couple more modelspecs and see how they score? It might be interesting - in particular, why does the current modelspec include age^2? perhaps it can be justified by comparing DIC with a modelspec that includes raw (1st order) age only
- finally, is it the done thing to include data in the repo? Since it's a public dataset it might be better to just download from UCI

**Comment by AustinRochford** [comment]
Also, there is a typo in the model section.  Should be $p_i = \frac{1}{1 + e^{-z_i}}$ (note the + in the denominator).

**Comment by springcoil** [comment]
The typo is an easy fix thanks @AustinRochford

**Comment by springcoil** [comment]
In the second commit I've sent in improvements for @jonsedar and @AustinRochford to have a look at. 

Nice use of glm to make life easy on the modelspec! Some thoughts:

It could be nice to have some plots of distributions of the input features - just to get a handle on them. - in the commit
I'm not sure any *IC measurement is that useful by itself, would you want to try a couple more modelspecs and see how they score? It might be interesting - in particular, why does the current modelspec include age^2? perhaps it can be justified by comparing DIC with a modelspec that includes raw (1st order) age only - in the commit
finally, is it the done thing to include data in the repo? Since it's a public dataset it might be better to just download from UCI - This is not resolved yet

**Comment by AustinRochford** [comment]
Looks great

**Comment by springcoil** [comment]
Cool. I guess then @twiecki,  @jsalvatier or @fonnesbeck can review this and add it into master. Anyone have any suggestions about the data source? I wasn't able to find any csv versions online with a quick google - perhaps someone knows a good UCI source. Or alternatively we could push this to master now, and I'll find a workaround in the future.

**Comment by jonsedar** [comment]
Looks good, I like the distribution plots. I also see some familiar code in there ;)

The default Adult set is up at https://archive.ics.uci.edu/ml/datasets/Adult - is that usable as is?

**Comment by springcoil** [comment]
I'll have a look at that now. Yes Jon I liberally stole some of your code, but those helper functions work well. You should submit them to the code base, I think they could be some useful contributions to the API.

**Comment by springcoil** [comment]
The default Adult is added to the source code now. I think that's the three pieces of feedback provided by Jon sorted then :) 
Updated to include acknowledgement of your code examples @jonsedar

**Comment by jonsedar** [comment]
I'd say so! Interesting to see the DIC measure leans towards age^2

**Comment by springcoil** [comment]
Yeah that is interesting, I think the original author J. Benjamin Cook just made that choice based on experience of modelling sociological stuff (he did computational sociology for a while). It's interesting to see the DIC measure basically supports that folk-wisdom. 

Like when I worked on risk models professionally, I worked with some non-mathematical professionals who by osmosis picked up the strategy of applying logs to their financial market data. This is a good strategy since most of that data is lognormal, so their intuition was based on sound mathematics but they were unable to articulate this. 

I wonder what other 'good modelling practices' a lot of us do, day-to-day without being able to prove or measure their validity.

**Comment by twiecki** [comment]
Looks great. I might have missed something but I think it's running linear regression, not logistic. For that, pass `family=pm.glm.families.Binomial()` to `glm`.

**Comment by springcoil** [comment]
Thanks for that feedback @twiecki. Updated the logistic regression based on your remark, and added a few more plots to understand the variables.

**Comment by twiecki** [comment]
image

This looks like you need to remove some burn-in draws (same for the plot below).

---

image

This is great -- a legend would make it even better (this is a bit hacky but you will have to specify the colored line artists individually http://matplotlib.org/api/lines_api.html#matplotlib.lines.Line2D and then call `legend([line_blue, line_red, ...], ['hours == 50', ....])`.

---

```
# Linear model with hours == 50 and educ == 16
lm2 = lambda x, samples: 1 / (1 + np.exp(-(samples['Intercept'] + 
                                          samples['age']*x + 
                                          samples['age2']*np.square(x) + 
                                          samples['educ']*16 + 
                                          samples['hours']*50)))
```

Why do you multiply here?

---

## `confidence interval` -> `credible interval` (confidence is frequentist)

image

The bar plot is a bit confusing because the absolute values don't really mean anything. Instead, we're looking for the magnitude of the relative differences. They can be pretty large in this case it seems which alters the interpretation and does seem to select the highest order model (lower scores are better here). Kinda odd but that's what it suggests.

**Comment by springcoil** [comment]
I'm working on some of those improvements. Not sure I can get the legend done though - would appreciate some help with that... :) I'm not very familiar with that aspect of the Matplotlib API. 

To be honest that's code I used from Ben Cooks work - I think the multiplication is because this is just to specify those parameters in the model. I think it works though for those parameters. 
@jbencook can you help explain this to me and Thomas?

**Comment by twiecki** [comment]
e.g.

``` python
import matplotlib.lines as mlines
red_line = mlines.Line2D([], [], color='r', label='mylabel')
plt.legend([red_line])
```

**Comment by springcoil** [comment]
Thanks :)

**Comment by springcoil** [comment]
Legend added, thanks Thomas. I changed those plots. Can't figure out how to fix the bar charts any suggestions. Is this good enough to be merged yet?

**Comment by twiecki** [comment]
Almost :) I'd still change confidence interval to credible interval (confidence is frequentist), should be quick to do.

**Comment by springcoil** [comment]
Done. I've avoided offending the Frequentist gods :)

**Comment by twiecki** [comment]
Available via http://pymc-devs.github.io/pymc3/GLM-logistic/

**Comment by springcoil** [comment]
Cool

On Tue, Jan 12, 2016 at 9:07 AM, Thomas Wiecki notifications@github.com
wrote:

> Available via http://pymc-devs.github.io/pymc3/GLM-logistic/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/931#issuecomment-170832866.

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Pull request merged**
