### PR TITLE
Adding logcdf method to inverse gamma distribution

### PR DESCRIPTION
**Pull request by dfm**
This pull request adds a `logcdf` method to the inverse gamma distribution. It looks like it'll need to wait on [this patch to Theano](https://github.com/Theano/Theano/pull/6751) for the tests to pass, but I wanted to open this anyways and we'll come back to it when it's ready.

An alternative would be to implement this without the `gammaincc` special function (some combination of `gammau` and `gammaln` should do it), but that might have numerical issues.

### CODE REVIEW

**Comment by dfm** [comment]
The Theano patch has been merged, so this should be good to go once the next version of Theano is released. Is there a procedure for dealing with features like this?

**Comment by ColCarroll** [comment]
I was under the impression that `theano` might not be making new releases any more, and pointing to the github version in case people want bugfixes. @nouiz, is that true?

image

**Comment by nouiz** [comment]
I do not plan to make more release and do not know someone that plan to do it. So yes, pointing to the github repo is the right things to do.

**Comment by dfm** [comment]
Got it! I'll let team PyMC3 decide what to do here in that case. This is definitely not a high priority feature. Thanks all!

**Comment by rpgoldman** [comment]
I thought the plan was to issue a release of `pymc-theano`, and move to requiring that. @twiecki ?

**Comment by twiecki** [comment]
Yes, we have a fork even though it's not set up properly yet (travis, conda etc). But it would be quite easy for me to put out another theano release from their original one. This might be a good time to switch, however.

**Comment by dfm** [comment]
I'm happy to help with infrastructure for the fork if that would be useful!

**Comment by twiecki** [comment]
@dfm That would be much appreciated! I just added you to the repo, feel free to push ahead without waiting for sign-offs.

https://github.com/pymc-devs/Theano-PyMC

**Comment by michaelosthege** [comment]
What's the state of this PR ?
Can we get it done for the 3.9 release?

**Comment by dfm** [comment]
Since this requires updates to Theano, I'm not sure that it's worth pushing forward on. It depends on how committed the project is to maintaining releases of the Theano fork. I pushed some updates to the fork to get some infrastructure working, but I'm late to the game so I haven't really been following the plans!

I don't actually need this function for the project that I implemented it for after all so it probably shouldn't be a high priority. Feel free to close this if you think that's best!

**Comment by michaelosthege** [comment]
In todays lab meeting we discussed that we might switch to the Theano fork with 3.11±, but want to maintain compatibility with the "real" Theano for a while too.

Adding a "don't merge" label and tagging @brandonwillard so we can add it when the compatibility is given.

**Comment by dfm** [comment]
Sounds good! Since I'm an idiot and opened this pull request from my master branch I'm going to close this and open a new pull request from a different branch (looks like you can only change the *base* branch of an open pull request :/)

**Comment by dfm** [comment]
New PR at #3944. Sorry about the noise!

**Pull request closed without merging**
