### PR TITLE
Move slightly duplicated RVs to PyTensor 

### PR DESCRIPTION
**Pull request by soma2000-lang**
What is this PR about?

WaldRV (extra param)
StudentTRV (duplicated)
Partially address https://github.com/pymc-devs/pymc/issues/6479
@ricardoV94 @OriolAbril @michaelosthege @larryshamalama @aloctavodia

### CODE REVIEW

**Comment by soma2000-lang** [comment]
just a gentle reminder @ricardoV94 @OriolAbril @michaelosthege @larryshamalama @aloctavodia

**Comment by michaelosthege** [comment]
Looks like the tests fail because WaldRV from PyTensor has a fewer parameters?

`TypeError: WaldRV.__call__() got multiple values for argument 'size'`

**Comment by soma2000-lang** [comment]
@michaelosthege  surely looking into this

**Comment by ricardoV94** [comment]
Closing this one for lack of activity. Feel free to open a new one if you want to still pursue it!

**Pull request closed without merging**
