### PR TITLE
Modifying iter_sample for streaming

### PR DESCRIPTION
**Pull request by ckrapu**
Some use cases can involve sampling many thousands of parameters. While the MCMC samplers are adequate for the problem, the inability to receive samples one-at-a-time presents limitations in terms of system memory which can quickly fill up even with a modest (<5000) number of samples for models with very large parameter sets. It may be useful to allow the `iter_sample` generator to return a single Point, rather than an entire MultiTrace object if the `streaming` keyword argument is set to `True`.

+ The functions `iter_sample` and `_iter_sample` have been modified to change their yielded values based on kwargs; most of the changes happen in the latter function
+ No tests currently exist for this yet.
+ The proposed changes make it so that the type of object returned by `_iter_sample` is a function of `streaming` which may be undesirable behavior and is worth discussing.

For an example of how this works, see the following snippet:

```
import pymc3 as pm

with pm.Model() as model:
    x = pm.Normal('x', shape=2)
    step = pm.NUTS(x)
    gen = pm.iter_sample(5, step, tune=5, streaming=True)

    for trace in gen:
        print(trace)

    gen_full = pm.iter_sample(5, step, tune=5)

    for trace in gen_full:
        print(trace)

    standard_trace = pm.sample(draws=10, tune=10)
    print(standard_trace['x'])
```

### CODE REVIEW

**Comment by michaelosthege** [comment]
Hi @ckrapu , that must be a big model you're dealing with!

The sampling code is already quite convoluted.. An alternative that could give you more features while being more long-term sustainable could be to implement a custom [backend](https://github.com/pymc-devs/pymc3/blob/master/pymc3/backends/base.py).

Leveraging OOP/interfaces we wouldn't need to touch the sampling code then.

Related: https://github.com/pymc-devs/pymc3/wiki/GSoC-2021-projects#replace-backends-with-xarray

**Comment by ckrapu** [comment]
I agree - this was an ugly solution. I like your suggestion of using a backend. Let's see how that turns out! Would you mind labeling this as a WIP?

**Comment by ricardoV94** [comment]
@ckrapu Any progress on this? Should we close this PR

**Comment by mjhajharia** [comment]
this PR was stale from march so i'm closing it, feel free to open it in case you want to continue @ckrapu!!

**Pull request closed without merging**
