### PR TITLE
Add Bayesian survival analysis example

### PR DESCRIPTION
**Pull request by AustinRochford**
@twiecki here it is, per our conversation on Twitter.

Did you want me to add it to `docs/notebooks` as well?  I will admit that I have had a hard time building the docs.

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @AustinRochford. Looks great.

Yes, please add a symbolic link to docs/notebooks as well as include it into `mkdocs.yml`.

**Comment by twiecki** [comment]
Also, please add yourself as an author at the top.

**Comment by twiecki** [comment]
Thanks @AustinRochford!

**Comment by twiecki** [comment]
Now available under http://pymc-devs.github.io/pymc3/survival_analysis/.

**Comment by AustinRochford** [comment]
Thanks!

**Comment by walterreade** [comment]
This is extremely useful. Thanks for putting it together.

**Pull request merged**
