### PR TITLE
Renamed logistic transformation to inverse_logit

### PR DESCRIPTION
**Pull request by fonnesbeck**
Minor change, but is a more accurate name, and complements existing `logit` transform.

### CODE REVIEW

**Comment by twiecki** [comment]
LGTM.

**Comment by fonnesbeck** [comment]
Has the failure with the rsv example been seen before? I don't see how it could be related to this change.

**Comment by twiecki** [comment]
I'm pretty sure it's unrelated and probably caused by some theano funkyness. We should probably just peg the travis version.

**Comment by twiecki** [comment]
Can you rebase against master?

**Comment by jsalvatier** [comment]
looks good.

**Pull request merged**
