### PR TITLE
Speed up and bug fix for test

### PR DESCRIPTION
**Pull request by junpenglao**
Fix travis error (appear after numpy 1.13 upgrade):
```python
E       TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
pymc3/tests/checks.py:6: TypeError
```

### CODE REVIEW

**Comment by junpenglao** [comment]
Has this thing ever occur before?

```python
=================================== FAILURES ===================================
________________________ TestNutsCheckTrace.test_linalg ________________________
self = <pymc3.tests.test_step.TestNutsCheckTrace object at 0x7f3976e970d0>
    def test_linalg(self):
        with Model():
            a = Normal('a', shape=2)
            a = tt.switch(a > 0, np.inf, a)
            b = tt.slinalg.solve(floatX(np.eye(2)), a)
            Normal('c', mu=b, shape=2)
            with warnings.catch_warnings(record=True) as warns:
                trace = sample(20, init=None, tune=5)
            assert np.any(trace['diverging'])
            assert any('diverging samples after tuning' in str(warn.message)
                       for warn in warns)
>           assert any('contains only' in str(warn.message) for warn in warns)
E           assert False
E            +  where False = any(<generator object <genexpr> at 0x7f3988d797d0>)
pymc3/tests/test_step.py:364: AssertionError
```

**Comment by aseyboldt** [comment]
I've never seen this, and I can't think of how that might have happened either. It works on my machine. 😕

**Comment by junpenglao** [comment]
@aseyboldt I cannot reproduce it as well 😕

**Comment by twiecki** [comment]
Thanks @junpenglao!

**Comment by junpenglao** [comment]
@twiecki it's not very pretty but it does the job (for now).

**Pull request merged**
