### PR TITLE
Add terms to the glossary

### PR DESCRIPTION
**Pull request by itsguneetsingh**
Made certain changes to formula for Bayes theorem

### CODE REVIEW

**Comment by michaelosthege** [comment]
The glossary is being edited in #4984 and #4987. Merging this PR would lead to quite some git conflicts.
So please either open a PR into those branches, or contribute edits/glossary terms with the "insert suggestion" feature on the diff.

**Comment by twiecki** [comment]
Thanks @Guneetconvent2002, can you give more descriptive titles?

**Comment by itsguneetsingh** [comment]
> The glossary is being edited in #4984 and #4987. Merging this PR would lead to quite some git conflicts.
> So please either open a PR into those branches, or contribute edits/glossary terms with the "insert suggestion" feature on the diff.

I don't really understand what you mean by the "insert suggestion" feature. About opening a PR in those branches, the 2 PRs have 2 different branches. Which one do you want me to use? or do you want me to put a PR for merging in their repos? I'm a little unclear here

**Comment by itsguneetsingh** [comment]
> Thanks @Guneetconvent2002, can you give more descriptive titles?
Sure, would this be fine?

**Comment by michaelosthege** [comment]
@Guneetconvent2002 #4987 is probably the right one. I was referring to this feature: https://til.hashrocket.com/posts/szgdi4at59-github-insert-a-suggestion-

Also the `CU-...` code in the PR title is to associated with an issue tracker used by the docs team. @martinacantaro can you take over to coordinate here? I'm not in the picture what you're currently doing with the glossary.

**Comment by martinacantaro** [comment]
Hi, I see the title changed to include "(Extension to PR #4986)", but it should say #4987. 
Also, from your comment in PR [#4987](https://github.com/pymc-devs/pymc3/pull/4987#issuecomment-926392545) I see that you will move forward by leaving suggestions on that PR, so I will close this one. Thank you.

**Comment by olgadk7** [comment]
@michaelosthege, thank you for your guidance. I’m also newish to OS and a little unclear on the process. Originally, the glossary instructions were for each contributor to work out of their own branch, thus #4984,  #4987, and #5014 were created (I assumed conflicts could be resolved by some rebasing). So what’s a principled way for several people to add to the same file simultaneously? If this PR (#5014) leads to conflict, then either #4984 or #4987 (whoever comes second?) would too - will it also be resolved by inserting suggestions? And how is #4987 “probably the right one” vs #4984.

**Comment by michaelosthege** [comment]
@olgadk7
You'll get git conflicts whenever two people edit the same lines (or when a lot has changed and git can't align it).
Technically you can resolve them by rebasing, but it's a rather advanced git technique and could be quite a hurdle for new contributors (I learned it less than a year ago).
Also all these rebase-related force-pushes trigger the CI pipeline which in our case consumes quite a lot of energy.

If you're creating the document from scratch and everybody is working on all paragraphs maybe draft it in HackMD or Google Docs first?
You can add [`Co-authored-by`](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) to a commit message to track contributions. It's automatically appended when using the "insert suggestion" feature.

Otherwise the best way to keep PRs conflict-free is fast iteration and avoiding to edit the same file simultaneously with multiple people.

**Comment by OriolAbril** [comment]
@Guneetconvent2002 as the other PR was merged before incorporating your comments I have reopened this one and fixed the git conflicts in order to merge your contributions and give you proper attribution.

**Review by OriolAbril — APPROVED** [review]

**Comment by itsguneetsingh** [comment]
Thank you @OriolAbril means a lot

**Pull request merged**
