### PR TITLE
update fastprogress import

### LINKED ISSUE #3749: Fatsprogress import
## Description of your problem

fastprogress 0.2.0 has new location for `progress_bar`

**Please provide a minimal, self-contained, and reproducible example.**

`from fastprogress import progress_bar` --> `from fastprogress.fastprogress import progress_bar`

**Please provide the full traceback.**
```
from fastprogress import progress_bar
ImportError: cannot import name 'progress_bar'
```

### PR DESCRIPTION
**Pull request by ahartikainen**
Fixes #3749 

Update fastprogress import statements from 5 files.

### CODE REVIEW

**Review by michaelosthege — APPROVED** [review]
LGTM

**Comment by ahartikainen** [comment]
I think you also should update the requirements.txt

    fastprogress>=0.1.21 --> fastprogress>=0.2.0

**Comment by ahartikainen** [comment]
I think you need to reset travis cache.

**Comment by ColCarroll** [comment]
Just cleared cache and kicked off the build again.

**Comment by ahartikainen** [comment]
`auto_update` is apparently removed, so it can not be disabled.

You could change the `__iter__` method for the `ProgressBar` class

```
    def __iter__(self):
        if self.total != 0: self.update(0)
        try:
            for i,o in enumerate(self.gen):
                if i >= self.total: break
                yield o
                self.update(i+1)
        except Exception as e:
            self.on_interrupt()
            raise e
```

Not sure how easy that would be.

https://github.com/fastai/fastprogress/blob/master/fastprogress/fastprogress.py

**Pull request merged**
