### PR TITLE
hdf5 trace

### PR DESCRIPTION
**Pull request by philastrophist**
An hdf5 trace based on `h5py`. `H5py`'s array structure makes it's api effectively the same as `NDArray`.
Example:
```
trace = pm.sample(5000, trace='hdf5')
```

### CODE REVIEW

**Comment by fonnesbeck** [comment]
This would be a good addition. We definitely would need tests for this, as it did tend to break every so often under PyMC 2.

**Comment by ColCarroll** [comment]
don't forget setup.py/requirements.txt!

**Comment by philastrophist** [comment]
Tests underway, they would just be the same as the others, so it should be quick.
I'll add the requirement and the tests tomorrow if I have time.

**Comment by twiecki** [comment]
```
======================================================================
ERROR: test_clean_interrupt (pymc3.tests.test_hdf5_backend.TestHDF50dSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 127, in test_clean_interrupt
    self.strace.close()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 105, in close
    for ds in self.samples.itervalues():
AttributeError: 'File' object has no attribute 'itervalues'
======================================================================
ERROR: test suite for <class 'pymc3.tests.test_hdf5_backend.TestHDF50dSelection'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 63, in setUpClass
    strace1.setup(cls.draws, chain=1)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 88, in setup
    for v in self.samples.itervalues():
AttributeError: 'File' object has no attribute 'itervalues'
======================================================================
ERROR: test_clean_interrupt (pymc3.tests.test_hdf5_backend.TestHDF51dSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 31, in setUp
    self.strace.setup(self.draws, self.chain)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
======================================================================
ERROR: test_standard_close (pymc3.tests.test_hdf5_backend.TestHDF51dSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 31, in setUp
    self.strace.setup(self.draws, self.chain)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
======================================================================
ERROR: test suite for <class 'pymc3.tests.test_hdf5_backend.TestHDF51dSelection'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 62, in setUpClass
    strace0.setup(cls.draws, chain=0)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
======================================================================
ERROR: test_clean_interrupt (pymc3.tests.test_hdf5_backend.TestHDF52dSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 31, in setUp
    self.strace.setup(self.draws, self.chain)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
======================================================================
ERROR: test_standard_close (pymc3.tests.test_hdf5_backend.TestHDF52dSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 31, in setUp
    self.strace.setup(self.draws, self.chain)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
======================================================================
ERROR: test suite for <class 'pymc3.tests.test_hdf5_backend.TestHDF52dSelection'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 62, in setUpClass
    strace0.setup(cls.draws, chain=0)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
======================================================================
ERROR: test suite for <class 'pymc3.tests.test_hdf5_backend.TestHDF5DumpLoad'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 267, in setUpClass
    super(DumpLoadTestCase, cls).setUpClass()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 62, in setUpClass
    strace0.setup(cls.draws, chain=0)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
======================================================================
ERROR: test suite for <class 'pymc3.tests.test_hdf5_backend.TestNDArrayHDF5Equality'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 316, in setUpClass
    super(BackendEqualityTestCase, cls).setUpClass()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/backend_fixtures.py", line 62, in setUpClass
    strace0.setup(cls.draws, chain=0)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 92, in setup
    old_draws = len(self)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/backends/hdf5.py", line 146, in __len__
    return self.samples.values()[0].shape[1]
TypeError: 'ValuesViewHDF5' object does not support indexing
```

**Comment by philastrophist** [comment]
Yes, I'm still using python 2.7 ...

**Comment by philastrophist** [comment]
There seems to be a problem with nose tests

**Comment by twiecki** [comment]
Indeed... opened an issue here: https://github.com/pymc-devs/pymc3/issues/1754

**Comment by philastrophist** [comment]
Tests failed due to other problems with `test_stats`. All backend tests pass

**Comment by twiecki** [comment]
Something seems to have gone wrong with a rebase as there are many commits on here that should not be.

**Comment by twiecki** [comment]
@philastropist can you try to rebase again or cherry pick on a new branch?

**Comment by philastrophist** [comment]
Cherry picked on a new branch and pushed a much cleaner commit history after renaming. All tests pass locally...

**Pull request merged**
