### PR TITLE
Simplify obj_optimizer to optimizer

### PR DESCRIPTION
**Pull request by fonnesbeck**
Since there is only one optimizer to specify, I'm replacing the `obj_optimizer` keyword with just `optimizer`, which is simpler and easier to remember.

### CODE REVIEW

**Comment by ferrine** [comment]
LGTM. Keep in mind that some methods require two optimizers(they are not yet implemented). I think that the following api(with changed kwarg) is more intuitive.

**Comment by ferrine** [comment]
What about `more_obj_params` I would rather leave it as is. It can be confusing in future if we change it to `more_params` as it will be not obvious to what object that params are related, moreover they are for experienced users that know underlying terminology.

**Comment by twiecki** [comment]
@ferrine When do you need two optimizers? What would the API look like?

**Comment by ferrine** [comment]
Langevin Stein Operator will require 2 optimizers: one for objective and another for test function.

**Comment by ferrine** [comment]
Api remains the same. It is supported by design.

**Comment by fonnesbeck** [comment]
Fair enough, thanks. I will close this.

**Pull request closed without merging**
