### PR TITLE
SMC: reduce autocorrelation posterior samples

### PR DESCRIPTION
**Pull request by aloctavodia**
This PR change how final samples are generated. 

Final samples are generated by running as many `chains` as `samples` are requested. Each chain is seeded from the previous chain (as usually done in SMC), as the number of `chains` and `samples` will generally not be the same the final chains will be seeded by sampling with replacement from the previous chains. The number of metropolis steps for each chain is `n_step`, the same number as for the first stage. BTW, this should solve #3042 as autocorrelation is reduced and hence accuracy improved.

### CODE REVIEW

**Comment by junpenglao** [comment]
Could you please also change the SMC test back - Colin's PR changed the `tol`

**Comment by aloctavodia** [comment]
I have reverted Colin's change.

**Comment by aloctavodia** [comment]
Oh wait. Do you mean to use Colin's `tol` value?

**Comment by ColCarroll** [comment]
Test looks good to me - I changed the `tol` high enough to make the tests pass, but not because I knew what I was doing.

**Comment by junpenglao** [comment]
Oh right I saw it now - look good to me.

**Pull request merged**
