### PR TITLE
Contributing Guidelines

### PR DESCRIPTION
**Pull request by springcoil**
I've added a contributing guidelines as a first pass. https://github.com/pymc-devs/pymc3/issues/1293 Not perfect but thought it'd be good to get this started.

### CODE REVIEW

**Comment by springcoil** [comment]
What needs to be added to this for this to be merged?

**Comment by twiecki** [comment]
Looks great.

**Comment by springcoil** [comment]
How about we get this merged once @fonnesbeck approves it. And then we can add more stuff to it in the future.

**Comment by fonnesbeck** [comment]
I've added some detail to the contribution guidelines. Feel free to edit or add to them.

**Comment by springcoil** [comment]
Can someone merge this

**Pull request merged**
