### PR TITLE
Migrate from mambaforge onto miniforge

### LINKED ISSUE #7579: Mambaforge sunsetting
### Description

Some [actions recently](https://github.com/pymc-devs/pymc/actions/runs/11930317241/job/33250898719?pr=7540) hit a [brownout day](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/) of the mambaforge sunset. We need to migrate away from mambaforge and onto miniforge.

### PR DESCRIPTION
**Pull request by lucianopaz**
## Related Issue

- [X] Closes #7579 
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [X] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7580.org.readthedocs.build/en/7580/

### CODE REVIEW

**Comment by maresb** [comment]
This is fine if you can get it to work

See also https://github.com/pymc-devs/pymc/pull/7213

Even better would be pixi

**Comment by lucianopaz** [comment]
Sorry about that @maresb! I hadn't seen your PR!

**Comment by maresb** [comment]
I am cautiously optimistic that #7213 is turning green now

**Comment by lucianopaz** [comment]
Closing in favor of #7213

**Pull request closed without merging**
