### PR TITLE
add distribution details to GraphViz output

### PR DESCRIPTION
**Pull request by Spaak**
As originally discussed in https://github.com/pymc-devs/pymc3/pull/3956, since the new `str` functionality has now been merged into master (https://github.com/pymc-devs/pymc3/pull/4076), we can use it in GraphViz renderings.

### CODE REVIEW

**Comment by Spaak** [comment]
Hmm all tests are passing locally, but failing in Travis. Will investigate.

**Review by ColCarroll — APPROVED** [review]
LGTM! There was a merge conflict, I'm not sure why...

**Comment by MarcoGorelli** [comment]
> LGTM! There was a merge conflict, I'm not sure why...

`black` autoformatter from a different PR, probably... that issue's _almost_ done though :innocent:

**Comment by twiecki** [comment]
Thanks!

**Pull request merged**
