### PR TITLE
Define MvNormal with `tau` instead of `cov`

### PR DESCRIPTION
**Pull request by philastrophist**

### CODE REVIEW

**Comment by philastrophist** [comment]
from #1409

**Comment by fonnesbeck** [comment]
If we change it, `Sigma` would be a more conventional choice; `Tau` usually implies an inverse-variance.

**Comment by philastrophist** [comment]
MvNormal doesn't appear to accept sigma though

**Comment by twiecki** [comment]
@philastrophist It does as of https://github.com/pymc-devs/pymc3/pull/1398. You need update your pymc3 to master.

**Pull request closed without merging**
