### PR TITLE
OPVI-ADVI notebook

### PR DESCRIPTION
**Pull request by ferrine**
delete unnecessary text and add some benchmarks in notebook

### CODE REVIEW

**Comment by fonnesbeck** [comment]
What's the motivation for deleting text? In general, we want them to be heavily annotated to act as stand-alone tutorials. In fact, it would be great of some of the comment lines from inside the models (e.g. cells 4,5) were moved out into Markdown cells, making the code cleaner.

**Comment by fonnesbeck** [comment]
Also, since when is the ELBO being minimized rather than maximized?

**Comment by fonnesbeck** [comment]
BTW, can we use the `fit` function for the examples, rather than the method? Again, for consistency in the interface. Most users do not need to know about the method.

**Comment by twiecki** [comment]
@fonnesbeck I suggested cleaning up the NB as it's an addition to the Bayesian NN one we already have. This one demonstrates the new syntax so I think it's best to focus on that and remove duplicate information.

**Comment by fonnesbeck** [comment]
Can we create one nice, comprehensive notebook instead of two slightly different ones? I'd really like to keep the set of notebooks streamlined.

**Comment by ferrine** [comment]
@fonnesbeck I would rather do it later when I integrate changes in gelato. There will be notebook with new api and new library. Now we can merge it just to highlight new API as @twiecki suggested. 
At the moment I work on extending OPVI with SVGD, Histogram(#1904) and [Optimization Framework](https://github.com/pymc-devs/pymc3/pull/1904#issuecomment-286988104).

**Pull request merged**
