### PR TITLE
Drop support for Python 3.7 and add support for Python 3.10

### LINKED ISSUE #5209: Run test suite on Python `3.10`
We should run our tests in Python `3.10` to see if anything is broken or dependencies are missing

### PR DESCRIPTION
**Pull request by ricardoV94**
Temporarily running all tests in 3.10, will remove last commit before merging.

Closes #5209

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Review by michaelosthege — CHANGES_REQUESTED** [review]
@ricardoV94 can you check the `check_all_tests_are_covered.py` script? It should have failed the `pre-commit` because several tests are running under two Python versions. Maybe it needs to be updated.

> Temporarily running all tests in 3.10, will remove last commit before merging.

I'm positng this as "request changes" as a safeguard against premature merges.

**Comment by ricardoV94** [comment]
> @ricardoV94 can you check the `check_all_tests_are_covered.py` script? It should have failed the `pre-commit` because several tests are running under two Python versions. Maybe it needs to be updated.

I think the script does not check for the new python-version matrix option. But any entry with more than on python-version must by definition result in duplicated tests

**Comment by ricardoV94** [comment]
Weird, windows aesara floatX=float64 3.10 failed to install, but aesara floatX=float32 3.10 installed just fine. Flaky conda?

**Comment by michaelosthege** [comment]
> Weird, windows aesara floatX=float64 3.10 failed to install, but aesara floatX=float32 3.10 installed just fine. Flaky conda?

```
  Encountered problems while solving:
    - package aesara-2.7.3-py37h65a5e79_0 requires python_abi 3.7 *_pypy37_pp73, but none of the providers can be installed
```

Why is there a `3.7`?

**Comment by ricardoV94** [comment]
Okay there was a typo in the last Windows test, so I expect that to also fail now with `3.10`

**Comment by ricardoV94** [comment]
So it looks like we have a Windows 10 incompatibility. Can someone try to replicate the issue by creating a test environment with mamba as we do in the CI?

**Comment by michaelosthege** [comment]
Nevermind, I ran the wrong env YAML.

**Comment by michaelosthege** [comment]
I reproduced the error locally, albeit with inserting `- python=3.10` in the `.yml` manually.

```
C:\Users\osthege\Repos\pymc-main\conda-envs>mamba env create -f windows-environment-test.yml
conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
pkgs/r/win-64                                                 No change
pkgs/msys2/win-64                                             No change
pkgs/main/win-64                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
pkgs/msys2/noarch                                             No change


Looking for: ['aeppl=0.0.31', 'aesara=2.7.3', "arviz[version='>=0.12.0']", 'blas', "cachetools[version='>=4.2.1']", 'cloudpickle', "fastprogress[version='>=0.2.0']", "h5py[version='>=2.7']", 'libpython', 'mkl==2020.4', 'mkl-service==2.3.0', 'm2w64-toolchain', "numpy[ve]


Encountered problems while solving:
  - package aesara-2.7.3-py37h65a5e79_0 requires python_abi 3.7 *_pypy37_pp73, but none of the providers can be installed
```

**Comment by michaelosthege** [comment]
It's the `mkl-service==2.3.0` dependency.


✔ `mamba create --dry-run -c conda-forge -n pmtest "python=3.10" "aeppl=0.0.31" "aesara=2.7.3" "arviz>=0.12" blas "cachetools>=4.2.1" cloudpickle "fastprogress>=0.2.0" "h5py>=2.7" libpython "mkl=2020.4"`

:x: `mamba create --dry-run -c conda-forge -n pmtest "python=3.10" "aeppl=0.0.31" "aesara=2.7.3" "arviz>=0.12" blas "cachetools>=4.2.1" cloudpickle "fastprogress>=0.2.0" "h5py>=2.7" libpython "mkl=2020.4" "mkl-service==2.3.0"`
```
Encountered problems while solving:
  - package mkl-service-2.3.0-py27h0b88c2a_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed
```

Unpinning doesn't help either.

:x: `mamba create --dry-run -c conda-forge -n pmtest "python=3.10" "aeppl=0.0.31" "aesara=2.7.3" "arviz>=0.12" blas "cachetools>=4.2.1" cloudpickle "fastprogress>=0.2.0" "h5py>=2.7" libpython "mkl=2020.4" mkl-service`
```
Encountered problems while solving:
  - package mkl-service-1.1.2-py27h0b88c2a_5 requires python >=2.7,<2.8.0a0, but none of the providers can be installed
```

**Comment by ricardoV94** [comment]
That looks like something else. Why is it requiring python 2.7?

**Comment by ricardoV94** [comment]
Seems to have worked!

**Comment by michaelosthege** [comment]
> That looks like something else. Why is it requiring python 2.7?

This really outdated `mkl-service` probably didn't pin `mkl` like the current versions do.
In my commit I removed `mkl` because it's already a dependency through `mkl-service`:

```
package mkl-service-2.4.0-py36h68aa20f_0 requires mkl >=2021.2.0,<2022.0a0, but none of the providers can be installed
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...because of our `mkl=2020.4` pin
```

**Review by michaelosthege — APPROVED** [review]

**Pull request merged**
