### PR TITLE
Update example robustregressionoutlierdetection

### PR DESCRIPTION
**Pull request by jonsedar**
Added a new model to the notebook for comparison which uses StudentT likelihood for robust regression. Compared the outputs with the OLS and Signal Vs Noise model. I think it's worth the comparison, since it makes quite clear that the StudentT method finds a similar robust regression as the Signal Vs Noise method.

Note 
1. I’ve taken the opportunity to update to python 3.4, since PyMC3 is now compatible
2. I’ve also updated the YAML excerpt
3. I’m using the very recently updated name for StudentT. I doubt it will break too much, but expecting I might have to update one or two things.
4. Still getting quite a lot of instability on the SignalVs Noise model regarding the outlier labels - perhaps the BinaryMetropolis gets stuck? I might have a play with the tuning param and see what happens.

### CODE REVIEW

**Comment by twiecki** [comment]
Do you want us to merge this or still add to it?

**Comment by jonsedar** [comment]
Merge away :) I'll leave it alone for now

**Comment by jonsedar** [comment]
Cheers :) Killed branch

**Comment by twiecki** [comment]
Great addition with the T-distribution. Also updated the website.

**Pull request merged**
