### PR TITLE
Workaround PyTensor bug in vectorize of logp graph

### LINKED ISSUE #7414: BUG: Dirichlet is broken under graph vectorization
### Describe the issue:

When trying to work out model logp vectorization, stucked with Dirichlet being broken under. It's most likely the pytensor issue, since the source of the error is in rewrites.

### Reproduceable code example:

```python
with pm.Model() as test_model:
    v = pm.Dirichlet("v", [1., 1., 1.], shape=3)
test_lp = test_model.logp()
test_values_vec = {
    v: v.type.clone(shape=(None, *v.type.shape))(name=f"{v.name}[]")
    for v in test_model.value_vars
}
test_vectorized_lp = pytensor.graph.vectorize_graph([test_lp], test_values_vec)
test_f = pm.compile_pymc(
    # works with mode="FAST_COMPILE"
    list(test_values_vec.values()), test_vectorized_lp
)
test_f(np.random.randn(10, 2))
```

### Error message:

<details>

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/dev/pymc/.venv/lib/python3.11/site-packages/pytensor/compile/function/types.py:959, in Function.__call__(self, *args, **kwargs)
    957 try:
    958     outputs = (
--> 959         self.vm()
    960         if output_subset is None
    961         else self.vm(output_subset=output_subset)
    962     )
    963 except Exception:

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 1

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[307], line 1
----> 1 test_f(np.random.randn(10, 2))

File ~/dev/pymc/.venv/lib/python3.11/site-packages/pytensor/compile/function/types.py:972, in Function.__call__(self, *args, **kwargs)
    970     if hasattr(self.vm, "thunks"):
    971         thunk = self.vm.thunks[self.vm.position_of_error]
--> 972     raise_with_op(
    973         self.maker.fgraph,
    974         node=self.vm.nodes[self.vm.position_of_error],
    975         thunk=thunk,
    976         storage_map=getattr(self.vm, "storage_map", None),
    977     )
    978 else:
    979     # old-style linkers raise their own exceptions
    980     raise

File ~/dev/pymc/.venv/lib/python3.11/site-packages/pytensor/link/utils.py:528, in raise_with_op(fgraph, node, thunk, exc_info, storage_map)
    523     warnings.warn(
    524         f"{exc_type} error does not allow us to add an extra error message"
    525     )
    526     # Some exception need extra parameter in inputs. So forget the
    527     # extra long error message in that case.
--> 528 raise exc_value.with_traceback(exc_trace)

File ~/dev/pymc/.venv/lib/python3.11/site-packages/pytensor/compile/function/types.py:959, in Function.__call__(self, *args, **kwargs)
    956 t0_fn = time.perf_counter()
    957 try:
    958     outputs = (
--> 959         self.vm()
    960         if output_subset is None
    961         else self.vm(output_subset=output_subset)
    962     )
    963 except Exception:
    964     restore_defaults()

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 1
Apply node that caused the error: Join(1, Add.0, [[0.]])
Toposort index: 5
Inputs types: [TensorType(int8, shape=()), TensorType(float64, shape=(None, 2)), TensorType(float64, shape=(1, 1))]
Inputs shapes: [(), (10, 2), (1, 1)]
Inputs strides: [(), (16, 8), (8, 8)]
Inputs values: [array(1, dtype=int8), 'not shown', array([[0.]])]
Outputs clients: [[Max{axis=1}(Join.0), Composite{switch(i2, i3, exp((i0 - i1)))}(Join.0, ExpandDims{axis=1}.0, Isinf.0, Exp.0)]]

Backtrace when the node is created (use PyTensor flag traceback__limit=N to make it longer):
  File "/home/ferres/dev/pymc/.venv/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/home/ferres/dev/pymc/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/ferres/dev/pymc/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/ferres/dev/pymc/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_921353/1334936598.py", line 8, in <module>
    test_vectorized_lp = pytensor.graph.vectorize_graph([test_lp], test_values_vec)
  File "/home/ferres/dev/pymc/.venv/lib/python3.11/site-packages/pytensor/graph/replace.py", line 301, in vectorize_graph
    vect_node = vectorize_node(node, *vect_inputs)
  File "/home/ferres/dev/pymc/.venv/lib/python3.11/site-packages/pytensor/graph/replace.py", line 217, in vectorize_node
    return _vectorize_node(op, node, *batched_inputs)
  File "/home/ferres/dev/pymc/.venv/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)

HINT: Use the PyTensor flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.

```

</details>

### Graph of the function

<detail>

```
Composite{(switch(or(i3, i4), -inf, 0.6931471805599453) + ((1.0986122886681098 + (3.0 * i2)) - (3.0 * (i1 + log(i0)))))} [id A] 20
 ├─ Sum{axis=1} [id B] 17
 │  └─ Composite{switch(i2, i3, exp((i0 - i1)))} [id C] 14
 │     ├─ Join [id D] 5
 │     │  ├─ 1 [id E]
 │     │  ├─ Add [id F] 3
 │     │  │  ├─ v_simplex__[] [id G]
 │     │  │  └─ ExpandDims{axis=1} [id H] 1
 │     │  │     └─ Sum{axis=1} [id I] 0
 │     │  │        └─ v_simplex__[] [id G]
 │     │  └─ [[0.]] [id J]
 │     ├─ ExpandDims{axis=1} [id K] 9
 │     │  └─ Max{axis=1} [id L] 7
 │     │     └─ Join [id D] 5
 │     │        └─ ···
 │     ├─ Isinf [id M] 12
 │     │  └─ ExpandDims{axis=1} [id K] 9
 │     │     └─ ···
 │     └─ Exp [id N] 11
 │        └─ ExpandDims{axis=1} [id K] 9
 │           └─ ···
 ├─ Max{axis=1} [id L] 7
 │  └─ ···
 ├─ Sum{axis=1} [id I] 0
 │  └─ ···
 ├─ Any{axis=1} [id O] 19
 │  └─ Lt [id P] 16
 │     ├─ Softmax{axis=1} [id Q] 13
 │     │  └─ Sub [id R] 10
 │     │     ├─ Join [id S] 4
 │     │     │  ├─ 1 [id E]
 │     │     │  ├─ v_simplex__[] [id G]
 │     │     │  └─ Neg [id T] 2
 │     │     │     └─ ExpandDims{axis=1} [id H] 1
 │     │     │        └─ ···
 │     │     └─ ExpandDims{axis=1} [id U] 8
 │     │        └─ Max{axis=1} [id V] 6
 │     │           └─ Join [id S] 4
 │     │              └─ ···
 │     └─ [[0]] [id W]
 └─ Any{axis=1} [id X] 18
    └─ Gt [id Y] 15
       ├─ Softmax{axis=1} [id Q] 13
       │  └─ ···
       └─ [[1]] [id Z]

Inner graphs:

Composite{(switch(or(i3, i4), -inf, 0.6931471805599453) + ((1.0986122886681098 + (3.0 * i2)) - (3.0 * (i1 + log(i0)))))} [id A]
 ← add [id BA] 'o0'
    ├─ Switch [id BB]
    │  ├─ OR [id BC]
    │  │  ├─ i3 [id BD]
    │  │  └─ i4 [id BE]
    │  ├─ -inf [id BF]
    │  └─ 0.6931471805599453 [id BG]
    └─ sub [id BH]
       ├─ add [id BI]
       │  ├─ 1.0986122886681098 [id BJ]
       │  └─ mul [id BK]
       │     ├─ t1{3.0} [id BL]
       │     └─ i2 [id BM]
       └─ mul [id BN]
          ├─ t1{3.0} [id BL]
          └─ add [id BO]
             ├─ i1 [id BP]
             └─ log [id BQ]
                └─ i0 [id BR]

Composite{switch(i2, i3, exp((i0 - i1)))} [id C]
 ← Switch [id BS] 'o0'
    ├─ i2 [id BT]
    ├─ i3 [id BU]
    └─ exp [id BV]
       └─ sub [id BW]
          ├─ i0 [id BX]
          └─ i1 [id BY]
```
</detail>

### PyMC version information:

'5.16.2+3.gc8b22df21'

### Context for the issue:

This issue is related to Empirical Bayes experiments to automatically set hyperpriors

### PR DESCRIPTION
**Pull request by ferrine**
fix #7414 

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7415.org.readthedocs.build/en/7415/

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Comment by ferrine** [comment]
what is this error in float64 tests, is it related?

**Comment by ricardoV94** [comment]
> what is this error in float64 tests, is it related?

That's weird, values seem transposed

**Comment by ferrine** [comment]
Another thing, I'm not able to reproduce the bug

```
(/home/ferres/dev/pymc/.venv) @c1 ➜ pymc git:(fix/vectorize-graph) PYTENSOR_FLAGS=floatX=float64 pytest tests/distributions/test_continuous.py::TestPolyaGamma::test_distribution
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.11.9, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/ferres/dev/pymc
configfile: pyproject.toml
collected 1 item

tests/distributions/test_continuous.py .                                                                                                                                                             [100%]

============================================================================================= warnings summary =============================================================================================
.venv/lib/python3.11/site-packages/pytensor/configdefaults.py:375
  /home/ferres/dev/pymc/.venv/lib/python3.11/site-packages/pytensor/configdefaults.py:375: DeprecationWarning: Use shutil.which instead of find_executable
    newp = find_executable(param)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================================================= 1 passed, 1 warning in 0.36s =======================================================================================
```

Should we merge instead and open a new issue to resolve that?

**Comment by ricardoV94** [comment]
If it's not failing on main we shouldn't merge. Did you retrigger the CI to see if it was a (very weird) fluke?

**Comment by ferrine** [comment]
same error, retriggered

**Comment by ferrine** [comment]
attempted to rebase on latest main

**Comment by ferrine** [comment]
I have not seen these transforms are even used by PolyaGamma

**Comment by ricardoV94** [comment]
I'll have to dig, is rather surprising, but somehow related

**Comment by zoj613** [comment]
> I have not seen these transforms are even used by PolyaGamma

Can you try pinning polyagamma to 1.3.6 just to see if the tests fail. I just released 1.3.7 which includes numpy 2.0 support. I suspect this [change](https://github.com/zoj613/polyagamma/pull/126) might be the root cause. 

Looking at this output:
```
E           AssertionError: 
E           Arrays are not almost equal to 6 decimals
E           
E           Mismatched elements: 14 / 15 (93.3%)
E           Max absolute difference: 0.25700269
E           Max relative difference: 7.27861386
E            x: array([0.175503, 0.304112, 0.32734 , 0.285465, 0.15268 , 0.208075,
E                  0.324094, 0.261004, 0.256576, 0.173434, 0.115312, 0.034482,
E                  0.121655, 0.047109, 0.358831])
E            y: array([0.358831, 0.047109, 0.121655, 0.034482, 0.115312, 0.173434,
E                  0.256576, 0.261004, 0.324094, 0.208075, 0.15268 , 0.285465,
E                  0.32734 , 0.304112, 0.175503])
```

It appears that the linked PR leads to values generated in a different order than in v1.3.6.

**Comment by ferrine** [comment]
I can confirm that updating the polyagamma to 1.3.7 I reproduce the error

**Comment by ferrine** [comment]
since this test is a blocker, I created an issue #7417 and a temporary solution #7418 to unblock any related work

**Comment by ferrine** [comment]
just rebased on the updated CI

**Pull request merged**
