### PR TITLE
BUG: get_tau_sd returns tau=0 when sd is an integer array

### PR DESCRIPTION
**Pull request by aflaxman**
Closes issue #716

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @aflaxman! Will merge once tests pass.

**Comment by aflaxman** [comment]
This exercise raised one question for me:  does pymc3 have a format for docstrings? I've heard that the numpy format is good http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_numpy.html

It might also be good to make a CONTRIBUTING.md file, like this one: https://github.com/jakevdp/mpld3/blob/master/CONTRIBUTING.md with some details about what pymc3 expects about tests, docs, examples, etc.

**Comment by kyleam** [comment]
Don't you think a float should always be returned for both `sd` and `tau`?

**Comment by aflaxman** [comment]
@kyleam I originally thought so, but then I decided that I don't understand this function well enough to have an opinion on the types.  If the input is an array, the output should be an array of the same shape, but if the input is an int, can the output be a numpy float array of dimension zero?  Or should it be an honest Python float?

**Comment by jsalvatier** [comment]
I think either a float array or an honest python float will be fine. Floats are probably always appropriate here.

**Comment by kyleam** [comment]
> If the input is an array, the output should be an array of the same
> shape, but if the input is an int, can the output be a numpy float
> array of dimension zero?  Or should it be an honest Python float?

My preference is to let the original input decide by multiplying the
supplied argument by "1.".  This is inline with the behavior for the
calculated parameter.

**Comment by aflaxman** [comment]
@kyleam that is simple, I'll do it.

**Pull request merged**
