### PR TITLE
Make ArviZ a proper requirement

### LINKED ISSUE #3609: Is arviz required?
Followup to #3608, but sampling does some convergence checks that will rely on arviz. Should we make that a required library in the setup.py?

### PR DESCRIPTION
**Pull request by ColCarroll**
Fixes #3609 

This let me delete some of the hacky code we'd had from adding the plotting, and I fixed up some of the imports. It works for me on master of arviz and pymc3. Note that the return values are often xarray objects now: 
image

### CODE REVIEW

**Comment by ColCarroll** [comment]
Tests are failing for the good reason that this also makes `matplotlib` required.

Should we see if there's appetite in ArviZ to make matplotlib optional? I am going to just add matplotlib to the requirements for now.

For what it is worth, the original objection to matplotlib being a requirement was making the download much larger. Here are sizes of a few libraries we require to compare -- i'm looking at the ballpark size of the wheel at, for example, https://pypi.org/project/numpy/#files:

- numpy: 15MB
- scipy: 25MB
- pandas: 15MB
- matplotlib: 14MB
- xarray: 0.5MB
- netcdf4: 5MB
- h5py: 5MB
- theano: 3MB (no wheel)

**Comment by ColCarroll** [comment]
Yeah, here is the original comment: https://github.com/pymc-devs/pymc3/issues/793#issuecomment-325762630

I think matplotlib install is much improved in the last 2 years.

**Comment by fonnesbeck** [comment]
Yeah, I think there were requests in the past to make PyMC installable without Matplotlib. Not sure if that would be an issue again. I'm still comfortable making it a hard requirement, given how vital it is for model checking.

**Comment by ColCarroll** [comment]
Tests are all passing, somewhat surprisingly.

**Comment by twiecki** [comment]
I agree, matplotlib is so common it should be fine to have it as a requirement.

**Pull request merged**
