### PR TITLE
hide transformed variables from the user

### PR DESCRIPTION
**Pull request by aloctavodia**
currently trace_to_dataframe expose hidden variables to the user.

### CODE REVIEW

**Comment by aloctavodia** [comment]
Travis is failing with an error unrelated to my PR :-( 

`ERROR: Failure: ImportError (No module named 'PyQt4')`

**Comment by twiecki** [comment]
I'll look into it.

**Comment by ColCarroll** [comment]
Looks like conda recently bumped matplotlib from 1.5.1 to 1.5.3 -- I'll try pinning the version to fix the build.

**Comment by aloctavodia** [comment]
In cases like this, there is a way for someone without write access to the repository to re-trigger Travis's checks (without doing another PR)?

**Comment by twiecki** [comment]
@aloctavodia In this case you have to rebase your branch off of recent master and then force-push. This will then trigger a rebuild. Otherwise travis will use the old broken commits from this current branch.

**Comment by twiecki** [comment]
Thanks!

**Pull request merged**
