### PR TITLE
SGFS clean up

### PR DESCRIPTION
**Pull request by junpenglao**
cleaner init for SGFS

### CODE REVIEW

**Comment by junpenglao** [comment]
@shkr Can [`step_size_decay`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/sgmcmc.py#L101) be removed? It was not documented and this parameter doesn't do much.

**Comment by shkr** [comment]
@junpenglao Yes that can be removed, if it simplifies init

**Comment by ferrine** [comment]
Insight about minibatching. I have extra ScanOp in case of minibatches

`pm.Minibatch`
```
Class
---
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  97.3%    97.3%      12.076s       7.45e-03s     Py    1622       2   theano.scan_module.scan_op.Scan
```

Old interface
```
Class
---
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  95.2%    95.2%       5.376s       6.63e-03s     Py     811       1   theano.scan_module.scan_op.Scan
```

My conclusion is that overhead is mainly because this extra Scan. Maybe I can investigate this problem later. I'm sure that this problem arises in your case too

**Comment by junpenglao** [comment]
@shkr btw, why is the trace return by SGFS seems to first oscillate then converge to a value? For example if I just sample from a Gaussian:
image

Do you know where I can find some information about this? I can not find ppl reporting the trace.

**Review by ColCarroll — APPROVED** [review]
lgtm -- is this ready to merge?

**Comment by junpenglao** [comment]
@ColCarroll Yes it is ready to merge. I will study a bit more about the property of SGFS but if there is any changes I will do it in another PR.

**Comment by shkr** [comment]
@junpenglao hey I should have been more clear -- the step_size_decay can stay constant is what I meant.

It is still required. Currently the implementation is not correct. The epsilon must reduce with time.

You will have to undo this [commit](https://github.com/pymc-devs/pymc3/pull/2427/commits/3537b14034c72c8b4b7916dd3443f288b9e6a30e)

**Comment by shkr** [comment]
The oscillation behavior is possibly because the step_size_decay has been removed, because the mixing rate remains constant, and as the approximation of the fisher score converges the oscillation converges close to the true posterior.

**Comment by junpenglao** [comment]
@shkr oh ok I see. I will open another PR.

**Comment by junpenglao** [comment]
> The oscillation behavior is possibly because the step_size_decay has been removed, because the mixing rate remains constant, and as the approximation of the fisher score converges the oscillation converges close to the true posterior.

That figure is actually from before removing the `step_size_decay`. But yes since it was a constant I think correct implementation should fix the problem.

**Pull request merged**
