### PR TITLE
Renamed ConstantDist to Constant

### PR DESCRIPTION
**Pull request by fonnesbeck**
We don't add a `Dist` suffix to any other distributions, so a constant should be no different. Added a deprecation warning to avoid breakage.

### CODE REVIEW

**Comment by twiecki** [comment]
LGTM.

**Comment by fonnesbeck** [comment]
Very odd TravisCI failures though. A ton of gradient-related exceptions that don't seem to be related to the changes I made:

```
TypeError: Elemwise{mul,no_inplace}.grad illegally  returned an integer-valued variable. (Input index 1, dtype bool)
```

**Comment by ColCarroll** [comment]
It looks like the `travis-ci/push` failures maybe need a rebase -- they have the error that's described in #1496 (and looking at the build logs, they're using theano 0.9.0.dev4, instead of 0.8.2).  

The `travis-ci/pr` failures have this flavor:

```
======================================================================
ERROR: test_constant_dist (pymc3.tests.test_distributions_random.ScalarParameterSamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions_random.py", line 474, in test_constant_dist
    pymc3_random_discrete(pm.Constant, {'c': I}, ref_rand=ref_rand)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions_random.py", line 37, in pymc3_random_discrete
    model = build_model(dist, valuedomain, paramdomains)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions.py", line 114, in build_model
    distfam('value', shape=valuedomain.shape, transform=None, **vals)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/step_methods/arraystep.py", line 50, in __new__
    vars = inputvars(vars)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/theanof.py", line 23, in inputvars
    return [v for v in inputs(makeiter(a)) if isinstance(v, tt.TensorVariable)]
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 697, in inputs
    vlist = ancestors(variable_list, blockers)
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 676, in ancestors
    dfs_variables = stack_search(deque(variable_list), expand, 'dfs')
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 644, in stack_search
    expand_l = expand(l)
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 674, in expand
    if r.owner and (not blockers or r not in blockers):
AttributeError: 'str' object has no attribute 'owner'
```

**Comment by springcoil** [comment]
@ColCarroll have you updated the Theano version to the newest one? Is that not the resolution of this?

**Comment by ColCarroll** [comment]
The PR that fixes our problem hasn't landed yet (https://github.com/Theano/Theano/pull/5175)  I'm keeping an eye on it, and will bump when it goes.  Rebasing should run travis against 0.8.2, which _should_ pass.

**Comment by twiecki** [comment]
Rebased

**Comment by twiecki** [comment]
Rebased again.

**Comment by twiecki** [comment]
```
======================================================================
ERROR: test_constant_dist (pymc3.tests.test_distributions_random.ScalarParameterSamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions_random.py", line 474, in test_constant_dist
    pymc3_random_discrete(pm.Constant, {'c': I}, ref_rand=ref_rand)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions_random.py", line 37, in pymc3_random_discrete
    model = build_model(dist, valuedomain, paramdomains)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions.py", line 116, in build_model
    distfam('value', shape=valuedomain.shape, transform=None, **vals)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/step_methods/arraystep.py", line 50, in __new__
    vars = inputvars(vars)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/theanof.py", line 23, in inputvars
    return [v for v in inputs(makeiter(a)) if isinstance(v, tt.TensorVariable)]
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 693, in inputs
    vlist = ancestors(variable_list, blockers)
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 672, in ancestors
    dfs_variables = stack_search(deque(variable_list), expand, 'dfs')
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 640, in stack_search
    expand_l = expand(l)
  File "/home/travis/minconda3/envs/testenv/lib/python3.5/site-packages/theano/gof/graph.py", line 670, in expand
    if r.owner and (not blockers or r not in blockers):
AttributeError: 'str' object has no attribute 'owner'
```

**Comment by fonnesbeck** [comment]
I was told these are Travis-related errors. I cannot replicate it locally. Can anyone else?

**Comment by ColCarroll** [comment]
I'll take a look tonight.

**Comment by ColCarroll** [comment]
Happens locally for me (in the docker image!)

**Comment by ColCarroll** [comment]
tricky -- there's a `step_methods.arraystep.Constant`, which overrides `distributions.discrete.Constant`  since `from step_methods import *` is run after `from distributions import *` in `__init__.py`.

**Comment by fonnesbeck** [comment]
Very tricky. Thanks. I will try to fix it.

**Comment by fonnesbeck** [comment]
So, I had entirely forgotten that we had a `Constant` step method. We can either drop this PR entirely and live with `ConstantDist` or rename the step method to `ConstantStep` (since it inherits from `ArrayStep`). Any preference? Does anyone use the `Constant` step method?

**Comment by twiecki** [comment]
I didn't know that existed either. Is it actually needed? In any case, I'm in favor of `ConstantStep`.

**Comment by fonnesbeck** [comment]
Yes, it seems like they both exist for a similar purpose. It seems a better approach to fix a parameter at the variable specification level, rather than at the step method level. I wonder if we shouldn't get rid of the step method altogether.

**Comment by fonnesbeck** [comment]
I've removed the `Constant` step method. This is only a bad idea if anyone actually uses this step method, of course. Thoughts?

**Comment by fonnesbeck** [comment]
I am again unable to replicate this failure. Anyone else?

**Comment by twiecki** [comment]
This almost looks like a new theano problem again.

**Comment by ColCarroll** [comment]
This looks like the one @ferrine fixed (https://github.com/Theano/Theano/pull/5232).  I restarted the travis job.

**Comment by fonnesbeck** [comment]
2/3 passed. Rebasing and trying again.

**Comment by fonnesbeck** [comment]
That appears to have done it. Merging.

**Pull request merged**
