### PR TITLE
Added python3.10 env

### LINKED ISSUE #5209: Run test suite on Python `3.10`
We should run our tests in Python `3.10` to see if anything is broken or dependencies are missing

### PR DESCRIPTION
**Pull request by 5hv5hvnk**
Ran test suit and added coda environment for python 3.10

resolves [#5209](https://github.com/pymc-devs/pymc/issues/5209)

### CODE REVIEW

**Comment by ricardoV94** [comment]
You seem to have based your branch on an old version of the repository. The tests were recently merged into a single file: https://github.com/pymc-devs/pymc/pull/5623

**Comment by michaelosthege** [comment]
Just start fresh from the latest main branch. Trying to resolve the git conflicts would be much more work than reapplying them manually.

And make sure that you only commit the necessary files. There are some coverage files that should not be git committed.

**Comment by ricardoV94** [comment]
You still seem to have committed 3 files that shouldn't have been committed: https://github.com/pymc-devs/pymc/pull/5638/files

**Comment by ricardoV94** [comment]
And you will need to swap the conda environment used in the tests to use this new one (and delete the old py37 environments): https://github.com/pymc-devs/pymc/blob/main/.github/workflows/tests.yml

**Comment by ricardoV94** [comment]
@michaelosthege Could the failing tests be a conda cache issue?

**Comment by michaelosthege** [comment]
I don't know about conda caching.

But the changes in `test.yml` affect all jobs at the same so it's really hard to tell. The current changes are
* Ubuntu `3.7`→`3.8`
* Windows `3.8`→ `3.9`
* MacOS `3.9`→`3.10`
* Ubuntu/Jax `3.9`→`3.10`
* Windows/float32 `3.8`→`3.9`

The Windows jobs are failing because the corresponding environment YAML does not exist.

The MacOS jobs fail because of build problems?

→→ I would advise to first bump **only** the Ubuntu job from `3.7`→`3.10` to see if it's even working there. But the Ubuntu/Jax job also has build problems, so the answer is likely "No"

**Pull request closed without merging**
