### PR TITLE
Implement CDF, CCDF, LCDF, LCCDF for Normal distribution.

### PR DESCRIPTION
**Pull request by domenzain**
Implement numerically stable convenience functions for the Normal distribution.
This will make the work in #1833 #1843 easier.

### CODE REVIEW

**Comment by domenzain** [comment]
The idea is to begin implementing CDF, CCDF and other useful functions for all distributions.

Does it make sense to put these functions here?
I can think of a few unit tests for these functions. Where should those go?

**Comment by fonnesbeck** [comment]
I'd prefer to wait until we have functions for all of the distributions, not just the normal. My recommendation is to focus on the log-cdf. Not sure the others are important to have, unless there are fitting algorithms that use them.

Going to close the PR.

**Comment by fonnesbeck** [comment]
If you like, I can create a "cdf" branch on the project, and individual CDFs can be merged into it until we have them for most of the distributions, then that branch can be merged into master. Sound good?

**Comment by domenzain** [comment]
Sure!

**Comment by domenzain** [comment]
@fonnesbeck could you push the `cdf` branch?

**Comment by fonnesbeck** [comment]
OK, there is a `cdf_methods` branch now that you can PR against. I've added your normal logcdf, as well as a test (which does not yet pass).

**Pull request closed without merging**
