### PR TITLE
Generalized plot_posterior to plot vector-valued variables

### LINKED ISSUE #1131: plot_posterior fails for vector-valued variables
`plot_posterior` fails when passed a vector-valued variable in `varnames`. For example, the `rate` vector in `disaster_model`:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-65-4a5dae961dfd> in <module>()
----> 1 plot_posterior(trace_missing, varnames=['rate'])

/Users/fonnescj/Repositories/pymc3/pymc3/plots.py in plot_posterior(trace, varnames, figsize, alpha_level, round_to, point_estimate, rope, ref_val, kde_plot, ax, **kwargs)
    740         for a, v in zip(ax, varnames):
    741             tr_values = trace.get_values(v, combine=True, squeeze=True)
--> 742             plot_posterior_op(tr_values, ax=a)
    743             a.set_title(v)
    744 

/Users/fonnescj/Repositories/pymc3/pymc3/plots.py in plot_posterior_op(trace_values, ax)
    707 
    708         format_axes()
--> 709         display_hpd()
    710         display_point_estimate()
    711         if ref_val is not None:

/Users/fonnescj/Repositories/pymc3/pymc3/plots.py in display_hpd()
    668         def display_hpd():
    669             hpd_intervals = hpd(trace_values, alpha=alpha_level)
--> 670             ax.plot(hpd_intervals, (plot_height * 0.02, plot_height * 0.02), linewidth=4, color='k')
    671             text_props = dict(size=16, horizontalalignment='center')
    672             ax.text(hpd_intervals[0], plot_height * 0.07, hpd_intervals[0].round(round_to), **text_props)

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1810                     warnings.warn(msg % (label_namer, func.__name__),
   1811                                   RuntimeWarning, stacklevel=2)
-> 1812             return func(ax, *args, **kwargs)
   1813         pre_doc = inner.__doc__
   1814         if pre_doc is None:

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_axes.py in plot(self, *args, **kwargs)
   1422             kwargs['color'] = c
   1423 
-> 1424         for line in self._get_lines(*args, **kwargs):
   1425             self.add_line(line)
   1426             lines.append(line)

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py in _grab_next_args(self, *args, **kwargs)
    384                 return
    385             if len(remaining) <= 3:
--> 386                 for seg in self._plot_args(remaining, kwargs):
    387                     yield seg
    388                 return

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py in _plot_args(self, tup, kwargs)
    362             x, y = index_of(tup[-1])
    363 
--> 364         x, y = self._xy_from_xy(x, y)
    365 
    366         if self.command == 'plot':

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py in _xy_from_xy(self, x, y)
    221         y = _check_1d(y)
    222         if x.shape[0] != y.shape[0]:
--> 223             raise ValueError("x and y must have same first dimension")
    224         if x.ndim > 2 or y.ndim > 2:
    225             raise ValueError("x and y can be no greater than 2-D")

ValueError: x and y must have same first dimension
```

Similarly, for the missing values in the disasters model with missingness:

```
array([<matplotlib.axes._subplots.AxesSubplot object at 0x124405940>], dtype=object)
Error in callback <function install_repl_displayhook.<locals>.post_execute at 0x105a75488> (for post_execute):
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py in post_execute()
    145             def post_execute():
    146                 if matplotlib.is_interactive():
--> 147                     draw_all()
    148 
    149             # IPython >= 2

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/_pylab_helpers.py in draw_all(cls, force)
    148         for f_mgr in cls.get_all_fig_managers():
    149             if force or f_mgr.canvas.figure.stale:
--> 150                 f_mgr.canvas.draw_idle()
    151 
    152 atexit.register(Gcf.destroy_all)

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/backend_bases.py in draw_idle(self, *args, **kwargs)
   2024         if not self._is_idle_drawing:
   2025             with self._idle_draw_cntx():
-> 2026                 self.draw(*args, **kwargs)
   2027 
   2028     def draw_cursor(self, event):

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    472 
    473         try:
--> 474             self.figure.draw(self.renderer)
    475         finally:
    476             RendererAgg.lock.release()

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/figure.py in draw(self, renderer)
   1157         dsu.sort(key=itemgetter(0))
   1158         for zorder, a, func, args in dsu:
-> 1159             func(*args)
   1160 
   1161         renderer.close_group('figure')

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2322 
   2323         for zorder, a in dsu:
-> 2324             a.draw(renderer)
   2325 
   2326         renderer.close_group('axes')

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     59     def draw_wrapper(artist, renderer, *args, **kwargs):
     60         before(artist, renderer)
---> 61         draw(artist, renderer, *args, **kwargs)
     62         after(artist, renderer)
     63 

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/text.py in draw(self, renderer)
    747 
    748         with _wrap_text(self) as textobj:
--> 749             bbox, info, descent = textobj._get_layout(renderer)
    750             trans = textobj.get_transform()
    751 

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/text.py in _get_layout(self, renderer)
    332         of a rotated text when necessary.
    333         """
--> 334         key = self.get_prop_tup()
    335         if key in self._cached:
    336             return self._cached[key]

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/text.py in get_prop_tup(self)
    901         need to know if the text has changed.
    902         """
--> 903         x, y = self.get_unitless_position()
    904         return (x, y, self.get_text(), self._color,
    905                 self._verticalalignment, self._horizontalalignment,

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/text.py in get_unitless_position(self)
    883         # This will get the position with all unit information stripped away.
    884         # This is here for convienience since it is done in several locations.
--> 885         x = float(self.convert_xunits(self._x))
    886         y = float(self.convert_yunits(self._y))
    887         return x, y

TypeError: only length-1 arrays can be converted to Python scalars
```

Its fine if the function only supports scalar values (though it would be nice to just call itself recursively when presented by a multivariate node), but it should return an informative message when passed an incompatible variable name, rather than an obscure matplotlib exception.

### PR DESCRIPTION
**Pull request by fonnesbeck**
This is a refactor of `plot_posterior` that accepts vector-valued parameters. I will add a test, but please test it on your favorite example.

Closes #1131

### CODE REVIEW

**Comment by ColCarroll** [comment]
Cool!  Works on [occupancy](https://github.com/pymc-devs/pymc3/blob/f2e08d5da70c465d3ca348e2eeeefb10a7a0fdbe/pymc3/tests/test_examples.py#L253) example -- changing `n=100` to `n = (2, 100)` in the `setUp` creates 200 plots for `z`, which seems correct.

Maybe a warning for too many plots?  Or an implicit upper bound?

**Comment by fonnesbeck** [comment]
We don't warn users for other plots, so I wouldn't put one here. If we think that's something we ought to have then it's probably best implemented module-wide in a separate PR.

**Review by springcoil — COMMENTED** [review]
I see nothing wrong with this fix. Maybe @ColCarroll has some objections though.

**Comment by ColCarroll** [comment]
No, this looks good -- @fonnesbeck should we wait for a test or merge now?  I was using the test below, if that helps.

```
import pymc3 as pm
import numpy as np

def test_plot_posterior(self):
    n = (2, 100)
    theta = 2.1
    pi = 0.4
    y = (np.random.random(n) < pi) * np.random.poisson(lam=theta, size=n)

    with pm.Model() as model:
        psi = pm.Beta('psi', 1, 1)
        pm.Bernoulli('z', psi, y.shape)
        theta = pm.Uniform('theta', 0, 100)
        pm.ZeroInflatedPoisson('y', theta, psi, observed=y)
        start = {'psi': 0.5, 'z': (y > 0).astype(int), 'theta': 5}
        step_one = pm.Metropolis([model.theta_interval_, model.psi_logodds_])
        step_two = pm.BinaryMetropolis([model.z])
        tr = pm.sample(50, [step_one, step_two], start)

    # should produce a plot for each dimension of n
    plots = pm.plot_posterior(tr, varnames=['z'])
    self.assertEqual(plots.shape, (np.prod(n),))
```

**Comment by twiecki** [comment]
I think we should add @ColCarroll's test.

**Comment by fonnesbeck** [comment]
The added test should do it, and it uses an existing test model run.

**Comment by ColCarroll** [comment]
Looks good to me -- will merge after travis passes

**Pull request merged**
