### PR TITLE
⬆️ UPGRADE: Autoupdate pre-commit config

### PR DESCRIPTION
**Pull request by twiecki**
## Base PullRequest

⬆️ UPGRADE: Autoupdate pre-commit config (#5430)

## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>add path</em></summary>

```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/build/src/bin
```

</details>
<details>
<summary><em>pip install pre-commit</em></summary>

```Shell
Collecting pre-commit
  Downloading pre_commit-2.17.0-py2.py3-none-any.whl (195 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.7/195.7 KB 12.7 MB/s eta 0:00:00
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.6.0-py2.py3-none-any.whl (21 kB)
Collecting identify>=1.0.0
  Downloading identify-2.4.8-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 KB 21.4 MB/s eta 0:00:00
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.13.1-py2.py3-none-any.whl (8.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 68.3 MB/s eta 0:00:00
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.3.1-py2.py3-none-any.whl (7.3 kB)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 KB 55.7 MB/s eta 0:00:00
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.4.1-py3-none-any.whl (14 kB)
Collecting filelock<4,>=3.2
  Downloading filelock-3.4.2-py3-none-any.whl (9.9 kB)
Collecting six<2,>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.4-py2.py3-none-any.whl (461 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.2/461.2 KB 51.0 MB/s eta 0:00:00
Installing collected packages: nodeenv, distlib, toml, six, pyyaml, platformdirs, identify, filelock, cfgv, virtualenv, pre-commit
Successfully installed cfgv-3.3.1 distlib-0.3.4 filelock-3.4.2 identify-2.4.8 nodeenv-1.6.0 platformdirs-2.4.1 pre-commit-2.17.0 pyyaml-6.0 six-1.16.0 toml-0.10.2 virtualenv-20.13.1
```

### stderr:

```Shell
WARNING: You are using pip version 22.0.2; however, version 22.0.3 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.10.2/x64/bin/python -m pip install --upgrade pip' command.
```

</details>
<details>
<summary><em>pre-commit autoupdate || (exit 0);</em></summary>

```Shell
Updating https://github.com/pre-commit/pre-commit-hooks ... [INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
already up to date.
Updating https://github.com/PyCQA/isort ... [INFO] Initializing environment for https://github.com/PyCQA/isort.
already up to date.
Updating https://github.com/asottile/pyupgrade ... [INFO] Initializing environment for https://github.com/asottile/pyupgrade.
already up to date.
Updating https://github.com/psf/black ... [INFO] Initializing environment for https://github.com/psf/black.
updating 21.12b0 -> 22.1.0.
Updating https://github.com/PyCQA/pylint ... [INFO] Initializing environment for https://github.com/PyCQA/pylint.
already up to date.
Updating https://github.com/MarcoGorelli/madforhooks ... [INFO] Initializing environment for https://github.com/MarcoGorelli/madforhooks.
already up to date.
```

</details>
<details>
<summary><em>pre-commit run -a || (exit 0);</em></summary>

```Shell
[INFO] Initializing environment for local:pandas,pyyaml.
[INFO] Initializing environment for local:pyyaml.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/pylint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/MarcoGorelli/madforhooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for merge conflicts................................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
debug statements (python)................................................Passed
fix end of files.........................................................Passed
don't commit to branch...................................................Passed
fix requirements.txt.....................................................Passed
trim trailing whitespace.................................................Passed
isort....................................................................Passed
pyupgrade................................................................Passed
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted benchmarks/benchmarks/benchmarks.py
reformatted pymc/bart/pgbart.py
reformatted pymc/distributions/dist_math.py
reformatted pymc/distributions/continuous.py
reformatted pymc/distributions/multivariate.py
reformatted pymc/distributions/timeseries.py
reformatted pymc/gp/gp.py
reformatted pymc/printing.py
reformatted pymc/model.py
reformatted pymc/smc/sample_smc.py
reformatted pymc/smc/smc.py
reformatted pymc/step_methods/hmc/base_hmc.py
reformatted pymc/sampling.py
reformatted pymc/step_methods/hmc/quadpotential.py
reformatted pymc/step_methods/metropolis.py
reformatted pymc/step_methods/step_sizes.py
reformatted pymc/step_methods/mlda.py
reformatted pymc/tests/models.py
reformatted pymc/tests/test_aesaraf.py
reformatted pymc/tests/test_distributions_moments.py
reformatted pymc/tests/test_distributions.py
reformatted pymc/tests/test_distributions_random.py
reformatted pymc/tests/test_gp.py
reformatted pymc/tests/test_minibatches.py
reformatted pymc/tests/test_parallel_sampling.py
reformatted pymc/tests/test_model.py
reformatted pymc/tests/test_starting.py
reformatted pymc/tests/test_sampling.py
reformatted pymc/tests/test_step.py
reformatted pymc/tuning/starting.py
reformatted pymc/tests/test_variational_inference.py
reformatted pymc/variational/approximations.py
reformatted pymc/variational/test_functions.py
reformatted pymc/variational/flows.py
reformatted pymc/variational/updates.py

All done! ✨ 🍰 ✨
35 files reformatted, 104 files left unchanged.

pylint...................................................................Passed
Disallow print statements................................................Passed
Sort dependencies in conda environment files.............................Passed
Check no tests are ignored...............................................Passed
Generate pip dependency from conda.......................................Passed
No relative imports......................................................Passed
```

</details>

</details>

## Changed files
<details>
<summary>Changed 36 files: </summary>

- .pre-commit-config.yaml
- benchmarks/benchmarks/benchmarks.py
- pymc/bart/pgbart.py
- pymc/distributions/continuous.py
- pymc/distributions/dist_math.py
- pymc/distributions/multivariate.py
- pymc/distributions/timeseries.py
- pymc/gp/gp.py
- pymc/model.py
- pymc/printing.py
- pymc/sampling.py
- pymc/smc/sample_smc.py
- pymc/smc/smc.py
- pymc/step_methods/hmc/base_hmc.py
- pymc/step_methods/hmc/quadpotential.py
- pymc/step_methods/metropolis.py
- pymc/step_methods/mlda.py
- pymc/step_methods/step_sizes.py
- pymc/tests/models.py
- pymc/tests/test_aesaraf.py
- pymc/tests/test_distributions.py
- pymc/tests/test_distributions_moments.py
- pymc/tests/test_distributions_random.py
- pymc/tests/test_gp.py
- pymc/tests/test_minibatches.py
- pymc/tests/test_model.py
- pymc/tests/test_parallel_sampling.py
- pymc/tests/test_sampling.py
- pymc/tests/test_starting.py
- pymc/tests/test_step.py
- pymc/tests/test_variational_inference.py
- pymc/tuning/starting.py
- pymc/variational/approximations.py
- pymc/variational/flows.py
- pymc/variational/test_functions.py
- pymc/variational/updates.py

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/create-pr-action) | [:memo: Issues](https://github.com/technote-space/create-pr-action/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/create-pr-action)

### CODE REVIEW

**Review by michaelosthege — APPROVED** [review]
The diff here looks good, but we should probably merge this after the other finish-line PRs, and most importantly after the VI PR ?
Is there a way to ask the bot to re-render after merging the other PRs?

**Comment by canyon289** [comment]
I assume someone could just pull main and run this new precommit on it and then make a PR, basically acting as the bot

**Comment by ricardoV94** [comment]
Rebased from main. The new `**` space default is much more sane!

**Comment by twiecki** [comment]
Yeah, really glad they finally got rid of it.

**Review by michaelosthege — APPROVED** [review]

**Pull request merged**
