### PR TITLE
fix the issue 3430

### PR DESCRIPTION
**Pull request by chang111**
fis the issue 3430
previous:
pmf = [1 / (u - l)] * len(x)
now:
pmf = [1 / (u - l + 1)] * len(x)

### CODE REVIEW

**Comment by chang111** [comment]
The error from travis is about 'import matplotlib'. I think it is not related to my pr

**Comment by lucianopaz** [comment]
Thanks! Yes, it seems that the docs should use your normalization. The problem with Travis was resolved in master (we deleted the cache files). Your PR seems to be pulling out old caches. Did you rebase on to of the pymc-devs/pymc3/master branch? If not, try rebasing your PR's branch on top of it and we'll see if Travis passes (you don't need to close this PR to make the rebase!).

One more thing, when I started my first PR's I would name them like you do. Then @twiecki pointed out that those names were not informative, and recommended that I make the titles more explicit as to what each PR did. For example, your PR could be titled "Fixed normalization constant in DiscreteUniform docs". I recommend you keep that in mind for your next contributions.

**Comment by chang111** [comment]
@lucianopaz Thanks to your reply. I will take your reccomendation.

**Comment by chang111** [comment]
@lucianopaz I feel confused about how I can rebasing your PR's branch on top of it . Please give a guide.

**Comment by chang111** [comment]
But I think the retest is not necessary for the reason that I just change the docs of the code. The test  in travis is not related. Do you think so.

**Comment by lucianopaz** [comment]
Yes, it's unnecessary for merging this PR, but if Travis still fails because of the import error, I'll reopen issue #3423.

**Comment by chang111** [comment]
Fine, I will try again.

**Comment by lucianopaz** [comment]
Also, if we merge this as is, we'll be reintroducing the corrupted cache files into circulation in the master branch.

**Comment by chang111** [comment]
@lucianopaz As for your PR name request, I will start a new PR and close this PR. Thank you very much for your advice.

**Pull request closed without merging**
