### PR TITLE
Fix VI `var_replacement` test

### LINKED ISSUE #6348: VI variable replacement broken with Aesara 2.8.8
### Description

We added an xfail to this [test]() in #6336. The issue is that this VI method is trying to replace an RV by a larger one. This is not allowed when the graph is created with a fixed size RV.

The test case doesn't seem needed at all, one can create a variable sized RV already with a shared variable and then resize it. Would this fulfill all the needs?

### PR DESCRIPTION
**Pull request by ricardoV94**
Closes #6348

### CODE REVIEW

**Comment by ricardoV94** [comment]
Failure is unrelated

**Review by ferrine — APPROVED** [review]

**Comment by ferrine** [comment]
What is wrong with pymc/tests/distributions/test_timeseries.py::TestGARCH11::test_batched_size ?

**Comment by ferrine** [comment]
is it safe to merge with this test?

**Comment by ricardoV94** [comment]
Yes, test is completely unrelated

**Pull request merged**
