### PR TITLE
[WIP] RMHMC

### PR DESCRIPTION
**Pull request by bhargavvader**
Restructure RMHMC to accommodate for the new refactoring by @aseyboldt . 
Closed the old PR #2240.

Currently implementing algorithms `algorithm 1` and `algorithm 2` on page 12 in this [paper](https://arxiv.org/pdf/1212.4693.pdf) which describes a Hamiltonian evolution for RMHMC. We will be using an approximation for the Hessian, preferably where the Hessian is the diagonal elements of the outer product of the potential, or take a crack at footnote 3, which talks about Hessian vector products.

### CODE REVIEW

**Comment by bhargavvader** [comment]
https://summerofcode2017.wordpress.com/2017/08/09/the-way-forward-gsoc-2017/

A small blog post for anyone else interested in taking this forward.

**Comment by jlumpe** [comment]
Exactly one year later... what's the status of this PR? Are you still planning on coming back to it, or just waiting on someone else to pick it up?

**Comment by fonnesbeck** [comment]
The PR is closed, so we do not anticipate further development.

**Comment by bhargavvader** [comment]
@jlumpe I'm afraid I don't have the bandwidth to take this up now. :(

**Comment by twiecki** [comment]
@jlumpe If you want to give it a shot, that'd be great. However, the utility of RMHMC is rather doubtful to me at this point.

**Comment by jlumpe** [comment]
Thank you for the responses, it's possible I may end up trying to take this on at some point.

**Pull request closed without merging**
