### PR TITLE
Rename pymc to pymc3.

### PR DESCRIPTION
**Pull request by twiecki**
For discussion see: https://github.com/pymc-devs/pymc/issues/677

### CODE REVIEW

**Comment by fonnesbeck** [comment]
So, the other advantage to the rename is that we can have separate repositories for both versions. Can I do this?

**Comment by kyleam** [comment]
I'm for two repositories.  I suppose that would also solve #680.

**Comment by twiecki** [comment]
@fonnesbeck I'm +1 on that, yeah. Would also solve the docs URL problem.

**Comment by twiecki** [comment]
Ah, that's what @kyleam was referring to.

**Comment by twiecki** [comment]
@fonnesbeck One thing to consider is the issues and PRs. There's certainly less for pymc2. So one other approach would be to create a pymc2 repo, then rename pymc->pymc3 and pymc2->pymc.

**Comment by fonnesbeck** [comment]
Yes, that's certainly the way to go. Any other issues with this we are forgetting?

**Comment by fonnesbeck** [comment]
OK, I have a clean `pymc2` repo on pymc-devs. If everything checks out, we can rename `pymc` to `pymc3`, remove the 2.x and related branches, move the outstanding PyMC 2.3 issues over, then rename `pymc2` to `pymc`. Sound good?

**Comment by twiecki** [comment]
:+1:

**Comment by fonnesbeck** [comment]
@kyleam and @jsalvatier, can you give me the thumbs up on this? I don't want to pull the trigger until everyone is aware of what is going on.

**Comment by kyleam** [comment]
(trying to figure out how @twiecki gets that thumbs up ...) :+1:

**Comment by jsalvatier** [comment]
Hey guys, sorry for the tardiness. Yeah, I think this is okay, it really is pretty different. :+1:

**Comment by fonnesbeck** [comment]
OK, this is done: PyMC 3 is now in `pymc3` and PyMC 2.3 is in `pymc`. I've deleted some obvious 2.3 branches from the set of branches, but if any of you have remote branches that you are done with, please go in and delete them. Looks like a lot of cruft.

I will move the extant 2.3-related issues over to `pymc`.

**Pull request merged**
