### PR TITLE
WIP: Initialize NUTS with ADVI

### PR DESCRIPTION
**Pull request by twiecki**
First attempt at initializing NUTS using ADVI. Check out the stoch vol model (https://github.com/pymc-devs/pymc3/blob/c7eabf17ddbc25b950720bc86f1966478a487c79/pymc3/examples/stochastic_volatility.ipynb): seems like we get way better convergence. Would be great if someone could try this on a model where NUTS has a hard time starting.

CC @fonnesbeck. Addresses https://github.com/pymc-devs/pymc3/issues/1087

### CODE REVIEW

**Comment by springcoil** [comment]
Do you still consider this a WIP or do you consider this worked out? Does this need other examples with ADVI running on it, for it to be merged?

**Comment by twiecki** [comment]
Would like to see if it helps with some other problems like stalling NUTS.

**Comment by springcoil** [comment]
I tried a few examples like Brandeis dice and cox model last night to go
avail.

**Comment by twiecki** [comment]
no avail?

**Comment by springcoil** [comment]
Yes :)

On Mon, May 16, 2016 at 3:46 PM, Thomas Wiecki notifications@github.com
wrote:

> no avail?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1088#issuecomment-219444035

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by twiecki** [comment]
https://gist.github.com/3df8f0067c367f09eed2f97a7d3b0ab3 seems to work.

**Comment by springcoil** [comment]
Cool - is that pushed to the master branch now?

On Mon, May 16, 2016 at 5:36 PM, Thomas Wiecki notifications@github.com
wrote:

> https://gist.github.com/3df8f0067c367f09eed2f97a7d3b0ab3 seems to work.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1088#issuecomment-219474697

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by twiecki** [comment]
no, still `init_advi`, but this one is up-to-date.

**Comment by twiecki** [comment]
I also added the cox-model.

**Pull request merged**
