### PR TITLE
Fixed failure in NegativeBinomial and Poisson related to logpow.

### LINKED ISSUE #842: Erroneous dimension mis-match error
As reported by another user, the following simple model fails on OS X and Python 3. It appears to be complaining about the size of the `observed` argument for the NegativeBinomial, which should not be happening. Changing to another distribution (e.g. Poisson) does not change this. Adding a `shape` argument to the likelihood also does not fix the problem, nor does removing `find_map`. Passing a scalar as data resolves the issue.

``` python
import pymc3 as pm
import numpy as np

data = [6.0,12.0,12.0,46.0,5.0,11.0,11.0,39.0,4.0,10.0,25.0,11.0,8.0,5.0,10.0,2.0,30.0,21.0]

with pm.Model() as model:
    alpha = pm.Uniform('alpha', lower=0.1, upper=100)
    mu = pm.Uniform('mu', lower=0.1, upper=100)

    y_pred = pm.NegativeBinomial('y_pred', mu=mu, alpha=alpha)

    y_est = pm.NegativeBinomial('y_est', 
                                mu=mu, 
                                alpha=alpha, 
                                observed=data)

    start = pm.find_MAP()

    step = pm.NUTS()
    trace = pm.sample(2000, step, start=start, progressbar=True)
```

Here's the error.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/fonnescj/anaconda3/lib/python3.4/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    839         try:
--> 840             outputs = self.fn()
    841         except Exception:

ValueError: Input dimension mis-match. (input[0].shape[0] = 1, input[4].shape[0] = 18)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-899599b91d18> in <module>()
     15                                 observed=data, shape=len(data))
     16 
---> 17     start = pm.find_MAP()
     18 
     19     step = pm.NUTS()

/Users/fonnescj/Github/pymc3/pymc3/tuning/starting.py in find_MAP(start, vars, fmin, return_raw, disp, model, *args, **kwargs)
     79     if 'fprime' in getargspec(fmin).args:
     80         r = fmin(logp_o, bij.map(
---> 81             start), fprime=grad_logp_o, disp=disp, *args, **kwargs)
     82     else:
     83         r = fmin(logp_o, bij.map(start), disp=disp, *args, **kwargs)

/Users/fonnescj/anaconda3/lib/python3.4/site-packages/scipy/optimize/optimize.py in fmin_bfgs(f, x0, fprime, args, gtol, norm, epsilon, maxiter, full_output, disp, retall, callback)
    787             'return_all': retall}
    788 
--> 789     res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
    790 
    791     if full_output:

/Users/fonnescj/anaconda3/lib/python3.4/site-packages/scipy/optimize/optimize.py in _minimize_bfgs(fun, x0, args, jac, callback, gtol, norm, eps, maxiter, disp, return_all, **unknown_options)
    841     else:
    842         grad_calls, myfprime = wrap_function(fprime, args)
--> 843     gfk = myfprime(x0)
    844     k = 0
    845     N = len(x0)

/Users/fonnescj/anaconda3/lib/python3.4/site-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
    283     def function_wrapper(*wrapper_args):
    284         ncalls[0] += 1
--> 285         return function(*(wrapper_args + args))
    286 
    287     return ncalls, function_wrapper

/Users/fonnescj/Github/pymc3/pymc3/tuning/starting.py in grad_logp_o(point)
     74 
     75     def grad_logp_o(point):
---> 76         return nan_to_num(-dlogp(point))
     77 
     78     # Check to see if minimization function actually uses the gradient

/Users/fonnescj/Github/pymc3/pymc3/blocking.py in __call__(self, x)
    117 
    118     def __call__(self, x):
--> 119         return self.fa(self.fb(x))

/Users/fonnescj/Github/pymc3/pymc3/model.py in __call__(self, state)
    397 
    398     def __call__(self, state):
--> 399         return self.f(**state)
    400 
    401 class LoosePointFunc(object):

/Users/fonnescj/anaconda3/lib/python3.4/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    849                         self.fn.nodes[self.fn.position_of_error],
    850                         self.fn.thunks[self.fn.position_of_error],
--> 851                         storage_map=self.fn.storage_map)
    852                 else:
    853                     # For the c linker We don't have access from

/Users/fonnescj/anaconda3/lib/python3.4/site-packages/theano/gof/link.py in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

/Users/fonnescj/anaconda3/lib/python3.4/site-packages/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

/Users/fonnescj/anaconda3/lib/python3.4/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    838         t0_fn = time.time()
    839         try:
--> 840             outputs = self.fn()
    841         except Exception:
    842             if hasattr(self.fn, 'position_of_error'):

ValueError: Input dimension mis-match. (input[0].shape[0] = 1, input[4].shape[0] = 18)
Apply node that caused the error: Elemwise{Composite{Switch(i0, i1, Switch(i2, Switch(i3, i1, i4), i1))}}(TensorConstant{(1,) of 0}, TensorConstant{(1,) of 0}, Elemwise{mul,no_inplace}.0, InplaceDimShuffle{x}.0, TensorConstant{[  6.  12... 30.  21.]})
Toposort index: 36
Inputs types: [TensorType(int8, vector), TensorType(int8, (True,)), TensorType(int8, (True,)), TensorType(int8, (True,)), TensorType(float64, vector)]
Inputs shapes: [(1,), (1,), (1,), (1,), (18,)]
Inputs strides: [(1,), (1,), (1,), (1,), (8,)]
Inputs values: [array([0], dtype=int8), array([0], dtype=int8), array([1], dtype=int8), array([0], dtype=int8), 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(Elemwise{Composite{Switch(i0, i1, Switch(i2, Switch(i3, i1, i4), i1))}}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

### PR DESCRIPTION
**Pull request by fonnesbeck**
Fixes #842

### CODE REVIEW

**Comment by twiecki** [comment]
It makes sense that this didn't work but I wonder if this is the correct fix. If m and/or x can be a scalar and/or vector, shouldn't we support all those cases? Perhaps something along the lines of `switch(any(eq(m, 0)) or any(eq(x, 0)), 0, m * log(x))` ?

**Comment by fonnesbeck** [comment]
Right, though we really only need to check `m`, correct? When `m` is zero, the return value should be zero irrespective of `x`, right? We were only trying to catch the failure of 0**0, but we shouldn't actually have to test `x` here.

**Comment by twiecki** [comment]
But if `m != 0` and `any(x == 0)` we'd get a `-inf` in the results. I suppose that's ok?

**Comment by fonnesbeck** [comment]
Yes, and actually, we should monitor `x` instead because if _any_ x is zero, we should be returning -inf, whereas if any `m` is zero, we should not be returning a zero for the whole vector. I will update the PR.

**Comment by twiecki** [comment]
Right, although I start to wonder why we need this at all. `m * log(x)` alone should handle the `0` and `-inf` case.

**Comment by fonnesbeck** [comment]
OK, I thought this was here because of a failure. Happy to remove the switch statement if this is not the case.

**Comment by twiecki** [comment]
I don't know, just thinking out loud. This is where it was added: https://github.com/pymc-devs/pymc3/commit/8d38b63b847bf6cb924c273ad1f6e0c2ec0c5f70

I don't think @jsalvatier would have added it otherwise and the doc string suggests it's required. But maybe checking under which scenarios an exception is raised to get this right.

**Comment by twiecki** [comment]
Well, I suppose if it works that's all we need. Not sure I understand why this fixes it in the first place. Here is an example that seems to suggest the function is doing the correct thing.

``` python
from pymc3 import *
import theano.tensor as tt
x = tt.dvector('x')
x.tag.test_value = np.array([1, 2, 3])
m = tt.scalar('m')
m.tag.test_value = 3
f = theano.function([x, m], switch(eq(x, 0) & eq(m, 0), 0, m * log(x)))
print(f(np.array([1, 2, 3]), 3))
print(f(np.array([1, 2, 3]), 0))
print(f(np.array([1, 2, 0]), 0))
print(f(np.array([0, 0, 0]), 0))
```

```
[ 0.          2.07944154  3.29583687]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
```

ping @jsalvatier

**Comment by fonnesbeck** [comment]
This fixes the problem because Theano.

**Comment by twiecki** [comment]
LGTM then ;)

**Comment by fonnesbeck** [comment]
The original problem was an input dimension mismatch, which seems odd for a switch statement. It must have something to do with the fact that `x` is a vector and `m` is a scalar, but that doesn't explain why it does not fail in your above example. Maybe if we slapped the `any` on the original formulation it would work fine. In any case, we should not need to test both `x` and `m`.

**Comment by twiecki** [comment]
@fonnesbeck lets just merge then? I don't think it's critical to get to the bottom of this.

**Pull request merged**
