### PR TITLE
Rerun notebooks

### PR DESCRIPTION
**Pull request by canyon289**
Trying to rerun all notebooks but been running into tons of errors because basically api changes in multiple libraries are breaking a bunch of the notebooks.

I'll push changes here and check off the ones that I have running. If anyone wants to help out thatd be great!

- [x] api_quickstart.ipynb
- [x] AR.ipynb
- [x] Bayes_factor.ipynb
- [x] bayesian_neural_network_advi.ipynb
- [x] bayes_param_survival_pymc3.ipynb
- [x] BEST.ipynb
- [x] blackbox_external_likelihood.ipynb
- [x] censored_data.ipynb
- [x] convolutional_vae_keras_advi.ipynb
- [x] cox_model.ipynb
- [x] dawid-skene.ipynb
- [x] dependent_density_regression.ipynb
- [x] Diagnosing_biased_Inference_with_Divergences.ipynb
- [x] dp_mix.ipynb
- [x] empirical-approx-overview.ipynb
- [x] Euler-Maruyama_and_SDEs.ipynb
- [x] gaussian-mixture-model-advi.ipynb
- [x] gaussian_mixture_model.ipynb
- [x] gaussian_process.ipynb
- [x] getting_started.ipynb
- [x] GLM-hierarchical-advi-minibatch.ipynb
- [x] GLM-hierarchical-binominal-model.ipynb
- [x] GLM-hierarchical.ipynb
- [x] GLM.ipynb
- [x] GLM-linear.ipynb
- [x] GLM-logistic.ipynb
- [x] GLM-model-selection.ipynb
- [x] GLM-negative-binomial-regression.ipynb
- [x] GLM-poisson-regression.ipynb
- [x] GLM-robust.ipynb
- [x] GLM-robust-with-outlier-detection.ipynb
- [x] GLM-rolling-regression.ipynb
- [x] GP-Kron.ipynb
- [x] GP-Latent.ipynb
- [x] GP-Marginal.ipynb
- [ ] GP-MaunaLoa2.ipynb
- [x] GP-MaunaLoa.ipynb
- [x] GP-MeansAndCovs.ipynb
- [x] GP-slice-sampling.ipynb
- [x] GP-smoothing.ipynb
- [x] GP-SparseApprox.ipynb
- [x] GP-TProcess.ipynb
- [x] hierarchical_partial_pooling.ipynb
- [x] howto_debugging.ipynb
- [x] lasso_block_update.ipynb
- [x] lda-advi-aevb.ipynb
- [x] live_sample_plots.ipynb
- [x] LKJ.ipynb
- [x] marginalized_gaussian_mixture_model.ipynb
- [x] model_averaging.ipynb
- [x] model_comparison.ipynb
- [x] multilevel_modeling.ipynb
- [x] MvGaussianRandomWalk_demo.ipynb
- [x] normalizing_flows_overview.ipynb
- [x] ODE_parameter_estimation.ipynb
- [x] posterior_predictive.ipynb
- [x] profiling.ipynb
- [x] PyMC3_tips_and_heuristic.ipynb
- [x] rugby_analytics.ipynb
- [x] sampler-stats.ipynb
- [x] sampling_compound_step.ipynb
- [x] SMC2_gaussians.ipynb
- [x] stochastic_volatility.ipynb
- [x] survival_analysis.ipynb
- [x] updating_priors.ipynb
- [x] variational_api_quickstart.ipynb
- [x] weibull_aft.ipynb

My current env

> alabaster                 0.7.12                   pypi_0    pypi
> algopy                    0.5.7                    pypi_0    pypi
> argh                      0.26.2                   pypi_0    pypi
> arviz                     0.3.3                    pypi_0    pypi
> astroid                   2.2.5                    pypi_0    pypi
> atomicwrites              1.3.0                    pypi_0    pypi
> attrs                     19.1.0                   pypi_0    pypi
> babel                     2.6.0                    pypi_0    pypi
> backcall                  0.1.0                    pypi_0    pypi
> blas                      1.0                         mkl  
> bleach                    3.1.0                    pypi_0    pypi
> bokeh                     1.0.4                    pypi_0    pypi
> ca-certificates           2019.1.23                     0  
> certifi                   2018.11.29               py37_0  
> cftime                    1.0.3.4                  pypi_0    pypi
> chardet                   3.0.4                    pypi_0    pypi
> commonmark                0.5.4                    pypi_0    pypi
> coverage                  4.5.2                    pypi_0    pypi
> cycler                    0.10.0                   pypi_0    pypi
> decorator                 4.3.2                    pypi_0    pypi
> defusedxml                0.5.0                    pypi_0    pypi
> docutils                  0.14                     pypi_0    pypi
> entrypoints               0.3                      pypi_0    pypi
> h5py                      2.9.0                    pypi_0    pypi
> idna                      2.8                      pypi_0    pypi
> imagesize                 1.1.0                    pypi_0    pypi
> intel-openmp              2019.1                      144  
> ipykernel                 5.1.0                    pypi_0    pypi
> ipython                   7.3.0                    pypi_0    pypi
> ipython-genutils          0.2.0                    pypi_0    pypi
> isort                     4.3.13                   pypi_0    pypi
> jedi                      0.13.3                   pypi_0    pypi
> jinja2                    2.10                     pypi_0    pypi
> jsonschema                3.0.1                    pypi_0    pypi
> jupyter-client            5.2.4                    pypi_0    pypi
> jupyter-core              4.4.0                    pypi_0    pypi
> jupyterlab                0.35.4                   pypi_0    pypi
> jupyterlab-server         0.2.0                    pypi_0    pypi
> keras                     2.2.4                    pypi_0    pypi
> keras-applications        1.0.7                    pypi_0    pypi
> keras-preprocessing       1.0.9                    pypi_0    pypi
> kiwisolver                1.0.1                    pypi_0    pypi
> lazy-object-proxy         1.3.1                    pypi_0    pypi
> libedit                   3.1.20181209         hc058e9b_0  
> libffi                    3.2.1                hd88cf55_4  
> libgcc-ng                 8.2.0                hdf63c60_1  
> libgfortran-ng            7.3.0                hdf63c60_0  
> libstdcxx-ng              8.2.0                hdf63c60_1  
> livereload                2.6.0                    pypi_0    pypi
> markupsafe                1.1.1                    pypi_0    pypi
> matplotlib                3.0.3                    pypi_0    pypi
> mccabe                    0.6.1                    pypi_0    pypi
> mistune                   0.8.4                    pypi_0    pypi
> mkl                       2019.1                      144  
> mkl_fft                   1.0.10           py37ha843d7b_0  
> mkl_random                1.0.2            py37hd81dba3_0  
> more-itertools            6.0.0                    pypi_0    pypi
> nbconvert                 5.4.1                    pypi_0    pypi
> nbformat                  4.4.0                    pypi_0    pypi
> nbsphinx                  0.4.2                    pypi_0    pypi
> ncurses                   6.1                  he6710b0_1  
> netcdf4                   1.4.3.2                  pypi_0    pypi
> nose                      1.3.7                    pypi_0    pypi
> nose-parameterized        0.6.0                    pypi_0    pypi
> notebook                  5.7.5                    pypi_0    pypi
> numdifftools              0.9.20                   pypi_0    pypi
> numpy                     1.16.2           py37h7e9f1db_0  
> numpy-base                1.16.2           py37hde5b4d6_0  
> numpydoc                  0.7.0                    pypi_0    pypi
> openssl                   1.1.1b               h7b6447c_1  
> packaging                 19.0                     pypi_0    pypi
> pandas                    0.24.1           py37he6710b0_0  
> pandocfilters             1.4.2                    pypi_0    pypi
> parso                     0.3.4                    pypi_0    pypi
> pathtools                 0.1.2                    pypi_0    pypi
> patsy                     0.5.1                    pypi_0    pypi
> pexpect                   4.6.0                    pypi_0    pypi
> pickleshare               0.7.5                    pypi_0    pypi
> pillow                    5.4.1                    pypi_0    pypi
> pip                       19.0.3                   py37_0  
> pluggy                    0.9.0                    pypi_0    pypi
> port-for                  0.3.1                    pypi_0    pypi
> prometheus-client         0.6.0                    pypi_0    pypi
> prompt-toolkit            2.0.9                    pypi_0    pypi
> ptyprocess                0.6.0                    pypi_0    pypi
> py                        1.8.0                    pypi_0    pypi
> pycodestyle               2.5.0                    pypi_0    pypi
> pyflakes                  2.1.1                    pypi_0    pypi
> pygments                  2.3.1                    pypi_0    pypi
> pylint                    2.3.1                    pypi_0    pypi
> pymc3                     3.6                       dev_0    <develop>
> pyparsing                 2.3.1                    pypi_0    pypi
> pyrsistent                0.14.11                  pypi_0    pypi
> pytest                    4.3.0                    pypi_0    pypi
> pytest-cov                2.6.1                    pypi_0    pypi
> python                    3.7.2                h0371630_0  
> python-dateutil           2.8.0                    py37_0  
> python-graphviz           0.10.1                   pypi_0    pypi
> pytz                      2018.9                   py37_0  
> pyyaml                    3.13                     pypi_0    pypi
> pyzmq                     18.0.1                   pypi_0    pypi
> readline                  7.0                  h7b6447c_5  
> recommonmark              0.5.0                    pypi_0    pypi
> requests                  2.21.0                   pypi_0    pypi
> scipy                     1.2.1                    pypi_0    pypi
> seaborn                   0.9.0                    pypi_0    pypi
> send2trash                1.5.0                    pypi_0    pypi
> setuptools                40.8.0                   py37_0  
> six                       1.12.0                   pypi_0    pypi
> snowballstemmer           1.2.1                    pypi_0    pypi
> sphinx                    1.8.4                    pypi_0    pypi
> sphinx-autobuild          0.7.1                    pypi_0    pypi
> sphinxcontrib-websupport  1.1.0                    pypi_0    pypi
> sqlite                    3.26.0               h7b6447c_0  
> statsmodels               0.9.0            py37h035aef0_0  
> terminado                 0.8.1                    pypi_0    pypi
> testpath                  0.4.2                    pypi_0    pypi
> theano                    1.0.4                    pypi_0    pypi
> tk                        8.6.8                hbc83047_0  
> tornado                   6.0.1                    pypi_0    pypi
> tqdm                      4.31.1                   pypi_0    pypi
> traitlets                 4.3.2                    pypi_0    pypi
> typed-ast                 1.3.1                    pypi_0    pypi
> urllib3                   1.24.1                   pypi_0    pypi
> watchdog                  0.9.0                    pypi_0    pypi
> wcwidth                   0.1.7                    pypi_0    pypi
> webencodings              0.5.1                    pypi_0    pypi
> wheel                     0.33.1                   py37_0  
> wrapt                     1.11.1                   pypi_0    pypi
> xarray                    0.11.3                   pypi_0    pypi
> xz                        5.2.4                h14c3975_4  
> zlib                      1.2.11               h7b6447c_3

### CODE REVIEW

**Comment by junpenglao** [comment]
I will help.
Running the notebooks I wrote and the GLM notebooks.

**Comment by junpenglao** [comment]
Also, we might want to prioritize those notebook have not been run for a while.

**Comment by ColCarroll** [comment]
I will run the `GP-` notebooks

**Comment by canyon289** [comment]
> Also, we might want to prioritize those notebook have not been run for a while.

How can we tell which one hasn't been run in a while?

**Comment by ColCarroll** [comment]
Via https://serverfault.com/questions/401437/how-to-retrieve-the-last-modification-date-of-all-files-in-a-git-repository and some messing around:
```bash
git ls-tree -r --name-only HEAD | grep notebooks | while read filename; do   echo "$(git log -1 --format="%ai" -- $filename) $filename"; done | sort
```

**Comment by ColCarroll** [comment]
```
2017-03-27 11:36:12 +0200 docs/source/notebooks/live_sample_plots.ipynb
2017-04-26 13:42:44 +0000 docs/source/notebooks/dawid-skene.ipynb
2017-06-23 16:10:24 -0400 docs/source/notebooks/GP-slice-sampling.ipynb
2017-08-17 13:52:51 +0300 docs/source/notebooks/gaussian-mixture-model-advi.ipynb
2018-01-26 06:20:54 -0300 docs/source/notebooks/smc.png
2018-02-03 18:07:03 -0600 docs/source/notebooks/normalizing_flows_overview.ipynb
2018-03-07 12:05:34 -0300 docs/source/notebooks/dp_mix.ipynb
2018-06-22 18:27:08 -0300 docs/source/notebooks/SMC2_gaussians.ipynb
2018-06-24 17:12:12 -0700 docs/source/notebooks/GP-MeansAndCovs.ipynb
2018-07-12 04:00:25 +0000 docs/source/notebooks/GLM-negative-binomial-regression.ipynb
2018-07-30 02:03:19 -0400 docs/source/notebooks/sampling_compound_step.ipynb
2018-07-31 13:32:52 -0400 docs/source/notebooks/dependent_density_regression.ipynb
2018-07-31 13:32:52 -0400 docs/source/notebooks/GP-SparseApprox.ipynb
2018-07-31 13:32:52 -0400 docs/source/notebooks/GP-TProcess.ipynb
2018-07-31 13:32:52 -0400 docs/source/notebooks/marginalized_gaussian_mixture_model.ipynb
2018-10-07 09:36:42 +0000 docs/source/notebooks/LKJ.ipynb
2018-11-15 01:14:31 +0900 docs/source/notebooks/lda-advi-aevb.ipynb
2018-12-19 13:15:50 +0100 docs/source/notebooks/cox_model.ipynb
2018-12-19 13:15:50 +0100 docs/source/notebooks/gaussian_process.ipynb
2018-12-19 18:27:06 +0100 docs/source/notebooks/table_of_contents_tutorials.js
2018-12-22 12:14:33 +0100 docs/source/notebooks/bayesian_neural_network_advi.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/blackbox_external_likelihood.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/censored_data.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/convolutional_vae_keras_advi.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/empirical-approx-overview.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/Euler-Maruyama_and_SDEs.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/gaussian_mixture_model.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/getting_started.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM-hierarchical-advi-minibatch.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM-hierarchical.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM-linear.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM-model-selection.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM-poisson-regression.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM-robust.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GLM-robust-with-outlier-detection.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GP-Latent.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GP-MaunaLoa.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/GP-smoothing.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/howto_debugging.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/lasso_block_update.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/multilevel_modeling.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/MvGaussianRandomWalk_demo.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/posterior_predictive.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/rugby_analytics.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/sampler-stats.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/survival_analysis.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/updating_priors.ipynb
2018-12-22 12:14:33 +0100 docs/source/notebooks/variational_api_quickstart.ipynb
2018-12-26 20:41:20 +0000 docs/source/notebooks/GP-Kron.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/Diagnosing_biased_Inference_with_Divergences.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/GLM-hierarchical-binominal-model.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/GLM-rolling-regression.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/GP-MaunaLoa2.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/hierarchical_partial_pooling.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/PyMC3_tips_and_heuristic.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/stochastic_volatility.ipynb
2018-12-27 20:26:54 +0000 docs/source/notebooks/weibull_aft.ipynb
2019-01-04 01:12:42 -0500 docs/source/notebooks/GLM-logistic.ipynb
2019-01-15 08:37:30 -0500 docs/source/notebooks/BEST.ipynb
2019-01-25 17:42:26 -0300 docs/source/notebooks/model_averaging.ipynb
2019-01-28 19:06:17 +0100 docs/source/notebooks/model_comparison.ipynb
2019-03-07 17:33:21 +0000 docs/source/notebooks/table_of_contents_examples.js
2019-03-07 20:18:23 +0000 docs/source/notebooks/ODE_parameter_estimation.ipynb
2019-03-08 20:41:43 -0800 docs/source/notebooks/Bayes_factor.ipynb
2019-03-08 21:10:16 -0800 docs/source/notebooks/api_quickstart.ipynb
2019-03-08 21:11:09 -0800 docs/source/notebooks/AR.ipynb
2019-03-08 21:25:58 -0800 docs/source/notebooks/bayes_param_survival_pymc3.ipynb
2019-03-09 08:03:41 +0100 docs/source/notebooks/profiling.ipynb
2019-03-09 10:31:01 -0500 docs/source/notebooks/GP-Marginal.ipynb
```

**Comment by fonnesbeck** [comment]
This might be an opportunity to retire notebooks that are either redundant or are not well-annotated. I think the suite is currently too big. Might be worth considering moving most of them to the pymc resources repo.

**Comment by twiecki** [comment]
`empirical-approx-overview.ipynb` has many problems, not sure if it's worth keeping around. @ferrine?

**Comment by twiecki** [comment]
How did you guys push to this branch?

**Comment by ferrine** [comment]
@twiecki, sorry for late update, let me have a look this night

**Comment by ferrine** [comment]
Do you mean bad documented?

**Comment by twiecki** [comment]
Yeah exactly. I think it's quite difficult to follow.

**Comment by junpenglao** [comment]
I did a rebase, hopefully did not mess up anything...

**Comment by junpenglao** [comment]
This is blocking our release - should we split the effort and run the essential notebooks?

**Comment by junpenglao** [comment]
I would say definitively the GP ones should be rerun

**Comment by ferrine** [comment]
@junpenglao if Empirical notebook is a concern, I can take it later and move them to inline docs. For now it is better option to leave it as is and open an issue.

PS I'm on vacations now

**Comment by twiecki** [comment]
Rebased off master, make sure to force pull.

**Comment by junpenglao** [comment]
The Dawid-Skene notebook is fairly OK I remember - any reason why removing it?

**Comment by twiecki** [comment]
I couldn't run it and gave up, if we figure it out should be fine.

**Comment by junpenglao** [comment]
Oh nice @lucianopaz ! I think we are finally ready to merge and do a release?

**Comment by lucianopaz** [comment]
Only the big manualoa2 is left, which takes like a full day to run

**Comment by lucianopaz** [comment]
Releasewise, I would really like #3456 to make it into the release

**Comment by canyon289** [comment]
Is anyone planning on running that one? I can run it on my desktop and leave it on all day

**Comment by canyon289** [comment]
Will push manualoa2 if it finishes running on my desktop and merge in a separate branch

**Pull request merged**
