### PR TITLE
Add additional test for multinomial distribution

### LINKED ISSUE #4487: Test multinomial distribution with probability vector containing zeros
A previous bug in the logp of the Multinomial made it return nan when the probability vector contained zeros. This was behind this issue #3069, and was fixed by https://github.com/pymc-devs/pymc3/pull/3059

The minimal example of issues #3069 is shown below. It had to do with with the last row of the `state_label_tran` which includes a zero-probability for the first class.

```python
import numpy as np
import pymc3 as pm

state_label_tran = np.array([
    [0.3, 0.2, 0.5],
    [0.1, 0.5, 0.4],
    [0.0, 0.05, 0.95],  # Would work fine without this row
])
shape = len(state_label_tran)

with pm.Model() as m:
    label_dist = [
        pm.Multinomial.dist(p=state_label_tran[i], n=1, shape=shape)
        for i in range(len(state_label_tran))
    ]
    label = pm.Mixture('label', w=np.ones(shape)/shape, comp_dists=label_dist, observed=[0, 1, 0])

print(label.logp())  # nan before PR #3059, and -1.386... afterwards
```

But it's enough to check the Multinomial directly:

```python
with pm.Model() as m:
    label = pm.Multinomial('m', n=1, p=[0, 0.05, 0.95], observed=[0, 1, 0])
print(label.logp())  # nan before, and -2.9957 afterwards
```

None of our current Multinomial tests check for a probability vector that includes zeros (except for `test_batch_dirichlet_multinomial` which sometimes does so randomly). We should add one.

_Originally posted by @ricardoV94 in https://github.com/pymc-devs/pymc3/issues/3069#issuecomment-772579318_

### PR DESCRIPTION
**Pull request by Devanshu24**
Fixes #4487 
* Fix logp value of multinomial with 0 as one of the prob-values

I am not sure if this is the correct way to write the test, if anything needs changing please let me know! :D

**Thank your for opening a PR!**

Depending on what your PR does, here are a few things you might want to address in the description:
+ [ ] what are the (breaking) changes that this PR makes?
+ [ ] important background, or details about the implementation
+ [x] are the changes—especially new features—covered by tests and docstrings?
+ [x] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [ ] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

### CODE REVIEW

**Comment by twiecki** [comment]
I think it would be better to test this against the scipy distribution. In that case this test could be added as an additional case to the existing multinomial logp test.

**Comment by Devanshu24** [comment]
Thank you for pointing that out!
To confirm if I understand it correctly, we want to edit this method to incorporate the new test?
https://github.com/pymc-devs/pymc3/blob/82ccb3be4e071ebcbf408c1f49db0c9542c8e88d/pymc3/tests/test_distributions.py#L1833-L1838

**Comment by twiecki** [comment]
@Devanshu24 Correct.

**Comment by Devanshu24** [comment]
Thank you, will get to it! :)

**Comment by michaelosthege** [comment]
@Devanshu24 we are looking to stop accepting PRs into `master`, to reduce rebasing effort on the `v4` branch (see [Timeline](https://github.com/pymc-devs/pymc3/wiki/Timeline)).

Since this PR is currently waiting on you to change the edit anyway, would you mind to instead open a new PR into the `v4` branch?

**Comment by Devanshu24** [comment]
Hi! Definitely I'll do that, sorry for the unexpectedly long delay. There is a lot of optimization done in `pymc3`, hopefully I'll figure it out :D
Thanks for the opportunity :)

**Pull request closed without merging**
