### PR TITLE
Use logging instead of print

### PR DESCRIPTION
**Pull request by ColCarroll**
Addresses #1405 -- there's a single logger that is used everywhere.

### CODE REVIEW

**Comment by twiecki** [comment]
Nice, this allows better control over by the user over which messages get displayed, right?

**Review by springcoil — APPROVED** [review]
Look fine to me :)

**Comment by springcoil** [comment]
@twiecki - is this fine to merge?

**Comment by twiecki** [comment]
Yeah, I think this is great.

**Pull request merged**
