### PR TITLE
Add chain_method kwarg to sample_numpyro_nuts

### PR DESCRIPTION
**Pull request by martiningram**
Hi all,

welcome to a tiny pull request!

*Motivation*: I've been using the JAX backend in PyMC v4 with the GPU. When only a single GPU is available, setting `chain_method="parallel"`, as is the default, is a bit inefficient because only one chain is run at a time. numpyro also provides the `chain_method="vectorized"`, which is able to run all chains at the same time on a single GPU. I've found this to be quite a bit faster. 

*Changes*: This just adds a keyword argument to `sample_numpyro_nuts` which allows users to specify the `chain_method` rather than hard-coding it to `parallel`. Default behaviour is the same as before.

Hope this all makes sense -- let me know if you need more information!

Best wishes,
Martin

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]
LGTM, thanks for opening the PR

**Comment by martiningram** [comment]
Thanks Ricardo!

**Comment by twiecki** [comment]
Should we default to `"vectorized"`?

**Comment by martiningram** [comment]
Hi @twiecki , good question! I'll have to double check, but it looked like maybe using `vectorized` on CPU was not a good idea; I suspect it might try to run all chains on a single CPU core, which obviously isn't good! Based on that, I think `parallel` is better on CPU, and `vectorized` is better on the GPU. Since most users probably run on CPU, I think keeping the default as-is makes sense. But I'll check to make sure I'm right about `vectorized` being bad on CPU.

**Comment by ricardoV94** [comment]
If that's the case we can check what jax device is being used: cpu or gpu and change the default (if not overridden by the user)

**Pull request merged**
