### PR TITLE
Unpin theano

### PR DESCRIPTION
**Pull request by ColCarroll**
Another try to unpin theano, since it appears *nothing* is building, maybe enough restarts will help this one.

### CODE REVIEW

**Comment by junpenglao** [comment]
```
E       raise RuntimeError('To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.')
```

**Comment by twiecki** [comment]
We probably shouldn't be blocked by travis. If tests pass locally I think we should merge.

**Comment by junpenglao** [comment]
> (From @ColCarroll)
> i cannot recreate the failures locally — if anyone is running linux and can, that would be interesting!
`python -m pytest -vsx pymc3/tests/test_sgfs.py::test_minibatch`
`python -m pytest -vsx pymc3/tests/test_text_backend.py::TestTextSampling::test_supports_sampler_stats`


I found out what the problem is: both test fail if setting `njobs=1`, which is the default for some reason in Travis.
Still trying to find out why test fail when njobs=1 tho, my guess is something to do with the random_seed

**Comment by ColCarroll** [comment]
Wow, thanks for fixing!

I think this is good enough for now – one is still marked experimental, one is not super well maintained. Seems like two reasonable goals for the next release might be making `sgfs` non-experimental, and deprecating all backends except `h5py`. 

Will let someone else merge, or object!

**Comment by nouiz** [comment]
We think we fixed the problem, but as we where not able to reproduce it, can you test with the master of Theano to confirm if the batch_gemm compilation problem is fixed?

**Pull request merged**
