### PR TITLE
Fix #4632 Replaced %s with f-strings

### LINKED ISSUE #4632: Replace old style string interpolation with f strings
Very minor issue, change `%` style interpolation to f string format. Although equally functional it's inconsistent with the fstring interpolation used elsewhere in the file and for someone newer to python could be a small tripping point

https://github.com/pymc-devs/pymc3/blob/v4/pymc3/model.py#L1125

### PR DESCRIPTION
**Pull request by callapa1**
**Thank your for opening a PR!**

Depending on what your PR does, here are a few things you might want to address in the description:
+ [x] what are the (breaking) changes that this PR makes?
No breaking changes. It's all the same except for a small syntax change
+ [ ] important background, or details about the implementation
+ [ ] are the changes—especially new features—covered by tests and docstrings?
+ [x] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [ ] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @callapa1! I think it would be better to use f-strings here.

**Comment by callapa1** [comment]
@twiecki Sure, I will replace that. Thanks for the feedback :)

**Comment by OriolAbril** [comment]
Isn't this the same as https://github.com/pymc-devs/pymc3/pull/4637? They both link to the same issue at least

**Comment by twiecki** [comment]
Yes, but this seems to catch quite a few more cases.

**Comment by twiecki** [comment]
@callapa1 Can you call `pre-commit`? not all style check passed.

**Comment by callapa1** [comment]
@twiecki Sorry I'm a newbie in the processes of contribution. I barely started yesterday so I didn't know what you meant

**Review by michaelosthege — APPROVED** [review]

**Pull request merged**
