### PR TITLE
refactor memoize

### PR DESCRIPTION
**Pull request by ferrine**
One question, should `self` contribute the key or not?

### CODE REVIEW

**Comment by junpenglao** [comment]
you mean contribute the key `memoize`?

**Comment by ferrine** [comment]
yes

**Comment by junpenglao** [comment]
To be honest I haven't use the memoize function yet - what is the use case?

**Comment by ferrine** [comment]
so that's about internal state of object. If it is changed, we can assume cache is outdated.

**Comment by ferrine** [comment]
for some reasons I can't track instances new/delete. clear_cache at this state works only with pure functions

**Comment by ferrine** [comment]
Need review

**Comment by twiecki** [comment]
@ferrine Can you give a description of what this does and why?

**Comment by ferrine** [comment]
ofc
First. I avoid using global storage cache for bounded methods. The reason is weird travis fails, seems like this approach is too fragile. More robust approach is to bind cache to instance itself so that it is removed along with it.
Second, I've tried to retain the same behaviour for `clear_cache` and I met weird behaviour again. del did not work properly. I'm worried about If we should support that. We usually pass objects to multiprocessing and who knows how it works there...

**Pull request merged**
