### PR TITLE
Implementation of Maxwell Distribution

### PR DESCRIPTION
**Pull request by tvwenger**
**What is this PR about?**
This PR implements the [Maxwell distribution](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.maxwell.html) following [this discussion](https://github.com/pymc-devs/pymc/discussions/6905) and [this related PR](https://github.com/pymc-devs/pytensor/pull/440), which implements the Maxwell RV in `pytensor`. Maxwell distribution appears often in physical systems and having access to it in `pymc` and `pytensor` would be generally useful.

I have attempted to follow the style of other similarly-implemented distributions, and I have included the relevant docstrings and tests.

I attempted to run `tests/distributions/test_continuous.py` before submitting this PR, but I received an error that seems to be irrelevant to these changes.

**Checklist**
+ [X] Explain important implementation details 👆
+ [X] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [X] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [X] Are the changes covered by tests and docstrings?
+ [X] Fill out the short summary sections 👇

## Major / Breaking Changes
- None

## New features
- Implementation of the `Maxwell` distribution

## Bugfixes
- None

## Documentation
- Included docstrings as necessary

## Maintenance
- N/A

----
:books: Documentation preview :books:: https://pymc--6907.org.readthedocs.build/en/6907/

### CODE REVIEW

**Comment by tvwenger** [comment]
Since this implementation depends on the `pytensor` PR, I don't really know the proper protocol/testing relationship. Any help would be appreciated!

**Comment by tvwenger** [comment]
I was also confused about how to implement `test_maxwell_moments`, so any help there would be appreciated as well!

**Comment by ricardoV94** [comment]
@tvwenger please open this PR on pymc-experimental. 

Let me know if yhe link I shared on the PyTensor PR helps with your question.

**Comment by tvwenger** [comment]
Related PR on `pymc-experimental`: https://github.com/pymc-devs/pymc-experimental/pull/239

**Pull request closed without merging**
