### PR TITLE
replacing mutable default value with None

### LINKED ISSUE #1598: Running advi_minibatch twice in succession results in DisconnectedInputError
With standard `advi`, the following can be used (relevant part at the end, calling `advi` twice in succession with differing `learning_rate`):

```
import pymc3 as mc
import theano.tensor as T

# make some data
ntri = 200
nvar = 5
x = np.random.normal(size=(nvar, ntri)).astype('float32')

weights = np.random.normal(size=nvar)

y = (np.dot(weights, x) + np.random.normal(size=ntri)/2).astype('float32')

model = mc.Model()
with model:
    beta = mc.Normal('beta', mu=0, sd=10, shape=nvar,
        testval=np.random.normal(size=nvar).astype('float32'),
        dtype='float32')
    intercept = mc.Normal('intercept', mu=0, sd=10,
        testval=np.asarray(0, dtype='float32'),
        dtype='float32')
    
    ypred = intercept + T.dot(beta, x)
    residual = mc.HalfNormal('residual', sd=10,
        testval=np.asarray(1, dtype='float32'),
        dtype='float32')
    y_modelled = mc.Normal('y_modelled', mu=ypred, sd=residual, observed=y)

    params = mc.advi(n=10000, start=model.test_point, learning_rate=0.1)
    params = mc.advi(n=10000, start=params.means, learning_rate=0.01)
```

but whenever I try something similar with `advi_minibatch`:

```
import pymc3 as mc
import theano.tensor as T

# make some data
ntri = 200
nvar = 5
x = np.random.normal(size=(nvar, ntri)).astype('float32')

weights = np.random.normal(size=nvar)

y = (np.dot(weights, x) + np.random.normal(size=ntri)/2).astype('float32')

def gen_minibatches(x, y, minibatch_size=50):
    rng = np.random.RandomState(0)

    while True:
        inds = rng.randint(len(y), size=minibatch_size)
        yield x[:,inds], y[inds]

model = mc.Model()
with model:
    beta = mc.Normal('beta', mu=0, sd=10, shape=nvar,
        testval=np.random.normal(size=nvar).astype('float32'),
        dtype='float32')
    intercept = mc.Normal('intercept', mu=0, sd=10,
        testval=np.asarray(0, dtype='float32'),
        dtype='float32')
    
    T_x = T.matrix('T_x', dtype='float32')
    T_x.tag.test_value = np.random.normal(size=(nvar, 50)).astype('float32')
    T_y = T.vector('T_y', dtype='float32')
    T_y.tag.test_value = np.random.normal(size=50).astype('float32')
    
    ypred = intercept + T.dot(beta, T_x)
    residual = mc.HalfNormal('residual', sd=10,
        testval=np.asarray(1, dtype='float32'),
        dtype='float32')
    y_modelled = mc.Normal('y_modelled', mu=ypred, sd=residual, observed=T_y)

    minibatch_tensors = [T_x, T_y]
    minibatches = gen_minibatches(x, y)
    
    params = mc.advi_minibatch(n=10000, minibatch_tensors=minibatch_tensors,
        minibatch_RVs=[y_modelled], minibatches=minibatches,
        total_size=len(y), start=model.test_point, learning_rate=0.1)
    
    params = mc.advi_minibatch(n=10000, minibatch_tensors=minibatch_tensors,
        minibatch_RVs=[y_modelled], minibatches=minibatches,
        total_size=len(y), start=params.means, learning_rate=0.01)
```

The first call runs through fine, but the second one raises a `DisconnectedInputError`:

```
Traceback (most recent call last):
  File "<...>/playground_advi_minibatch.py", line 181, in <module>
    total_size=len(y), start=params.means, learning_rate=0.01)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi_minibatch.py", line 384, in advi_minibatch
    updates = OrderedDict(optimizer(loss=-1 * elbo, param=params))
  File "/home/eelke/repos/pymc3/pymc3/variational/advi.py", line 259, in optimizer
    grad = tt.grad(loss, param_)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 537, in grad
    handle_disconnected(elem)
  File "/home/eelke/repos/Theano/theano/gradient.py", line 524, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError:  
Backtrace when that variable is created:

  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/guiintegration.py", line 424, in run
    self._QtGui.real_QApplication.exec_()
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 566, in process_commands
    self._process_commands()
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 659, in _process_commands
    self.runlargecode(msg)
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 825, in runlargecode
    self.execcode(code)
  File "/home/eelke/repos/pyzo/pyzo/pyzokernel/interpreter.py", line 930, in execcode
    exec(code, self.locals)
  File "<...>/playground_advi_minibatch.py+131", line 46, in <module>
    total_size=len(y), start=model.test_point, learning_rate=0.1)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi_minibatch.py", line 357, in advi_minibatch
    global_order)
  File "/home/eelke/repos/pymc3/pymc3/variational/advi_minibatch.py", line 75, in _init_uw_global_shared
    uw_global_shared = theano.shared(uw_start, 'uw_global_shared')
```

### PR DESCRIPTION
**Pull request by Spaak**
fixes #1598

### CODE REVIEW

**Comment by ferrine** [comment]
Hi! Please add a test for this case

**Comment by ferrine** [comment]
Hm, do we really need a test? @Spaak what do you think?

**Comment by fonnesbeck** [comment]
I don't think a test is relevant here. I wonder if linters pick these sorts of coding errors up?

**Comment by ferrine** [comment]
@fonnesbeck yes, pylint will help. I think that it is a good idea to configure pylint and pep8 for codebase

**Comment by ColCarroll** [comment]
I'm in favor of pycodestyle/flake8, but we'd need to

1. have a completely clean codebase first
2. agree on a configuration

I've seen some attempts to run such checks only on changed code, and it is
complicated (
https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/travis/flake8_diff.sh).


Perhaps we configure flake8 to ignore almost everything, then create an
issue to resolve one violation at a time (which could also be good for new
contributors).

**Comment by ferrine** [comment]
> Perhaps we configure flake8 to ignore almost everything, then create an
issue to resolve one violation at a time (which could also be good for new
contributors).

@ColCarroll I like this idea

**Comment by fonnesbeck** [comment]
Yeah, we have some work to do, judging by our pylint score:

```
Global evaluation
-----------------
Your code has been rated at 0.82/10
```

**Comment by fonnesbeck** [comment]
@ColCarroll sounds like you can do [something similar with pylint](https://codewithoutrules.com/2016/10/19/pylint/).

**Comment by Spaak** [comment]
@ferrine I agree I wouldn't quite know how to code a relevant test for this, except by simply calling `advi_minibatch` twice, which seems silly because then we could be testing all functions like that just to ensure no mutable default arguments. Thanks for merging!

**Pull request merged**
