### PR TITLE
fix issue 3483 where model is not rendered when using sharedvars

### PR DESCRIPTION
**Pull request by sidravi1**
Fix for this issue: https://github.com/pymc-devs/pymc3/issues/3483

### CODE REVIEW

**Comment by lucianopaz** [comment]
Thanks for the fix, @sidravi1! It looks fine but could you please add a test to `test_model_graph.py` that asserts that this works as expected and the issue in #3483 is correctly solved?

Another thing, please add a line at the end of the maintenance section of RELEASE-NOTES.md specifying the fix.

Finally, you will have to wait for PR #3485 to get cleaned and merged, and then please rebase the work you did here on top of pymc3/master.

**Comment by sidravi1** [comment]
Hi @lucianopaz - I modified an existing test (let me know if that is a no-no) and merged in changes from PR #3485. Let me know if you need me to do anything

**Comment by twiecki** [comment]
Some things are showing up in the diff that shouldn't, can you try rebasing?

**Comment by sidravi1** [comment]
Had to fix some of it manually but should be all set now. Files changed only has the two files that i edited in it. (Not sure why it says there is a conflicting file...)

**Comment by rpgoldman** [comment]
I tried to fix the conflict in the changelog file using the web editor. I've never used that before, and I'm not sure it worked properly.

**Comment by rpgoldman** [comment]
OK, I think I successfully fixed it up.  Probably the history should be tidied by squashing out the merges, etc.

**Comment by twiecki** [comment]
Seems like the merge was unsuccessful. 
image
Either try rebasing or starting a new branch off of master and cherry-picking the appropriate commits.

**Pull request closed without merging**
