### PR TITLE
WIP: ARMA model from the Stan docs (cleaner fork)

### PR DESCRIPTION
**Pull request by springcoil**
Cleaned up the fork a little.

### CODE REVIEW

**Comment by springcoil** [comment]
This is something I need to come back to - and fix up but I don't have time right now.

**Comment by springcoil** [comment]
Any suggestions for fixing this? @fonnesbeck

**Comment by fonnesbeck** [comment]
I run into some positive-definiteness issues, but the following is close, I think:

``` python
with Model() as arma:

    sigma = Cauchy('sigma', 0, 5)
    theta = Normal('theta', 0, sd=2)
    phi = Normal('phi', 0, sd=2)
    mu = Normal('mu', 0, sd=10)

    nu0 = mu + phi*mu
    err0 = y[0] - nu0

    nu = T.vector('nu')
    err = T.vector('err')

    def calc_next(y, err, mu, phi, theta):
        nu_t = mu + phi*y + theta*err
        err_t = y - nu_t
        return err_t

    err, _ = scan(fn=calc_next,
                          sequences=dict(input=y, taps=[-1]),
                          outputs_info=[dict(initial=err0, taps=[-1])],
                          non_sequences=[mu, phi, theta])
    like = Potential('like', Normal.dist(0, sd=sigma).logp(err))
```

I'm curious as to why `err` was provided as data in your code -- should it not be calculated?

**Comment by springcoil** [comment]
Thanks Chris.
An oversight by me. Err shouldn't be constant you are correct.

The scan looks good to me.

**Comment by springcoil** [comment]
Had a look at this this morning, it looks good to me no idea why the positive definite errors are happening. Care to have a look @twiecki or @jsalvatier

**Comment by fonnesbeck** [comment]
It's pretty ugly in any case. We need to be able to automate recursive models like this.

**Comment by springcoil** [comment]
Yeah agreed.

**Comment by springcoil** [comment]
I've not forgotten about this just don't have time right now.

**Comment by springcoil** [comment]
Yeah I'll need to look at this again sometime if I ever have time. I've never gotten around to fixing this - do we put this to one side for the moment?

**Comment by twiecki** [comment]
Sure.

**Comment by springcoil** [comment]
I'm reopening this one as a possible one to have ADVI run on. I've not got access here - but could @twiecki have a go with his branch?

**Comment by springcoil** [comment]
this even fails with advi....

**Comment by springcoil** [comment]
Does anyone have any idea why this is failing? Is there any obvious mistake I'm making @fonnesbeck or @twiecki. I'd love to get this example into PyMC3 before the release...

**Comment by fonnesbeck** [comment]
`scan` is nasty. Would be great if users never have to touch it.

**Comment by springcoil** [comment]
I opened an issue on this https://github.com/pymc-devs/pymc3/issues/1144 no idea though where that would go in the code... :)

**Comment by fonnesbeck** [comment]
@springcoil Does [this](https://gist.github.com/a8da89ba6833c2e982814fdba38b90ec) look reasonable?

**Comment by springcoil** [comment]
LGTM

**Comment by springcoil** [comment]
I pushed that through - let's see if there's any errors.

**Comment by springcoil** [comment]
This is a mess I'll fix this up

**Pull request closed without merging**
