### PR TITLE
fix summary for single chain

### PR DESCRIPTION
**Pull request by aloctavodia**
Avoid trying to computing `n_eff` and `Rhat` for single-chain traces

### CODE REVIEW

**Comment by junpenglao** [comment]
Maybe also a warning?

**Comment by aloctavodia** [comment]
something saying `n_eff` and `Rhat` was no computed because the trace has only a single chain? Not sure, maybe a better option could be to just put that statement in the docstring.

**Comment by junpenglao** [comment]
> something saying n_eff and Rhat was no computed because the trace has only a single chain?

That's what I have in mind.

**Comment by aloctavodia** [comment]
@junpenglao  Let me know if you like the docstring, if not I can still add the warning.

**Review by junpenglao — APPROVED** [review]
LGTM

**Pull request merged**
