### PR TITLE
fix wrong parameter name in beta's repr_latex

### PR DESCRIPTION
**Pull request by aloctavodia**
BTW, shouldn't we use actual Greek letters for the parameters' names?

### CODE REVIEW

**Comment by fonnesbeck** [comment]
We are using the argument names for each distribution. I don't think the world is ready for Greek-letter argument names yet.

**Comment by fonnesbeck** [comment]
LGTM

**Comment by ColCarroll** [comment]
In particular, you need to do a little dance to allow unicode characters in python source files.  Specifically something like 

```
# -*- coding: latin-1 -*-
``` 

in the first two lines of the file

**Comment by aloctavodia** [comment]
I was thinking only about making changes to repr_latex. But that will introduce and inconsistency between the parameters' names and their representation...

**Comment by fonnesbeck** [comment]
The original thinking was that the variable names should correspond to the arguments in the distribution itself. Of course, if you use Greek letters in your own variable names, they do show up:

**Pull request merged**
