### PR TITLE
Make multinomial with two possibilities and n=0 act the same as binomial...

### PR DESCRIPTION
**Pull request by hgbrian**
Make multinomial with two possibilities and n=0 act the same as binomial with n=0.
Addressing #657.

> > > pm.Binomial.dist(p=.5, n=0).logp(0).eval()
> > > array(-0.0, dtype=float32)

Before change:

> > > pm.Multinomial.dist(p=np.array([.5,.5]), n=0).logp(np.array([0,0])).eval()
> > > array(-inf)
> > > After change:
> > > pm.Multinomial.dist(p=np.array([.5,.5]), n=0).logp(np.array([0,0])).eval()
> > > array(0.0)

I have only done one pull request before, so apologies if this is way off.

### CODE REVIEW

**Comment by twiecki** [comment]
Hm, I do see your reasoning and indeed the binomial allows for `n=0`. Wikipedia however bounds multinomial to have `n>1` instead: http://en.wikipedia.org/wiki/Multinomial_distribution

Not sure what the right thing is..

**Comment by hgbrian** [comment]
Hi,
yeah, I guess binomial or multinomial with n=0 doesn't really mean anything. Maybe I can add a detailed example just in case. 

Let's say we have two biased coins and N flips where n1 flips are from coin1 (prob head = t1) and n2 flips are from coin2 (prob head = t2). 
The logP is logP(D | t1,n1) + logP(D | t2,n2)
I sample from t1, t2, n1, n2.

If n2==0 (all flips from from coin1) then the logP of the model is either logP(D | t1,N) or -inf.

The only way I could come up with to solve this problem was the fix above (or creating my own Multinomial_0 replacement function, which is fine too)

0

**Comment by hgbrian** [comment]
I agree that n=0 doesn't mean much for either binomial or multinomial. I can also just use my own Multinomial_0 function that acts this way, and that's fine.

I'll add a bit more detail though, because the following situation seems common, so I am wondering how it should be properly addressed if not by the above change.

Let's say I have two coins, with biases t1 and t2 and I flip the coins n1 and n2 times.
I am sampling from t1, t2, n1, n2 (i.e. I want to work out the biases of the two coins and the number of times each was flipped).

Then if n2==0, the log likelihood 
logP(D | t1,n1) + logP(D | t2,n2) 
is either equal to logP(D | t1,n1) (with the above change) or -inf (without the above change).

**Comment by twiecki** [comment]
Yeah, it does make sense stated that way. Well, I'll merge it if it helps you and potentially others. Seems like an easy change to make and easy change to revert if a good reason comes up.

**Pull request merged**
