### PR TITLE
Test conditional workflow runs

### PR DESCRIPTION
**Pull request by OriolAbril**
Also use the opportunity for some cleanup of infrastructure related files

### CODE REVIEW

**Comment by OriolAbril** [comment]
Tried using the info from: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore but doesn't seem to work

**Comment by OriolAbril** [comment]
If someone can look into the actions thing that would be great, otherwise I'll remove those files from the PR and keep only the removals of unused files

**Review by michaelosthege — APPROVED** [review]

**Comment by michaelosthege** [comment]
For the CI runs here, your changes did not have an effect. Maybe because it need to have been merged first?

**Comment by OriolAbril** [comment]
Let's try if merging works, good idea

**Pull request merged**
