### PR TITLE
Remove unused variable, rename internal variable

### PR DESCRIPTION
**Pull request by ColCarroll**
This is just tidying up some of the covariance adaptation code. It should not change any behavior, just makes things a little more readable.

I left a few things in so the `QuadPotentialDiagAdaptGrad` can be worked on in the future.

### CODE REVIEW

**Comment by junpenglao** [comment]
I am not sure if we should make this change, IIUC the `weight` is for potentially adding a decaying weighting like exponential. Although right now `weight=1` but I imagine removing it will make doing experiment more difficult (although nobody is actually doing these kind of experiment currently).

**Comment by ColCarroll** [comment]
Agree -- I'll roll that back, but leave some of the other changes in. I consider this a promise that you'll continue these experiments, though!

**Comment by junpenglao** [comment]
I will put it in my OKR for the next quarter 😂

**Comment by rpgoldman** [comment]
@ColCarroll Any reason not to merge this?

**Comment by ColCarroll** [comment]
Should be good now!

**Pull request merged**
