### PR TITLE
Switched clone to True in FunctionGraph calls for sample_jax

### LINKED ISSUE #5384: MissingInputError upon completion of `sample_numpyro_nuts`
## Description of your problem

Running a model with `sample_numpyro_nuts` samples to completion,  but then fails before returning the trace:

<details><summary>Complete error traceback</summary>

```python
MissingInputError                         Traceback (most recent call last)
<ipython-input-26-9a9cb2e2e693> in <module>()
      2 
      3     try:
----> 4         trace = sample_numpyro_nuts(1000, tune=2000, chains=1, target_accept=0.95)
      5     except NameError:
      6         trace = pm.sample(1000, tune=2000, cores=4, target_accept=0.95)

3 frames
/usr/local/lib/python3.7/dist-packages/pymc/sampling_jax.py in sample_numpyro_nuts(draws, tune, chains, target_accept, random_seed, model, var_names, progress_bar, keep_untransformed, chain_method)
    230     mcmc_samples = {}
    231     for v in vars_to_sample:
--> 232         fgraph = FunctionGraph(model.value_vars, [v], clone=False)
    233         optimize_graph(fgraph, include=["fast_run"], exclude=["cxx_only", "BlasOpt"])
    234         jax_fn = jax_funcify(fgraph)

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in __init__(self, inputs, outputs, features, clone, update_mapping, memo, copy_inputs, copy_orphans)
    165 
    166         for output in outputs:
--> 167             self.import_var(output, reason="init")
    168         for i, output in enumerate(outputs):
    169             self.clients[output].append(("output", i))

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in import_var(self, var, reason, import_missing)
    335         # Imports the owners of the variables
    336         if var.owner and var.owner not in self.apply_nodes:
--> 337             self.import_node(var.owner, reason=reason, import_missing=import_missing)
    338         elif (
    339             var.owner is None

/usr/local/lib/python3.7/dist-packages/aesara/graph/fg.py in import_node(self, apply_node, check, reason, import_missing)
    400                                 "for more information on this error."
    401                             )
--> 402                             raise MissingInputError(error_msg, variable=var)
    403 
    404         for node in new_nodes:

MissingInputError: Input 1 (x_std) of the graph (indices start from 0), used to compute Elemwise{mul,no_inplace}(InplaceDimShuffle{x}.0, x_std), was not provided and not given a value. Use the Aesara flag exception_verbosity='high', for more information on this error.
 
Backtrace when that variable is created:

  File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-6bb22e74edec>", line 9, in <module>
    x_std = pm.Data('x_std', (df_clean.stuff_plus.values - mean_stuff) / std_stuff, mutable=True)
  File "/usr/local/lib/python3.7/dist-packages/pymc/data.py", line 648, in Data
    x = aesara.shared(arr, name, **kwargs)
```

</details>

The error appears to be related to a covariate input:

```python
    x_std = pm.Data('x_std', (df_clean.stuff_plus.values - mean_stuff) / std_stuff, mutable=True)

    ...

    # Failure rate
    rate = pm.Deterministic('rate', lambda0[age_ind] * at.exp(beta*x_std))
```

I can't submit this model as a reproducible example due to its proprietary nature, but will try and generate a simpler reproducible example.

## Versions and main components

* PyMC/PyMC3 Version: 4.0.0b2
* Aesara/Theano Version: 2.3.4
* Python Version: 3.7.12
* Operating system: Colab (linux)
* How did you install PyMC/PyMC3: pip

### PR DESCRIPTION
**Pull request by fonnesbeck**
Switched `clone=False` to `clone=True` in `FunctionGraph` calls.

Closes #5384

### CODE REVIEW

**Comment by ricardoV94** [comment]
This didn't fix your issue though right?

**Comment by ghost** [comment]
It did not. Creating a PR was the easiest way to load the change onto Colab. We can close it if the actual fix does not involve this change.

**Comment by ricardoV94** [comment]
This change is needed, it's just I didn't find a good test for it yet.

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
I'll go ahead and merge this...

**Pull request merged**
