### PR TITLE
DOCS Updating the Rugby docs

### PR DESCRIPTION
**Pull request by springcoil**
I've updated the Hierarchical Rugby model in the Documentation.

I've added - more data from more years, since before it only had 2014. 

I've updated a few things in terms of the explanations, added a few more visualizations/ exploratory data analysis and added a few links to other resources. 

I'd appreciate some proof reading, and for someone to verify if they run correctly.

### CODE REVIEW

**Comment by springcoil** [comment]
Anyone know why this build is breaking? @twiecki @junpenglao ?

**Comment by ColCarroll** [comment]
It looks like travis randomly killed everything... I restarted all builds

**Comment by ColCarroll** [comment]
Oh, you might need to rebase off master: we pinned `Theano` to 0.9.0 for some reasons (#2728), but it looks like it is trying to install Theano 1.0.1 right now.

Notebook diffs are hard to see what changed!  Generally there are a few edits I would make on the introduction. Feel free to ignore (especially ones that aren't associated with this change), and I can make a bunch of nits myself in a future PR.

- First sentence should be something like 
> I came across the following blog post on [Daniel Weitzenfeld](http://danielweitzenfeld.github.io/passtheroc/blog/2014/10/28/bayes-premier-league/)'s blog, based on the work of [Baio and Blangiardo](http://discovery.ucl.ac.uk/16040/1/16040.pdf).

Note that I changed the link for the Baio and Blangiardo paper, since the old one is dead.

- Remove the bullet points in the introduction, since most of them are not referred to later.  The first (about which countries are in the Six Nations) is useful to know, but should be included in the previous sentence:

> Since I am a rugby fan I decide to apply the results of the paper to the Six Nations Championship, which is a competition between Italy, Ireland, Scotland, England, France and Wales.

- The last sentence of the introduction should be updated for the new data

- The "Motivation" section might also be reworked. There is some capitalization which should not be there, and a stray close parens.  I would drop the `TODO` as well.

- You might reorder the `data_csv_201X` section to be chronological.  You could also add a "year" column, and dump the csv in "pymc3/examples/data/rugby.csv", then use `df_all = pd.read_csv(pm.get_data('rugby.csv'))`

**Comment by springcoil** [comment]
I made those changes you suggested Colin.

**Comment by springcoil** [comment]
If this builds correctly we can merge it I think. There's a few nitpicks etc, but I could fix them or @ColCarroll at some other point.

**Comment by ColCarroll** [comment]
This is really good - I like that we have a new data set! Feel free to merge whenever - you did not write any code that is run in the test suite, so travis is not going to say anything useful. (I am not merging right now because I am interested to see _if_ it passes, or if travis is still unhappy for other reasons)

**Comment by springcoil** [comment]
I want to see that too. I think it's awesome we've another data set?

**Comment by springcoil** [comment]
Seems to still be failing....

**Comment by AustinRochford** [comment]
If you're using `format` instead of `f`-strings, you can take the `lambda` out of this expression

```python
CONVERGENCE_TITLE = lambda: "BFMI = {}\nGelman-Rubin = {}".format(bfmi, max_gr)
```

**Comment by AustinRochford** [comment]
Looks good overall!  My only comment is that you may be able to avoid duplicating some of the model math in `simulate_season` with `sample_ppc`.

**Review by AustinRochford — APPROVED** [review]

**Comment by springcoil** [comment]
I think the sample PPC could be a future PR

**Comment by junpenglao** [comment]
Thanks @springcoil!

**Comment by springcoil** [comment]
Anyone know why the build is still failing?

**Comment by junpenglao** [comment]
Travis CI is not building correctly in py2.7 on master for a while now. @twiecki will contact the Travis support.

**Pull request merged**
