### PR TITLE
Applied Formatting using Black Command on 13 files

### PR DESCRIPTION
**Pull request by Yash1256**
Issue #4109 Applied Formatting Using `black` Command and After That run `pre-commit run pyupgrade --all` to all the files.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
@Yash1256 this looked like it was on the right track

**Comment by Yash1256** [comment]
@MarcoGorelli Sir it was my bad actually I should make a 15 files in a one commit but after that I applied the `black` in more than 15 files so quite difficult to analyze the pr from your side, thereby closed the pr. I will again open this pr and made all the changes in the patch of 15 files.

**Comment by MarcoGorelli** [comment]
sure, no hurry, feel free to ping me if you want/need help

**Comment by MarcoGorelli** [comment]
>  and After That run pre-commit run pyupgrade --all to all the files.

I think you would just need to do `pre-commit run`, so that the code quality checks are only applied to the files you've staged

**Comment by Yash1256** [comment]
@MarcoGorelli Thanks Sir I will Sure come up with the right pr.

**Pull request closed without merging**
