### PR TITLE
Advi minibatch

### PR DESCRIPTION
**Pull request by taku-y**
I have written code for mini-batch advi. #1038 
- Support mini-batch in advi.
- Add a test for ELBO on a Gaussian model, the same as in Stan. 
- Add a constant term to ELBO. 

To know usage, see my notebooks at gist (e.g., https://gist.github.com/taku-y/b4da34be310718a6ea02). Notebooks are not included this PR, because I'm note sure example notebooks should be included in the main repo, as discussed in gitter.

### CODE REVIEW

**Comment by springcoil** [comment]
LGTM. The test is kinda cool.

**Comment by twiecki** [comment]
Can you rebase? Not sure where the conflicts come from.

**Comment by taku-y** [comment]
I'll try it.

**Comment by twiecki** [comment]
I suppose if the changes are not relevant you can create a new PR into master directly.

**Comment by taku-y** [comment]
I think changes for advi does not affect other functionality of master. Should I close this PR?

**Comment by taku-y** [comment]
Forgot to say that I create a new PR into mater.

**Comment by twiecki** [comment]
I meant the conflicting changes in the current advi branch.

**Comment by taku-y** [comment]
Sorry, I'm confused and not sure what to do next. Now I have finished to rebase my branch advi_minibatch onto advi branch locally. Should I create a new PR for the rebased advi branch onto the advi branch in the master repo? I'm sorry again for my redundant explanation.

**Comment by twiecki** [comment]
OK yes, that works well. Sorry for not being clear.

**Pull request closed without merging**
