### PR TITLE
remove non-central because non-central t is distinct distribution

### PR DESCRIPTION
**Pull request by DanielWeitzenfeld**

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Right, I suppose this is just a non-standardized Student's T as implemented.

**Comment by springcoil** [comment]
Should we just merge this :)

**Comment by twiecki** [comment]
Thanks @DanielWeitzenfeld. If you have the non-central version, we'd certainly add it.

**Comment by singhketan** [comment]
Does PyMC3 currently have non-central T distribution (with 4 parameters)?

**Comment by twiecki** [comment]
We don't currently, PRs welcome!

**Comment by singhketan** [comment]
Sorry for being a total noob, but what's "PR"? I'm actually pretty new to PyMC3 and probabalistic programming in general. 

Is it possible to use Scipy's nct implementation with PyMC3?

**Comment by fonnesbeck** [comment]
A PR is a "pull request", which is how we accept contributions to the project (see the tab near the top of the page). 

PyMC can't use SciPy distributions, as it is based on Theano. Have a look at the other distributions in the source code to get an idea of how they are implemented. Good luck!

**Pull request merged**
