### PR TITLE
add calendar to website

### PR DESCRIPTION
**Pull request by OriolAbril**
cc @cluhmann @reshamas

### CODE REVIEW

**Comment by OriolAbril** [comment]
Preview available at https://pymc--5786.org.readthedocs.build/en/5786/community/calendar.html

**Comment by cluhmann** [comment]
This looks good to me.  @reshamas had pointed me to sci-kit learn's public calendar ([here](https://blog.scikit-learn.org/calendar/)) and we might consider following that as a model.  So maybe we consider adding elements of the blurb they have above the calendar (particularly the relevance of the CoC to team events)?

**Comment by reshamas** [comment]
@OriolAbril @cluhmann 
Yay!!! This looks *very* nice!  Congrats!

**Comment by reshamas** [comment]
@cluhmann Wondering if you would prefer to use UTC instead of CET for default timezone.

P.S.  It is "scikit-learn", *not* "sci-kit" ;)

**Comment by OriolAbril** [comment]
added some description, it would be nice to add more details, not necessarily now. I don't think we can expect users to read this and understand which of the available meetings is the one they should attend

**Review by cluhmann — APPROVED** [review]
Looks good to me.

**Review by twiecki — APPROVED** [review]

**Pull request merged**
