### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by bhargavvader**
Replaces `pylab` with `plt` in the `getting_started` notebook, as reported in #2069 .

### CODE REVIEW

**Comment by junpenglao** [comment]
For clarity it should be called `pyplot`

**Comment by twiecki** [comment]
Ping @bhargavvader

**Comment by bhargavvader** [comment]
Whoops, sorry I missed this. Will fix with `pyplot`.

**Comment by twiecki** [comment]
@bhargavvader You need to do this change again it seems on a recent master.

**Pull request closed without merging**
