### PR TITLE
Array step docstring

### PR DESCRIPTION
**Pull request by springcoil**
Closes https://github.com/pymc-devs/pymc3/issues/1221
I didn't understand however what fs was.. perhaps you know @fonnesbeck 

Also what would you call Array Step in the docstring?

### CODE REVIEW

**Comment by springcoil** [comment]
Is this a randomization error 

`````` python
======================================================================
FAIL: test_geometric (pymc3.tests.test_distributions_random.ScalarParameterSamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions_random.py", line 700, in test_geometric
    ref_rand=lambda size, p=None: nr.geometric(p, size=size))
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_distributions_random.py", line 76, in pymc3_random_discrete
    assert p > alpha, str(pt)
AssertionError: {'p': array(0.99)}```
``````

**Comment by springcoil** [comment]
Now it passes so if it's good enough it can be merged @fonnesbeck but this random error I encountered above might need to be fixed - any suggestions?

**Comment by twiecki** [comment]
Seems like `fs` is the `logp` theano function. Maybe we can rename this to `logp_func` or something like that.

**Comment by springcoil** [comment]
I'll get to that later and rebase.

**Comment by fonnesbeck** [comment]
`ArrayStep` isn't a public class, so we don't need much. Its just a blocked step method that is generalized to accept vectors of variables.

As far as the stochastic errors go, we may not be seeding correctly in `test_distribution_random`. We may have to seed further down the line so that it reaches the scipy random number generators.

**Comment by springcoil** [comment]
Is this ready to merge then? Since we need so little

**Comment by twiecki** [comment]
I would just add the `fs` and saying what @fonnesbeck wrote above about the blocked sampler.

**Comment by springcoil** [comment]
Ok will fix this

**Comment by springcoil** [comment]
Ok that fix should work.

**Pull request merged**
