### PR TITLE
add notebook with VI quickstart

### PR DESCRIPTION
**Pull request by ferrine**
I've prepared an overview of cool features in variational module

### CODE REVIEW

**Comment by junpenglao** [comment]
Nice!
Nitpick: there are quite a few typos and some sentence is not very smooth, maybe a native English speaker can proofread this?
for example: 
"We do not need comples models to play with VI API," comples->complex
"We can't compute analitical expectations quickly here" analitical->analyitical
"Mut running MCMC every time we need to calculate an expression is not the thing needed in many experiments." Mut->But, also the sentence is unclear
"you don inference on it, then experiments comming" -> you do inference on it, then experiments come after

**Comment by ColCarroll** [comment]
I'm happy to do language editing after merge

**Comment by ferrine** [comment]
Thanks for quick feedback! I want to become more proficient in English, so I'll do it after workout by myself:)

**Comment by fonnesbeck** [comment]
Not directly related to this PR, but we might want to shorten the class name `CheckParametersConvergence`. Sort of redundant to say "parameters convergence", since its always going to be parameters we are talking about in this context.

**Comment by ferrine** [comment]
@fonnesbeck we can also check loss convergence. If we implement both it would be confusing

**Comment by junpenglao** [comment]
`CheckConverge_Param` and `CheckConverge_Loss`?

**Comment by ferrine** [comment]
Sounds not much better that the current name. I hope users might want use this callback not frequently. When training large DNN you look with your own eyes on results and decide if it is ok. For small models it is usually fast and trade off is not significant. That matters only for some black box algorithms like our `pm.sample` and there I see no problem in descriptive name for this callback.

**Comment by ferrine** [comment]
I've added some more comments and doc printing for `Tracker`, it made things more clear

**Comment by fonnesbeck** [comment]
A couple of notes:

- It would be helpful to have a Markdown cell explaining how to interpret your convergence plots. And maybe only plot the first 5000 in the first example? Are they really that different? Looking at the variation of the plot at iteration 5000, they look pretty similar, if you take the y-axis difference into account.
- It would also be worth mentioning why mean-field ADVI does not get the multimodality.
- Outside of the scope of the PR, would it be possible to automate the eval in callables -- for example, allow advi.approx.mean to be specified rather than advi.approx.mean.eval? Presumably you'd always want expressions evaluated.

**Comment by fonnesbeck** [comment]
Also, would it be possible to automate the `eval` in callables -- for example, allow `advi.approx.mean` to be specified rather than `advi.approx.mean.eval`? Presumably you'd always want expressions evaluated.

**Comment by twiecki** [comment]
This is excellent, exactly the type of tutorial we need for the VI submodule. A few typos:

* comutes -> computes
* multomodality, multimidality -> multimodality
* beter -> better
* ans -> and
* grasients -> gradients

Other comments:
* I would be a bit more verbose, for example, before calling `plt.plot(mean_field.hist);` say what you're plotting and why.
* It makes available to track arbitrary statistics during inference -> It allows tracking of arbitrary statistics during inference
* You are missing a few "the"s
* `a = x**2; b = pm.math.sin(x)` When you got to this part I forgot what `x` was, so a quick reminder is helpful here, and also more explanation of what we are trying to achieve with the replacements call after.
* Maybe find a different parameter name than `ass` ;)

**Comment by twiecki** [comment]
@ferrine Wow, the new addition works extremely well. I would add a bit more explanation around `sample_node`, `replacements`, and `more_replacements`, when you need what etc.

**Comment by fonnesbeck** [comment]
We can iterate on the text a little after it is merged too.

**Comment by ferrine** [comment]
Added more comments for replacements, added rendering in docs quick start.

Out of the scope of this PR I think that SDVG init with either trace ot empirical is ugly. I want to change it to `SVGD.from_empirical` instead of overloading init with extra arguments

**Comment by ferrine** [comment]
I believe quickstart is ready. You can check out the updates

**Comment by junpenglao** [comment]
Good work @ferrine! This is really extensive and well-explained.

**Comment by ferrine** [comment]
I hope VI will be our strong side that will make pymc3 preferable for many tasks, especially for deep learning. Is it true that STAN is more about sampling than VI?

**Comment by fonnesbeck** [comment]
@ferrine Stan was more or less designed from the ground up to do gradient-based MCMC. The Stan team does not seem comfortable with the idea of using VI as a drop-in replacement for MCMC, given how little is known about when it does or does not approximate well for larger models.

**Comment by kyleabeauchamp** [comment]
typo: "at requires knoledge about latents"

**Comment by twiecki** [comment]
I'm going to merge this but someone will need to edit it further down the line.

**Pull request merged**
