### PR TITLE
3.2 Release

### PR DESCRIPTION
**Pull request by fonnesbeck**
Updated release notes and incremented version number.

### CODE REVIEW

**Comment by junpenglao** [comment]
Why is v3.2 not appear in the release?

**Comment by fonnesbeck** [comment]
Not sure what you mean. Commit 3942 increments the version from 3.2rc1 to 3.2.

**Comment by fonnesbeck** [comment]
Or are you talking about [this](https://github.com/pymc-devs/pymc3/releases/tag/v3.2)?

**Comment by junpenglao** [comment]
Yep, I guess it's just some delay...

**Pull request merged**
