### PR TITLE
waic function, return also the effective number of parameters

### PR DESCRIPTION
**Pull request by aloctavodia**

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I wonder if this is best implemented as an optional argument that can be set to `True` as needed?

```
waic(trace, model=None, n_eff=False)
```

**Comment by aloctavodia** [comment]
Sure, I did not thing about that because p_waic is already computed, so there is no extra cost to report it. But may be you are right and most users will only care about the value of waic and not p_waic.

**Comment by springcoil** [comment]
I'd vote for optional.

**Comment by springcoil** [comment]
But good iniative

**Comment by aloctavodia** [comment]
It seems that Travis is failing but with something unrelated to this pull request.

**Comment by twiecki** [comment]
LGTM, can we merge? @fonnesbeck

**Comment by springcoil** [comment]
I vote for merge. But @fonnesbeck has the final approval

**Pull request merged**
