### PR TITLE
Removed temporary pin of Aesara version

### LINKED ISSUE #4961: Aesara 2.2.0 release broke tests on `main`
## Description of your problem

The recent merge of #4955 broke lots of tests on `main`:
https://github.com/pymc-devs/pymc3/actions/runs/1153556997

The authors & reviewers of #4955 are not to blame though, because over there the CI was green ✔ on 2021-08-19T17-33Z.

At 2021-08-19T19-37Z (two hours later) however a new [Aesara version 2.2.0](https://github.com/aesara-devs/aesara/releases/tag/rel-2.2.0) was released.

The next CI run was on `main` after the merge and blew up.`

The automated PR #4960 has a red CI because of this.

## Versions and main components

* PyMC3 Version: `main`
* Aesara/Theano Version: `2.2.0`

### PR DESCRIPTION
**Pull request by kc611**
Fixes #4961

### CODE REVIEW

**Comment by kc611** [comment]
The current test failure in `pymc3/tests/test_ode.py::TestDiffEqModel::test_scalar_ode_2_param` looks flaky  (possibly unrelated). I'm unable to replicate it locally.

**Comment by twiecki** [comment]
Thanks @kc611! Rerunning tests.

**Review by twiecki — APPROVED** [review]

**Comment by ricardoV94** [comment]
This commit could be reverted: https://github.com/pymc-devs/pymc3/commit/78b1380eebca3f15644533c1f8931aec569ba3a0

**Comment by twiecki** [comment]
Cool, lets do it.

**Pull request merged**
