### PR TITLE
some doc fixes

### LINKED ISSUE #6198: Bad version name showing up in the rendered docs
Related to versioneer #6078 

image

### PR DESCRIPTION
**Pull request by OriolAbril**
**What is this PR about?**
Trying to fix the bad and ugly version in docs and unpinning the theme (ref #6115)

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))

## Docs / Maintenance
- Fix bad version in the documentation navbar
- Unpin the theme and add a lower bound to the latest release

### CODE REVIEW

**Comment by OriolAbril** [comment]
I have tested the bad version issue locally and the fix does seem to work, so not a draft anymore.

**Review by ricardoV94 — APPROVED** [review]

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Do we need to make these changes to the pymc-examples as well?

**Comment by OriolAbril** [comment]
Yes, these and more already have an open PR: https://github.com/pymc-devs/pymc-examples/pull/439

**Comment by gbrunkhorst** [comment]
@OriolAbril is there more work to do on documentation?  I am a first time contributor.  I saw that there are data umbrella youtube videos that can help me to get oriented with github, but I would like some direction on what to work on.  Thanks!

**Comment by OriolAbril** [comment]
I would recommend checking https://github.com/pymc-devs/pymc/issues/5459 or https://github.com/pymc-devs/pymc/issues/5460 and then choose a docstring or notebook to work on in doing the changes described there.

**Comment by gbrunkhorst** [comment]
We'll do, thanks.

**Pull request merged**
