### PR TITLE
Include more PyTensor functions in math module

### PR DESCRIPTION
**Pull request by jaharvey8**
Added zeros, ones, fill, fill_like, broadcast_to, mean, matmul to math.py issue #6948 

----
:books: Documentation preview :books:: https://pymc--6956.org.readthedocs.build/en/6956/

### CODE REVIEW

**Comment by jaharvey8** [comment]
Looks like `fill_like` isn't in pytensor.tensor. Should I remove and recommit?

**Comment by ricardoV94** [comment]
Might be called full_like (in which case we want full instead of fill as well)

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
LGTM, any other thing people would like to add?

**Review by twiecki — APPROVED** [review]

**Comment by cluhmann** [comment]
Nice! This looks great.

**Pull request merged**
