### PR TITLE
Fix image link (not showing up on the web)

### PR DESCRIPTION
**Pull request by davidbrochart**
The image was pointing to local `smc.png` file, and not showing in https://docs.pymc.io/notebooks/SMC2_gaussians.html.

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks!

**Comment by davidbrochart** [comment]
Actually, I can see [here](https://docs.pymc.io/notebooks/SMC2_gaussians.html) that it fetches the image there:
```html
<img alt="../_images/notebooks_SMC2_gaussians_14_0.png" src="../_images/notebooks_SMC2_gaussians_14_0.png" />
```
So I don't think my change will fix anything.

**Comment by davidbrochart** [comment]
The image could be embedded in the notebook:
```python
from IPython.display import Image
Image('smc.png')
```
But that can't be in the same markdown cell.
Otherwise I don't know how the online documentation is created from the notebook.
cc @aloctavodia

**Comment by ColCarroll** [comment]
I still do not understand why your change did not work. In the radon example, a markdown image is used:

`radon`

I do not understand how that would be different from what you already did?

SMC 2 Gaussians

**Comment by davidbrochart** [comment]
Yes but https://docs.pymc.io/notebooks/SMC2_gaussians.html has this line:
```html
<img alt="../_images/notebooks_SMC2_gaussians_14_0.png" src="../_images/notebooks_SMC2_gaussians_14_0.png" />
```
instead of:
```html
<img alt="https://github.com/pymc-devs/pymc3/raw/master/docs/source/notebooks/smc.png" src="https://github.com/pymc-devs/pymc3/raw/master/docs/source/notebooks/smc.png" />
```
I don't know how this static HTML file is built from the notebook.

**Comment by ColCarroll** [comment]
Oh shoot. I wrote that 🤦‍♂️. I _think_ markdown/html should be just rendered as markdown/html, but let me go find the right code.

**Comment by ColCarroll** [comment]
On review [this code](https://github.com/pymc-devs/pymc3/blob/master/docs/source/sphinxext/gallery_generator.py#L66) only creates the gallery, it does not do the notebook --> html conversion.

Looks like we use `nbsphinx`. These [are the docs](https://nbsphinx.readthedocs.io/en/latest/markdown-cells.html) for markdown cells, and there is a binder link at the top _to the notebook that generates the doc_. They also do a remote image with a markdown tag instead of raw html, so maybe we try that? 

`Remote image: Python logo (remote)`

**Comment by davidbrochart** [comment]
Even a local image seems to work:

`Local image: Jupyter notebook icon`

But one or the other, the documentation build has to be triggered, is it done when there is a release?

**Comment by ColCarroll** [comment]
I need more coffee. So this original PR was fine, I guess?

Yes, the build has to be triggered, and we started only triggering doc builds manually on a release.

We're planning to cut a release soon. Should we revert-revert this? @twiecki?

**Comment by davidbrochart** [comment]
Maybe the original PR was fine. It would be good to trigger the doc build locally to check.

**Comment by ColCarroll** [comment]
I'll try to remember that tonight (~8hrs). I have a server for testing doc builds. 

I'll ping when it is up there.

**Comment by ColCarroll** [comment]
Somehow this doesn't make the image show up. I edited locally to the markdown image tag, and _that_ one works: 
https://pymc3.colindcarroll.com/notebooks/SMC2_gaussians.html

**Comment by ColCarroll** [comment]
Do you have time to make that PR, or want me to send one in?

**Comment by davidbrochart** [comment]
Done in https://github.com/pymc-devs/pymc3/pull/3455.

**Pull request merged**
