### PR TITLE
Remove Text, SQLite and HDF5 backends

### PR DESCRIPTION
**Pull request by fonnesbeck**
Since the warning has been present for over half a year, this PR removes the storage backends other than NDArray. 

This might be a good place to remove save/load for NDArray as well, or this can be done in a separate PR.

### CODE REVIEW

**Review by michaelosthege — COMMENTED** [review]
So much deleted code! 🤩

In principle I approve, but before someone accidentally hits "merge": Do we want to deprecate the backends already for `3.10`?
I'd say yes, but we have a major bump coming up and could do it there too.

**Comment by AlexAndorra** [comment]
As the warnings have been here for a while now, and as ArviZ netcdf backend is already available, I think we can go ahead and depreacte this in 3.10.
Maybe the next major version will implement `return_inferencedata=True` as the default for `pm.sample`, in which case it's good that users already experienced and transitioned to `az.to_netcdf`

**Review by michaelosthege — APPROVED** [review]

**Comment by DanPen** [comment]
I'm pretty confused. Why were these backends removed? I'm running out of memory trying to sample a model, thought that writing to disk was pretty cool. Unsure what to do.

**Comment by michaelosthege** [comment]
@DanPen they were removed because because couldn't think of examples that would not work with the standard backend, and we saw no activity in Github/Discourse that indicated that they were being used at all.
Also, we are interested in transitioning to an xarray-based backend, because it would seamlessly integrate with `InferenceData`.

Now to your problem: Can you give some details about the size of the model and sampling strategy? Running out of memory sounds like you either have a memory leak, or your model is astronomically gigantic, or you're including things in the trace that are deterministic and take a lot of memory.

**Comment by DanPen** [comment]
@michaelosthege Thanks for the quick response!

I'm following the [Dependent density regression](https://docs.pymc.io/notebooks/dependent_density_regression.html?highlight=dependent%20density%20regression) tutorial with my own dataset. As I increase my number of observations to ~500, my 32GB of memory gets used up. I'm sampling with 4 metropolis chains, 20,000 samples, and 10,000 burn-in. Memory seems to increase linearly as sampling continues.

Should I open a new issue?

**Comment by michaelosthege** [comment]
@DanPen that's 266 kB per iteration, roughly equivalent to 8000 float32 values. I doubt that your model has that many parameters (if it does, you should give up on `Metropolis` right now). So something else than model parameters must be chewing up that memory -> either a memory leak, or a `Deterministic` that has much more dimensions than the actual parameters.

You can `print(model.ndim)` and also go and print the shapes of all variables in the trace (after sampling a few iterations).

In a Jupyter notebook:
```
with model:
   idata = pm.sample(return_inferencedata=True, tune=70, draw=30)
idata
```

**Comment by DanPen** [comment]
@michaelosthege  Cool. `ndim=200` and the posterior's dimensions are `alpha_dim_0: 40, beta_dim_0: 40, chain: 4, delta_dim_0: 40, draw: 30, gamma_dim_0: 40, mu_dim_0: 490, mu_dim_1: 40, tau_dim_0: 40, w_dim_0: 490, w_dim_1: 40`.

Not sure I understand why `mu` and `w` are 2D.

**Comment by michaelosthege** [comment]
@DanPen Then it's indeed the 2D `Deterministic` variables `mu` and `w` that blow up the size of the posterior.
The other variables make up the 200 free paramters, but the (490, 40)-shaped `mu` and `w` add a combined 39_200 numbers per chain per iteration.

In such cases it's better to not save them at all. You can do this by not wrapping them in `Deterministic`. This should reduce your memory footprint by 197x.
If you need them later, you can always reconstruct them (that's why it's called `Deterministic`...).

**Pull request merged**
