### PR TITLE
Notebook cleanup

### LINKED ISSUE #1117: hierarchical example needs annotation
The `hierarchical.ipynb` example seems to have been committed in an intermediate state, and includes a lot of extraneous code. The example should include extensive annotation to explain what the example is trying to show. We should have a cleaner example for an illustration of hierarchical modeling, which is a core application of Bayesian modeling.

### PR DESCRIPTION
**Pull request by fonnesbeck**
Currently, the example notebooks in master are a combination of py2 and py3 kernels, of old (v3) and new (v4) Jupyter notebook formats, and are in varying degrees of completeness. This PR converts all notebooks to Py3 kernels by default and v4 Jupyter notebook format. Three very old and poorly-maintained notebooks are removed.

I have also moved all of the example notebooks to a `notebooks` subfolder. Things were getting unwieldy with so many examples. We may consider culling additional examples if they are redundant, or moving them to the wiki.

Closes #1117

### CODE REVIEW

**Comment by springcoil** [comment]
Cool. I'll merge this when the tests pass :)

**Comment by fonnesbeck** [comment]
Hold of for a minute. I'm doing a little more cleanup.

**Comment by fonnesbeck** [comment]
Travis timeouts plaguing this PR as well. Not sure what's up.

**Comment by fonnesbeck** [comment]
OK, ready to merge when the non-timeout tests pass. I've moved the notebooks to their own folder.

**Comment by twiecki** [comment]
This also allowed to structure the docs/notebooks directory in an easier way.

**Comment by springcoil** [comment]
Ok restarted those builds to see if we can merge them.

On Fri, May 20, 2016 at 9:20 AM, Thomas Wiecki notifications@github.com
wrote:

> This also allowed to structure the docs/notebooks directory in an easier
> way.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1118#issuecomment-220544550

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by fonnesbeck** [comment]
These again are timeout failures, so I will go ahead and merge.

**Pull request merged**
