### PR TITLE
Add recent changes to RELEASE-NOTES

### PR DESCRIPTION
**Pull request by fonnesbeck**
Notes the functionality added by #2635

### CODE REVIEW

**Comment by junpenglao** [comment]
There are also quite a few bugfix since 3.2:
https://github.com/pymc-devs/pymc3/pulls?page=2&q=is%3Apr+is%3Aclosed

**Comment by junpenglao** [comment]
benchmarking setup was quite major https://github.com/pymc-devs/pymc3/pull/1829

**Comment by fonnesbeck** [comment]
I will generalize this to add recent commits.

**Comment by fonnesbeck** [comment]
We also ought to have better titles for PRs that "Bugfix for <issue number>"

**Comment by ColCarroll** [comment]
[PULL_REQUEST_TEMPLATE.md](https://github.com/blog/2111-issue-and-pull-request-templates)?  I can make a pull request!

**Comment by fonnesbeck** [comment]
Golden idea.

**Comment by springcoil** [comment]
Great idea. Very easy to be lazy. Good defaults add to it.

**Pull request merged**
