### PR TITLE
Pin to higher theano

### LINKED ISSUE #3340: Theano breaks on new numpy
Running `pip install pymc3` in a fresh environment today installs `numpy==1.16.0`, which throws an error (via `theano`) for pretty much any input. We should pin numpy to below 1.16 for now, until we can get a fix into theano.

Here's one reproducible example along with the traceback:

```python
with pm.Model():
    pm.Normal('x')
    pm.sample()
```

```pythontb
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 41, in __new__
    dist = cls.dist(*args, **kwargs)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 52, in dist
    dist.__init__(*args, **kwargs)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/pymc3/distributions/continuous.py", line 432, in __init__
    self.variance = 1. / self.tau
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/tensor/var.py", line 203, in __rtruediv__
    return theano.tensor.basic.true_div(other, self)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/op.py", line 670, in __call__
    no_recycling=[])
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'
```

### PR DESCRIPTION
**Pull request by ColCarroll**
This fixes #3340 with numpy and theano.

### CODE REVIEW

**Comment by junpenglao** [comment]
Also pin numpy version?

**Comment by twiecki** [comment]
`pip._vendor.pkg_resources.ContextualVersionConflict: (Theano 1.0.3 (/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages), Requirement.parse('theano>=1.0.4'), {'pymc3'})` not sure where 1.0.3 is getting pulled in though...

@junpenglao I think we're still fine with older numpy versions. 1.0.4 added compatibility with numpy 1.6 but didn't deprecate older versions.

**Comment by nouiz** [comment]
typo in the comment above. We added compatibility with 1.16, not 1.6.

Just for your information, Theano 1.0.4 is available on pypi and our conda channel and conda-forge, BUT NOT the "default" conda channel.

**Comment by ColCarroll** [comment]
Thanks @nouiz for the advice *and* the quick fix -- this seems like the best move, and now we will know the easiest way to troubleshoot install issues from users.

**Pull request merged**
