### PR TITLE
removed .K(...) calls from the notebooks

### PR DESCRIPTION
**Pull request by bwengals**
For some reason the change to from ```reduce``` to ```tt.mul``` and ```tt.add``` in the ```Add``` and ```Prod``` classes of cov.py threw errors for me.  Just a heads up.

### CODE REVIEW

**Comment by twiecki** [comment]
@bwengals Can we add some of these as unittests?

**Comment by bwengals** [comment]
I adapted the unittests for cov.py from GP-covariance.ipynb

**Comment by fonnesbeck** [comment]
Maybe rebase to the `gp_classes` branch to fix some of the failures?

**Comment by bwengals** [comment]
failures in travis look like #1754

**Pull request merged**
