### PR TITLE
WIP: Added scripts and configuration for linting with pylint

### PR DESCRIPTION
**Pull request by fonnesbeck**
This is probably long overdue. We can iterate through this until we get a configuration we are happy with (see .pylintrc).

### CODE REVIEW

**Comment by ColCarroll** [comment]
Is there a different pylint for python2 vs 3?  My recent update to .travis.yml made it so the global python is ignored, and we install `miniconda2` or `miniconda3` to manage testing in python2/3.  In a perfect world, changing `pip install pylint` to `conda install -y pylint` would set that up correctly.

**Comment by fonnesbeck** [comment]
I agree, it would be great to use `conda`. Failing that, we could also just do linting on Python 3; I don't think its critical to do both, is it?

**Comment by ColCarroll** [comment]
Good point -- linting for python3 seems fine.

Seems like we need to do two things then:
1. Figure out why the `disable` setting isn't working (maybe have to use the codes instead?)
2.  Right now, it will run pylint 6 times, once for each env.  Probably altering TEST_COMMAND somehow. 

I may have time to take a look at this later this week, too.

**Comment by fonnesbeck** [comment]
Yeah, the config file I posted is just a skeleton; we need to strip out most of the options, I think, to make linting feasible for use with CI.

**Comment by ColCarroll** [comment]
I'm taking a look at this now.

**Comment by ColCarroll** [comment]
Looks good to me -- right now we are linting 6 times which isn't ideal, but it adds only 20s to each test run and will take some futzing to fix.  Probably the right answer is to do 6 test runs, and one lint, but I'm not sure how to tell travis to do this.

**Comment by fonnesbeck** [comment]
I added what seem to be a reasonable set of checks. We may want to turn on the `unused-wildcard-import` check at some point.

It didn't occur to me until I saw the report that we redefine the `vars` builtin all over the place!

**Comment by ColCarroll** [comment]
I think that's a good set.  I'd argue though that we comment them all out for now in favor of having small commits and not causing too much merge trouble.  Then open a separate issue whose goal is to uncomment all of those.  Probably also we bring this into the 3.1 branch.

**Comment by ColCarroll** [comment]
This looks good to me -- will merge soon if there are no objections.  Might make sense to also rebase `3.1` off of `master` again, so that the variational base class can start using this.

**Comment by fonnesbeck** [comment]
Great. Once 3.0 is released (any hour/day now!) we can just merge to master, so no rush.

**Comment by ferrine** [comment]
What about pep8 additional check?

**Comment by twiecki** [comment]
Yes, running `flake8` is also a good alternative. However, we should be more lax on the 80 char line-limit.

**Comment by fonnesbeck** [comment]
@ferrine Pylint will enforce as much/little of PEP8 as we want. 

@twiecki we currently have it set to fail at 100 characters.

**Comment by twiecki** [comment]
Closing in favor of #1704.

**Pull request closed without merging**
