### PR TITLE
Fixed broken links

### PR DESCRIPTION
**Pull request by ArjitJ**
Updated links for model_comparison.ipynb and GLM-model-selection.ipynb

### CODE REVIEW

**Comment by junpenglao** [comment]
Thanks for the fix! Could you please replace `http://docs.pymc.io/` with `http://pymc-devs.github.io/pymc3/`?

**Comment by ArjitJ** [comment]
@junpenglao  #2843

**Comment by ArjitJ** [comment]
@junpenglao  i changed my file in patch-1 but its not showing here the changes

**Comment by junpenglao** [comment]
Looking at your branch, it only shows the current changes: https://github.com/ArjitJ/pymc3/tree/patch-1
Did you check out the right branch locally? It seems the change you are making is in ArjitJ/pymc3 master

**Comment by ArjitJ** [comment]
It worked. Thanks a Ton

**Comment by junpenglao** [comment]
Great! Thanks!

**Pull request merged**
