### PR TITLE
GP-smoothing example

### PR DESCRIPTION
**Pull request by akuz**
I added an example on Gaussian Process smoothing. I think it would be pretty useful for many people. I just added one notebook file containing the example. I don't know how to make it appear in the documentation menu etc. Please let me know what you think.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
This is excellent. Thanks for the contribution. One suggestion is to use the IPython `interact` widget to replace several of the repetitive plots towards the end. It would allow the user to set the smoothing with a slider, and update the model on the fly. Looks something like this:

interact

What do you think?

**Comment by akuz** [comment]
Hi Chris,

Thanks for the good words. It takes the model a few seconds (2-5) to find the MAP solution for the 200 data points. Do you think it will be a good user experience? I can do it, if you think it will be ok. I haven't seen this widget before, but I am sure I can make it work quickly tomorrow and update this pull request.

Cheers,
A

**Comment by akuz** [comment]
Hi Chris,

I added the interactive example as you wanted. Also I still left some extreme smoothing graphs towards the end, because it would be hard to make them with the interactive chart, and I thought it would be nice for readers to just follow the like of thinking as if just reading the text.

Cheers,
A

**Comment by fonnesbeck** [comment]
Sorry for the late reply. You may be right regarding the slow updating of the model. How about something like this instead, which might be the optimal way to compare values:

``` python
fig, axes = subplots(2, 2)

for ax, smoothing in zip(axes.ravel(), [0.95, 0.99, 0.999, 0.9999]):
    model, z = make_model(smoothing, y)
    z_val = infer_map(model, z)

    ax.plot(x, y)
    ax.plot(x, z_val)
    ax.set_title('Smoothing={:05.4f}'.format(smoothing))
```

this produces the following:

unknown

let me know what you think.

**Comment by akuz** [comment]
@fonnesbeck Yes, that's a great idea, looks good. I've updated the example with this layout. Do I need to do anything extra for it to appear in the documentation?

**Comment by akuz** [comment]
P.S. Slightly off-topic question. Is there a way to create a model once, and than just update the smoothing variable value to a new observed value? I was looking, but couldn't find anything that would let me create a parameter that could be changed or update the observed value...

**Comment by twiecki** [comment]
@akuz See http://pymc-devs.github.io/pymc3/posterior_predictive/ for how to use `theano.shared` to change values.

**Comment by akuz** [comment]
thanks @twiecki - I'll try to update this example in a few hours to use this. Btw, do you know if I need to do anything to make it appear in the documentation? Is it going to happen automatically?

**Comment by twiecki** [comment]
- Hyperlink to the `docs/notebooks` directory
- Adding it to `mkdocs.yml`.

**Comment by akuz** [comment]
@fonnesbeck @twiecki - thanks guys, I've pushed new version which uses the shared variable to specify smoothing, so the inference is very fast after creating the model. Therefore, I put back the interactive block into the notebook. I also added a symlink and a doc entry. Hope all good now. Cheers

**Comment by twiecki** [comment]
@akuz This is awesome, thanks for the contribution. Will merge now.

**Comment by twiecki** [comment]
Available via http://pymc-devs.github.io/pymc3/GP-smoothing/

**Comment by akuz** [comment]
Great! ;)

**Pull request merged**
