### PR TITLE
Add Dirichlet process mixture model

### PR DESCRIPTION
**Pull request by AustinRochford**
@twiecki per Twitter

### CODE REVIEW

**Comment by AustinRochford** [comment]
It now builds correctly.
screen shot 2016-02-26 at 8 36 01 pm

**Comment by springcoil** [comment]
@twiecki can you go ahead and merge this - my understanding was you had to build something yourself to get this kinda stuff into the website. 

:+1: 
Good work Austin - looks a really neat example. I think there is an example like this in _Probabilistic Programming and Bayesian Methods for Hackers_ am I correct?

**Comment by twiecki** [comment]
@AustinRochford This is really neat, I've been wanting an example like this for a long time. It's great to see that the truncation works so well and is moreover very easy to implement in pymc3. 

I'm going to merge this but it might be worthwhile to think of making this a bit more user-friendly in pymc3. For example, the model parts of the DP mixture could easily be their own function (similar to what I did here: https://github.com/pymc-devs/pymc3/pull/701). Also, the PPC plots are really instructive but I wonder if there's perhaps a way to use the existing ppc functionality we already have in pymc3. Anyway, as I said that would be just frosting (and who doesn't like frosting).

**Comment by AustinRochford** [comment]
@twieck thanks, I'll see what I can to to make it a bit cleaner.  I haven't used pymc3's PPC functionality much yet so I tend to forget about it!

I was also pleased to see how well truncation worked, because I really try not to write too many custom samplers by hand.  Even though some of the Chinese restaurant process-based Gibbs samplers for the DP are quite clever, I prefer to use pymc3 where possible.

I would also be interested in writing about DP mixtures for clustering, but to get interesting (read: multidimensional) examples I think #535 will need to be resolved.

**Comment by AustinRochford** [comment]
@springcoil a quick search for "Dirichlet" in the PPBMH repo shows no results.

https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/search?utf8=%E2%9C%93&q=Dirichlet

**Comment by springcoil** [comment]
I was clearly mistaken.

**Comment by AustinRochford** [comment]
Would be cool to contribute, but I'll likely wait for the pymc3 port, as my pymc2 is a bit rusty.

**Comment by fonnesbeck** [comment]
I wrote a post about implementing [stick-breaking DP in PyMC 2](http://stronginference.com/implementing-dirichlet-processes-for-bayesian-semi-parametric-models.html) a couple years ago.

**Pull request merged**
