### PR TITLE
Disable sudo in .travis

### PR DESCRIPTION
**Pull request by aseyboldt**
Trying to see if we can switch to `sudo: false` in travis

### CODE REVIEW

**Comment by twiecki** [comment]
Seems like we still need these:
```
pymc3/tests/test_plots.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pymc3/plots/traceplot.py:79: in traceplot
    ax = get_axis(ax, len(varnames), 2, squeeze=False, figsize=figsize)
pymc3/plots/utils.py:27: in get_axis
    _, ax = plt.subplots(*default_shape, **default_kwargs)
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/matplotlib/pyplot.py:1202: in subplots
    fig = figure(**fig_kw)
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/matplotlib/pyplot.py:535: in figure
    **kwargs)
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py:81: in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
../../../miniconda2/envs/testenv/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py:89: in new_figure_manager_given_figure
    window = Tk.Tk()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```

**Comment by aseyboldt** [comment]
at least the matplotlib rc seems to be unnecessary. And we can disable sudo.

**Comment by fonnesbeck** [comment]
@aseyboldt the `matplotlibrc` used to be necessary for that particular version, but we can probably move on now, I agree.

**Comment by twiecki** [comment]
Thanks @aseyboldt.

**Pull request merged**
