### PR TITLE
A commit of Rugby Analytics

### PR DESCRIPTION
**Pull request by springcoil**
I wasn't able to correct run mkdocs build due to a mathjax error.

Too many files here as I clearly didn't write all the documentation.

Rugby_analytics in the docs and the examples folder is mine.

### CODE REVIEW

**Comment by twiecki** [comment]
`Showing  108 changed files  with 19,351 additions and 0 deletions.` Something must have gone wrong here.

**Comment by springcoil** [comment]
Any idea what went wrong
I forked it...

**Comment by springcoil** [comment]
Going to retry

**Comment by kyleam** [comment]
Instead of opening another PR, you can just update this one:

```
git reset HEAD~1
git add mkdocs.yml pymc3/examples/rugby_analytics.py docs/notebooks/rugby_analytics.ipynb <any other files you touched directly>
<commit>
git push -f <your-remote> <your-branch>
```

**Pull request closed without merging**
