### PR TITLE
WIP - Added a quick explanation of debugging parallelized models and what t…

### PR DESCRIPTION
**Pull request by springcoil**
…o expect

This is probably a WIP - and will get fleshed out more in the future. I wasn't sure where to put this so I stuck it under debugging.

cc @twiecki - is this what you had in mind?

### CODE REVIEW

**Comment by springcoil** [comment]
@twiecki This is such a small change I see no harm in merging it - but I defer to you.

**Comment by twiecki** [comment]
The sentence seems to end half-way through.

**Comment by springcoil** [comment]
Probably...

**Comment by peadar-elevate** [comment]
This needs some work.

**Comment by springcoil** [comment]
This needs some work.

**Comment by twiecki** [comment]
Closing due to inactivity. Feel free to reopen if completed.

**Pull request closed without merging**
