### PR TITLE
WIP: Removed transformed variables from trace

### PR DESCRIPTION
**Pull request by fonnesbeck**
Variable transformations excluded from traces to prevent them from being summarized and plotted.

### CODE REVIEW

**Comment by twiecki** [comment]
```
======================================================================
ERROR: pymc3.tests.test_examples.test_examples1('pymc3.examples.gelman_schools',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_examples.py", line 15, in check_example
    example.run("short")
  File "/home/travis/build/pymc-devs/pymc3/pymc3/examples/gelman_schools.py", line 46, in run
    l = loo(tr)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 123, in loo
    log_py = log_post_trace(trace, model)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 96, in log_post_trace
    return np.hstack([obs.logp_elemwise(pt) for pt in trace] for obs in model.observed_RVs)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/numpy/core/shape_base.py", line 275, in hstack
    arrs = [atleast_1d(_m) for _m in tup]
  File "/home/travis/build/pymc-devs/pymc3/pymc3/stats.py", line 96, in <genexpr>
    return np.hstack([obs.logp_elemwise(pt) for pt in trace] for obs in model.observed_RVs)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/model.py", line 453, in __call__
    return self.f(**point)
  File "/home/travis/miniconda2/envs/testenv/lib/python2.7/site-packages/theano/compile/function_module.py", line 880, in __call__
    self.inv_finder[c]))
TypeError: Missing required input: tau_log
```

**Comment by fonnesbeck** [comment]
please test

**Comment by aloctavodia** [comment]
untransformed_vars contains both transformed and untransformed variables and so the traceplot.

**Comment by fonnesbeck** [comment]
dammit

**Comment by fonnesbeck** [comment]
The issue is that some model checking functions (`waic` and `loo`) require the transformed variables in the trace, which is not optimal. This should be refactored to allow the original variables to be transformed as needed. We should not be storing variables in the trace that are only used as a numerical convenience.

**Comment by twiecki** [comment]
I think hiding is a good approach. Are we happy with this? @aloctavodia

**Comment by aloctavodia** [comment]
It looks good to me.

**Comment by twiecki** [comment]
Me too. @fonnesbeck squash-merge at your convenience.

**Comment by fonnesbeck** [comment]
Hmm. Not sure why my `merge --squash` did not close this. Closing manuall.

**Pull request closed without merging**
