### PR TITLE
#2899: (draft) add Weibull AFT and censoring examples

### PR DESCRIPTION
**Pull request by jazzmuesli**
This is an early draft of 
* https://github.com/pymc-devs/pymc3/issues/2899 copied code from https://github.com/pymc-devs/pymc3/pull/1870/files
* https://github.com/junpenglao/Planet_Sakaar_Data_Science/blob/master/PyMC3QnA/discourse_1107.ipynb

I think it's too early to merge and more work needs to be done.

### CODE REVIEW

**Comment by junpenglao** [comment]
I think it is appropriate to put these notebooks under a new session and index them on the website:
- Analysis of censored data
    - censoring analysis (fix https://github.com/pymc-devs/pymc3/issues/2899)
    - Bayesian Survival analysis (the note currently in the doc but not indexed: http://docs.pymc.io/notebooks/survival_analysis.html)
    - Basic Weibull model (the new notebook here)
    - Bayesian Survival analysis with weibull AFT (http://austinrochford.com/posts/2017-10-02-bayes-param-survival.html)

**Comment by fonnesbeck** [comment]
These are looking good. Make sure they are annotated with markdown cells throughout the notebook. Many of the comments can be moved out of code cells and into their own markdown cells. A bit of interpretive text at the end would be helpful too.

**Review by AustinRochford — COMMENTED** [review]
Agree with Chris that breaking some of the larger code cells apart and adding explanatory text would be good.

**Comment by springcoil** [comment]
Any update on this @jazzmuesli? 
It looks awesome in fact, with a bit of polish - this would make a great contribution to the docs - I agree with the structure suggested by @junpenglao 

I think a bit more explanatory test would make this super!

**Comment by junpenglao** [comment]
Thanks for the effort :) hope you can contribute next time.

**Pull request closed without merging**
