### PR TITLE
Changes on ADVI functions

### PR DESCRIPTION
**Pull request by taku-y**
This PR includes the following changes.

1. Change the definition of optimizers

Optimizers for `advi()` and `advi_minibatch()` had required to take a shared variable of parameters as an argument. However, when the optimizer function accepts list of shared variables as a set of parameters, like in Lasagne and Keras, the requirement makes optimization inefficient. This PR changes the requirement for optimizers to accept a list of shared variables. By this change, the ADVI functions levarage potential of these optimizers.  

2. Make global RVs optional

In general, probabilistic models involve global random variables (global RVs), which determines the distributions of all observations. However, autoencoding variational bayes (AEVB), implemented in `advi_minibatch()`, can handle probabilistic models containing only local RVs, each of which is relevant to each observation and its variational parameters are inferred via neural networks. The current version of `advi_minibatch()` requires global RVs to be defined in the model, while this PR makes `advi_minibatch()` accepting probabilistic models without global RVs. An example of such a probabilistic model is convolutional VAE, added in the notebook directory via this PR. 

3. Use Theano float type in `advi_minibatch()`

To enable this feature, you need to set `theano.config.floatX` before importing PyMC3. 

With these changes, I checked some notebooks using ADVI to run.

### CODE REVIEW

**Comment by twiecki** [comment]
This is really cool, love the new Convolutional example. Can you add that to https://raw.githubusercontent.com/pymc-devs/pymc3/master/docs/source/examples.rst so that it will be part of the HTML?

**Comment by taku-y** [comment]
Thanks for reviewing the notebook. I added it.

**Comment by springcoil** [comment]
I think it's time for this to be merged :) What do you think @twiecki ?

**Review by springcoil — COMMENTED** [review]
LGTM, I've seen some other changes talked about like this recently. I also looked at the AEVB stuff before and reviewed it.

**Comment by taku-y** [comment]
Thanks Peadar for review and merge!

**Comment by twiecki** [comment]
Now available here: http://pymc-devs.github.io/pymc3/notebooks/convolutional_vae_keras_advi.html

**Comment by springcoil** [comment]
I'm getting errors when trying to run that locally https://gist.github.com/springcoil/c12826130458db9e9ddb96db61eca37e 

@taku-y did you use the latest version of Keras.

**Comment by taku-y** [comment]
Sorry, I used the latest version. I will add a note in the notebook after work.

**Comment by taku-y** [comment]
Hi Peadar, did you use the previous version of PyMC3?

**Comment by twiecki** [comment]
you can also remove the note on using your branch.

**Comment by springcoil** [comment]
Hi
I did `python setup.py develop` based on what was in that version of master

**Comment by taku-y** [comment]
Looking at the output in your gist, an old version of function _join_global_RVs() seems to be invoked. Could you check the function definitions on your PC and the current github master repo? In the code I committed, it is checked if global RVs is empty or not.

**Comment by springcoil** [comment]
Ok I'll do that

**Pull request merged**
