### PR TITLE
New example robust regression with outliers

### PR DESCRIPTION
**Pull request by jonsedar**
Added a standalone notebook example of robust regression with outliers using the Hogg 2010 method. This is a port of pymc2 code exampled by Jake VDP in the astroML library. 

It finds very similar results to Jake VDP model (the 3 major outliers are identical, with some slight variations in lesser outliers according to sampling) and is also compared to an OLS.

The motivation, package requirements, observations, clarifications etc are noted inline.

### CODE REVIEW

**Comment by twiecki** [comment]
Fantastic contribution.
- The correct spelling is "Jake Vanderplas".
- The forest plot didn't make a lot of sense to me since the error bars go all the way. How should I interpret that?
- For alternative to that model, can you link to http://pymc-devs.github.io/pymc3/GLM-robust/?

**Comment by jonsedar** [comment]
I'm glad you like it! Took me quite a while to grok all the details of the method, so I thought the notebook would help at least me and hopefully others trying to implement similar.

I'll correct Jake's name and will make additional links to the GLM-robust.

Regarding the forestplot, in the submitted notebook there's 3 datapoints which have only a single dot where x =1. This was created with alpha=0.05 aka CR = 95%, so I'm stating (I hope correctly) that these 3 points have only outlier = 1 for 95% of their samples. Contrastingly I can see 6 points which never leave x = 0. The remaining 11 points have a mixture of 0's and 1's over their traces, so they display an 'error bar' indicating the time spent in each state. I hope my interpretation is okay?

EDIT: there's only 2 available states on the forestplot: x in [0,1]. Perhaps for clarity I'll remove the xticks & xticklabels except for [0,1]

**Comment by twiecki** [comment]
Ah and one more point. `as_op` is the wrong approach here (as you found out). You'd only use that if the likelihood can not be expressed as a theano expression. In your case that's certainly possible so no need to use it and you get the gradient computation for free (something you could point out too). You should also be able to move that function outside the model context (but fine to leave it in too).

**Comment by twiecki** [comment]
> Regarding the forestplot, in the submitted notebook there's 3 datapoints which have only a single dot where x =1. This was created with alpha=0.05 aka CR = 95%, so I'm stating (I hope correctly) that these 3 points have only outlier = 1 for 95% of their samples. Contrastingly I can see 6 points which never leave x = 0. The remaining 11 points have a mixture of 0's and 1's over their traces, so they display an 'error bar' indicating the time spent in each state. I hope my interpretation is okay?

I wonder if a forestplot is the correct thing to look at then. Wouldn't just a plot that plots the probability (% of 1's in the trace) be more informative?

**Comment by jonsedar** [comment]
> Wouldn't just a plot that plots the probability (% of 1's in the trace) be more informative?

Actually, yes it definitely would! I'll replace that forestplot.

Thanks for the info on as_op, I didn't know that. I'll edit my comments above that particular function.

**Comment by jonsedar** [comment]
I tried moving the `logp_signoise()` function outside of the model scope by the way, and had no success. I couldn't find a way to supply the right number of variables. Are there any other examples of using a custom logp function within `DensityDist()` with an observed variable?

**Comment by twiecki** [comment]
http://pymc-devs.github.io/pymc3/getting_started/#arbitrary-distributions and https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/arbitrary_stochastic.py but both have the function inside. It's totally fine to have it inside the model context but a bit surprising. The DensityDist certainly would have to be in the model context. What's the error you're getting?

**Comment by jonsedar** [comment]
Aha, thanks for the examples! My mistake was calling the logp function without passing the full set of observed variables as a dict. Now when I call the function like, say...

```
## Define custom likelihood using DensityDist
likelihood = pm.DensityDist('likelihood', logp_signoise
                    ,observed={'yobs':yobs, 'is_outlier':is_outlier
                            ,'yest_in':yest_in, 'sigma_y_in':sigma_y_in
                            ,'yest_out':yest_out, 'sigma_y_out':sigma_y_out})
```

... it works correctly. I'll note that as a newb the kwarg name `observed` does seem slightly counterintuitive for `pm.DensityDist()`, since when using e.g. a `pm.Normal()` distribution for the likelihood, if I pass a variable using `observed=` I expect this to be the value against which the computed likelihood is compared. For `pm.DensityDist()`, the `observed` kwarg seems to be basically giving everything that the `logp` function requires.

Anyhow, I'll make changes, re-run the notebook and re submit the PR

**Comment by twiecki** [comment]
OK, that looks great. One final nitpicking comment: PEP8, which we don't follow religiously but take as a rough guide, specifies to break multiple args like this:

```
func(a,
     b)
```

Rather than

```
func(a
    ,b)
```

**Comment by twiecki** [comment]
And the `observed` thing is a bit odd indeed. I'll have to take a closer look.

**Comment by jonsedar** [comment]
Haha, of course, I'll make changes accordingly, just rerunning the notebook now. For some reason my personal style is always commas first, no sure why since I'm usually PEP8 friendly!

**Comment by twiecki** [comment]
Thanks @jonsedar !

**Comment by twiecki** [comment]
This now also available on http://pymc-devs.github.io/pymc3/RobustRegression_OutlierDetection_Hogg/

**Comment by jonsedar** [comment]
FYI, I've added a StudentT likelihood to this just for comparison, seems to work well - will open a new branch later on

**Pull request merged**
