### PR TITLE
⬆️ UPGRADE: Autoupdate pre-commit config

### PR DESCRIPTION
**Pull request by twiecki**
## Base PullRequest

default branch (https://github.com/pymc-devs/pymc/tree/main)

## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>add path</em></summary>

```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/build/src/bin
```

</details>
<details>
<summary><em>pip install pre-commit</em></summary>

```Shell
Defaulting to user installation because normal site-packages is not writeable
Collecting pre-commit
  Downloading pre_commit-3.6.0-py2.py3-none-any.whl (204 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.0/204.0 KB 6.7 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from pre-commit) (5.4.1)
Collecting nodeenv>=0.11.1
  Using cached nodeenv-1.8.0-py2.py3-none-any.whl (22 kB)
Collecting identify>=1.0.0
  Downloading identify-2.5.33-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 KB 22.4 MB/s eta 0:00:00
Collecting cfgv>=2.0.0
  Using cached cfgv-3.4.0-py2.py3-none-any.whl (7.2 kB)
Collecting virtualenv>=20.10.0
  Downloading virtualenv-20.25.0-py3-none-any.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 75.3 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from nodeenv>=0.11.1->pre-commit) (59.6.0)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit) (4.1.0)
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 73.4 MB/s eta 0:00:00
Collecting filelock<4,>=3.12.2
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Installing collected packages: distlib, nodeenv, identify, filelock, cfgv, virtualenv, pre-commit
Successfully installed cfgv-3.4.0 distlib-0.3.8 filelock-3.13.1 identify-2.5.33 nodeenv-1.8.0 pre-commit-3.6.0 virtualenv-20.25.0
```

</details>
<details>
<summary><em>pre-commit autoupdate || (exit 0);</em></summary>

```Shell
[https://github.com/pre-commit/pre-commit-hooks] already up to date!
[https://github.com/lucianopaz/head_of_apache] already up to date!
[https://github.com/astral-sh/ruff-pre-commit] updating v0.1.11 -> v0.1.13
[https://github.com/MarcoGorelli/madforhooks] already up to date!
```

</details>
<details>
<summary><em>pre-commit run -a || (exit 0);</em></summary>

```Shell
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Installing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for merge conflicts............................................................Passed
check toml...........................................................................Passed
check yaml...........................................................................Passed
debug statements (python)............................................................Passed
fix end of files.....................................................................Passed
don't commit to branch...............................................................Passed
fix requirements.txt.................................................................Passed
trim trailing whitespace.............................................................Passed
Apply Apache 2.0 License.............................................................Passed
ruff.................................................................................Passed
ruff-format..........................................................................Passed
Disallow print statements............................................................Passed
Check no tests are ignored...........................................................Passed
Generate pip dependency from conda...................................................Passed
No relative imports..................................................................Passed
Check no links that should be cross-references are in the docs.......................Passed
```

</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- .pre-commit-config.yaml

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/create-pr-action) | [:memo: Issues](https://github.com/technote-space/create-pr-action/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/create-pr-action)

----
📚 Documentation preview 📚: https://pymc--7102.org.readthedocs.build/en/7102/

### CODE REVIEW

**Comment by maresb** [comment]
I'd recommend [enabling pre-commit-ci](https://github.com/pymc-labs/pymc-marketing/pull/476#issuecomment-1902167918). I can do this if you'd like.

**Comment by maresb** [comment]
Ping @twiecki and @ricardoV94.

pre-commit-ci would supersede the `pre-commit` workflow. It should be quicker and have more features. It would be one less workflow to worry about. There should be no harm in running them both concurrently.

**Comment by twiecki** [comment]
Sounds good @maresb, I don't think we need both concurrently.

**Comment by maresb** [comment]
I turned on pre-commit-ci. The concurrency thing is not a suggestion so much as a note that we have time to wind down this workflow carefully while we monitor that pre-commit-ci is running well. I am on my phone so I can't do it right now, but I can work out the steps.

**Comment by maresb** [comment]
We should be able to delete the pre-commit-autoupdate workflow. The current pre-commit workflow should be renamed to mypy and the pre-commit part removed. We should try to run the hooks on the oldest supported Python to get a fast fail when someone uses a too-modern Python feature.

Pre-commit-ci will autofix PRs by default. This can be disabled if desired so that autofix is only triggered by a PR comment command.

The auto update from pre-commit-ci runs on Monday 16:00 UTC, so let's hold off merging this PR until then.

**Comment by twiecki** [comment]
I granted access.

**Comment by twiecki** [comment]
## Command results
<details>
<summary>Details: </summary>

<details>
<summary><em>add path</em></summary>

```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/build/src/bin
```



</details>
<details>
<summary><em>pip install pre-commit</em></summary>

```Shell
Defaulting to user installation because normal site-packages is not writeable
Collecting pre-commit
  Downloading pre_commit-3.6.0-py2.py3-none-any.whl (204 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.0/204.0 KB 7.4 MB/s eta 0:00:00
Collecting nodeenv>=0.11.1
  Using cached nodeenv-1.8.0-py2.py3-none-any.whl (22 kB)
Collecting virtualenv>=20.10.0
  Downloading virtualenv-20.25.0-py3-none-any.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 22.7 MB/s eta 0:00:00
Collecting cfgv>=2.0.0
  Using cached cfgv-3.4.0-py2.py3-none-any.whl (7.2 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from pre-commit) (5.4.1)
Collecting identify>=1.0.0
  Downloading identify-2.5.33-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 KB 25.9 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from nodeenv>=0.11.1->pre-commit) (59.6.0)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit) (4.1.0)
Collecting filelock<4,>=3.12.2
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 29.2 MB/s eta 0:00:00
Installing collected packages: distlib, nodeenv, identify, filelock, cfgv, virtualenv, pre-commit
Successfully installed cfgv-3.4.0 distlib-0.3.8 filelock-3.13.1 identify-2.5.33 nodeenv-1.8.0 pre-commit-3.6.0 virtualenv-20.25.0
```



</details>
<details>
<summary><em>pre-commit autoupdate || (exit 0);</em></summary>

```Shell
[https://github.com/pre-commit/pre-commit-hooks] already up to date!
[https://github.com/lucianopaz/head_of_apache] already up to date!
[https://github.com/astral-sh/ruff-pre-commit] updating v0.1.13 -> v0.1.14
[https://github.com/MarcoGorelli/madforhooks] already up to date!
```



</details>
<details>
<summary><em>pre-commit run -a || (exit 0);</em></summary>

```Shell
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Installing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for merge conflicts............................................................Passed
check toml...........................................................................Passed
check yaml...........................................................................Passed
debug statements (python)............................................................Passed
fix end of files.....................................................................Passed
don't commit to branch...............................................................Passed
fix requirements.txt.................................................................Passed
trim trailing whitespace.............................................................Passed
Apply Apache 2.0 License.............................................................Passed
ruff.................................................................................Passed
ruff-format..........................................................................Passed
Disallow print statements............................................................Passed
Check no tests are ignored...........................................................Passed
Generate pip dependency from conda...................................................Passed
No relative imports..................................................................Passed
Check no links that should be cross-references are in the docs.......................Passed
```



</details>

</details>

## Changed files
<details>
<summary>Changed file: </summary>

- .pre-commit-config.yaml

</details>

<hr>

[:octocat: Repo](https://github.com/technote-space/create-pr-action) | [:memo: Issues](https://github.com/technote-space/create-pr-action/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/create-pr-action)

**Comment by maresb** [comment]
To be clear, the update from 1 hour ago is from the old workflow. The new workflow should run in about 6 hours from now.

**Comment by twiecki** [comment]
Do we need to switch this off?

**Pull request closed without merging**
