### PR TITLE
DOCS: Updated Changelog

### PR DESCRIPTION
**Pull request by springcoil**
I created a more thorough changelog using [this cool tool](https://github.com/skywinder/github-changelog-generator)

### CODE REVIEW

**Comment by springcoil** [comment]
Any views @fonnesbeck and @twiecki ?

**Comment by twiecki** [comment]
nifty!

**Comment by springcoil** [comment]
I'm getting an error but has nothing to do  with changelog. I vote to merge

**Comment by springcoil** [comment]
Ok @twiecki looks good to merge

**Comment by fonnesbeck** [comment]
Is it a stochastic error? If so, make a note and we can add a random seed to the test in question.

**Comment by fonnesbeck** [comment]
Changelog looks great

**Comment by springcoil** [comment]
The error disappeared. Just a git checkout error.

**Pull request merged**
