### PR TITLE
ENH: Double plotting issue

### PR DESCRIPTION
**Pull request by aflaxman**
This one-line change addresses the issue of two copies of the traceplot appearing when using `pm.traceplot(trace)` in the `ipython notebook`, as described in #243.  I know there is a simple workaround described there, but I would prefer this to "just work".  I couldn't find any code where the returned `fig` was used, and if you have some, you can use `plt.gcf()` to get a reference to the current figure after calling `pm.traceplot`.

### CODE REVIEW

**Comment by jsalvatier** [comment]
Oh yeah, that seems much better! Didn't know about that. The double plotting issue was annoying.

However, can you rebase your change on top of master instead of merging it?

**Comment by jsalvatier** [comment]
You could also do 

```
git checkout master
git checkout -b doubleplot
git cherry-pick c6ad789
```

**Comment by fonnesbeck** [comment]
I'm not sure I'm on board with this one. A limitation with the PyMC 2 plots is that they are essentially unmodifiable because the functions do not return the figure object when plotted. The nice thing about the plots in PyMC 3 is that with the figure object returned, you can add elements to the plot that are non-standard. It may not sound like a big deal, but when it comes time to use figures for publications, etc., one often requires some customization. All you have to do to prevent double-plotting with the current implementation is to either assign the output to a variable, or use a semi-colon at the end of the call.

One alternative would be to allow for an `axis` argument on the plots to which one could pass a set of axes that could subsequently be modified.

**Comment by jsalvatier** [comment]
hmm, good point. We could also have an argument that causes the value to be returned. Or we could always return it in a tuple or something so it doesn't get plotted the second time.

**Comment by jsalvatier** [comment]
How do the plotting libraries work here? with `%pylab inline` `plot` seems to return a value but not get double plotted.

**Comment by fonnesbeck** [comment]
Yeah, returning `(fig, ax)` should do the trick.

**Comment by fonnesbeck** [comment]
See if the fix in [double_plot_fix](https://github.com/pymc-devs/pymc3/blob/double_plot_fix/pymc3/plots.py) fits the bill.

**Comment by jsalvatier** [comment]
The reason why out plots double plot and pylab plots dont is that we're returning a matplotlib.figure.Figure and they're returning objects like [matplotlib.lines.Line2D at 0x104b492c].

**Comment by jsalvatier** [comment]
@fonnesbeck the double plot fix looks good to me, though you're overwriting some other changes.

**Comment by aflaxman** [comment]
@fonnesbeck your `double_plot_fix` works fine for me.  Happy to have that instead, if you think the returned stuff will be of use.

**Comment by fonnesbeck** [comment]
@jsalvatier that's bizarre. Not sure how that happened. Will fix.

**Comment by fonnesbeck** [comment]
Closing this in favor of #745

**Pull request closed without merging**
