### PR TITLE
implement `forward_val` in transform as a numpy function

### PR DESCRIPTION
**Pull request by junpenglao**
it is faster to do forward transformation in numpy, could be useful for sampling from prior.

### CODE REVIEW

**Comment by aloctavodia** [comment]
LGTM! Just out of curiosity, how fast is this?

**Comment by junpenglao** [comment]
I didnt do proper benchmark but it is way faster.

**Comment by ColCarroll** [comment]
So this is making `transform` be a theano op, and `transform_val` be numpy?

It might be nice to enforce this in a test somewhere (i can do that in a separate PR)

**Comment by junpenglao** [comment]
> So this is making transform be a theano op, and transform_val be numpy?
That's the idea yes.

I had it amended it into in the test, but I can make it into a separate test.

**Comment by ColCarroll** [comment]
Ooh, I'd missed that.  Yes, that test is exactly what I was thinking of!  Maybe update the name of the test to like, `test_transform` or something more inclusive?

**Comment by junpenglao** [comment]
Good call.
Ready when test pass.

**Pull request merged**
