### PR TITLE
Docstring fixes in gp

### PR DESCRIPTION
**Pull request by fonnesbeck**
Very minor residual docstring issues from GP refactoring PR.

### CODE REVIEW

**Comment by ColCarroll** [comment]
LGTM, but want to note that [numpy docstring](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard) suggests there should be a single declarative sentence summarizing functionality, then a linebreak, then an (unindented) extended summary.  This would effect most of the docstrings in this file (...and project)!

**Comment by fonnesbeck** [comment]
Good point.

**Comment by fonnesbeck** [comment]
This should do the trick for this file.

**Comment by ColCarroll** [comment]
Thanks!  Might be a goal of the docathon to do this everywhere

**Pull request merged**
