### PR TITLE
Remove matplotlib as a requirement

### PR DESCRIPTION
**Pull request by ColCarroll**
This should remove matplotlib as a requirement from pymc3.  See #793 for discussion.  
    - Added a deprecation warning when using a plotting function (i.e., `pm.autocorrplot`) from the top level namespace in version 3.2, suggesting to use, for example, `pm.plots.autocorrplot` instead.  I verified locally that this works, and plots, as expected.  
    - Functions that use matplotlib import the functionality themselves, rather than into the global namespace.  There is a test that enforces this.

On reflection, the warning should probably say 3.3 or 3.4 for removal?

### CODE REVIEW

**Comment by twiecki** [comment]
As the imports are all local now, why do we even need to muck with the namespace change?

**Comment by ColCarroll** [comment]
That's a really good point.  

The good things about the namespace change are that
    - Right now the behavior is somewhat surprising, namely, that you should not import matplotlib, even in the `plots` module
    - For aesthetic reasons, I like things in the top namespace all being enabled by default

The bad things are:
    - Deprecation dances
    - People who do not join the deprecation dance
    - Perhaps harder to find plotting functions

I'll have some time to update again tonight, and will pick one of those two (perhaps using the thumbs up/thumbs down vote on your comment).

**Comment by twiecki** [comment]
Just to make sure we're on the same page: Here you implement both methods, where we would just need one.

**Comment by ColCarroll** [comment]
Ah, good point.  There are a few other places where plotting functions are imported (for example, in `sampling`, in order to do live trace plots), so the local imports are somewhat required.  

I've updated to remove the deprecation warnings.

**Comment by fonnesbeck** [comment]
Would it not be easier just to handle the matplotlib import exceptions where they occur?

**Comment by ColCarroll** [comment]
I tried to set things up so exceptions are thrown as soon as possible, which typically is right after a user would try to call a plotting function.  Maybe I don't understand what exactly you mean by handling the import exceptions where they occur, but something like https://github.com/pymc-devs/pymc3/blob/master/pymc3/sampling.py#L14 would throw an exception on importing pymc3 if matplotlib is not installed.

**Comment by fonnesbeck** [comment]
I'm referring to simply wrapping the existing import statements in `try ... except` blocks:

```python
try:
    import matplotlib.pyplot as plt
except ModuleNotFoundError:
    pass
```

This would avoid having to move import statements to various places inside of functions.

**Comment by ColCarroll** [comment]
That would throw super inscrutable errors when plotting functions were accessed.  Python is smart/efficient about (re)importing modules.  The only tax here is for imports to be in unexpected places.

**Comment by ColCarroll** [comment]
Oh, gosh, just read your suggestion more carefully, where you `pass` on error, instead of throwing something.  I updated to use that pattern, and removed the test case, which passed no matter what.  

If anyone has an idea on how to test this, that'd be super useful, since it is hard to enforce that `matplotlib` is optional.

**Comment by fonnesbeck** [comment]
Its hard to test something that happens in the absence of a package being installed. If matplotlib is not installed then calling plotting functions will fail no matter what, so we don’t need a test for that. What else are we testing for?

**Comment by ColCarroll** [comment]
Would be nice to enforce that the library is usable/importable without `matplotlib` getting installed.  This feels like something that will accidentally get broken, but it also seems like a corner case.  

I had a test earlier that would enforce that `from pymc3 import *` did _not_ import `matplotlib`, but in the new behavior, it should import it if it exists.

**Comment by fonnesbeck** [comment]
Is is possible to set up a test that deletes MPL from the namespace and runs things?

**Comment by ColCarroll** [comment]
Just pushed one attempt -- a "faster" way would involve some nasty metaprogramming:  you could go into `.venv/pymc3/lib/python3.6/site-packages`, rename `matplotlib`, confirm that you can import, then rename the package back.

**Comment by twiecki** [comment]
Looks great!

**Pull request merged**
