### PR TITLE
Lint for unused variables

### PR DESCRIPTION
**Pull request by ColCarroll**
No more unused variables!  The most possibly objectionable part of this PR is a lot of examples go from:
```
with pm.Model() as model:
   mu = pm.SomeDistribution()
   trace = pm.sample()
```
into something like:
```
with pm.Model():
    pm.SomeDistribution()
    pm.sample()
```
I prefer the second (it makes it clear that state is being updated in place), but can close the PR if some of you who have taught more tutorials think it is worse.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I don't think we want that. Assigning them to variables, even if unused, is a form of notation as much as anything. It would be odd to read otherwise. This is where we break from PEP8, I think.

**Comment by twiecki** [comment]
Agree with @fonnesbeck. Thanks in any case though!

**Comment by ColCarroll** [comment]
I think this would still be useful to have for everything except the `examples/` directory -- I will update the PR.

**Comment by twiecki** [comment]
Yeah,everything except models.

**Comment by ColCarroll** [comment]
Deactivated the check rather than ignoring on a line by line basis.

**Comment by twiecki** [comment]
@fonnesbeck I'm fine with this, what do you think?

**Comment by twiecki** [comment]
Ping @fonnesbeck.

**Comment by fonnesbeck** [comment]
All good from my vantage point. Just rebase and merge.

**Comment by twiecki** [comment]
@ColCarroll want to rebase and merge?

**Pull request merged**
