### PR TITLE
Changed more uses of theano.tensor to tt convention

### PR DESCRIPTION
**Pull request by jamestwebber**

### CODE REVIEW

**Comment by jamestwebber** [comment]
Redundant with (but more comprehensive than!) #1188

**Comment by springcoil** [comment]
Damnit - we did the same work. Do you want to let me get my merges in first - and then you'll be able to finish off the others.

**Comment by jamestwebber** [comment]
Up to you, since I can't merge anything.

**Comment by springcoil** [comment]
Give us 20 minutes - I'll merge in mine. Then you'll have to rebase and send your ones in afterwards

**Comment by springcoil** [comment]
But great - thanks for noticing this :) I'm sorry we both worked on the same thing - and you did even more than I did.

**Comment by springcoil** [comment]
Sorted

**Pull request merged**
