### PR TITLE
Cache .theano on travis

### PR DESCRIPTION
**Pull request by aseyboldt**
Enable caching of miniconda and .theano on travis.

### CODE REVIEW

**Comment by ferrine** [comment]
You can set timeout for cache in case of miniconda updates

**Comment by aseyboldt** [comment]
@ferrine as far as I understand it the timeout is only for down and uploading the cache. So updates from miniconda should not count towards the timeout.

**Comment by junpenglao** [comment]
Seems it's working! test time 49 mins --> 24 mins!

So we just need to "Delete all repository caches" from time to time or?

**Comment by aseyboldt** [comment]
Looks like it. It just added caching for miniconda, too.
However, this shouldn't stop us from trying to improve the tests, we still need to be able to run them from time to time without the cache.

**Comment by junpenglao** [comment]
Agree. 
Another idea is to gether those tests that we dont care that much of the build cache, and put them all into a single travis build.

**Comment by aseyboldt** [comment]
Plus, we can use model=FAST_COMPILE on some tests.

**Pull request merged**
