### PR TITLE
TST: make travis run all tests

### PR DESCRIPTION
**Pull request by aflaxman**
and make a glm tests run instead of error (although it still fails)

(Note, this is work in progress, and the pull request was issued by a 1 year old)

### CODE REVIEW

**Comment by twiecki** [comment]
Hm, why did it not run all tests before?

**Comment by aflaxman** [comment]
The `.travis.yml` file has some sneaky stuff to parallelize the testing, which leaves out some tests.  I changed it to just `nosetest pymc3`, which is slower, and [fails on the `glm` module](https://travis-ci.org/pymc-devs/pymc3/jobs/64802788#L477):

```
======================================================================
FAIL: test_glm_link_func (pymc3.tests.test_glm.TestGLM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_glm.py", line 70, in test_glm_link_func
    self.assertAlmostEqual(coeff.tag.test_value, true_val, 0)
AssertionError: 0.0 != 3 within 0 places
----------------------------------------------------------------------
```

But if I change it to nosetest everything, there are also some tests in the `test_sqlite_backend` that fail.  Do you know if these are supposed to pass?  I'm going to update the .travis.yml file to demonstrate this.

**Comment by kyleam** [comment]
> But if I change it to nosetest everything, there are also some tests in the test_sqlite_backend that fail. Do you know if these are supposed to pass? 

Yes.  Everything is passing on my end when I run

```
nosetests pymc3.tests.test_sqlite_backend
```

What's failing on your end?

**Comment by aflaxman** [comment]
@kyleam when I run locally, there are 9 failures, with half about sqlite and network drives not working well together, and the other half about comparing int and float arrays. Here is an example of the latter:

```
======================================================================
FAIL: test_get_values_burn_keyword (pymc3.tests.test_sqlite_backend.TestSQLite2dSelection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snfs2/HOME/abie/projects/2015/pymc3/pymc3/tests/backend_fixtures.py", line 142, in test_get_values_burn_keyword
    npt.assert_equal(result, expected)
  File "/homes/abie/anaconda/envs/testenv/lib/python2.7/site-packages/numpy/testing/utils.py", line 255, in assert_equal
    assert_equal(actual[k], desired[k], 'item=%r\n%s' % (k, err_msg), verbose)
  File "/homes/abie/anaconda/envs/testenv/lib/python2.7/site-packages/numpy/testing/utils.py", line 260, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/homes/abie/anaconda/envs/testenv/lib/python2.7/site-packages/numpy/testing/utils.py", line 718, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/homes/abie/anaconda/envs/testenv/lib/python2.7/site-packages/numpy/testing/utils.py", line 599, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
item=0

(shapes (6, 2, 3), (3, 2, 3) mismatch)
 x: array([[[ 12.,  13.,  14.],
        [ 15.,  16.,  17.]],
...
 y: array([[[12, 13, 14],
        [15, 16, 17]],
...
```

Let's see if the travis version can replicate any of these failures.

**Comment by kyleam** [comment]
Hmmm.   I think that's actually an issue with shapes, not float/int comparison, because `np.assert_equal` doesn't distinguish int versus float.

```
import numpy.testing as npt
npt.assert_equal(np.arange(2.), np.arange(2))
```

It seems like your result has twice as many iterations as it should (first dimension has length of 6 rather than 3).   I wonder if the test database isn't getting cleaned up properly (it should always get removed by the tear down method).

**Comment by kyleam** [comment]
Just to clarify... the dtype mismatch is an issue (here and in general, as mentioned by #722), which I'm working on fixing.  It's just not the reason that this test is failing.

**Comment by aflaxman** [comment]
Looks like the sqlite stuff all works on travis.  I'm going to make it skip one failing test (https://travis-ci.org/pymc-devs/pymc3/jobs/64859056#L478), unless there is an easy fix for it.  

@kyleam Is there an package for sqlite or something else that could be out of date on my local conda?

Here is what I have now:

```
(testenv)abie@abie-dev:~/projects/2015/pymc3$ conda update sqlite
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /homes/abie/anaconda/envs/testenv:
#
sqlite                    3.8.4.1                       1
```

**Comment by kyleam** [comment]
> Is there an package for sqlite or something else that could be out of
> date on my local conda?

Hmm, I don't know.  Perhaps someone that uses conda can comment on
whether the sqlite tests pass for them.

**Pull request merged**
