### PR TITLE
Redone Covariances notebook, small fixes to GP notebooks

### PR DESCRIPTION
**Pull request by bwengals**
This PR cleans up the covariance examples.  Also got rid of the `import sys; sys.path.insert...` (thanks @ColCarroll for spotting those!).  Moved the GP documentation into the API section.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Is there really no way to get Bokeh to display in rendered notebooks? There seem to be some [examples](http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/00%20-%20Introduction%20and%20Setup.ipynb).

**Comment by ColCarroll** [comment]
I think it is just github policy -- you can actually load these on nbviewer: 

http://nbviewer.jupyter.org/github/bwengals/pymc3/blob/0ebb8d3f07f0ff53dbe25c64378a4bb9a4a65006/docs/source/notebooks/GP-MaunaLoa.ipynb

The first two bokeh figures do not load for me, but the third does...

**Comment by bwengals** [comment]
I wonder why the first couple don't work on nbveiwer.  The rest look fine.  When I build the docs locally all bokeh plots are render properly.

**Comment by fonnesbeck** [comment]
I did a spot check on these, and they look good to me.

**Comment by bwengals** [comment]
Great!  Here's how I organized the documentation.  I moved the GP intro from the "API" section to "Getting Started", but I'm not sure if that's the best place for it.  

Also the bokeh plots look to be working, and I think this PR should fix  #2554.  I think the problem there was that I forgot to change the notebook name in `examples.rst`.

docs1
--------------------
docs2

**Pull request merged**
