### PR TITLE
Fixing np.bool Depreciation warnings: 3 files

### PR DESCRIPTION
**Pull request by larryshamalama**
Addressing issue [4670](https://github.com/pymc-devs/pymc3/issues/4670)

Not sure where the test warnings come from. I changed "np.bool" to "np.bool_" in 3 files as the warning suggests.

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks for taking this on! The warning says to just replace it with `bool`, rather than `np.bool_`.

**Comment by larryshamalama** [comment]
Oh, I see, I assumed that numpy data types were preferred because of the other key/value pairs in `stats_dtypes`. Is `bool` preferred over `np.bool_`?

**Comment by twiecki** [comment]
Seems like `np.bool` was just an alias to `bool` anyway, so let's just stick with that.

**Comment by larryshamalama** [comment]
Fixed! (+ other files not mentioned in the error shown in the original issue)

**Review by michaelosthege — APPROVED** [review]

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @larryshamalama and congrats on your first PR! 🥳

**Comment by larryshamalama** [comment]
Thank you very much! 🙂

**Pull request merged**
