### PR TITLE
Build bugfix: Add another level to doc folder copying in setup

### PR DESCRIPTION
**Pull request by eoinhurrell**
Package data wasn't copied correctly because of the behaviour of
python's glob module, which needed a further '/*' appended to it.

This affects docs/source/data/6bb8d06c69c0666e6da14c094d4320d115f1ffc8
which is a directory but isn't processed as such by glob, resulting in a
build error.

Build error before this fix was applied:

```
copying setup.py -> build/lib
copying setupegg.py -> build/lib
creating build/lib/pymc3/examples/data
copying pymc3/examples/data/__init__.py -> build/lib/pymc3/examples/data
copying pymc3/examples/data/cty.dat -> build/lib/pymc3/examples/data
copying pymc3/examples/data/Guber1999data.txt -> build/lib/pymc3/examples/data
copying pymc3/examples/data/HtWt.csv -> build/lib/pymc3/examples/data
copying pymc3/examples/data/jester-dataset-v1-dense-first-1000.csv -> build/lib/pymc3/examples/data
copying pymc3/examples/data/pancreatitis.csv -> build/lib/pymc3/examples/data
copying pymc3/examples/data/radon.csv -> build/lib/pymc3/examples/data
copying pymc3/examples/data/SP500.csv -> build/lib/pymc3/examples/data
copying pymc3/examples/data/srrs2.dat -> build/lib/pymc3/examples/data
copying pymc3/examples/data/test_scores.csv -> build/lib/pymc3/examples/data
copying pymc3/examples/data/wells.dat -> build/lib/pymc3/examples/data
creating build/lib/docs
creating build/lib/docs/source
creating build/lib/docs/source/data
error: can't copy 'docs/source/data/6bb8d06c69c0666e6da14c094d4320d115f1ffc8': doesn't exist or not a regular file

----------------------------------------
```

Command "/Users/ehurrell/anaconda3/bin/python -u -c "import setuptools, tokenize;**file**='/var/folders/6w/ql9m8kjj2pbdnmdhdtl2mrg40000gn/T/pip-obj34ksi-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/6w/ql9m8kjj2pbdnmdhdtl2mrg40000gn/T/pip-6ajnwm43-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/6w/ql9m8kjj2pbdnmdhdtl2mrg40000gn/T/pip-obj34ksi-build/

I'm currently using Python 3.5 from Anaconda3, fairly vanilla but I'm attaching the output of pip freeze in case that's of use.
[list.txt](https://github.com/pymc-devs/pymc3/files/462268/list.txt)

### CODE REVIEW

**Comment by springcoil** [comment]
Looks good to me. However I think @fonnesbeck needs to review this or
@twiecki

**Comment by ColCarroll** [comment]
@eoinhurrell I think you actually want 
`'docs': ['source/*/*/*', 'source/*/*'],`

I'm fuzzy on the setup.py stuff, but I'm checking this by running 

`python setup.py sdist && diff SOURCES.txt.copy pymc3.egg-info/SOURCES.txt`. 

Your change seems to remove some files, but this change seems to only add the files you're looking for.

**Comment by eoinhurrell** [comment]
@ColCarroll Hmmm, good point, I'm fuzzy on glob's behaviour myself, I'll update this, thanks!

**Comment by fonnesbeck** [comment]
That should work, thanks. 

I'm not sure why we are keeping data in a folder with a name like that. Might be worth renaming it.

**Comment by eoinhurrell** [comment]
Just to note, the data in question are test/train data for this notebook: https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/pmf-pymc.ipynb, concerning jester joke data (which is a different dataset also present) and matrix factorisation.

**Pull request merged**
