### PR TITLE
Added new example: Model Selection using DIC and WAIC

### PR DESCRIPTION
**Pull request by jonsedar**
New Notebook example for basic model selection.

Creates two toy datasets under linear and quadratic models, and then tests the fit of a range of polynomial linear models upon those datasets using DIC and WAIC. See Notebook for details.

This is fairly basic and I feel would benefit from more detail, particularly for Bayes Factor comparison work. Would be good to get @twiecki and or @AustinRochford involved.

The notebook also shows more examples of using the glm submodule and some posterior predictive plotting that I might try to bung into mcmcplotlib if anyone thinks it might be useful.

Also updated mkdocs

### CODE REVIEW

**Comment by twiecki** [comment]
Not sure how the mkdocs.yml.orig got messed up. I fixed it on master. Can you rebase?

**Comment by jonsedar** [comment]
Yeah, strange one that. May have been me, not sure! Anyhow, I've rebased and pushed, lets see if this one works :)

**Comment by twiecki** [comment]
I'm pretty sure that it was me :)

**Comment by AustinRochford** [comment]
> It's good to see the manual method agrees with the implemented package method

:)

**Comment by jonsedar** [comment]
@AustinRochford the missing clause there is: "it ought to match, since I pretty much copied the code verbatim" (!)

Any thoughts on why the WAIC appears quite flat? I've tried more datapoints (n=50) but it still seems quite flat and uninformative - I suppose I need to look into the theory more

**Comment by springcoil** [comment]
I just reviewed this example, it looks good to me. I wasn't aware that these methods had been added to PyMC3. I'll have to add some model selection into my next talk on PyMC3.

**Pull request merged**
