### PR TITLE
ENH Arbitrary optimizer for ADVI

### PR DESCRIPTION
**Pull request by taku-y**
In response to #1287, arbitrary optimizers are supported in ADVI. An example of using Adam of Lasagne is [here](https://gist.github.com/taku-y/841937617c49bed1235e70cbd47ace8e).

### CODE REVIEW

**Comment by springcoil** [comment]
LGTM. Maybe have @twiecki look at it before we merge.

**Comment by twiecki** [comment]
This is awesome! Code looks good to me, seems like you were able to do some other simplifications too.

**Comment by twiecki** [comment]
Want to add your example to the NB so people can easier find out how to use it?

**Comment by taku-y** [comment]
I'm making a NB for ADVI tutorial including usage of optimizers. Will send another PR in future.

**Pull request merged**
