### PR TITLE
Dev opvi docs

### PR DESCRIPTION
**Pull request by ferrine**
#docathon!

### CODE REVIEW

**Comment by junpenglao** [comment]
I dont have enough expertise of VI to judge the content, but I think (personally at least) it would be great to see how it works for an actual implementation showing how to "constructs loss from given Model, Approximation and Test Function". It would be ideal for example, since you are working on Normalizing flow, given a simple pymc3 model, how `NF` constructs loss from this model, how `NF` approximate the parameters, etc. By pointing to specific part of the code or using code snippet, it would be much easier to understand if I want to implement a new class of VI, how can it fit into the OPVI API.

**Comment by twiecki** [comment]
I've read through it and it looks great. I agree with @junpenglao that there could be a few more examples.

**Comment by junpenglao** [comment]
@ferrine Maybe this should be rewritten after #2416?

**Comment by ferrine** [comment]
Ye, this refactoring has very large diff

**Comment by twiecki** [comment]
@ferrine What about this one? Should we still try to merge it?

**Comment by ferrine** [comment]
Don't think so, I've made docs with docstrings in GSoC. In my opinion that's quite enough to dive in for a new developer. And as we are about moving to new backend I don't expect future development of variational module.

**Pull request closed without merging**
