### PR TITLE
Restructure and update release notes.

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Review by AlexAndorra — APPROVED** [review]
Nice, thanks @twiecki ! Will merge once tests pass

**Comment by MarcoGorelli** [comment]
> Nice, thanks @twiecki ! Will merge once tests pass

If travis build are indeed frozen, then that may take a while 🤣

**Comment by AlexAndorra** [comment]
Yeah but merging is blocked anyway 😕 We probably have to wait for #4254 to be merged then, unless there is a manual way to make Travis validate this PR?

**Comment by twiecki** [comment]
Thanks for reviewing!

**Pull request merged**
