### PR TITLE
[WIP] Pull master into tensorflow branch

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
1.  Reduce the amount of commented out code (which makes the diff very hard to read)
2.  Merge in some changes from master

There are still probably some places where I didn't fully merge in the latest logic from master, so we will need to do another pass of trying to sync up with master before this goes back into master again.

You can view the amount of "diff from master" via this comparison: https://github.com/pymc-devs/pymc3/compare/master...kyleabeauchamp:tf?expand=1  

cc @twiecki  @crgagne

### CODE REVIEW

**Comment by twiecki** [comment]
@kyleabeauchamp Does the example still run?

**Comment by kyleabeauchamp** [comment]
I checked that the `multiple_computational_backends` notebook still runs the first few cells (the theano sampling and the tf sampling).

**Comment by crgagne** [comment]
Thanks Kyle. I was trying to get the ValueGradFunciton working for TF the other night. Not quite there yet. Uncommenting everything and adding in a way to determine whether things are available for TF is definitely the crucial next step as well as pulling in changes from master. Are you going to commit what you've done so far to the tensorflow branch? I can then pull, finish uncommenting, and rebase completely with the master. What do you think is the best way to determine what is available for import? We could use "if S.backend()=='tensorflow'" in the init files and following this conditional only import things that no longer contain theano directly?

**Comment by kyleabeauchamp** [comment]
I don't have write permissions to merge, but I suspect @twiecki would like for you to verify that my changes won't disrupt your work---then we can merge.

**Comment by twiecki** [comment]
Yes, was waiting for @crgagne's input.

**Comment by crgagne** [comment]
Gotcha, thanks.

**Pull request merged**
