### PR TITLE
[WIP] Fix to issue #3481.

### PR DESCRIPTION
**Pull request by rpgoldman**
Fix to issue #3481, from @lucianopaz.

### CODE REVIEW

**Comment by lucianopaz** [comment]
Thanks @rpgoldman. That's the idea of the fix, but you have to import `broadcast_distribution_samples` from `shape_utils` first. I'll try to better explain what causes the issue you saw back on #3481's thread

**Comment by twiecki** [comment]
Can this be merged?

**Comment by twiecki** [comment]
Needs a line in release-notes.

**Comment by lucianopaz** [comment]
I think that to have this ready to merge, we need to at least add a test that proves that issue #3481 is fixed by this (and also add it to the release notes)

**Review by twiecki — CHANGES_REQUESTED** [review]
Needs a test and release notes.

**Comment by lucianopaz** [comment]
@rpgoldman, I took a look at the codebase and found that `Triangular`, `TruncatedNormal`, `Rice` and `ZeroInflatedNegativeBinomial` suffer from the same error of #3481. I'll make a new issue an PR a fix with tests for all.

**Comment by lucianopaz** [comment]
Superseeded by PR #3509.

**Pull request closed without merging**
