### PR TITLE
More tests for hmc and fixed path length

### PR DESCRIPTION
**Pull request by aseyboldt**

### CODE REVIEW

**Comment by junpenglao** [comment]
Why do you want to remove the step size jitter? Stan still uses step size jitter (see Stan manual 34.2, p395 of v2.17.0).

**Comment by aseyboldt** [comment]
Oh, I completely forgot about this one :-)
Step size jitter is still in there. Only changing path lengths aren't (I actually put those in the original PR accidentally, that was just for experimentation.)

**Comment by twiecki** [comment]
LGTM, probably should be added to release-notes.

**Comment by twiecki** [comment]
Closing because of age. Feel free to reopen if you want to fix this up.

**Pull request closed without merging**
