### PR TITLE
refactor variational module, add histogram approximation

### PR DESCRIPTION
**Pull request by ferrine**
Here I implement Histogram Approx with the same interface as other approximations

### CODE REVIEW

**Comment by ferrine** [comment]
Histogram is needed to put trace into theano graph for general purposes

**Comment by twiecki** [comment]
What's Histogram? Is there a reference?

**Comment by ferrine** [comment]
Not yet

**Comment by ferrine** [comment]
@twiecki, do you mean a paper on arxiv under reference?

**Comment by twiecki** [comment]
@ferrine Anything that makes me understand what this is useful for.

**Comment by ferrine** [comment]
@twiecki I'll use posterior widely for minimizing Bayesian Risk.
1. Consider you have a model that for given inputs yields posterior predictive distribution.
`X -> p(y|theta)`
2. You know the desired `y` you want, name it `y_target`, and a loss function `L(y_target, y_true)`
3. Your decision is to choose the best `X` that minimizes `L`

So the objective is `E_theta[L(y_target, y_true)] -> min X`

Here I do not need to know anything about `p(theta|D)` I want to sample from it. I can do it with variational approximation only now. After implementing Histogram I can use SVGD/NUTS to make a trace and sample from it.

**Comment by twiecki** [comment]
OK, what's an example application? Also, do you assume theta is already estimated?

**Comment by ferrine** [comment]
Ye posterior is already estimated. You will be able to use any PyMC3 posterior for cost-benefit optimization. At my work I do exactly what I described. I want to minimize costs of inputs with archiving my target and be confident I can do it. I can't give more details because of NDA:(
I'm planning to implement all that stuff in few weeks to write a post including toy examples of
 * Maximizing stochastic output of model `E_{p(theta|D)}[f(X)] -> max X`
 * Minimizing costs of inputs to archive target`E_{p(y|X, theta, D)}[L(y_target, X, y)] -> min X`
 * Minimizing Bayesian risk: `E_{p(y|X, theta, D)}[L(y_p, y)] -> min y_p`
I'm going to use ADAM for optimization

**Comment by ferrine** [comment]
@twiecki I want to merge Histogram tomorrow when I'm sure tests pass as I have ~95% coverage. I also think that `sample_vp` method should be renamed to `sample` as here I use traces from step methods. For other approximations I want to do the same as I want consistent interface for sampling. Your thoughts?

**Comment by ferrine** [comment]
I've forgot Docs for the class:( I'll add them in a separate PR

**Comment by fonnesbeck** [comment]
Can we get a working example of this, either as a notebook if you have time to do a fully-documented case study, or a model in the `pymc3/examples` folder.

**Pull request merged**
