### PR TITLE
[WIP] Updated GP notebooks

### PR DESCRIPTION
**Pull request by fonnesbeck**
This PR will fix the GP notebooks. Currently the first Mauna Loa notebook has been fixed; working on a couple of others.

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Awesome, thanks Chris! Going on holidays until July 17, so I'll be away from GH, but I'll be happy to review when I get back 😉 
Also, to avoid any double work, note that @bwengals [already updated](https://github.com/pymc-devs/pymc3/pull/3978) `GP-Latent.ipynb`
PyMCheers 🖖

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Thanks @fonnesbeck, almost all good -- just a nitpick: `theano.tensor` is imported but unused so it can be dropped. 
Also, I can't see the Bokeh plots in the updated version, but I suppose it's due to ReviewNB?

**Comment by twiecki** [comment]
Ping @fonnesbeck .

**Comment by fonnesbeck** [comment]
Wasn't quite ready to merge. Will open another PR,

**Comment by twiecki** [comment]
Sorry for jumping the gun.

**Pull request merged**
