### PR TITLE
WIP: Appropriate step method assignment for missing data

### LINKED ISSUE #1091: Exception on Categorical with missing value imputation
Hi, I was experimenting with the missing values imputation (which is pretty awesome) for a variety of variable types.

I stumbled across this problem: if I sample with a (useless) model in this way:

``` python
x_obs = [1, 1, 0, 0, 2, 2, 2]

with pm.Model() as multin_model:
    x = pm.Categorical('x',  [0.33, 0.33, 0.33], shape=3, observed=x_obs)
    y = pm.Normal('y', shape=3)
    v = y[x] * pm.Normal('z')
    step = pm.Metropolis()
    trace = pm.sample(1000, step=step)
```

It runs without exception, but as soon as I introduce missing values I get an IndexError exception:

``` python
x_obs = np.ma.masked_equal([1, 1, 0, 0, 2, -1, -1], -1)

with pm.Model() as multin_model:
    x = pm.Categorical('x',  [0.33, 0.33, 0.33], shape=3, observed=x_obs)
    y = pm.Normal('y', shape=3)
    v = y[x] * pm.Normal('z')
    step = pm.Metropolis()
    trace = pm.sample(1000, step=step)
```

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/gabriele/anaconda/envs/medschool/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:

IndexError: index 3 is out of bounds for size 3

During handling of the above exception, another exception occurred:
... long traceback
```

Is the feature unsupported?

### PR DESCRIPTION
**Pull request by fonnesbeck**
In the current master, missing data stochastics are assigned `NoDistribution` as its probability distribution. The implication of this is that the Metropolis sampler is always selected as the step method, making the imputation of binary or categorical variables very inefficient. This PR reads the attributes of the "parent" distribution (the `distribution` attribute of the observed data) and uses that for step method selection. While it fixes the issue in some instances, it is broken for categoricals (e.g. still chokes on #1091 example), so the work is not done.

Other changes:
- renames `ElemwiseCategoricalStep` to `ElemwiseCategorical`, since no other step methods have `Step` in the name
- changes competence constants to upper case, to be PEP8-compliant

Closes #1091

### CODE REVIEW

**Comment by twiecki** [comment]
As CategoricalStep is removed now, can we merge this to get the fix for the other distributions?

**Comment by springcoil** [comment]
:+1:

**Comment by fonnesbeck** [comment]
Will rebase first.

**Comment by springcoil** [comment]
This needs a rebase, I see 12 commits. But maybe you've fixed that :)

**Comment by twiecki** [comment]
Yes, something is weird here. Needs a clean rebase.

**Comment by fonnesbeck** [comment]
This was cleanly rebased. The failure appears to be a stochastic error. Noticed that `test_distribution_random` does not use random number seeds, which is odd.

**Pull request merged**
