### PR TITLE
IPyNB and unit test for EM SDE

### PR DESCRIPTION
**Pull request by maedoc**
This adds a notebook demonstrating the EM scheme with two SDE examples. #1480 @springcoil 
- a linear SDE, using the EM distribution class
- a nonlinear oscillator model, using a custom class (to be converted to new EM class)

this is an update of a notebook I wrote back in July, and for some reason, the estimates were great back then and completely terrible right now.. to be fixed, but I just wanted to get this started.

Comments and suggestions for other SDE systems welcome, especially where datasets are real and not simulated.

### CODE REVIEW

**Comment by maedoc** [comment]
Restarting the notebook improved the estimates back to normal and the two examples now both use the new EM class. I'm open to suggestions. 

One of these could also be converted to a unit test if that'd be useful?

**Comment by springcoil** [comment]
This looks cool! 
Could you convert one of these to a unit test, just a few assert statements proving that the estimates are in the right range as is what is expected?

Maybe keeping one example as a unit test and one example as an example notebook. 

I've no real ideas of the top of my

**Comment by maedoc** [comment]
@springcoil here's the linear SDE as a test: I checked that the damping coefficient is recovered in 95% confidence and 95% PPC covers 95% of the "observable" time series. If this is not sufficient, lemme know.

**Comment by springcoil** [comment]
If it passes the tests. I'll merge it

**Pull request merged**
