### PR TITLE
SMC experimental

### PR DESCRIPTION
**Pull request by ColCarroll**
I tried submitting this to @hvasbath's fork, but was having trouble (it had hundreds of commits), so tthis might be a new version of #1923 
 
1. fixes the `joblib` problem (locally, at least!  travis isn't running jobs on my branch), which I think is related to https://github.com/scikit-learn/scikit-learn/issues/3835, which sounds like the solution is "move to a current version of python", or don't use `joblib`.
2. Adds experimental warnings

### CODE REVIEW

**Comment by twiecki** [comment]
Checks, pass, very nice! `docs/source/notebooks/SMC2_gaussians.ipynb` needs a title.

**Comment by hvasbath** [comment]
Wow very nice! Thanks a lot @ColCarroll - omg the whole struggle just because I used imap_unordered instead of map... so in the end it was only that one single line different- compared to pre joblib solving excursion trials ;) .

**Comment by junpenglao** [comment]
Great job @hvasbath @ColCarroll ! I tried yesterday and it samples nicely on the cases I tested.

**Comment by hvasbath** [comment]
@junpenglao I am happy to read that ;) . I dont know how to checkout @ColCarroll fork then I could add the title. Can someone please post a git line to do so?

**Comment by ColCarroll** [comment]
Sorry @hvasbath, I couldn't figure that out either -- part of why I like the idea of merging this so we can have multiple people working it.  I added a title and reran the notebook (with the experimental warnings!)

**Comment by twiecki** [comment]
Looks great, let's (squash) merge when tests pass.

**Pull request merged**
