### PR TITLE
Docstring update to pymc.DiscreteUniform

### PR DESCRIPTION
**Pull request by hyosubkim**
**What is this PR about?**
Added close-figs context and edited parameter descriptions.

**Checklist**
+ [ ] Explain important implementation details 👆
+ [ x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## Bugfixes / New features
- ...

## Docs / Maintenance
- ...

### CODE REVIEW

**Comment by michaelosthege** [comment]
This looks good, but it looks like we have some more distributions with the same problem - at least Categorical and the ZeroInflatedBinomial are missing the `:context: close-figs` thing too.

@hyosubkim could you go through them and fix it there too?

**Comment by hyosubkim** [comment]
@michaelosthege - I made the suggested fixes. Sorry for all the commits--I was running into some issues because my branch wasn't caught up to the remote and wasn't sure how to fix correctly at first.

**Comment by michaelosthege** [comment]
superseded by #6301 if I'm not mistaken

**Comment by hyosubkim** [comment]
Yes, that's right.

**Pull request closed without merging**
