### PR TITLE
Add Lognormal with location parameter

### PR DESCRIPTION
**Pull request by MalteBrinch**
After working on a custom lognormal distribution with a location parameter (theta), i was asked to add it to pymc3 through a PR. I have tried to add the location paramter to the lognormal function under the built-in functions. I am not entirely sure if this works completely as intended, there may need to be a tt.switch to check if theta>value, but i have tried to add that condition to bounded in logp.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Thanks for submitting a PR. I'm not sure its worth adding this, given the rarity of its use (I've never seen this parameterization in the wild). Its pretty easy to just add a shift to the `Lognormal` whenever you need to do this:

```python
x = pm.Lognormal('x', mu, sigma)
x_t = x + theta
```
Are there situations where this would not work well?

**Comment by MalteBrinch** [comment]
I agree it is fairly easy to add, it was mostly for convenience sake. One of the problems is there needs to be a check for whether theta>x or else we will have a negative logarithm, but other than that it works with no problems.

**Comment by eigenfoo** [comment]
I think the main issue is that this is not a popular parameterization of the lognormal distribution. `theta` would be an unconventional and therefore confusing parameter to add to PyMC3, regardless of the convenience that it gives us.

Is there a particular reason why you would need need this parameterization? If not, I will close this issue. Thank you for your contribution though!

**Comment by MalteBrinch** [comment]
For my case i needed it is because the function i was looking at could take on those values and it is related to the physics/geometry of the object, but if it is confusing then i agree it should not be included.

**Pull request closed without merging**
