### PR TITLE
Fix 2948

### LINKED ISSUE #2948: Theano does not sample from HalfCauchy and Lognormal together
Theano does not sample from a very simple model.

I have purged the theano cache, reinstalled theano/pymc3 to no avail.
I always get an error relating to dimension mis-match. I don't understand.

The model runs fine if I leave out `nu` or `sigma`. Both together just results in the error message below.

    import theano
    theano.compile.DebugMode = True
    print(theano.__version__)
    print(pm.__version__)

    ndim = 3
    with pm.Model() as model:
        sigma = pm.Lognormal('sigma', np.zeros(ndim), np.ones(ndim), shape=ndim)  # variance for the correlation matrix
        nu = pm.HalfCauchy('nu', beta=10) 
        pm.sample(10)

Answer:

    1.0.1
    3.4.1

    ValueError: Input dimension mis-match. (input[0].shape[0] = 3, input[1].shape[0] = 1)
    Apply node that caused the error: Elemwise{Composite{((-i0) + i1 + i2)}}(Elemwise{Composite{log(exp(i0))}}.0, TensorConstant{(1,) of -1.0}, TensorConstant{(1,) of 1.0})
    Toposort index: 8
    Inputs types: [TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, (True,))]
    Inputs shapes: [(3,), (1,), (1,)]
    Inputs strides: [(8,), (8,), (8,)]
    Inputs values: [array([-0.0915752 ,  0.1090227 , -0.38337466]), array([-1.]), array([ 1.])]
    Outputs clients: [[IncSubtensor{InplaceInc;int64:int64:}(Alloc.0, (d__logp/dsigma_log__), Constant{1}, Constant{4})]]
    
    HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
    HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

## Versions and main components

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.1
* Python Version: 3.6.5
* Operating system: Scientific Linux  3.10.0-514.el7.x86_64
* How did you install PyMC3: (conda/pip):
`pip install git+https://github.com/pymc-devs/pymc3.git`

### PR DESCRIPTION
**Pull request by junpenglao**
Reverse the logpt tensor computation back to pre #2499.
close #2948

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Maybe we should add in a test from #2948?  E.g., ideally we want to end up in a place where tests guarantee that both #2948 and #2482 are resolved.

**Comment by junpenglao** [comment]
This will not effect the fix for #2482.
I am still trying to find out why it only fail for Lognormal... if it really is an edge case I will then add a test accordingly.

**Comment by junpenglao** [comment]
So far this is really weird... 
```python
ndim = 3
with pm.Model() as model:
    sigma = pm.Lognormal('sigma', 
                         mu=np.zeros(ndim),
                         tau=np.ones(ndim), 
                         shape=ndim)  # variance for the correlation matrix
    nu = pm.HalfCauchy('nu', beta=10)

factors = [var.logpt for var in model.basic_RVs] + model.potentials
logp = tt.sum([tt.sum(logpt) for logpt in factors]) --> fail
logp = tt.add(*map(tt.sum, factors)) --> works
func = pm.model.ValueGradFunction(logp, model.basic_RVs)
func.set_extra_values(model.test_point)
q = np.array([2.30258509, 1., 1., 1.])
func(q)
```
And the error only appears using Lognormal when the tau or sd is multi dimensional...

**Comment by junpenglao** [comment]
I will merge this if no more comment.

**Comment by ColCarroll** [comment]
LGTM, though the previous code also looked good.  Glad you added some tests!

**Comment by ColCarroll** [comment]
Possible performance hit from this change?  http://pandas.pydata.org/speed/pymc3/#benchmarks.NUTSInitSuite.track_glm_hierarchical_ess

**Comment by junpenglao** [comment]
Thanks for the heads up. I am a bit surprised that it effected the effective sample size - will report back.

**Pull request merged**
