### PR TITLE
Clean up docstring for `sample`.

### PR DESCRIPTION
**Pull request by rpgoldman**
Simple clarifications to documentation for `step` argument.

### CODE REVIEW

**Review by fonnesbeck — COMMENTED** [review]
This is not exactly true. NUTS is only chosen for continuous variables.

**Comment by rpgoldman** [comment]
@fonnesbeck 

> This is not exactly true. NUTS is only chosen for continuous variables.

How about

    By default the NUTS step method will be used, if applicable; this is a good default for beginning users.

This is the behavior most people will see, and the "if applicable" gives us an out.  The details of step function choice for more complex cases is probably too much to go into in a docstring.  Maybe we should have a bigger discussion (that I am not competent to write!) on the web page?

**Comment by fonnesbeck** [comment]
Yeah, that's better. Or "if suitable for the model".

**Comment by rpgoldman** [comment]
Ok. I'll fix it

--  
Robert P. Goldman

**Comment by rpgoldman** [comment]
Should be good to go now.

**Pull request merged**
