### PR TITLE
WIP: Expand diagnosing divergences notebook

### PR DESCRIPTION
**Pull request by rpgoldman**
As I have been working through this notebook to improve my skills in diagnosis, I have also been reading over this notebook with an eye to clarifying it for users, like myself, with less sophisticated knowledge of statistics and the internals of HMC.

In the process, I have also found some aspects of the notebook that were invalidated by recent changes to PyMC3.  Notably, we say that the R-hat metric and the traces look fine in the case with many divergences.  However, they _don't_ look fine!  As run now, the R-hat metrics are high and the traces look bad!

### CODE REVIEW

**Comment by rpgoldman** [comment]
<p>Thanks!  I have rewritten all the calls to <code>pm.sample()</code>  to use 4 chains (this lets me keep a single value for the <code>SEED</code>  constant...</p><p> </p><p>I get a bunch of divergences again, now, but they are flagged by R hat and bad-looking traces, as well as by divergences.  I'm not yet sure if this is a problem with the seed, or whether we have introduced bugs into PyMC3 -- stay tuned!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3972/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p><code>az.summary</code>  invokes <code>from_pymc3</code>,  which needs model context to behave properly.  This is a somewhat unfortunate side-effect of outsourcing to ArviZ -- the user won't necessarily understand why the model context is required, but it is.  OTOH, the error messages are clear, so that's probably not bad.</p><p> </p><p>I would like to have the calls to <code>sample()</code> return an <code>InferenceData</code>  object, but I don't know if that provides the same information about diverging transitions.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3972/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Fixed, thanks for catching that!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3972/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>A difference is that I don't know how to plot the <em>log </em>of tau with <code>plot_pair</code>,  only the value of <code>tau</code>  itself.  I suppose I could add a <code>Deterministic</code>  or somehow do something to extract the value from a combination of groups, but that's hardly convenient.</p><p> </p><p>Is there some obvious solution to this problem that I am missing?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3972/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>I can do this, but since the original figure isn't labeled at all, and there is no doubling in figure 5 b in the paper referred to, I really don't know what is going on in here.</p><p> </p><p>What are the colors referring to?</p><p> </p><p>I should probably be able to understand this by reading the code, but I don't.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3972/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Thanks for catching the typo. Fixed.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3972/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Where are you on this @rpgoldman ? Is this ready for review?

**Comment by rpgoldman** [comment]
@AlexAndorra It's not ready for review yet, I think.  Discussions have clarified my thinking about the diagnosis process, and I will put that write-up in there soon, I hope (work has been super-busy).  Then it will be good to review, clarify, and correct!

**Comment by twiecki** [comment]
@rpgoldman do you want another round of reviews, think we should merge?

**Comment by MarcoGorelli** [comment]
@rpgoldman is this still active? If so, could you open a PR to pymc-examples?

**Comment by MarcoGorelli** [comment]
closing as notebooks are being moved out of pymc3

**Pull request closed without merging**
