### PR TITLE
Update Aesara dependency

### PR DESCRIPTION
**Pull request by ricardoV94**

### CODE REVIEW

**Review by michaelosthege — APPROVED** [review]
<s>🛳 it</s>

**Review by michaelosthege — CHANGES_REQUESTED** [review]
No, wait. That failing test looks like a new bug?

**Comment by ricardoV94** [comment]
> No, wait. That failing test looks like a new bug?

Which test?

**Comment by ricardoV94** [comment]
Aesara issue opened: https://github.com/aesara-devs/aesara/issues/955

**Comment by twiecki** [comment]
Can we xfail or is this critical?

**Comment by michaelosthege** [comment]
Looks like some kind of tensor typing problem:
https://github.com/pymc-devs/pymc/runs/6374288465?check_suite_focus=true#step:7:1429

`TypeError: The type of the replacement (TensorType(float64, (1, None))) must be compatible with the type of the original Variable (TensorType(float64, (1, 20))).`

**Comment by ricardoV94** [comment]
No need to guess guys, there's a linked issue: https://github.com/aesara-devs/aesara/issues/955

**Comment by ricardoV94** [comment]
This should only show up as a warning under normal aesara flags, and only in some edge cases. It will be fixed in a future release but for now I think it's fine to temporarily xfail

**Comment by ricardoV94** [comment]
The test that is failing will be removed in #5806, it was not easy to turn it off due to the way it is parametrized. 

In the meantime I rebased from main to see if anything else fails.

**Comment by twiecki** [comment]
Seems still broken, or another test?

**Comment by ricardoV94** [comment]
It's the same test, it will be removed in https://github.com/pymc-devs/pymc/pull/5806, then we can rebase and it should be good to go.

**Review by twiecki — APPROVED** [review]

**Pull request merged**
