### PR TITLE
Update Mauna Loa Notebooks

### PR DESCRIPTION
**Pull request by AlexAndorra**
I was re-reading these notebooks and came across some typos, so I'm updating them. While I was at it I formatted them with the [style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style).
They are really awesome so I think it's valuable to have them up-to-date on the website 👌 

NB: This is not ready for review and merge yet because the last model of Mauna Loa 2 is super long to sample (18 hours we reran it, 10 hours estimated on my laptop). I'll push and mark as ready once this monster sampled 👹

### CODE REVIEW

**Comment by AlexAndorra** [comment]
@bwengals this is now ready for review 🍾 Thanks a lot in advance 😉 
Note that the last Mauna Loa 2 model doesn't converge (which is why it takes so long to sample). It was already diverging in the previous version, it's just that we didn't see it because only one chain was sampled. 
I don't know what you think about that, but could be worth finding a better parametrization so that the chains sample 🤷‍♂️ No urgency tough, so could be in another PR, as the last model's results make sense (I don't why however 😅).

**Comment by twiecki** [comment]
Ping @bwengals

**Comment by bwengals** [comment]
Hey sorry I was slow.  I think the notebooks look much better.  Yeah, sampling that last model in the 2nd notebook takes forever.  I'd bet that fiddling around and giving more informative priors when possible could help... but that would also take a while (14 hours instead of 18, yay!).  I'd wanted to demo a GP with something really nonstandard, like with the uncertainty on the x locations, that would be really difficult using other software.  But yeah, the predictions look alright though, so hopefully that's ok for a demo.

**Review by bwengals — APPROVED** [review]

**Comment by AlexAndorra** [comment]
Yeah, I'm surprised too that the results look so good, despite the sampler having a lof of difficulties, which is why I think it's ok to include it -- the model is indeed really awesome and show cases lots of features of the GP module! I was just wondering whether there were some low hanging fruits somewhere 🤷‍♂️ 
Thanks again for the review --> merging now 🎉

**Pull request merged**
