### PR TITLE
Update links to book website and book image

### PR DESCRIPTION
**Pull request by JWarmenhoven**
Update to PyMC3 website (section 'Books and Videos):
- Doing Bayesian Data Analysis (Kruschke): update links to book website and book image.

**Thank your for opening a PR!**

Depending on what your PR does, here are a few things you might want to address in the description:
+ [ ] what are the (breaking) changes that this PR makes?
+ [ ] important background, or details about the implementation
+ [ ] are the changes—especially new features—covered by tests and docstrings?
+ [ ] consider adding/updating relevant example notebooks
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks!

**Comment by JWarmenhoven** [comment]
@twiecki I am not completely sure how/when the PyMC website content is (re)generated so the changes are only in the source code now.

**Comment by ColCarroll** [comment]
Should be each release, which is speeding up a bit lately. 

The image for the book looks like it is not static, sadly, so we should figure out a better one to use, or maybe host an image here.

I get a 403 error for:
https://lh5.googleusercontent.com/R1T8ZXbMi4vSO0JlnLQMkEQNvd2ncBb23OmHOsmw-t_oEOF6jJlfWuJoOK0MMmECSDymhUdfTS2yoMgkR2TY-xIiBTHCpeuYjzXqD3xhZ-MuIhs2ARcJ=w1280

**Comment by JWarmenhoven** [comment]
Ok.
Yes, I think it is better to host a copy of the image here just to be sure. 

Here I guess? 
https://github.com/pymc-devs/pymc3/tree/master/docs/source/images

There also seems to be a problem with BDA3 (Gelman et al.), looks like a certificate issue.

**Pull request merged**
