### PR TITLE
Avoid storing bound methods as variables to prevent pickling problems

### PR DESCRIPTION
**Pull request by ghost**
Fixes the problem with tests on Python 2.7 for #2201.

### CODE REVIEW

**Comment by junpenglao** [comment]
thanks @a-rodin, is this PR work on top of #2201?

**Comment by ghost** [comment]
@junpenglao Yes, it works on top of #2201.

**Comment by junpenglao** [comment]
thanks @a-rodin, i accidentally deleted my question. So it need to wait for #2201 to merge first right?

**Comment by ghost** [comment]
Not necessary, the target branch of this PR is `latex_dists`, so the PR can be just merged into that branch and the commit would appear in #2201 after the merge.

**Comment by twiecki** [comment]
@fonnesbeck This is a fix for your open PR to make it python 2 compatible.

**Comment by fonnesbeck** [comment]
Thanks!

**Pull request merged**
