### PR TITLE
Estimate missing data

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR re-establishes the `v3` way of handling missing data: i.e. add missing data terms to the model and estimate them during MCMC.

In this case, transformed values should also be handled correctly.

### CODE REVIEW

**Comment by ricardoV94** [comment]
Looks good. I will review it later today. 

Do you want to add a small test to show missing value variables are being automatically transformed. This was actually broken in V3. 

We can close this issue together with this PR if that's the case: https://github.com/pymc-devs/pymc3/issues/4488

**Comment by brandonwillard** [comment]
> Do you want to add a small test to show missing value variables are being automatically transformed. This was actually broken in V3.

There is one.

**Comment by ricardoV94** [comment]
> There is one.

Are you referring to using the Uniform in this one? https://github.com/pymc-devs/pymc3/blob/428f478847a2a5ed583ae66582c0dd0192a50f25/pymc3/tests/test_missing.py#L97

Would the test fail if the Uniform was imputed but not automatically transformed?

**Comment by ricardoV94** [comment]
There might be a kind of double counting going on with the logp of missing values.

```python
# Reference logp is -4 for observed and unobserved alike (due to picking x=1)
with pm.Model() as m1:
    x = pm.Gamma('x', 1, 1, observed=[1, 1, 1, 1])
print(m1.logp())  # -4.0

with pm.Model() as m2:
    x = pm.Gamma('x', 1, 1, size=4)
print(m2.logp({'x_log__': np.array([0, 0, 0, 0])}))  # -4.0

# But it becomes -5 when imputing a missing value
with pm.Model() as m3:
    x = pm.Gamma('x', 1, 1, observed=[1, 1, 1, np.nan])
print(m3.logp({'x_missing_log__': np.array([0])}))  # -5.0

# Also happens without transform
with pm.Model() as m4:
    x = pm.Gamma('x', 1, 1, observed=[1, 1, 1, np.nan], transform=None)
print(m4.logp({'x_missing': np.array([1])}))  # -5.0

with pm.Model() as m5:
    x = pm.Gamma('x', 1, 1, observed=[1, 1, np.nan, np.nan], transform=None)
print(m5.logp({'x_missing': np.array([1, 1])}))  # -6.0

-4.0
-4.0
-5.0
-5.0
-6.0
```

**Comment by brandonwillard** [comment]
> Would the test fail if the Uniform was imputed but not automatically transformed?

Not transforming should cause the initial point check to fail (e.g. `-inf` log-likelihood), but we can perform a more explicit check.

**Comment by ricardoV94** [comment]
> > Would the test fail if the Uniform was imputed but not automatically transformed?
> 
> Not transforming should cause the initial point check to fail (e.g. `-inf` log-likelihood), but we can perform a more explicit check.

I see. I would still go with an explicit check. A non-infinite assertion on the output of the point check or a direct logp call would make it pretty obvious what is doing.

**Comment by brandonwillard** [comment]
> There might be a kind of double counting going on with the logp of missing values.

Yeah, the log-likelihood is the sum of both the observed and unobserved distributions, and the observed distribution also contains the unobserved values.  We can either make them two disjoint distributions or remove the missing values distribution from the likelihood.

Both should be mathematically equivalent, but the latter produces a single, simple graph, while the former doesn't; however, the former fits the general framework much better and doesn't require any special treatment for missing variables.

**Comment by brandonwillard** [comment]
I've updated the commit so that it creates two disjoint random variables: one for the missing values and one for the non-missing ones.  This is by far the best approach.

**Comment by ricardoV94** [comment]
Looks great.

One thing still to consider is whether we want to alter prior/posterior predictive sampling to stitch back the variables after the fact. 

This was the behavior in V3:
```python
with pm.Model() as m:
    x = pm.Gamma('x', 1, 1, shape=4, observed=np.array([1, 1, 1, np.nan]))
    prior = pm.sample_prior_predictive()
    post = pm.sample()
    pp = pm.sample_posterior_predictive(post)
print(prior.keys(), prior['x'].shape, prior['x_missing'].shape)
print(pp.keys(), pp['x'].shape)
```
```
dict_keys(['x_missing', 'x']) (500, 4) (500, 4)]  # Unnecessary duplication going on in V3
dict_keys(['x']) (4000, 4)
```

And in V4:
```python
with pm.Model() as m:
    x = pm.Gamma('x', 1, 1, size=4, observed=np.array([1, 1, 1, np.nan]))
    prior = pm.sample_prior_predictive()
    post = pm.sample()
    pp = pm.sample_posterior_predictive(post)
print(prior.keys(), prior['x'].shape, prior['x_missing'].shape)
print(pp.keys(), pp['x'].shape)
```
```
dict_keys(['x', 'x_missing']) (500, 3) (500, 1)
dict_keys(['x']) (4000, 3)
```

**Comment by brandonwillard** [comment]
> One thing still to consider is whether we want to alter prior/posterior predictive sampling to stitch back the variables after the fact.

We can add the combined array as a "deterministic".

**Comment by brandonwillard** [comment]
Now, there's a deterministic in there for the complete observed variable.  The observed portion is given the original variable name with the added `_observed` suffix, complementing the existing `_missing` suffix for the missing portion.

**Comment by ricardoV94** [comment]
This is what I see now by in prior / sample / posterior predictive with the example from above:

```python
print(prior.keys())
# dict_keys(['x_observed', 'x', 'x_missing'])

print(post.varnames)
# ['x_missing', 'x_missing_log__', 'x']

print(pp.keys())
# dict_keys(['x_observed'])
```

Some observations:
1. ~~In prior predictive sampling it seems the `x` `Deterministic` gets disconnected from the inputs `x_observed` and `x_missing`, as it retains the observed values from `x_observed`  (and not the newly sampled values found in it)  and the values corresponding to `x_missing` do not match: `np.mean(prior['x'][:, -1] == prior['x_missing'].squeeze())  # 1`~~.
2. In prior predictive sampling do we want the `x` to include the newly sampled values of `x_observed`? Right now it includes the original observed data + the sampled `x_missing`.
3. There seems to be a disconnect between the `x` `Deterministic` and `x_missing` during normal sampling? `np.mean(post['x'][:, -1] == post['x_missing'].squeeze())  # 0.0`
4. In posterior predictive sampling, should we try to get `x` as well? This would not only match the `V3` behavior, but I think it's also the most intuitive for users.

**Comment by brandonwillard** [comment]
> 1. In prior predictive sampling it seems the `x` `Deterministic` gets disconnected from the inputs `x_observed` and `x_missing`, as it retains the observed values from `x_observed`  (and not the newly sampled values found in it)  and the values corresponding to `x_missing` do not match: `np.mean(prior['x'][:, -1] == prior['x_missing'])  # .002`.

Ah, yes, I added the missing entries to the _data_, but we need to construct a new array altogether and fill it with both the missing _and_ observed random variables.

After making that quick change, I'm seeing a weird issue involving gradients and `BroadcastTo`. 
 It looks like the parameter lifting operation applied to the `RandomVariable`s is introducing those `BroadcastTo` `Op`s in a way that results in a `*IncSubtensor*` being applied to the result of a `BroadcastTo`, but, since the output of a `BroadcastTo` is a view, it can't be updated like that.

```python
E   ValueError: input/output array is read-only
E   Apply node that caused the error: AdvancedIncSubtensor1{inplace,set}((d__logp/dtheta1), TensorConstant{(3,) of 0.0}, TensorConstant{[0 1 3]})
...
E   Debug print of the apply node: 
E   AdvancedIncSubtensor1{inplace,set} [id A] <TensorType(float64, vector)> ''   
E    |<aesara.tensor.extra_ops.BroadcastTo object at 0x7f49c73965b0> [id B] <TensorType(float64, vector)> '(d__logp/dtheta1)'   
E    |TensorConstant{(3,) of 0.0} [id C] <TensorType(float64, vector)>
E    |TensorConstant{[0 1 3]} [id D] <TensorType(int64, vector)>
```

I'll put together a smaller example and see if there's a quick direct solution to this; otherwise, we can always remove/replace the `BroadcastTo`s.

**Comment by brandonwillard** [comment]
Here is a minimal reproduction of the issue:
```python
import numpy as np

import aesara
import aesara.tensor as at


a = at.zeros((5,))
d = at.vector("d")
c = at.set_subtensor(a[np.r_[0, 1, 3]], d)
b = at.broadcast_to(c, (5,))
e = at.set_subtensor(b[np.r_[0, 1, 3]], np.r_[0, 0, 0])
```
```python
>>> aesara.dprint(e)
AdvancedIncSubtensor1{no_inplace,set} [id A] ''
 |BroadcastTo [id B] ''
 | |AdvancedIncSubtensor1{no_inplace,set} [id C] ''
 | | |Alloc [id D] ''
 | | | |TensorConstant{0.0} [id E]
 | | | |TensorConstant{5} [id F]
 | | |d [id G]
 | | |TensorConstant{[0 1 3]} [id H]
 | |Subtensor{int64} [id I] ''
 |   |TensorConstant{(1,) of 5} [id J]
 |   |ScalarConstant{0} [id K]
 |TensorConstant{(3,) of 0} [id L]
 |TensorConstant{[0 1 3]} [id M]
```

Evaluating with `e.eval({d: np.r_[-0, -1, -3]})` (re)produces the error.

**Comment by brandonwillard** [comment]
All right, everything should be fixed once https://github.com/pymc-devs/aesara/pull/368 goes through.

**Pull request merged**
