### PR TITLE
DOC finalized GLM model selection doc

### PR DESCRIPTION
**Pull request by junpenglao**
add PSIS-LOO.

A more general doc on model selection will follow shortly, extending the existing model_comparison.ipynb with math and explanation from @avehtari 's survey paper.

### CODE REVIEW

**Comment by springcoil** [comment]
Cool looks promising. I always wanted to write this :)

**Comment by twiecki** [comment]
Very cool @junpenglao.

**Comment by aloctavodia** [comment]
upps I have some comments to do, could I still post them here?

**Comment by junpenglao** [comment]
@aloctavodia Sure - I will add them to my next PR on model comparison

**Comment by twiecki** [comment]
@aloctavodia sorry about that.

**Comment by aloctavodia** [comment]
(no way to review a notebook, right?)

I found a couple of typos

"Watanabe - Akaike (or Widest Available)" should be "Watanabe - Akaike (or Widely Applicable)"

"A Widely Applicable Bayesian Information Criterion" should be "A Widely Applicable Information Criterion" (although the similar names these are two different things)

I think the sections **Contents**, **note** and **Package Requirements (shown as a conda-env YAML):** should be removed. We do not have those in others examples.

Not very happy with the Bayes Factor section, but probably because I am not very have with Bayes factors :-) Maybe we could add something about why Bayes factors could be problematic (not only the computational part) but the sensitivity to priors or something like that (in the line of Gelman et al). I also think the sentence "The Bayesian approach proceeds very differently." Is a little bit misleading in this context as it seems to be saying that all the previous content in notebook was not _truly Bayesian_.

@twiecki don`t worry I did not sleep well last night and I am slower today ;-)

**Comment by junpenglao** [comment]
@aloctavodia Thanks for the review.
Yes I would vote to remove the Bayes Factor part as well.

**Comment by aloctavodia** [comment]
I don't know if we should remove the Bayes Factor part. I think we mabybe should say something about them, something about why we do not recommend using them (_I am assuming we not!_), or at least some of the caveats. My only concern is that probably many people use BF (or at least have heard about them), so they will be expecting some reference in the docs.

**Comment by junpenglao** [comment]
@aloctavodia I see what you mean now... But we don't have an easy implementation of computing BF, so for the purpose of this doc, I would still prefer removing them.

As for a more general discussion of model comparison, I agree with you: we can reuse the same text but explain why it is not recommended (with some refs).

**Pull request merged**
