### PR TITLE
WIP Use theano float type

### PR DESCRIPTION
**Pull request by twiecki**
Rebase of https://github.com/pymc-devs/pymc3/pull/1253

### CODE REVIEW

**Comment by springcoil** [comment]
I assume this is still a WIP...

**Comment by twiecki** [comment]
Yeah, alas. It's enables GPU but makes pymc3 picky about which float dtypes it accepts as inputs.

**Comment by ferrine** [comment]
Is it alive? And is it currently possible to run computations advi/sampling on gpu?

**Comment by twiecki** [comment]
Rebased off of master.

**Comment by twiecki** [comment]
I think @tyarkoni had problems after we merged a previous version of this PR, but I can't find it. @tyarkoni do you remember what it was?

**Comment by tyarkoni** [comment]
I think you're referring to the thread in #1283. I don't know if these changes address my concern there, but FWIW, I think the issue was that something somewhere was still introducing float64 dtypes, as models were failing on the GPU.

**Comment by twiecki** [comment]
I wonder if we should just force everything to `float32` internally.

**Comment by tyarkoni** [comment]
It looks like I still get the same precision-related error in Theano when using the GPU (with RC6) and initializing with ADVI. So I don't think the problem is entirely solved. But it does look like at least part of the earlier concern was addressed, since sampling with NUTS no longer throws the same error.

Looking at the [variational](https://github.com/pymc-devs/pymc3/tree/7584b3b815cccb81e7d0bf3e9bb0cf60ac795ffa/pymc3/variational) module, it looks like `advi_minibatch.py` checks `theano.config.floatX` and sets the dtype accordingly, but `advi.py` does not. Have not tested the minibatch code to see if that solves the issue, but I'm guessing maybe the advi module just needs to be patched to use the same approach?

**Comment by twiecki** [comment]
Closing in favor of #1690.

**Pull request closed without merging**
