### PR TITLE
fix GARCH11: missing [] in tt.concatenate()

### LINKED ISSUE #2938: Test for GARCH11
Based on what we discovered in the review off #2937 we need a test for GARCH11.

### PR DESCRIPTION
**Pull request by smartass101**
This is just a simple fix, not sure if it ever worked without it.
close #2938

### CODE REVIEW

**Comment by springcoil** [comment]
Good catch :) Could you add a little test to this too?

**Review by springcoil — APPROVED** [review]
LGTM, is there a test for this though?

**Comment by junpenglao** [comment]
I am surprised that we dont have any test for GARCH11.
Not sure if we should address this here, as in the timeseries we only have test for `EulerMaruyama` and `AR`

**Comment by springcoil** [comment]
Maybe a different commit - something to be opened up.

**Comment by smartass101** [comment]
Sorry, didn't follow your discussion while working on the test. Just tried to create something similar to the AR test, will see if it passes.

**Comment by junpenglao** [comment]
@smartass101 nicely done ;-)

**Comment by springcoil** [comment]
Looks awesome. I was going to have a go this afternoon. Well done

**Comment by springcoil** [comment]
Well done :) Welcome @smartass101 on your first commit :)

**Pull request merged**
