### PR TITLE
Rename aesara.tensor acroynm to at

### LINKED ISSUE #4538: Rename aesara.tensor import from aet to at
Ref https://github.com/pymc-devs/aesara/issues/328

### PR DESCRIPTION
**Pull request by farhanreynaldo**
fixes https://github.com/pymc-devs/pymc3/issues/4538

**Thank your for opening a PR!**

Depending on what your PR does, here are a few things you might want to address in the description:
+ [x] <s>what are the (breaking) changes that this PR makes?</s> internal changes only
+ [x] important background, or details about the implementation --> see linked issue
+ [x] are the changes—especially new features—covered by tests and docstrings?
+ [x] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [x] <s>[consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)</s> does not apply
+ [x] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

### CODE REVIEW

**Review by michaelosthege — APPROVED** [review]
These changes look good to me. Rebasing `v4` will be a pain, but delaying this change won't help us either.

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @farhanreynaldo!

@michaelosthege This is a situation where having a `master` and `v4` is making things more difficult.

**Review by brandonwillard — DISMISSED** [review]
This amount of refactoring requires a lot of reviewing.  We prefer that project members make such large refactorings to save on the amount of time spent reviewing, no?

Also, there's still a rather large open question regarding whether or not this `master` branch will be used going forward.  We currently have a `v3` branch from which we plan to cut releases, and we have no plans to merge `master` with `v3`, right?  Are we assuming that `v4` will be merged into `master`?  If that's the case, it's better to put PRs like this in `v4`, so that we reduce the amount of merge conflicts down the road.

**Comment by michaelosthege** [comment]
> This amount of refactoring requires a lot of reviewing. We prefer that project members make such large refactorings to save on the amount of time spent reviewing, no?
I don't think so - this PR is as good as we need it to be.

The branching is also as outlined in the [Timeline wiki page](https://github.com/pymc-devs/pymc3/wiki/Timeline).

My impression is that we are operating like this:
* `master` is supposed to be *functional* (which it is, right now)
* `v4` is about the switch to `RandomVariable` - as soon as it's *functional* we can merge into `master`

So everything that does not directly contribute to `RandomVariable` sampling can/should go into `master` directly.

> we have no plans to merge master with v3, right?

Correct. `v3` has diverged. We *can*, however, `cherry-pick` specific things for backporting.

**Comment by brandonwillard** [comment]
> The branching is also as outlined in the [Timeline wiki page](https://github.com/pymc-devs/pymc3/wiki/Timeline).

Then the plan is to rebase `v4` onto `master`, which&mdash;with these changes&mdash;could easily lead to a considerable amount of merge conflicts that will need to be resolved.  

At the very least, we will need to create a new issue for a `v4`/`master` rebase after merging this, and, when that's done, everyone with open `v4` PRs will need to rebase and resolve&mdash;hopefully fewer&mdash;conflicts, as well.

**Comment by michaelosthege** [comment]
After some internal discussion/coordination about the order or merges/rebasing we're now going to merge this. Thanks @farhanreynaldo !

Next up after that will be #4533, which shouldn't need a rebase.
We will then continue with rebasing the `v4` branch to get it back to a mergeable state.

Also we'll freeze stop accepting PRs into `master`  for the meantime, so we can avoid rebasing `v4` over and over again.

**Comment by farhanreynaldo** [comment]
Thank you @michaelosthege @twiecki @brandonwillard!

Just wanted to clarify, if I wanted to help on another issue, I should do PR on v4 branch, right?

**Comment by michaelosthege** [comment]
> Just wanted to clarify, if I wanted to help on another issue, I should do PR on v4 branch, right?

Yes

**Pull request merged**
