### PR TITLE
Add attribute access for variable names

### PR DESCRIPTION
**Pull request by kyleam**

### CODE REVIEW

**Comment by kyleam** [comment]
Well, based on the failing test, this can get into a bad state.  I'll look into to adding checks to prevent the infinite loop.

**Comment by kyleam** [comment]
All tests are passing now.

**Comment by twiecki** [comment]
Looks good, thanks!

**Comment by jsalvatier** [comment]
Could we add a short test for this just so the code path gets exercised?

**Comment by kyleam** [comment]
Yes, we should.  Now tested in 8664d3a1d0f.

**Pull request merged**
