### PR TITLE
Create .gitpod.yml

### PR DESCRIPTION
**Pull request by ferrine**
Adding gitpod workspace integration that works really great if you do not to set up local environment. You just open gitpod workspace like this:

https://gitpod.io/#https://github.com/pymc-devs/pymc/tree/gitpod

For open source community there is a free plan

https://www.gitpod.io/blog/gitpod-for-opensource

### CODE REVIEW

**Review by canyon289 — APPROVED** [review]

**Comment by maresb** [comment]
This looks pretty cool. I've been doing a bunch of devcontainer stuff myself lately.

Startup is pretty slow, but we could use mamba, or even better, prebuild a Docker image...

Also, I was running stuff localy, but just discovered GitHub Codespaces, but Gitpod looks even better since it seems independent.

**Comment by ferrine** [comment]
I tried to optimize the startup but did not spend too much time on it. The docker startup should be great

**Comment by maresb** [comment]
I have a [base image](https://github.com/mamba-org/micromamba-devcontainer) which should be pretty much perfect for this case. I'll see if I can get this running smoothly over the weekend.

**Comment by rowan-schaefer** [comment]
Awesome! 🙌 If we need contributing docs explaining usage I can help with that

**Comment by twiecki** [comment]
@rowangayleschaefer That'd be great!

**Pull request merged**
