### PR TITLE
Leave-one-out cross-validation

### PR DESCRIPTION
**Pull request by fonnesbeck**
Implements LOO cross-validation using Pareto-smoothed cross-validation, following Vehtari et al (2015). Still needs to have tests written.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
The 8 schools example, which I have added here, is a good example of a model that should run very fast, but is quite slow under NUTS (#739).

**Comment by datnamer** [comment]
Could it just be the overhead of accessing python classes?  Does this happen many times?

**Comment by springcoil** [comment]
I think @jonsedar or @AustinRochford was working on stuff related to this. Just so there's no double work.

**Comment by AustinRochford** [comment]
I am not working on anything like this.

**Comment by fonnesbeck** [comment]
This should be good to go now. I have rebased to current master. If anyone can think of a good test, let me know. I don't know if doing full cross-validation as a test would be worthwhile given how long it would take.

**Comment by springcoil** [comment]
Looking at the code I think we can merge this in - without a test. As it looks good to me. Let's leave the test for a separate PR. Can you squash this commit though Chris - 59 commits is a lot to push in one go.

**Comment by twiecki** [comment]
Yeah, something seems to have gone wrong with this branch.

**Comment by fonnesbeck** [comment]
I rebased it, so it should be good. Are you having issues with it @twiecki ?

**Comment by twiecki** [comment]
No, but just looking at files changed shows a huge diff.

**Comment by fonnesbeck** [comment]
That's just a months' worth of commits from the rebase. I can create a new branch if you'd prefer.

**Comment by fonnesbeck** [comment]
Closing in favor of #1003

**Pull request closed without merging**
