### PR TITLE
CLN fix missing newlines

### PR DESCRIPTION
**Pull request by MarcoGorelli**
xref this comment by @twiecki  https://github.com/pymc-devs/pymc3/pull/4076#discussion_r483937597

> missing new line

How about adding a pre-commit check for this, so that reviewers never have to worry about leaving such a review in the future :smile: ?

### CODE REVIEW

**Comment by twiecki** [comment]
I like that :)

**Review by AlexAndorra — APPROVED** [review]
Looks neat, thanks @MarcoGorelli ! Don't know why it changed some JS files though 🤷‍♂️ 
Also, how would devs go ahead and apply that in their PR workflow?

**Comment by MarcoGorelli** [comment]
> Looks neat, thanks @MarcoGorelli ! 

:+1: 

> Don't know why it changed some JS files though man_shrugging

Pre-commit isn't a Python-specific tool. This particular hook will run against lots of different types of files, if they don't have newlines at the end (like the JS files modified here didn't) it'll add them

> Also, how would devs go ahead and apply that in their PR workflow?

If they install pre-commit, the pre-commit checks will run against any files they've modified when they do `git commit`

**Comment by AlexAndorra** [comment]
Sounds good! Thanks a lot @MarcoGorelli 👌

**Pull request merged**
