### PR TITLE
Implement iterative NUTS algorithm

### PR DESCRIPTION
**Pull request by ColCarroll**
This seems more readable, and perhaps modestly more efficient than the recursive implementation.  As far as I can tell, it is also novel: the original c++ and matlab versions, as well as versions in julia, python, and R are all recursive (and use the original notation).  

It passes all existing tests (except this `test_parallel_start` one?), but would appreciate another look.

### CODE REVIEW

**Review by springcoil — COMMENTED** [review]
The changes look good to me after a first pass

**Comment by kyleabeauchamp** [comment]
It would be great to have a PDF version written up somewhere, as the recursive implementation has been a "barrier to entry" for myself and several colleagues.

**Comment by ColCarroll** [comment]
That failure looks funny, and might have more to do with conda than with anything else.  It passed on my branch and when I reinstalled things locally -- I'll see if force pushing my branch will kick off another build that fixes it.

@kyleabeauchamp -- I'll type up the notes I made this weekend, which might also help to find any problems!

**Comment by ColCarroll** [comment]
apparently it is a thing!  i'll look into it -- we should probably be pinning all the versions in conda.

**Comment by twiecki** [comment]
These conda version issues are pretty annoying. Maybe this is now fixed already on their end?

**Comment by springcoil** [comment]
Wow this error is annoying :)

**Comment by springcoil** [comment]
Ok I'll merge this now - great work @ColCarroll I look forward to that IPyNB or PDF write up or blog post (however you wish to do it) on how this algorithm actually works. I've not seen it anywhere else.

**Pull request merged**
