### PR TITLE
REL Update version to 3.0.

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by springcoil** [comment]
This LGTM - but the BDFL gets final say.

**Comment by springcoil** [comment]
@ColCarroll Add in the readme...

**Comment by ColCarroll** [comment]
Er, will need to make sure tests *actually* pass on 3.6 -- I can push something in ~2hrs after work unless someone else gets to it first.  Hopefully it won't come up, but should tests passing on 3.6 be a release blocker?

**Comment by springcoil** [comment]
Ohh that's a valid point. I wouldn't consider it being a release blocker. But @fonnesbeck is probably the one to ask.

**Comment by fonnesbeck** [comment]
I don't think a 3.6 test is necessary for 3.0, but if someone feel strongly about it and wants to make it work, then I'm happy to wait a day.

**Comment by ColCarroll** [comment]
Fails, but because of `pyqt`.  I don't know much about the library -- grepping for it turns up no results, but maybe it is used for some of the plotting?

https://travis-ci.org/ColCarroll/pymc3/jobs/189623258

**Comment by springcoil** [comment]
This looks good to me @twiecki in terms of documentation. Is the python 3.6 error fixed yet? cc @ColCarroll

**Comment by twiecki** [comment]
I removed the 3.6 support.

**Comment by twiecki** [comment]
Woohoo! Let's get conda-forge updated. Can you handle that @springcoil ?

**Comment by fonnesbeck** [comment]
Pushed to PyPI.

**Comment by springcoil** [comment]
https://github.com/conda-forge/pymc3-feedstock/pull/6 done :)

**Pull request merged**
