### PR TITLE
Fix VI test not skipping in Windows

### PR DESCRIPTION
**Pull request by ricardoV94**
## Description

The test `test_fit_start[SVGD-mini]` stopped raising a NotImplementedInferenceError in Windows recently. 

https://github.com/pymc-devs/pymc/blob/f8b19a52c19dcc77aaabd6dc7464bee9304ebc58/tests/variational/test_inference.py#L206-L210

It should come from https://github.com/pymc-devs/pymc/blob/2051d0b422a10ef0477cff0b3994ede4ec7c26ad/pymc/variational/operators.py#L145-L148

It still works correctly on Linux?

Link to failing test:
https://github.com/pymc-devs/pymc/actions/runs/7783900052/job/21223348962?pr=7136

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [x] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7136.org.readthedocs.build/en/7136/

### CODE REVIEW

**Comment by aerubanov** [comment]
@ricardoV94  I try to run this test locally on Linux. It is fails when I use `pytest==8.0 `and skipped with `pytest==7.* `

**Comment by ricardoV94** [comment]
Thanks @aerubanov that's some nice info. Could you dig anything that changed with pytest 8.0?

**Comment by aerubanov** [comment]
Yeah, will try to find something relevant for this issue

**Comment by aerubanov** [comment]
Looks like in pytest 7 missing warning were ignored if some exception was raised, but now it`s still checking and that`s why this test fails. Relevant PR: https://github.com/pytest-dev/pytest/pull/11129

**Comment by ricardoV94** [comment]
Great, how should we fix it though :D?

**Comment by aerubanov** [comment]
@ricardoV94 I see two options:
- Do not use `pytest.warn()` here and check for warning manualy
- Keep list of parameters for which `NotImplementedInference` should be raised and call `pytest.skip()` before `interface.fit()`

**Comment by aerubanov** [comment]
Yeah, looks like first will require less changes in the future. Will try to implement it.

**Comment by aerubanov** [comment]
@ricardoV94 could you please take a look https://github.com/pymc-devs/pymc/pull/7144?

**Pull request closed without merging**
