### PR TITLE
Fix broken VI test (pytest issue)

### PR DESCRIPTION
**Pull request by ferrine**
One test is mentioned to be broken in #3775, #3776 is created to remove the test, but it would be a temporary solution.

### CODE REVIEW

**Comment by rpgoldman** [comment]
@ferrine Unfortunately, fixing this for the benefit of `test_variational_inference` breaks it in the test file that's the source of the fixture.

I think an easier fix might be to give up on figuring out the scoping, and just copy the fixture from the source file into `test_variational_inference`.  This is unsatisfactory, but fighting pytest is unsatisfactory, too.

**Comment by ferrine** [comment]
I'll do that then

**Comment by ferrine** [comment]
I think that this may happen due to module scoping

**Comment by lucianopaz** [comment]
Great @ferrine! Looks like you fixed this! For some reason we seem to have to CI builds running in the PR. Maybe we are in the [situation described here?](https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests) I'm in my cellphone and can't take a closer look into that but maybe it would be worth opening an issue

**Review by lucianopaz — APPROVED** [review]

**Comment by ferrine** [comment]
> @ferrine! Looks like you fixed this! 

Lol, I did not think I did it and tried to find my PR for 5 mins

**Comment by ferrine** [comment]
I see some pytest issues on this https://github.com/pytest-dev/pytest/issues/6497

**Pull request merged**
