### PR TITLE
Used SkipTest decorator to bypass test_examples

### PR DESCRIPTION
**Pull request by fonnesbeck**
More elegant disabling of long-running tests.

### CODE REVIEW

**Comment by twiecki** [comment]
:+1:

**Comment by fonnesbeck** [comment]
Perhaps I am using `SkipTest` incorrectly, but it does not seem to work as advertised:

```
ERROR: Failure: TypeError (Can't make a test from <function test_examples0 at 0x7fb015b44140>)
```

**Comment by twiecki** [comment]
That's probably because we try to call these functions explicitly rather than via nosetests: https://github.com/pymc-devs/pymc3/blob/master/.travis.yml#L33 Maybe we should just disable there.

**Comment by twiecki** [comment]
Seems to pass, at last.

**Pull request merged**
