### PR TITLE
Updated import of IPython components for IPython 4.0

### PR DESCRIPTION
**Pull request by fonnesbeck**
Eliminates deprecation warnings for traitlets and widgets following re-organization of IPython

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Not clear what went wrong. A ton of ValueErrors complaining about graphs with cycles, none of which appear to be linked to IPython imports.

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/issues/803

**Comment by fonnesbeck** [comment]
Everyone happy with this?

**Comment by jsalvatier** [comment]
:+1: Seems okay, do we have the theano people fixing the issue?

**Comment by twiecki** [comment]
I'm not sure if someone is working on it but we're not the only one with
that problem. I think we should just wait it out.

**Pull request merged**
