### PR TITLE
Added a modelBuilder class for deployment

### PR DESCRIPTION
**Pull request by 5hv5hvnk**
**What is this PR about?**
This PR resolves  issue #4687, By creating a model builder class to perform `fit` , `predict` , `save`, `load` and few more things. Having direct API calls would be useful for users to deploy their standard model and allow people to use them directly using the methods mentioned above.
...

**Checklist**
+ [ ] Explain important implementation details 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## Bugfixes / New features
- ...

## Docs / Maintenance
- ...

### CODE REVIEW

**Comment by ferrine** [comment]
In pymc you can already do this

```python
class LinearRegression(pm.Model):
    def __init__(self, data: pd.DataFrame, *, sigma=1, sigma_obs=1, observed=None, **kwargs):
        super().__init__(**kwargs)
        # use self.name_for to avoid name collisions for coords
        self.add_coord(self.name_for("coefs"), data.columns)
        alpha = pm.Normal("alpha", sigma=sigma, dims=self.name_for("coefs"))
        intercept = pm.HalfCauchy("intercept", 1)
        eps = pm.HalfNormal("sigma", sigma_obs)
        y = pm.Normal("y", data.values @ alpha + intercept, observed=observed)
```

and then use the template model like this

```python
data = pd.DataFrame(np.random.randn(100, 10))
lr = LinearRegression(data)
lr1 = LinearRegression(data, name="new")
```
image

The base Model class already supports a lot of automation for name creation and model building blocks. You can extend the idea to provide methods to the Model class itself, so that it is possible to do like this:

```
trace = lr.sample()
ppc = lr.sample_poseterior_predictive(trace)
```

an additional check should pass `lr1.isroot is True` to avoid cases like

```python
with pm.Model() as model:
    lr1 =  LinearRegression(data, name="first")
    y1 = lr1.y
    lr2 =  LinearRegression(data, name="second")
    lr1.sample()
>>> TypeError("Can't call model.sample on nested models")
```

**Comment by ferrine** [comment]
This discussion is also related https://github.com/pymc-devs/pymc/discussions/6024

**Comment by fonnesbeck** [comment]
The PyMC convention is to use underscores for file names rather than camelCase, so I would rename `modelBuilder.py` to `model_builder.py`.

**Comment by twiecki** [comment]
@ferrine This inherits from `Model` but adds more functionality. And current `Model` still lacks a bunch of other functionality we're adding here. Or are you suggesting to just beef up `Model` directly?

**Comment by ricardoV94** [comment]
> @ferrine This inherits from `Model` but adds more functionality. And current `Model` still lacks a bunch of other functionality we're adding here. Or are you suggesting to just beef up `Model` directly?

I think inheriting makes sense. 

Could we do this in pymc-experimental?

**Comment by twiecki** [comment]
> Could we do this in pymc-experimental?

Yes, that's probably the right place for now.

**Comment by 5hv5hvnk** [comment]
I have generated a PR on PyMC experimental [#64](https://github.com/pymc-devs/pymc-experimental/pull/64)

**Pull request closed without merging**
