### PR TITLE
Add DIC calculation; references #797

### PR DESCRIPTION
**Pull request by AustinRochford**
~~Needs tests~~

### CODE REVIEW

**Comment by AustinRochford** [comment]
``` bash
> ./bin/python2.7 ./bin/nosetests-2.7 pymc3.tests.test_stats:test_dic
.
----------------------------------------------------------------------
Ran 1 test in 4.834s

OK
```

^ for my own reference on how to run single tests with `nose`

**Comment by jsalvatier** [comment]
This seems like its going to be relatively slow because it has to loop over the whole trace. I wonder if there's not an intuitive way to just record the logps the whole way through with an option. Or maybe even by default?

**Comment by AustinRochford** [comment]
Storing the logp on each iteration (optionally) is how `pymc2` does it, I will see if I can put that together.

**Comment by AustinRochford** [comment]
I've added `logp` storage during sampling to the `NDArray` backend, but it seems kind of clunky to add this one special case to each of the backends.  @jsalvatier any thoughts on how to do it a bit more elegantly?

**Comment by twiecki** [comment]
So we'd have to do this for each backend? I'm starting to think that the your first implementation is the way to go. DIC isn't computed all too often so some overhead there seems fine. At least, I prefer that over the added code complexity of having logps being stored in the trace. Unless there will be other uses for that going forward?

**Comment by AustinRochford** [comment]
I can't see a more elegant way to store it than modifying each backend separately, and tend to agree that since DIC will probably only be calculated once per model, the time to iterate through the trace is an acceptable tradeoff.

**Comment by twiecki** [comment]
The total computation time should be the same regardless. In one case we're calling it while sampling and in the other case we're calling during DIC calculation and on-demand. That's pretty clear.

**Comment by twiecki** [comment]
@jsalvatier Let me know what you think, but I think it's better to recompute.

**Comment by jsalvatier** [comment]
Yeah, recomputing does seem better than modifying the backend. 

We should actually be able to compute the model logp quite easily by adding `model.logpt` to the list of tracked variables. We could just advise users to say `sample(3000, step=steps, trace=model.vars+[model.logpt])`. Though we probably have to add a line [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/model.py#L158) saying `logpt.name = 'logp'`.

This seems a little undesirable, but also we probably don't always want to store the logp since its not usually going to be used. 

I think its fine to do it this way now and then we can automate it a bit more later.

**Comment by AustinRochford** [comment]
Thanks for the feedback, all.  Let me know if there are any more changes you think are necessary to get this merged.

**Comment by jsalvatier** [comment]
LGTM.

**Pull request merged**
