### PR TITLE
Fix #895: Bug pickling model instances

### LINKED ISSUE #895: HIGHEST_PROTOCOL breaks pickling
It seems as though, during deserialisation, `__new__` is being called to make new objects, but the correct model context isn't available at that point when using HIGHEST_PROTOCOL so deserialisation fails.

In this case cPickle.HIGHEST_PROTOCOL == 2

``` Python
import cPickle

with open('model.pkl', 'wb') as f:
    cPickle.dump(model, f, protocol=cPickle.HIGHEST_PROTOCOL)

with open('model.pkl', 'r') as f:
    model_unpickeled = cPickle.load(f)
```

```
TypeError                                 Traceback (most recent call last)
<ipython-input-51-96ec8b006af6> in <module>()
     11 
     12 with open('model.pkl', 'r') as f:
---> 13     model_unpickeled = cPickle.load(f)

/Users/andy/anaconda/lib/python2.7/site-packages/pymc3/distributions/distribution.pyc in __new__(cls, name, *args, **kwargs)
     17             model = Model.get_context()
     18         except TypeError:
---> 19             raise TypeError("No model on context stack, which is needed to use the Normal('x', 0,1) syntax. Add a 'with model:' block")
     20 
     21         if isinstance(name, str):

TypeError: No model on context stack, which is needed to use the Normal('x', 0,1) syntax. Add a 'with model:' block
```

### PR DESCRIPTION
**Pull request by burnpanck**

### CODE REVIEW

**Comment by twiecki** [comment]
I don't understand why that fixes things but great that it does. And I assume you confirmed that the test breaks without it but works with it?

**Comment by ColCarroll** [comment]
Really cool!  Taught me a new thing: [`__getnewargs__`](https://docs.python.org/2/library/pickle.html#object.__getnewargs__).  

I'd be happier if `name` wasn't so heavily weighed down (in that it can be a string *or* `_Unpickled`), but can't see how to change that:  it looks like python3.4+ has `__newargs_ex__` so we could pass a keyword flag, but only for protocol 4+.

Any chance you could document the `_Unpickling` class, perhaps pointing to the docs, and explaining that it is used as a flag to unpickle distributions?

**Comment by burnpanck** [comment]
Yes, the test breaks without the fix, at least locally on my machine, at protocol 2 (and probably everything above), under python 3.5. If I'm right, protocol 2 introduced `__getnewargs__`. That one was there before the fix, but it used `None` as a sentinel. However, the test for the sentinel was after the check for the model context, which it failed under pickling circumstances.
I changed the sentinel to make it more clear that it is only for pickling purposes.

Instead of having a sentinel, we could also enter special unpickle context and detect that one. I discarded that because that will be less efficient. A third option would be to rely on [`__reduce__`](https://docs.python.org/3/library/pickle.html#object.__reduce__).

In my eyes, the real problem here is that the constructor wants to enforce a model context. To me, the most important aspect for a library like this is a well designed data structure/API that allows for easy programmatic introspection and manipulation. Given that, one can implement event the most fancy user magic on top of it. The other way around is difficult: If the data structure is convolved with magic, all programmatic manipulation will need to work around that magic. In the case at hand here, the pythonic API to create instances is to call the constructor, which is not what this constructor does, so all programmatic manipulation of `Distribution` will need to be special-cased.

**Comment by twiecki** [comment]
Thanks @burnpanck! Your thoughts on design are intriguing.

**Comment by burnpanck** [comment]
I have second thoughts: Changing the sentinel from `None` to something different will break pickles generated without the patch, when loaded with the patch. While these pickles would anyway fail during loading under normal circumstances, it was possible to work around by initiating a dummy context stack. This fails now. While there are plenty of warnings in the pickle documentation that one shouldn't rely on pickle for long-term storage, there are many people who do (including me). I assume storing model instances is done rarely, but still. We could add a check for `None` and emit a warning. What do you think?

**Comment by twiecki** [comment]
I think that's fine. This will be part of RC3 and 3.0. If it came in later I would agree with you.

**Pull request merged**
