### PR TITLE
Add simple test case for coords behavior

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
This PR adds a simple test case that attempts to trigger issue #3976.  I'm mainly checking to see whether the current CI/CD reproduces the issue I'm seeing.  I've also bumped the minimum version of arviz to ensure correct behavior of coords.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Can someone confirm that Travis will pick up a test like this?  It's not obvious whether the test harness only includes a select subset on travis, or whether all additions will get picked up by default.

**Comment by kyleabeauchamp** [comment]
OK, looks like my new test is running and failing, now I just need to wait for the error message to print out.

```
pymc3/tests/test_coords.py::test_coords FAILED                           [  0%]

```

**Comment by kyleabeauchamp** [comment]
Boom:

```
=================================== FAILURES ===================================
_________________________________ test_coords __________________________________
    def test_coords():
        chains = 2
        n_features = 3
        n_samples = 10
    
        coords = {"features": np.arange(n_features)}
    
        with pm.Model(coords=coords):
            a = pm.Uniform("a", -100, 100, dims="features")
            b = pm.Uniform("b", -100, 100, dims="features")
            tr = pm.sample(n_samples, chains=chains, return_inferencedata=True)
    
>       assert "features" in tr.posterior.a.coords.dims
E       AssertionError: assert 'features' in ('chain', 'draw', 'a_dim_0')
```

**Comment by kyleabeauchamp** [comment]
I suspect this will be fixed by the next arviz release?  Anyone know for sure?

**Comment by kyleabeauchamp** [comment]
I think this is the arviz PR that needs to be present for pymc3 <> arviz coords behavor to work: https://github.com/arviz-devs/arviz/pull/1228

**Comment by kyleabeauchamp** [comment]
I've added to this PR a version bump on Arviz that ensures the correct version in the pymc3 requirements.  This is ready for review and merge.  The only test failure is an unrelated failure on text_matrix_multiply.

**Comment by lucianopaz** [comment]
Pinging @michaelosthege as it would be great to bump the bug fix version of pymc3 (move it to 3.9.2) to ensure an upgrade of pymc3 will also upgrade to the proper arviz version.

**Review by michaelosthege — APPROVED** [review]

**Review by AlexAndorra — APPROVED** [review]

**Pull request merged**
