### PR TITLE
Add additional parameterizations to continous distributions 

### PR DESCRIPTION
**Pull request by 7ayushgupta**
Builds upon #4600. I have added a mu and (alpha+beta) parameterization to the Beta distribution following [this](https://en.wikipedia.org/wiki/Beta_distribution#Alternative_parametrizations). 
The other feature requested in the issue is for the scaled inverse chi-squared distribution. Need some clarity on the way to implement it - hence the PR is a WIP.

### CODE REVIEW

**Comment by ricardoV94** [comment]
Thanks for opening this PR!

Unfortunately, right now master is frozen in terms of new features. After merging V4 which is being tracked in #4500 we can start working on new functionalities.

Note that a lot of the logic about how distributions work has changed and the code in this PR won't match with those changes. 

I recommend either waiting until v4 is merged and / or start refactoring the new code to be "mergeable" with V4 either as it stands now or in the near future.

We would also need tests for the new parametrizations. You can check the `check_logp` tests in `test_distributions.py` where there are some examples of tests for alternative parametrizations of other distributions.

**Comment by ricardoV94** [comment]
Even more important perhaps, is whether this alternative parametrization is needed often enough to warrant implementing it...

**Comment by 7ayushgupta** [comment]
Right, I think this parameterisation would help in parameter estimation in experiments where one administers a test to a number of individuals. That said, I am not really sure of how many individuals do actually need this, since the most common way of introducing the beta distribution is using the shape parameterization itself. 
Someone with more experience in Bayesian modelling can guide better.

**Comment by twiecki** [comment]
I think this would need to be refactored for the new distributions.

**Pull request closed without merging**
