### PR TITLE
replaced all imports of tqdm with tqdm.auto

### PR DESCRIPTION
**Pull request by vnherdeiro**
Prototyping a pymc3 model inside a Jupyter notebook the tqdm progress bars can get ugly or buggy. There is a version of these progress bars tailored for notebooks and addressing these issues. The imports are now aware of the environment and load the appropriate ones.

### CODE REVIEW

**Comment by twiecki** [comment]
Needs a line in the release notes. Also, can you post a screenshot of what this now looks like for single and parallel sampling?

**Comment by vnherdeiro** [comment]
@twiecki Screenshots for single and parallel sampling, respectively:

Screenshot 2019-06-26 at 11 55 14

Screenshot 2019-06-26 at 11 51 25

About the release note: not sure what to add.

**Comment by twiecki** [comment]
Under new features write: `* Make use of new tqdm auto mode which improves progress bars in jupyter notebooks" or something along those lines.

**Comment by vnherdeiro** [comment]
Went for:

 - Makes use of new `tqdm` auto import mode which adapts the progress bars to console or jupyter notebook environments.

**Comment by ericmjl** [comment]
@twiecki, I'm going to hit merge, this is small enough that I'm confident it won't break anything :smile:

**Comment by vnherdeiro** [comment]
Can I get a PyMC3 laptop sticker for this contribution?

ps: shamelessly sorry for bumping this..!

**Comment by ColCarroll** [comment]
Totally. Send an address to colcarroll at gmail.

**Pull request merged**
