### PR TITLE
Fix the documentation on Weibull distribution

### PR DESCRIPTION
**Pull request by chang111**
fix the issue [3432](https://github.com/pymc-devs/pymc3/issues/3432)
previous:
\beta^2\Gamma(1+2/\alpha-\mu^2)
now:
\beta^2(\Gamma(1+2/\alpha)-\mu^2/\beta^2)

### CODE REVIEW

**Comment by chang111** [comment]
@twiecki All the check has passed. Please review it.

**Review by lucianopaz — APPROVED** [review]

**Comment by lucianopaz** [comment]
Thanks!

**Comment by aakhmetz** [comment]
@chang111 Sorry, I just check it, and apparently two brackets were forgotten :(

It should be:
```Variance  :math:`\beta^2(\Gamma(1 + \frac{2}{\alpha}) - \mu^2/\beta^2)```

**Comment by chang111** [comment]
@aakhmetz Fine, I will repush one

**Pull request merged**
