### PR TITLE
Rugby Analytics commit

### PR DESCRIPTION
**Pull request by springcoil**
Second rugby analytics commit

### CODE REVIEW

**Comment by jsalvatier** [comment]
Cool! Thanks :) 

A few comments. 

You don't need the first `model = pm3.Model()` since you already use the `with` statement.
I would fit a slightly different model. I don't think you need to de-mean atts and defs. Or maybe I'm misunderstanding why you've done that.

Also, you don't seem to be using `away_theta`?

```
with pm3.Model() as model:
    # global model parameters
    home        = pm3.Normal('home',      0, .0001)
    tau_att     = pm3.Gamma('tau_att',   .1, .1)
    tau_def     = pm3.Gamma('tau_def',   .1, .1)
    intercept   = pm3.Normal('intercept', 0, .0001)

    # team-specific model parameters

    atts   = pm3.Normal("atts", 
                           mu   =0,
                           tau  =tau_att, 
                           shape=num_teams)

    home = pm3.Normal("mean_defs", 0, .0001)
    defs   = pm3.Normal("defs", 
                           mu   =home,
                           tau  =tau_def,  
                           shape=num_teams) 

    home_theta  = tt.exp(intercept + atts[away_team] + defs[home_team])

    # likelihood of observed data
    home_points = pm3.Poisson('home_points', mu=home_theta, observed=observed_home_goals)
```

**Comment by springcoil** [comment]
The demeaning was necessary when reproducing the paper. It might be just a
hack though.

On Wednesday, 17 June 2015, John Salvatier notifications@github.com wrote:

> Cool! Thanks :)
> 
> A few comments.
> 
> You don't need the first model = pm3.Model() since you already use the
> with statement.
> I would fit a slightly different model. I don't think you need to de-mean
> atts and defs. Or maybe I'm misunderstanding why you've done that.
> 
> Also, you don't seem to be using away_theta?
> 
> with pm3.Model() as model:
>     # global model parameters
>     home        = pm3.Normal('home',      0, .0001)
>     tau_att     = pm3.Gamma('tau_att',   .1, .1)
>     tau_def     = pm3.Gamma('tau_def',   .1, .1)
>     intercept   = pm3.Normal('intercept', 0, .0001)
> 
> ```
> # team-specific model parameters
> 
> atts   = pm3.Normal("atts",
>                        mu   =0,
>                        tau  =tau_att,
>                        shape=num_teams)
> 
> home = pm3.Normal("mean_defs", 0, .0001)
> defs   = pm3.Normal("defs",
>                        mu   =home,
>                        tau  =tau_def,
>                        shape=num_teams)
> 
> home_theta  = tt.exp(intercept + atts[away_team] + defs[home_team])
> 
> # likelihood of observed data
> home_points = pm3.Poisson('home_points', mu=home_theta, observed=observed_home_goals)
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/764#issuecomment-112959077.

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
The away theta should be used but maybe I deleted it. I will look tomorrow

On Wednesday, 17 June 2015, Peadar Coyle peadarcoyle@googlemail.com wrote:

> The demeaning was necessary when reproducing the paper. It might be just a
> hack though.
> 
> On Wednesday, 17 June 2015, John Salvatier <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Cool! Thanks :)
> > 
> > A few comments.
> > 
> > You don't need the first model = pm3.Model() since you already use the
> > with statement.
> > I would fit a slightly different model. I don't think you need to de-mean
> > atts and defs. Or maybe I'm misunderstanding why you've done that.
> > 
> > Also, you don't seem to be using away_theta?
> > 
> > with pm3.Model() as model:
> >     # global model parameters
> >     home        = pm3.Normal('home',      0, .0001)
> >     tau_att     = pm3.Gamma('tau_att',   .1, .1)
> >     tau_def     = pm3.Gamma('tau_def',   .1, .1)
> >     intercept   = pm3.Normal('intercept', 0, .0001)
> > 
> > ```
> > # team-specific model parameters
> > 
> > atts   = pm3.Normal("atts",
> >                        mu   =0,
> >                        tau  =tau_att,
> >                        shape=num_teams)
> > 
> > home = pm3.Normal("mean_defs", 0, .0001)
> > defs   = pm3.Normal("defs",
> >                        mu   =home,
> >                        tau  =tau_def,
> >                        shape=num_teams)
> > 
> > home_theta  = tt.exp(intercept + atts[away_team] + defs[home_team])
> > 
> > # likelihood of observed data
> > home_points = pm3.Poisson('home_points', mu=home_theta, observed=observed_home_goals)
> > ```
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pymc-devs/pymc3/pull/764#issuecomment-112959077.
> 
> ## 
> 
> Peadar Coyle
> Skype: springcoilarch
> www.twitter.com/springcoil
> peadarcoyle.wordpress.com

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by jsalvatier** [comment]
Ah, gotcha, its reproducing a paper. That makes a lot of sense. Maybe add a
comment that you might not want to do that.

**Comment by springcoil** [comment]
I will add a comment.
Something about the mean of teams affected the results. I forget the
details.

I will flesh it out :)

On Wednesday, 17 June 2015, John Salvatier notifications@github.com wrote:

> Ah, gotcha, its reproducing a paper. That makes a lot of sense. Maybe add a
> comment that you might not want to do that.
> 
> On Wed, Jun 17, 2015 at 2:46 PM, springcoil <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > The demeaning was necessary when reproducing the paper. It might be just
> > a
> > hack though.
> > 
> > On Wednesday, 17 June 2015, John Salvatier <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > Cool! Thanks :)
> > > 
> > > A few comments.
> > > 
> > > You don't need the first model = pm3.Model() since you already use the
> > > with statement.
> > > I would fit a slightly different model. I don't think you need to
> > > de-mean
> > > atts and defs. Or maybe I'm misunderstanding why you've done that.
> > > 
> > > Also, you don't seem to be using away_theta?
> > > 
> > > with pm3.Model() as model:
> > > 
> > > # global model parameters
> > > 
> > > home = pm3.Normal('home', 0, .0001)
> > > tau_att = pm3.Gamma('tau_att', .1, .1)
> > > tau_def = pm3.Gamma('tau_def', .1, .1)
> > > intercept = pm3.Normal('intercept', 0, .0001)
> > > 
> > > # team-specific model parameters
> > > 
> > > atts = pm3.Normal("atts",
> > > mu =0,
> > > tau =tau_att,
> > > shape=num_teams)
> > > 
> > > home = pm3.Normal("mean_defs", 0, .0001)
> > > defs = pm3.Normal("defs",
> > > mu =home,
> > > tau =tau_def,
> > > shape=num_teams)
> > > 
> > > home_theta = tt.exp(intercept + atts[away_team] + defs[home_team])
> > > 
> > > # likelihood of observed data
> > > 
> > > home_points = pm3.Poisson('home_points', mu=home_theta,
> > > observed=observed_home_goals)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/pymc-devs/pymc3/pull/764#issuecomment-112959077.
> > 
> > ## 
> > 
> > Peadar Coyle
> > Skype: springcoilarch
> > www.twitter.com/springcoil
> > peadarcoyle.wordpress.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/pymc-devs/pymc3/pull/764#issuecomment-112960618.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/764#issuecomment-112960919.

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
I know this is still on me, but I've been busy lately. I'll get back to it soon

**Comment by springcoil** [comment]
I made some updates based on what you said John. I think it should be ready to be merged soon. Let me know if you need any other documentation.

**Comment by springcoil** [comment]
It passed the checks and the documentation is ready. Can someone like @jsalvatier or @twiecki merge this?

**Comment by twiecki** [comment]
Thanks! Isn't there more description in PP for hackers or a blog post we could include here? Would make the example much stronger.

**Comment by springcoil** [comment]
Hey Thomas,
Yeah sure - I'll dive into my blog posts and turn the .py file into
something with more substance.

I agree the example could be made much stronger

ᐧ

On Fri, Aug 14, 2015 at 8:30 AM, Thomas Wiecki notifications@github.com
wrote:

> Thanks! Isn't there more description in PP for hackers or a blog post we
> could include here? Would make the example much stronger.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/764#issuecomment-130990261.

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by twiecki** [comment]
We probably don't even need the .py file, just the ipython NB which we could then convert to a .py.

**Comment by springcoil** [comment]
I updated the IPython notebook, I thought I correctly used rebase,
however it seems I haven't I'll need to squash these commits. 
I used git fetch upstream and git rebase -i origin master

**Comment by springcoil** [comment]
Anyone have any idea why this build is failing?

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/issues/803

**Comment by twiecki** [comment]
But also, something seems to have gone wrong with the rebase.

```
git checkout mybranch
git rebase master
git push -f origin mybranch
```

**Comment by springcoil** [comment]
Opening a new branch :)

**Comment by springcoil** [comment]
This is a lot of commits - can anyone advise me on how to properly rebase this?

**Comment by springcoil** [comment]
Hmm I tried rebasing etc and it didn't work...

**Comment by kyleam** [comment]
> Hmm I tried rebasing etc and it didn't work...

It seems like things got into a pretty messy state.  I've pushed what (I
think) was the intended state to km/rubgy-fix.

So I'd suggest you
- Back up your local rugby_analytics branch from #807 to another branch.
- Fetch from the pymc3 repo.
- With rugby_analytics as your current branch, reset it to the new
  branch I pushed.
  
  git reset --hard <pymc3-remote>/km/rubgy-fix
- Re-run the notebook and update the commit with 'git commit --amend'.
- Force push to the pymc3 repo.  This will update PR #807.

**Comment by kyleam** [comment]
Doh, please look under the folded text for my last comment.  GitHub thinks the rest of my email is my signature.

**Pull request closed without merging**
