### PR TITLE
Add test_quadpotential.py in the test suite

### LINKED ISSUE #3748: `test_quadpotential.py` Should be added to test suite
Discovered this while isolating NUTS into its own library.

In our [`.travis.yml`](https://github.com/pymc-devs/pymc3/blob/master/.travis.yml), it appears that we don't run the tests in [`test_quadpotential.py`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_quadpotential.py). We should add this to the test runs.

### PR DESCRIPTION
**Pull request by rushabh-v**
Fixes: #3748

### CODE REVIEW

**Comment by rushabh-v** [comment]
build is failing here https://travis-ci.org/pymc-devs/pymc3/jobs/639075878#L2867
Is that something related to this PR?

**Comment by rpgoldman** [comment]
@rushabh-v That travis failure is not your fault.  Something in pytest is causing `test_fit_oo[ADVI-full]` to fail.  If that's the only failure you see, then you should treat the tests as passing.

**Comment by rushabh-v** [comment]
Thanks for responding :)
Yes, that's the only failure I am seeing. Can you review this PR please?

**Comment by lucianopaz** [comment]
This looks fine. Thanks @rushabh-v! I hadn't seen #3748 when it was opened but I just want to point out that the tests in test_quadpotential.py were being executed in the environments 1 and 5 because test_quadpotential.py wasn't in the ignored list. I think it's clearer to have the tests explicitly included in an environment so I'm in favor of merging this as is, but @eigenfoo, in #3748, did you mean that something else wasn't being tested?

**Review by eigenfoo — APPROVED** [review]
@lucianopaz no, just my ignorance of how a `.travis.yml` configured our tests! I'm also in favor of merging this as is.

**Comment by eigenfoo** [comment]
Thanks for the fix @rushabh-v and congrats on your first contribution to PyMC3! 😄

**Pull request merged**
