### PR TITLE
Fix: Change determinant in Wishart log probability.

### PR DESCRIPTION
**Pull request by kiudee**
The PDF of the Wishart distribution is given by:
255ae736aa2bdc387ed3134453a4cb9d

In the current code both determinants are calculated for the matrix V, but the one in the numerator should be the determinant of matrix X.

### CODE REVIEW

**Comment by kiudee** [comment]
I am currently trying to fix the Wishart distribution and have been stumbling over more parts of the code which look wrong.
- `multigammaln(a, p)` is called with the arguments swapped -> `multigammaln(p, n/2))`
- The implementation of `multigammaln(a, p)` does not match the result of other implementations:

``` python
import scipy
scipy.special.multigammaln(2, 3), pm.distributions.special.multigammaln(2, 3).eval()
=> (1.5963125911388552, array(2.694924881149894))
```

This code returns the correct value:

``` python
def multigammaln(a, p):
    """Multivariate Log Gamma

    :Parameters:
        a : tensor like
        p : int degrees of freedom
            p > 0
    """
    i = arange(1, p + 1)

    return p * (p - 1) * log(pi) / 4. + t.sum(gammaln(a + (1. - i) / 2), axis=0)
```

Please correct me if I missed something.

**Comment by twiecki** [comment]
@kiudee Just making sure that this one is still relevant and not superseded by the other one?

**Comment by kiudee** [comment]
The changes in this branch fix parts which are wrong with high probability (determinant of wrong matrix, wrong order of parameters).
So they should be save to merge, but since the Wishart distribution in its current state does not produce correct results, more work needs to be done.

As soon as we have a working version of the LKJ distribution, I will try to find the problem.

**Comment by twiecki** [comment]
OK, I'm merging this then as it's an improvement over the status quo. Thanks!

**Pull request merged**
