### PR TITLE
Fix bug in pseudo_likelihood computation

### PR DESCRIPTION
**Pull request by aloctavodia**
log_pseudolikelihood computations were wrong as the indexes were not properly resampled.

### CODE REVIEW

**Comment by ricardoV94** [comment]
Should we add a test?

**Comment by aloctavodia** [comment]
I do not have a very good test for checking that the pseudo_likelihoods values are good, I am not sure about which distribution they should follow.  I could check something like the variance is not too big.

**Comment by aloctavodia** [comment]
@ricardoV94 what do you think of the test I added?

**Review by junpenglao — APPROVED** [review]

**Comment by ricardoV94** [comment]
It's not obvious for me what the test actually does. Would it have failed before the new patch?

**Comment by aloctavodia** [comment]
Yes, it would have failed as the pseudo-likelihood values would have had a wider distribution.

**Review by ricardoV94 — APPROVED** [review]
I see, LGTM

**Pull request merged**
