### PR TITLE
Update survival_analysis.ipynb

### PR DESCRIPTION
**Pull request by olgadk7**
Fixes typos in the survival_analysis notebook as per issue #4603, including typos in column names of the example df.

### CODE REVIEW

**Comment by ricardoV94** [comment]
Thanks @olgadk7, the changes look good.

@OriolAbril can a PR be accepted here instead of in the pymc-examples repo?

**Comment by OriolAbril** [comment]
It should go in https://github.com/pymc-devs/pymc-examples indeed, sorry about the confusion @olgadk7 the collection of example notebooks reached a tipping point a while ago so we moved them to their own repo. You'll see that the `notebooks` folder doesn't exist anymore in this repo and this PR says "This branch has conflicts that must be resolved"

**Comment by michaelosthege** [comment]
> It should go in https://github.com/pymc-devs/pymc-examples indeed, sorry about the confusion @olgadk7 the collection of example notebooks reached a tipping point a while ago so we moved them to their own repo. You'll see that the `notebooks` folder doesn't exist anymore in this repo and this PR says "This branch has conflicts that must be resolved"

Git submodules are confusing for many (including me). For that reason I would even vote to remove the submodule. We can realize the docs build without it and for anybody who want to fetch/clone the notebooks, https://github.com/pymc-devs/pymc-examples is easier to work with anyway. (cc @MarcoGorelli @ColCarroll )

**Comment by MarcoGorelli** [comment]
@michaelosthege you can still fetch/clone the notebooks as before, whether the submodule is there or not, you can do `git clone git@github.com:pymc-devs/pymc-examples.git` in a separate directory and work in there if you prefer

**Comment by MarcoGorelli** [comment]
> @OriolAbril can a PR be accepted here instead of in the pymc-examples repo?

I'm pretty sure that's impossible, though would happily be proven wrong :)

**Comment by ricardoV94** [comment]
@olgadk7 Sorry for the confusion. In case it wasn't clear from the comments above, this PR should be closed and opened instead on the pymc-examples repository where our notebooks live now: https://github.com/pymc-devs/pymc-examples (assuming the typos can still be found in the latest version over there).

Let us know if you have any questions!

**Comment by olgadk7** [comment]
Got it, thanks. Closing it here and reopening on pymc-examples.

**Pull request closed without merging**
