### PR TITLE
DOC Fixes to rolling regression

### PR DESCRIPTION
**Pull request by twiecki**
Do not chunk by time, increase tune, accept_prob and max_tree_depth to not have divergent samples.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
This looks much better, thanks.

**Comment by junpenglao** [comment]
Under 
## Analysis result
I dont think it is still true to say "$\alpha$, the intercept, does not seem to change over time."

**Comment by twiecki** [comment]
@junpenglao good catch. I'll fix this up further.

**Comment by junpenglao** [comment]
Also, the part below is changed as well right? As you are no longer doing bins (I kind of like the binning idea)?
> Next, we define the regression parameters that are not a single random variable but rather a random vector with the above stated dependence structure. So as not to fit a coefficient to a single data point, we will chunk the data into bins of 50 and apply the same coefficients to all data points in a single bin.

**Comment by etyurin** [comment]
I like how it looks more "natural" - no longer stacking alpha/beta on repeat. The price for that is re-evaluation at every data-point. Is it possible to keep this new model description, but maybe force updating to be almost trivial for 98-99% of the datapoints (as if binning every 50-100 points)?

Also, what does pm.sample( samples=200) do? I only found this as an options to pm.sample_ppc().

**Comment by twiecki** [comment]
OK, I did some more fixing, good from my end.

**Comment by junpenglao** [comment]
Thanks @twiecki!

**Pull request merged**
