### PR TITLE
ENH: Adding an exception to loo

### PR DESCRIPTION
**Pull request by springcoil**
I added a simple exception based on the paper by Vehtari et al and my own experience of trying this on an ill-posed model.

### CODE REVIEW

**Comment by springcoil** [comment]
@fonnesbeck do you see any problems with this?

**Comment by fonnesbeck** [comment]
We already have a similar exception raised just above this, which actually gets triggered at a lower threshold. Not opposed to changing the threshold in order to conform to the current literature, but we don't need two exceptions for the same parameter, I think.

**Comment by springcoil** [comment]
Yeah I know there is a similar threshold, however I consider these two different things. One is a warning, and one is an exception. These are two different things :)

**Comment by fonnesbeck** [comment]
Fair enough. The only change I would make is to check for the exception condition first, so that you only ever get one message at most -- the exception or the warning.

**Comment by springcoil** [comment]
Ok cool :) Note for posterity - Resolves #1363

**Comment by springcoil** [comment]
Since this is reviewed already and I'm impatient I'll merge this.

**Pull request merged**
