### PR TITLE
Remove MultinomialRV override

### LINKED ISSUE #5560: Remove `MultinomialRV` override
The current [`MultinomialRV`](https://github.com/pymc-devs/pymc/blob/620546b77f035623b50a5602b530f7ad2413a682/pymc/distributions/multivariate.py#L485) overrides the one from Aesara.
According to the docstring It was implemented 1 year ago, because the Aesara one doesn't broadcast.

@ricardoV94 can we remove the override now?

### PR DESCRIPTION
**Pull request by danhphan**
This PR closes #5560 

I just remove the [`MultinomialRV`](https://github.com/pymc-devs/pymc/blob/8b063f9c3b344753acdf91416cf2bb3c4533f80a/pymc/distributions/multivariate.py#L487) class, and instead use the `multinomial` directly from aesara. Thanks

### CODE REVIEW

**Comment by danhphan** [comment]
From CI tests, 2 tests failed at `pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial`. Something related to `aeppl.logprob.ParameterValueError`

But, when I run this test at my local computer, It passed. 

```
$pytest  pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.9.10, pytest-7.1.0, pluggy-1.0.0
rootdir: /home/danph/Repos/win_ssd/oss/pymc, configfile: pyproject.toml
plugins: anyio-3.5.0, cov-3.0.0
collected 2 items                                                                                                                                                                                 

pymc/tests/test_mixture.py ..                                                                                                                                                               [100%]
.............
================================================================================= 2 passed, 2 warnings in 11.21s ==================================================================================
```
I am trying to reproduce the errors using the similar config of `pymc-test-py37` in `environment-test-py37.yml`:
```
Run conda activate pymc-test-py37
  conda activate pymc-test-py37
  python -m pytest -vv --cov=pymc --cov-append --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
  shell: /bin/bash -l {0}
  env:
    TEST_SUBSET: pymc/tests/test_modelcontext.py
  ...
  pymc/tests/test_mixture.py
============================= test session starts ==============================
platform linux -- Python 3.7.1
rootdir: /home/runner/work/pymc/pymc, configfile: pyproject.toml
plugins: cov-3.0.0
```

**Comment by danhphan** [comment]
Hi @ricardoV94 

When running similar config of `pymc-test-py37` in `environment-test-py37.yml` on my local machine (ubuntu 18.04). The tests failed at:

- **run all tests**
```
$pytest --cov=pymc pymc/tests 
FAILED pymc/tests/test_distributions.py::TestMatchesScipy::test_multinomial_vectorized[extra_size2-p1-10] - aeppl.logprob.ParameterValueError
FAILED pymc/tests/test_distributions.py::TestMatchesScipy::test_multinomial_vectorized[extra_size2-p1-n1] - aeppl.logprob.ParameterValueError
..........
FAILED pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial[(3, 4)] - aeppl.logprob.ParameterValueError
FAILED pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial[(20,)] - aeppl.logprob.ParameterValueError
```

But when I try to debug each test method `test_distributions.py::TestMatchesScipy::test_multinomial_vectorized`, or `test_mixture.py::TestMixtureSameFamily::test_with_multinomial`: they work fine.

- **run or debug only this test**
```
$pytest --cov=pymc pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial
==================== 2 passed, 2 warnings in 19.10s ==========================
```


Any suggestion? Thanks!

**Comment by ricardoV94** [comment]
First thing to check is if the tests are deterministic or have something random in them.

**Comment by danhphan** [comment]
Hi, can you be more specific?

Do you mean the random in `np.random`? For example, the following line of codes is used in [`test_with_multinomial`](https://github.com/pymc-devs/pymc/blob/7a6bd027ec827ee45056cfbe04b51b75643d2d19/pymc/tests/test_mixture.py#L957): 

`p = np.random.uniform(size=(*batch_shape, self.mixture_comps, 3))`

Thank you :)

**Comment by ricardoV94** [comment]
> Hi, can you be more specific?
> 
> Do you mean the random in `np.random`? For example, the following line of codes is used in [`test_with_multinomial`](https://github.com/pymc-devs/pymc/blob/7a6bd027ec827ee45056cfbe04b51b75643d2d19/pymc/tests/test_mixture.py#L957):
> 
> `p = np.random.uniform(size=(*batch_shape, self.mixture_comps, 3))`
> 
> Thank you :)

Yes, so the question is if you rerun the test multiple times locally, how often does it fail? Since you are seeing failures in some places but not others, it might be due to that or another source of randomness. Once you understand the source of such failing (perhaps values are incorrect or too extreme), we can fix it by being more clever about how we create values. Or if the randomness is not important, we can just fix the values (using seeding). This process may also uncover a bug that needs to be solved.

So the first step, is to understand if the tests fail due to randomness (and not differences between your local machine and github), and why is it failing in those cases.

**Comment by danhphan** [comment]
Hi @ricardoV94 , maybe what I have described is not clear.

What I means here is that I not sure what is the different when `run all test` vs. `run one test` (`TestMixtureSameFamily::test_with_multinomial`). When you have time, please checkout this commit and run these two following commands, to see what I mean :) 

- **run only this test**
```
$pytest --cov=pymc pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial
==================== 2 passed, 2 warnings in 19.10s ==========================
```

- **run all tests**
```
$pytest --cov=pymc pymc/tests 
..........
FAILED pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial[(3, 4)] - aeppl.logprob.ParameterValueError
FAILED pymc/tests/test_mixture.py::TestMixtureSameFamily::test_with_multinomial[(20,)] - aeppl.logprob.ParameterValueError
```

For the later, when run all tests, my problem is that I do not know how to catch the bug :(

**Comment by ricardoV94** [comment]
My suspicion is that if you run the individual test a couple of times it will also fail sometimes.

**Comment by danhphan** [comment]
Hi, I just run the individual test more than 10 times and it still fine :D

**Comment by danhphan** [comment]
FYI, I will re-run these tests this week, since the new Aesara version has just been updated on #5672

Thanks.

**Comment by danhphan** [comment]
hi @ricardoV94, it seems that all tests pass with the new Aesara upgrade, but not sure why test coverage decreases a lot :(

**Comment by ricardoV94** [comment]
@danhphan the coverage is sometimes flaky / lagging behind. Changes look good!

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Thanks for your help!

**Comment by danhphan** [comment]
Thanks mate :)

**Pull request merged**
