### PR TITLE
support multidimensional arrays in forestplot

### PR DESCRIPTION
**Pull request by aplavin**

### CODE REVIEW

**Comment by junpenglao** [comment]
Thanks @aplavin, it works locally for the forestplot but the I got an error on the rhat plot. Code below:

```python
import pymc3 as pm
import numpy as np
import scipy.stats as stats
import theano.tensor as tt

Nd = 3
N = 200

K = np.array([[  3.40, -2.75, -2.00],
              [ -2.75,  5.50,  1.50],
              [ -2.00,  1.50,  1.25]])

latent = stats.multivariate_normal.rvs(np.zeros(Nd), K, size=N)

with pm.Model() as model:
    mu = pm.Normal('mu', mu=0, sd=1, shape=Nd)
    
    sd_dist = pm.HalfCauchy.dist(beta=2.5)
    packed_chol = pm.LKJCholeskyCov('chol_cov', n=Nd, eta=1, sd_dist=sd_dist)
    # compute the covariance matrix
    chol = pm.expand_packed_triangular(Nd, packed_chol, lower=True)
    cov = pm.Deterministic('cov', tt.dot(chol, chol.T))
    
    yobs = pm.MvNormal('yobs', mu=mu, chol=chol, observed=latent)
    trace = pm.sample(2000, njobs=4)
pm.forestplot(trace)
```
```python
Traceback (most recent call last):

  File "<ipython-input-18-e9c23f0fa358>", line 27, in <module>
    pm.forestplot(trace)

  File "/home/laoj/Documents/Github/pymc3/pymc3/plots/forestplot.py", line 327, in forestplot
    varnames, plot_transformed)

  File "/home/laoj/Documents/Github/pymc3/pymc3/plots/forestplot.py", line 67, in _make_rhat_plot
    ax.plot([min(r, 2) for r in R[varname]],

  File "/home/laoj/Documents/Github/pymc3/pymc3/plots/forestplot.py", line 67, in <listcomp>
    ax.plot([min(r, 2) for r in R[varname]],

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Also, could you please add a test?

**Comment by ericmjl** [comment]
ping @aplavin, keeping this alive.

**Comment by aplavin** [comment]
Guys, sorry for not responding, but not having enough time to deal with it now. I made this simple fix locally long ago as I routinely have 2d vars and thought it should fit as-is here, but I don't use rhat plot so have no idea how to fix it.

**Comment by ericmjl** [comment]
all good, @aplavin, totally understand :-)

ping @junpenglao close or keep open?

**Comment by junpenglao** [comment]
I will fix it no problem ;-) Thanks for the contribution @aplavin

**Pull request merged**
