### PR TITLE
add densityplot

### PR DESCRIPTION
**Pull request by aloctavodia**
In the same _spirit_ of #2736 a `densityplot` can be used to compare several traces/models (and also works for a single trace/model). 

index

The KDE plots are truncated at their HPD interval, a point estimate (the mean by default) is represented using... a point. Each group of variables share the same scale (like in a traceplot and unlike a forestplot). At some point I though about implementing a ridgeline plot (AKA joyplot) but I am still not connived that those plots add too much value except for their coolness and fanciness.

Let me know if you think this could be a good addition to the PyMC3 plots, suggestions for alternative names are also welcomed.

### CODE REVIEW

**Comment by springcoil** [comment]
I think it adds something. Not sure about the name though

**Comment by aloctavodia** [comment]
Thanks for the feedback @springcoil, just to add perspective the previous name was `aplot` :-)

**Comment by springcoil** [comment]
Maybe Density plot is fine. Compared to aplot. I'd add that to the release
notes

**Comment by ColCarroll** [comment]
Thanks for including the sample! Can you show a snippet of code that would produce that?  I am wondering in particular what `m_0, m_1, m_2` are (and why the legend appears in only one figure).

**Comment by aloctavodia** [comment]
Hi @ColCarroll 

You will have to do: `pm.densityplot(traces)` to get that plot where `traces` is a list of traces (3 in this case). `m_0, m_1, m_2` are the names of the 3 models/traces, these names are assigned automatically (the same with the colors) unless the user provides custom values. The legend appear only once to avoid redundancy/cluttering, you are comparing 3 models across all panels (variables), even when a model could not have all variables, like `m_0` in this example that is missing the beta parameter.

This PR also adds a very simple usage example to an existing notebook of the `pm.densityplot` (and of the new `forestplot`)

**Comment by aloctavodia** [comment]
Still not happy with this plot, another two options to help see the limits of the distributions

density_plot_03

density_plot_02

**Comment by springcoil** [comment]
I like this last one. Do you think it's worth merging now, and iterating on it in the future.

**Comment by aloctavodia** [comment]
Hi @springcoil, I need to commit the code for the last two figures and I should add a test. I could do it tomorrow.

I guess we don't need to choose between these 3 variations, they can be offered as different options, but which one should be the default one? The last one?

@ColCarroll what do you think?

**Comment by springcoil** [comment]
Yeah a test would help. I think having three options is good, I think the last one should be the default one.

**Comment by aloctavodia** [comment]
@springcoil thanks for the feedback! I will work on this.

**Comment by ColCarroll** [comment]
Probably helpful to mimic the api of https://seaborn.pydata.org/examples/distplot_options.html , since it will be known to users already.  In particular, they pass in `kde_kwargs` to allow `shade=True` or `shade=False`.  Agree that the last one should probably be default -- it would be very tricky to set the `alpha` automatically for lots of densities to make them all visible.

Also agree that we can iterate on some of this after merging, so it isn't all on you!

**Comment by springcoil** [comment]
Yeah I think shipping this, and then people experimenting with it will mean that the load isn't all on you.

**Comment by aloctavodia** [comment]
Following your suggestions, @springcoil and @ColCarroll,  I update the code and set a different default style. I changed the name of argument `opacity` to `shade` for internal consistency (this is the name we use for `energyplot` and `kdeplot`). BTW we use a float for the shade instead of a `boolean`, in that way we can avoid having one argument to turn on/off the shade and another one to set the alpha-level.

**Comment by springcoil** [comment]
LGTM :)

**Pull request merged**
