### PR TITLE
[WIP]Add Dirichlet Mixture model

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by twiecki** [comment]
This is not a Dirichlet Mixture model. @souravsingh can you only open PRs when you feel comfortable with the code?

**Comment by souravsingh** [comment]
@twiecki I think I made a mistake while understanding the Dirichlet Mixture model example code. I will correct it.

**Comment by souravsingh** [comment]
@twiecki Just to clarify, the Dirichlet Mixture model will have two classes, One inherits from Continuous and second inherits from the Mixture model, correct?

**Comment by twiecki** [comment]
@souravsingh I'm closing this in the mean-time. Feel free to reopen when you think its ready.

**Pull request closed without merging**
