### PR TITLE
Small compatibility fix for master of Theano-PyMc

### PR DESCRIPTION
**Pull request by semohr**
+ Import of pymc3 failed with the most recent master branch of Theano-PyMC 
+ I could nail down the problem to [this commit ](https://github.com/pymc-devs/Theano-PyMC/commit/f1016f7fec226f521f588936574dc59971fbf18a) on the Theano-PyMC GitHub
+ Changed the `__init__.py` to use the new config style

### CODE REVIEW

**Comment by twiecki** [comment]
We probably need a new Theano release and pin.

**Comment by twiecki** [comment]
CC @brandonwillard @dfm

**Comment by MarcoGorelli** [comment]
Maybe after this is fixed we also need a theano-pymc-compatibility CI job which installs the latest commit to master (similarly to the arviz-compatibility one)

**Comment by brandonwillard** [comment]
There is already an open [Theano-PyMC compatibility update PR](https://github.com/pymc-devs/pymc3/pull/4248) that's waiting for the next release of Theano-PyMC (the PR title is too specific to one of the updates, though).  All these updates are better off in a single PR corresponding to a single new release of Theano-PyMC.

The changes addressed in this PR were merged just last night, so they haven't been added to the existing PR, and the version of Theano-PyMC used by PyMC3 should already be pinned in this repo (from a commit merged a while back).  In other words, the relevant Theano-PyMC changes aren't an active issue, since one would need to install an explicitly unsupported version of Theano-PyMC for them to appear.

**Comment by semohr** [comment]
Sorry if I wasted your time here a bit. I just tried to get the new jax sampler working, I noticed this problem and found a easy fix for it.

Thought I should share this, since maybe someone else could have the same problem.

I'm not too sure how you want to handle such small fixes.
Feel free to delete this PR.

Best Sebastian

**Comment by brandonwillard** [comment]
If you want to take on these recent updates, you can pull in the changes from the existing PR and make this one the cumulative update PR.  There shouldn't be much in that PR, so you could probably just look at the diffs and apply them manually.

We simply need those changes in a single PR, because we can't merge them one at a time&mdash;at least not without temporarily putting the repo in a truly broken state.

Otherwise, did you install a development version of PyMC3 (e.g. `master`) and it pulled in the most recent Theano-PyMC?  If that's the case, we should probably find out why and fix it, because it implies that our pinned version is being ignored/circumvented.

**Comment by semohr** [comment]
I totally unterstand, will look into that.

Yes I installed the master branch. Tried the jax branch beforehand but that one also installed the master theano-pymc branch.

**Comment by brandonwillard** [comment]
> Tried the jax branch beforehand but that one also installed the master theano-pymc branch.

~Ah, that's probably it; if you're referring to the `pymc3jax` branch, it might need to be rebased onto `master` in order to get the commit that pinned Theano-PyMC (and some previous compatibility updates, as well).~

@twiecki, wasn't the `pymc3jax` merged?  If so, we might want to delete it; otherwise, people could accidently use it and run into problems.

**Comment by brandonwillard** [comment]
The updates in this PR will also close https://github.com/pymc-devs/Theano-PyMC/issues/216.

**Comment by brandonwillard** [comment]
This won't pass until https://github.com/conda-forge/theano-pymc-feedstock/pull/8 is merged and `theano-pymc==1.0.12` is made available via conda-forge.

**Comment by twiecki** [comment]
Merged now.

**Review by twiecki — APPROVED** [review]

**Pull request merged**
