### PR TITLE
ENH: Moyal distribution

### PR DESCRIPTION
**Pull request by fearghuskeeble**
I made a class for this distribution when I was working on my thesis.  The use may be a little niche but it's at least popular enough to have a [scipy class](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.moyal.html). I added documentation and testing for it so please add it if you would like.

Also included is a typo fix in the Student's T dist. documentation.

For reference the Moyal doc plot would look like this:
moyal_distribution

### CODE REVIEW

**Comment by twiecki** [comment]
Seems like travis is unhappy.

**Comment by fearghuskeeble** [comment]
Yes, I'd better check that one on docker because I don't get it locally.

**Comment by fearghuskeeble** [comment]
I believe this is ready now

**Comment by twiecki** [comment]
Thanks @fearghuskeeble!

**Pull request merged**
