### PR TITLE
Minor improvements to GitPod

### PR DESCRIPTION
**Pull request by maresb**
Update the dev container base image, and also run the initial Conda installs and pre-commit installs in the background.

**What is this PR about?**
...

**Checklist**
+ [X] Explain important implementation details 👆
+ [X] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- ...

## Bugfixes
- ...

## Documentation
- ...

## Maintenance
- Minor improvements to improve the GitPod experience

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by maresb** [comment]
Hmm, any idea why the tests are blocked?

**Comment by reshamas** [comment]
@Armavica may have an idea?

**Comment by Armavica** [comment]
I would say that it is because none of the files modified match any of the patterns listed here: https://github.com/pymc-devs/pymc/blob/main/.github/workflows/tests.yml#L4-L12

**Comment by maresb** [comment]
Ah, so we should adjust to make the tests conditionally required (if possible) or ensure required tests run regardless. For now, is there any admin who could override?

**Comment by ricardoV94** [comment]
> Ah, so we should adjust to make the tests conditionally required (if possible) or ensure required tests run regardless. For now, is there any admin who could override?

You mean to merge?

**Comment by maresb** [comment]
> You mean to merge?

Yes

**Comment by maresb** [comment]
Thanks @ricardoV94!

**Pull request merged**
