### PR TITLE
A second CO2 example for GPs

### PR DESCRIPTION
**Pull request by bwengals**
This example shows off more advanced modeling + features.  It also adds the `ScaledCov` covariance function.  The notebook shows how to several things which aren't documented well:

- Model inputs whose exact locations are uncertain (uncertainty in 'x')
- Design a semiparametric Gaussian process model
- Build a changepoint covariance function / kernel using `ScaledCov`
- Definine a custom mean and a custom covariance function

### CODE REVIEW

**Comment by twiecki** [comment]
This is incredible (and quite depressing)!

image

I would put dates on the x-axis.

image
This shows some convergence problems. Have you tried more tuning steps?

"But his isn't a changepoint covariance function yet" typo "his".

**Comment by junpenglao** [comment]
More informative/narrow prior for the length scale might help convergence.

**Comment by bwengals** [comment]
Thanks, good catches.  Yeah its pretty crazy...

**Comment by bwengals** [comment]
I think this could be merged.  I also split the GP tests into two files in this PR.

**Comment by fonnesbeck** [comment]
Make sure the axis labels are all there in the 2nd one. For some reason, in some of them the labels are missing even though the axis label code is there.

**Comment by springcoil** [comment]
Are there plans to publish this?

**Comment by twiecki** [comment]
image

First two plots seem to have index problems.

**Comment by twiecki** [comment]
Good to merge or still WIP?

**Comment by bwengals** [comment]
nope, good to merge I think

**Comment by springcoil** [comment]
Travis error should we be concerned?

**Comment by bwengals** [comment]
SMC test error, restarted the job

**Comment by bwengals** [comment]
passed this time

**Comment by twiecki** [comment]
This looks excellent!

**Comment by bwengals** [comment]
thanks! and thanks for finding the climate guy, i guess ill just merge it!

**Pull request merged**
