### PR TITLE
Fix NUTS scaling bounds #1581 

### LINKED ISSUE #1581: NUTS scaling issue regression
I have found an issue with one of my models that was sampling fast before but then kept stalling. I identified this commit to be the issue: https://github.com/pymc-devs/pymc3/commit/362c8eedd6e7622137203b2859f6f6ac518eae64

CC @fonnesbeck 

I'm still investigating which part of the PR introduced the problem.

### PR DESCRIPTION
**Pull request by twiecki**
Commit 362c8ee introduced a bug by switching the bounds of the scaling matrix. The bounds 1e-3 are also too stringent for some data types, like returns. This thus adjusts bounds to 1e-8 instead of 1e-3.

Closes #1581.

### CODE REVIEW

**Comment by twiecki** [comment]
Travis fails because of the regression tests that @ColCarroll added. @ColCarroll what's the best way to update these values?

**Comment by fonnesbeck** [comment]
Would be great to eventually set this value dynamically, but for now this makes sense.

**Comment by ColCarroll** [comment]
1. Make super sure you mean to change the sampled values :)
2. Add the line `print(repr(trace.get_values('x')))` to line 127 in [test_step.py](https://github.com/pymc-devs/pymc3/blob/master/pymc3/tests/test_step.py#L127)
3. Run the test again with the flag `-s`.  I'd use: 
```
./scripts/test.sh -sx pymc3/tests/test_step.py:TestStepMethods.test_sample_exact
```

4. Copy/paste the output of that back into the test.

**Review by springcoil — COMMENTED** [review]
LGTM

**Pull request merged**
