### PR TITLE
Gaussian process functions and classes

### PR DESCRIPTION
**Pull request by fonnesbeck**
Replaces `gp_classes` branch. Will eventually include a `GP` class, mean functions, and a function for drawing realizations from the GP after sampling.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Getting close, but the GP class returns biased estimates.

**Comment by fonnesbeck** [comment]
Have a peek at the interface. I have updated the GP-introduction notebook in this PR to use it. Predictive sampling now happens outside of MCMC sampling, using `sample_gp`, which uses the same API as `sample_ppc`. This seems to make sense to me, but would like to hear what others think.

/cc @bwengals

**Comment by twiecki** [comment]
API looks great! Would the new ESS work well here?

**Comment by bwengals** [comment]
This is awesome!  Yeah, this looks good to me.  Also, looks like NUTS and ADVI did well!  I had trouble getting those to work.  That is very cool.

**Comment by fonnesbeck** [comment]
@bwengals NUTS and ADVI did not work well on the second example -- ADVI kept getting nans.

**Comment by bwengals** [comment]
Oh, huh.  I wonder why.  Well I like the new GP class.

**Comment by fonnesbeck** [comment]
Using two-stage integration seemed to help quite a lot with the second example.

**Comment by fonnesbeck** [comment]
Need to write some tests and docs, and we should be good.

**Comment by fonnesbeck** [comment]
The remaining test failure does not make sense:

```
Traceback (most recent call last):
  File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_gp.py", line 151, in test_1d
    K = theano.function([], cov(X))()
  File "/home/travis/build/pymc-devs/pymc3/pymc3/gp/cov.py", line 249, in __call__
    return tt.power(Linear(self, X, Z) + self.offset, self.d)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/gp/cov.py", line 222, in __init__
    Covariance.__init__(self, input_dim, active_dims)
  File "/home/travis/build/pymc-devs/pymc3/pymc3/gp/cov.py", line 32, in __init__
    self.active_dims = np.arange(input_dim)
TypeError: unsupported operand type(s) for -: 'Polynomial' and 'int'
```

Appears to fail at `arange` but the `TypeError` is not from that call.

**Comment by twiecki** [comment]
can you pass integrator='two-stage' to sample() to still get ADVI init? We might need to improve the kwarg forwarding.

**Comment by fonnesbeck** [comment]
ADVI init kept failing with NaN errors, so I turned it off.

**Comment by fonnesbeck** [comment]
Unusual test failure only on 2.7. Is it a different version of Theano there?

**Comment by fonnesbeck** [comment]
This appears to pass now. I will add docs in a separate PR.

**Comment by twiecki** [comment]
This is great

**Comment by AustinRochford** [comment]
Yes, this is really exciting! I have an old talk on Bayesian optimization that I'm excited to port to `pymc3`

**Comment by fonnesbeck** [comment]
I'd be interested in seeing that!

**Pull request merged**
