### PR TITLE
Update case study to match blog post

### PR DESCRIPTION
**Pull request by thompsonjjet23**
Update case study example to match [blog post](https://austinrochford.com/posts/2021-05-29-horseshoe-pymc3.html)

----
:books: Documentation preview :books:: https://pymc--6930.org.readthedocs.build/en/6930/

### CODE REVIEW

**Comment by twiecki** [comment]
Don't you have to re-execute?

**Comment by thompsonjjet23** [comment]
> Don't you have to re-execute?

@twiecki  I was having trouble running this notebook when I tried to re-execute --

In cell 13: 

`test_scores = pd.read_csv(pm.get_data("test_scores.csv"), index_col=0)`
`test_scores.head()`

I get this error when trying to read the test scores data:

`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)>`

I tried googling around a bit but I'm not sure how to fix it , have you seen that error before?

**Comment by twiecki** [comment]
It sounds like the link has gotten stale.

**Comment by thompsonjjet23** [comment]
> It sounds like the link has gotten stale. Can you download from that link manually? Otherwise, can you find a new one and fix that?

Ah I'm sorry -- what link do you mean? I want to help but I'm not sure what you mean by "find a new one" ? Apologies to be a bother!

**Comment by thompsonjjet23** [comment]
@twiecki is there any chance that the mypy failure here could be related to https://github.com/pymc-devs/pymc/pull/6926 ? it's odd that it's complaining about `data.py` since I didn't modify that file in this PR?

**Comment by thompsonjjet23** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/pymc-devs/pymc/pull/6930/discussion/#comment-1737132545) on ReviewNB
> 
> _twiecki commented on 2023-09-27T10:29:48Z_ ----------------------------------------------------------------
> 
> This plot is missing.

fixed!

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks!

**Pull request merged**
