### PR TITLE
Add pickle test and revert theano var names (hopefully temporarily)

### PR DESCRIPTION
**Pull request by canyon289**
This commit does a couple of things per comments in https://github.com/pymc-devs/pymc3/issues/4112
1. Adding tests to cover this issue 
2. "Comment out" reverts changes in https://github.com/pymc-devs/pymc3/pull/4076

Proposed steps, pending successful CI, is that we merge this to fix broken SMC parallel capability and ArviZ pipelines, and then try reimplementing this feature in a way that doesn't break pickling of `pm.Deterministic`

### CODE REVIEW

**Comment by canyon289** [comment]
This is ready for review, I guess our code coverage tolerance is set pretty high hence the CI failure

**Comment by AlexAndorra** [comment]
Pinging @Spaak, as I did in the associated issue

**Comment by canyon289** [comment]
Sounds good, going to ask if we can merge in 24 hours if no strong objection is raised, as this right now put ArviZ at risk

**Comment by Spaak** [comment]
Thanks for the ping also here, and for the tests. The issue appears to be with the "type hacking" I added to Deterministic in order to force `str` override to work with non-class-based types, and thankfully not with the new string machinery in general. I'll file a PR for a more targeted fix in a few hours.

**Comment by MarcoGorelli** [comment]
@Spaak do you have a test which fails if you just do
```python
    var.__str__ = functools.partial(_repr_deterministic_rv, var, formatting='plain')
```
? For me, `TestStrAndLatexRepr` from `pymc3/tests/test_distributions.py` passes like this:
```
$ pytest pymc3/tests/test_distributions.py -k TestStrAndLatexRepr -q
...                                                                                                                                                                                                [100%]
============================================================================================ warnings summary ============================================================================================
pymc3/tests/test_distributions.py::TestStrAndLatexRepr::test__repr_latex_
  /home/marco/miniconda/envs/pymc3-dev/lib/python3.8/site-packages/theano/tensor/var.py:468: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    isinstance(args_el, collections.Iterable)):

pymc3/tests/test_distributions.py: 48 warnings
  /home/marco/pymc3-dev/pymc3/util.py:149: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
    return asscalar(value)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
3 passed, 144 deselected, 49 warnings in 2.52s
```

**Comment by Spaak** [comment]
> @Spaak do you have a test which fails if you just do
> 
> ```python
>     var.__str__ = functools.partial(_repr_deterministic_rv, var, formatting='plain')
> ```
> 
> ?

@MarcoGorelli Yes, I do now, see #4120 . Patching `__str__` like that on the fly was the first thing I tried, but unfortunately Python does not always use an instance's `obj.__str__()` when `str(obj)` is called, but instead does some other type of lookup, which is why I had to add the type-patching. See also https://stackoverflow.com/a/5918210/1692028

**Comment by canyon289** [comment]
Thanks @Spaak!!

**Pull request closed without merging**
