### PR TITLE
Refactor build

### PR DESCRIPTION
**Pull request by ColCarroll**
Factors out the steps from the travis build so they may be run locally, and reasoned about separately.  Getting set up and running tests should now be as easy as:

```
$ . ./scripts/install_miniconda.sh  # doesn't do anything if `conda` is already in the path
...
$ . ./scripts/create_testenv.sh  # sets up virtual environment
...
$ . ./scripts/test.sh -vv --with-timer -e test_examples  # for example
```

Travis build works as before.  This might also be a first step towards a CONTRIBUTING.md file.

### CODE REVIEW

**Comment by twiecki** [comment]
This is great, thanks!

**Comment by twiecki** [comment]
How do you mean "This might also be a first step towards a CONTRIBUTING.md file."?

**Comment by ColCarroll** [comment]
Was looking at contributing, and had trouble setting up a dev environment (mostly the problem was not using conda).  A short guide to installing, running tests, and submitting pull requests may help.  happy to help with that if it is wanted!

**Comment by twiecki** [comment]
Definitely, that'd be great.

**Comment by fonnesbeck** [comment]
Yes, thanks for this. I have added an issue for us to get guidelines for contributing added to the repository #1293

**Pull request merged**
