### PR TITLE
Fix to Source files don't contain Apache license #3738 

### PR DESCRIPTION
**Pull request by ac-optimus**
Hi,
I wrote a small script that transverses the directory(`pymc3`) and adds the licence to the top of each of the `.py` source file found using `sed`.

Thanks!

### CODE REVIEW

**Comment by ac-optimus** [comment]
oops! just saw someone did it.

**Review by eigenfoo — CHANGES_REQUESTED** [review]
This looks great @ac-optimus! And I only just noticed that there is a duplicated PR #3781 from @rushabh-v. I hate to have duplicated effort (and I _really_ hate having to decline a PR because of duplicated effort!), so it would be wise to decide who's going to take the lead on this, so that nobody's time is wasted.

Other than that, I have basically the same comment for both PRs , which I've just copy-pasted below for reference.

Unfortunately I think we shouldn't be licensing the documentation or the examples: a few of them are actually taken or adapted from other projects or resources and already provide relevant credits, and I'd prefer not to license them as our own code. (For instance, the baseball example is taken from the Stan user guide.)

So, to be explicit: the `.py` files under the `docs/` and `pymc3/examples/` directory should not have the license comments.

**Comment by rushabh-v** [comment]
> so it would be wise to decide who's going to take the lead on this, so that nobody's time is wasted.

@ac-optimus I have taken the lead. You may not wish to waste your time doing it.

**Comment by ac-optimus** [comment]
@rushabh-v sure no issues! But a small suggestion, please check before addressing a issue if someone who previously worked on it is currently not working on it. @eigenfoo I am closing this PR.

Thanks!

**Comment by rushabh-v** [comment]
Oh, I am sorry for that. Actually it was 4 days of reopening of the issue. And you didn't replied to it. So I thought you might not be interested in doing it. @ac-optimus I will definitely take your suggestion in consideration next time onwards :)

**Pull request closed without merging**
