### PR TITLE
Release 3.5

### PR DESCRIPTION
**Pull request by fonnesbeck**

### CODE REVIEW

**Comment by junpenglao** [comment]
Should we fix the Travis fail in py 2.7 here?

**Comment by fonnesbeck** [comment]
If it can be, sure.

**Comment by ColCarroll** [comment]
Should this be v3.5.0? It does not seem like a bug fix.

**Comment by ferrine** [comment]
Vote for 3.4.2, 3.5 for arviz

**Comment by fonnesbeck** [comment]
Colin's made a pretty good case for this being a 3.5 release. If so, let's be assiduous about making sure all the notebooks run without error and conform to current best practices. I think they are mostly there, but its worth spot-checking them.

**Review by ferrine — APPROVED** [review]

**Pull request merged**
