### PR TITLE
Add warning about change of sign in hessian functions

### LINKED ISSUE #6310: Hessian (d2logp) has the wrong sign
In PyMC, the Hessian of the a model is [defined as](https://github.com/pymc-devs/pymc/blob/7ccfdaa891ec05c5af2ba69ad548ebefbc6882f3/pymc/aesaraf.py#L520) $-\nabla\nabla\log f$ and not $\nabla\nabla\log f$ which is the generally accepted mathematical definition, as the collection of second-order derivatives.

I accept that there is probably a good reason for computing the negative Hessian rather than the Hessian but, for clarity when reading the code and documentation, could these functions be renamed to indicate that this is the negative Hessian?

Context: For pedagogical/demonstration purposes, I am implementing the [Laplace approximation](https://en.wikipedia.org/wiki/Laplace%27s_approximation) using the `logp`, `dlogp`, and `d2logp` functions and the sign error in `d2logp` took me a long time to figure out, eventually by looking through the code and finding the definition of `aesaraf.hessian`.

### PR DESCRIPTION
**Pull request by aseyboldt**
The hessian function incorrectly returned the negative of the hessian.

This does change the output of `Model.d2logp` however, so we should mention this in the release notes.

## Major / Breaking Changes
Sign of the hessian is fixed, and therefore different than before

Fixes #6310

### CODE REVIEW

**Comment by ricardoV94** [comment]
I opted to something like this when we changed the sign of an operation before: https://github.com/pymc-devs/pymc/blob/4acd98ee2bc31ef1fb63accdfb1012ba64fcebd5/pymc/math.py#L308-L331

If this is critical enough, we can do the same for the output of the hessian

**Comment by maresb** [comment]
Without understanding much context, as a geometer I must warn that a common sign convention for the Hessian in geometry and physics is indeed _negative_ nabla-squared.

The reason for this is that it makes the Hessian _positive_ semi-definite on plane-waves of the form $e^{i k x}$. Namely,

$$-\nabla^2 e^{i k x} = +k^2 e^{i k x}.$$

Nerd rant over.  :nerd_face:

**Comment by ricardoV94** [comment]
@maresb I think that keeping it in line with PyTensor is a good reason enough?

@aseyboldt I added a FutureWarning that can be disabled with `negate_output=False`, and kept the default behavior the same. WDYT? Do you mind reviewing my changes? I also changed other places in the codebase to behave the same as before (expect a non-negated output and so on).

**Review by maresb — APPROVED** [review]
Given that the typical user of PyMC isn't a differential geometer, I approve of this approach. I like @ricardoV94's deprecation plan

I'm still a bit :exploding_head: that this appears to be an accidental(?) rediscovery of the geometer's convention for the Laplacian. Although perhaps not too surprising, since when considering Bayesian stats as real-valued quantum mechanics, the minus sign that makes -logp positive-ish is the same minus sign that geometers like since it gives a positive spectrum.

**Pull request merged**
