### PR TITLE
Change coverage from coveralls to codecov

### PR DESCRIPTION
**Pull request by lucianopaz**

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @lucianopaz!

**Comment by twiecki** [comment]
Not sure why and how but it seems to have broken travis:
```
+++pip install --no-cache-dir --ignore-installed -e .
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/testenv/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 9, in <module>
    from pip._internal.commands.download import DownloadCommand
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/pip/_internal/commands/download.py", line 10, in <module>
    from pip._internal.operations.prepare import RequirementPreparer
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 9, in <module>
    from pip._internal.distributions import (
  File "/home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/pip/_internal/distributions/__init__.py", line 1, in <module>
    from pip._internal.distributions.source import SourceDistribution
ImportError: cannot import name 'SourceDistribution'
```

**Comment by lucianopaz** [comment]
Looks like it's a recent [pip bug](https://github.com/pypa/pip/issues/7217)

**Comment by lucianopaz** [comment]
@twiecki, it looks like pip might have broken itself when `pip install --upgrade pip` to the latest release. [Some people said](https://github.com/pypa/pip/issues/7217#issuecomment-542705309) that clearing their CI's cache fixed the problem. I cleared the cache and triggered a new build.

**Pull request merged**
