### PR TITLE
Added theano.gof.graph.Constant into the type checks done in distributions.py

### LINKED ISSUE #3595: ValueError: Unexpected type in draw_value: <class 'theano.gof.graph.Constant'> in sample_posterior_predictive
Hi Pymc3 Devs,
I've hit a strange error when trying to sample_ppc.
It appears that somewhere in the theano graph a NoneConst is being created, and sample_posterior_predictive throws an error when it tries to sample from it.

In the example below, the simple mean model has set of mean parameters with a dimension for a factor (x), a dimension for another factor (g), and a dimension for a single y output (although this problem also occurs when y has a cardinality of 2 or more). Both g and x are used to pick a specific parameter as a y datapoint's mean.

I think this is something to do with funny broadcasting, because when I don't include they y dimension in my parameters, there is no issue (see note in code). 

It could be something i'm doing wrong, but regardless, the error thrown is very hard to debug, and could maybe be improved.

An example:
```python
    #create some data
    n_d = 500
    n_x = 2
    n_g = 10
    g = np.random.randint(0, n_g, (n_d,))  # group
    x = np.random.randint(0, n_x, (n_d,))  # x factor
    true_x_effect = np.random.normal(0, 10, (n_x,))
    true_g_effect = np.random.normal(0, 10, (n_g,))
    y = np.random.normal(true_x_effect[x]+true_g_effect[g], 1)
    data = pd.DataFrame({'x':x, 'y1':y, 'g':g})
    y_vars = ['y1']
    n_y = len(y_vars)

    with pm.Model() as model:
        multi_dim_rv = pm.Normal('multi_dim_rv', mu=0, sd=1, shape=(n_x, n_g, n_y))
        indexed_rv = multi_dim_rv[data['x'], data['g'], :] #if : is replaced by 0 (effectivly removing y dimention), this works fine
        error = pm.HalfCauchy('error', 10)
        obs_data = data[y_vars].values
        obs = pm.Normal('obs', mu=indexed_rv, sd=error, observed=obs_data)
        print('dist_shape', obs.distribution.logp(data[y_vars].values).tag.test_value.shape) #shapes seem ok
        print('data_shape', obs_data.shape) #shapes seem ok
        trace = pm.sample() #samples fine.
        pm.sample_posterior_predictive(trace) #NoneConst error here.
```

Trace:
```python
Traceback (most recent call last):
  File "/home/bdyetton/PSleep/src/modeling/run_models.py", line 323, in <module>
    test_ppc_issue()
  File "/home/bdyetton/PSleep/src/modeling/run_models.py", line 282, in test_ppc_issue
    pm.sample_posterior_predictive(trace) #NoneConst error here.
  File "/home/bdyetton/anaconda3/envs/psleep/lib/python3.7/site-packages/pymc3/sampling.py", line 1167, in sample_posterior_predictive
    values = draw_values(vars, point=param, size=size)
  File "/home/bdyetton/anaconda3/envs/psleep/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 627, in draw_values
    size=size)
  File "/home/bdyetton/anaconda3/envs/psleep/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 817, in _draw_value
    size=None))
  File "/home/bdyetton/anaconda3/envs/psleep/lib/python3.7/site-packages/pymc3/distributions/continuous.py", line 495, in random
    point=point, size=size)
  File "/home/bdyetton/anaconda3/envs/psleep/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 627, in draw_values
    size=size)
  File "/home/bdyetton/anaconda3/envs/psleep/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 851, in _draw_value
    raise ValueError('Unexpected type in draw_value: %s' % type(param))
ValueError: Unexpected type in draw_value: <class 'theano.gof.graph.Constant'>
```

## Versions and main components

* PyMC3 Version: Master (8/18/19)
* Theano Version: 1.0.4
* Python Version: 3.7
* Operating system: Windows 10
* How did you install PyMC3: pip

I also asked this question on [discourse](https://discourse.pymc.io/t/valueerror-unexpected-type-in-draw-value-class-theano-gof-graph-constant/3750)

### PR DESCRIPTION
**Pull request by lucianopaz**
This closes #3595

### CODE REVIEW

**Comment by rpgoldman** [comment]
With all due respect, I think this calls out the problem thatt we don't have a clear statetment of what datta types can be in our networks and counted as variables. This causes us to have lots of duplicate if-then-else's that are prone to incompleteness...
It would be nice, for example, if I could put
```
assert instanceof(x, PyMCEntity)
```
in my code, but AFAICT there is no such assertion I can make.
If we could do that, we could also try to come up with a typecase-style statement that would be guaranteed to be complete.

**Comment by lucianopaz** [comment]
You are right that we are leaving many types out of our checks in `_draw_value`. However, would a `PyMCEntity` help us here? The type checking is done to determine the appropriate method to call (i.e. `value`, `get_value`, `random`, `theano.function`), which are different for different types. We should be able to deal with anything `theano` can throw at us, any `numpy` array and any RV or Distribution that we have. In my case, I wasn't aware of `theano.gof.graph.Constant`'s existence, and only thought of `theano.tensor.Constant`.

**Comment by rpgoldman** [comment]
> You are right that we are leaving many types out of our checks in `_draw_value`. However, would a `PyMCEntity` help us here? The type checking is done to determine the appropriate method to call (i.e. `value`, `get_value`, `random`, `theano.function`), which are different for different types. We should be able to deal with anything `theano` can throw at us, any `numpy` array and any RV or Distribution that we have. In my case, I wasn't aware of `theano.gof.graph.Constant`'s existence, and only thought of `theano.tensor.Constant`.

I agree that we should be able to deal with anything that can be thrown at us, but it's impossible to do that with any assurance unless we know what can be thrown at us, and speaking as a new-to-PyMC3 developer, I don't have that knowledge, and seems like I get it only by trial and error.

In particular, given a model, `m`, and a varname `nm`, it would be nice to have a clear understanding of what types of entity `m[nm]` can return.  I *think* that's `pm.FreeRV`, `pm.ObservedRV`, and `Theano.Variable` (for Deterministic), but I can't swear to it.  There's a similar uncertainty in other places in the code base.  I'm trying to cope with that myself by adding type hints, but some more information would be helpful.

**Comment by lucianopaz** [comment]
`m[nm]` can return any of our RVs: free, transformed, observed and multiObserved. Then it can also be any `theano` kind of variable or part of a compute graph. I don't know all of the types theano can throw at us but at least I thought that they could be summarized into constants, shareds and variables, but apparently not.
Besides that, distribution parameters could also be numbers or numpy arrays.

I also got most of this from trial and error and some source code inspection. The type hints you are adding are very helpful!

**Review by michaelosthege — APPROVED** [review]
lgtm

**Comment by michaelosthege** [comment]
@lucianopaz if you can identify groups of types that should always be checked together, you could put them as a tuple somewhere. No need for a custom type hierarchy..

**Comment by lucianopaz** [comment]
Thanks for the idea @michaelosthege, I'll group the two kinds of constants in a tuple in vartypes and then merge

**Pull request merged**
