### PR TITLE
Enable pygrep-hooks

### PR DESCRIPTION
**Pull request by Armavica**
## Description

This PR adds grep-based hooks that notably check for the use of double backticks for code in rst files, and that all noqa and type ignore statements are qualified.

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7507.org.readthedocs.build/en/7507/

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
The failing tests don't seem a fluke. But not related to this PR either?

**Comment by Armavica** [comment]
No, they are failing on main too.

**Comment by ricardoV94** [comment]
> No, they are failing on main too.

Probably related to the new Pytensor release

**Comment by ricardoV94** [comment]
> No, they are failing on main too.

Opened PR to fix it: #7529

**Review by twiecki — APPROVED** [review]

**Pull request merged**
