### PR TITLE
Bug fix #2279

### LINKED ISSUE #2279: Need informative error message for duplicate variable names
Having duplicate variable names in a model, such as the following: 

```python
β = pm.Beta('β', 1., α, shape=C)
...
β = pm.Normal('β', 0, sd=10, shape=3)
```

currently results (if you're lucky) in a cryptic error when recording a sampled value results in a shape mismatch.

```python
/Users/fonnescj/Repos/pymc3/pymc3/backends/ndarray.py in record(self, point, sampler_stats)
     95         for varname, value in zip(self.varnames, self.fn(point)):
     96             print(varname)
---> 97             self.samples[varname][self.draw_idx] = value
     98 
     99         if self._stats is not None and sampler_stats is None:

ValueError: could not broadcast input array from shape (3) into shape (20)
```

If the shapes are the same, you might not get any sort of message. There needs to be a name error raised when variables are added to a model that alerts users of the conflict. This model happily ran under ADVI until NUTS sampling began.

### PR DESCRIPTION
**Pull request by junpenglao**
* add_random_variable for potential and transformed
* fix typo

### CODE REVIEW

**Comment by aseyboldt** [comment]
Maybe also add a tests that the exceptions are raised. You can use pytest.raises:
```
with pytest.raises(ValueError) as err:
    with model:...
err.match('part of the message text')

**Comment by junpenglao** [comment]
@aseyboldt not sure I understand what you mean - what is this test for?

**Comment by aseyboldt** [comment]
The test should make sure the expected exception is actually raised:

```python
def test_duplicate_vars():
    with pytest.raises(ValueError) as err:
        with pm.Model():
            pm.Normal('a')
            pm.Normal('a')
    err.match('duplicate')

    with pytest.raises(ValueError) as err:
        with pm.Model():
            pm.Normal('a')
            pm.Normal('a', transform='log')
    err.match('duplicate')

    with pytest.raises(ValueError) as err:
        with pm.Model():
            pm.Normal('a')
            pm.Potential('a', 1)
    err.match('duplicate')

    with pytest.raises(ValueError) as err:
        with pm.Model():
            pm.Binomial('a')
            pm.Normal('a', transform='log')
    err.match('duplicate')
```

**Comment by junpenglao** [comment]
Oh I see. Good call thanks!

**Pull request merged**
