### PR TITLE
Black formatted 15 files

### PR DESCRIPTION
**Pull request by Sayam753**
Black formatted last 15 files listed in #4109. This is fun to do. I think in PyMC4, we do have tests for formatting as well.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @Sayam753 !

This is interesting - once you apply `black` to 
```python
                raise ParametrizationError('Discrete variables are not supported by VI: {}'
                                           .format(var))
```
then `pyupgrade` can change it to
```python
                  raise ParametrizationError(
                      f"Discrete variables are not supported by VI: {var}"
                 )
```

Can you either run `pyupgrade` on `pymc3/variational/opvi.py` or install pre-commit and then run
```bash
pre-commit run pyupgrade --all
```
?

**Comment by Sayam753** [comment]
This is indeed interesting. I did nothing apart from running black and then why did pyupgrade fail?

**Review by michaelosthege — APPROVED** [review]
Took a while to compare all the lines but 👍

**Comment by MarcoGorelli** [comment]
> This is indeed interesting. I did nothing apart from running black and then why did pyupgrade fail?

because, once `black` splits the error message for `ParametrizationError` so `.format` is on the same line as a string, then `pyupgrade` realises it can upgrade it to be an f-string

**Comment by Sayam753** [comment]
> because, once black splits the error message for ParametrizationError so .format is on the same line as a string, then pyupgrade realises it can upgrade it to be an f-string

Wow. `pyupgrade` is so powerful. Now I am curious to add pyupgrade to VSCode as an auto formatter.

**Pull request merged**
