### PR TITLE
Add moments for KroneckerNormalDistribution

### PR DESCRIPTION
**Pull request by anirudhacharya**
Moments and tests for KroneckerNormalDistribution

### CODE REVIEW

**Comment by anirudhacharya** [comment]
cc: @ricardoV94 for review.

**Comment by anirudhacharya** [comment]
@ricardoV94 is this PR good to go? The test failures in `jax-sampling` seem unrelated to this PR. 

It is failing on `test_sampling_jax.py::test_transform_samples` and `test_sampling_jax.py::test_get_log_likelihood` with `NotImplementedError`

And the pre-commit is failing on some code formating issue, I think. Is there some specific pre-commit hook that you use? How do I make this pass?

**Comment by ricardoV94** [comment]
> Is there some specific pre-commit hook that you use? 

Yes, it's explained in here: https://docs.pymc.io/en/latest/contributing/python_style.html

**Comment by ricardoV94** [comment]
The failing tests are likely due to dependency versions that have been fixed in the main branch. If you rebase your PR on top of it, they should go away.

**Review by mjhajharia — APPROVED** [review]
lgtm, @ricardoV94 i saw this marked as done in #5078, can this be merged now?

**Comment by ricardoV94** [comment]
We need to rebase and rerun tests, as they were failing

**Comment by anirudhacharya** [comment]
Give me a couple of hours, I will rebase, run the tests and push the code.

**Comment by mjhajharia** [comment]
no worries, i rebased it @anirudhacharya, the tests should pass now, thanks for contributing to PyMC!!!

**Pull request merged**
