### PR TITLE
Remove workflow to autoupdate pre-commit hook versions

### PR DESCRIPTION
**Pull request by maresb**
## Description

Autoupdate functionality is now handled by pre-commit-ci.

Closes #7135

## Related Issue

See https://github.com/pymc-devs/pymc/pull/7102#issuecomment-1905228570

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [X] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7112.org.readthedocs.build/en/7112/

### CODE REVIEW

**Comment by maresb** [comment]
Hmm, RTD is now failing? That's weird.

**Review by twiecki — APPROVED** [review]

**Comment by maresb** [comment]
Closes #7135

**Comment by ricardoV94** [comment]
> Closes #7135
> 
> Not sure why it's not linking

I don't think you can close PRs like that, only issues

**Comment by ricardoV94** [comment]
Ah the linking only works on the first message of the PR!

**Comment by maresb** [comment]
> Ah the linking only works on the first message of the PR!

Actually I suspect you may be right about issues vs PRs. Note that I did edit the initial description with the closing keyword.

**Comment by ricardoV94** [comment]
I think the other PR was automatically closed

**Comment by maresb** [comment]
> I think the other PR was automatically closed

Ah, indeed! At least the timestamps agree to the minute.

Maybe it's just another GitHub glitch? Like it did get linked but didn't show up?

**Pull request merged**
