### PR TITLE
GP multiple observations

### PR DESCRIPTION
**Pull request by bwengals**
This WIP PR is to enable support for multiple observations from a GP.  Each observation has the same covariance matrix.  Instead of the observation being a vector, it can also be a matrix.

### CODE REVIEW

**Comment by bwengals** [comment]
One issue is that for MvNormal, the observed data (and mu) shape it expects is: number of observations by number of data points per observation.  This is a bit awkward for gps, since the X matrix is number of data points by number of dimensions.  Why not the transpose of this, because then the shapes for the expression (x - \mu)^T \Sigma (x - \mu) would work?

Would people prefer to have the gp classes transpose internally, so that the shape of the observed data lines up with the shape of X?  or would it be better to stick with the convention for MvNormal?

**Comment by junpenglao** [comment]
I support transposing internally in GP.

**Comment by bwengals** [comment]
Sounds good @junpenglao.  Only issue that comes up is with `gp.conditional`.  The output of `conditional` is an an instance of `MvNormal`.  When you transpose it, it's no longer a RV type, and its name changes to, say, "`fcond.T`" and `sample_ppc` doesn't like it.  I altered `sample_ppc` to draw from theano tensor types when previous graph nodes are given, but the addition of the `.T` to the name is annoying. 

Easiest option is to allow the output of `conditional` to have the wrong shape.  This probably isn't too big of a deal, the solution is for the user to just transpose the output if need be.

**Comment by fonnesbeck** [comment]
@bwengals Did you do this elsewhere?

**Comment by bwengals** [comment]
No sadly, this is blocked by #3118, which im still tinkering with

**Comment by twiecki** [comment]
Ping @bwengals

**Comment by bwengals** [comment]
I know its stale, but can we leave open?  Hoping to return to this and #3118 at some point...  Or I suppose it can be closed and reopened later also.

**Comment by twiecki** [comment]
Sure we can.

**Comment by twiecki** [comment]
@bwengals Still planning to get back to this?

**Comment by fonnesbeck** [comment]
@bwengals are you planning to implement coregionalization here?

**Comment by bwengals** [comment]
actually I do have some time now.  so yes on both here.

**Comment by StanczakDominik** [comment]
Hi, is there any way I could help with this one? I'd love to be able to use this functionality!

**Comment by michaelosthege** [comment]
This looks really cool. Unfortunately, I do not yet understand the math behind it enough to really be of help.

@StanczakDominik the diff has a few things that could be worked on:
* some lines of code are just commented out (that's a no-go)
* comments on what it does next to the code
* test that assert what didn't work before and does work with this PR
* the notebook can be polished into a nice example notebook

**Comment by twiecki** [comment]
Closing due to inactivity.

**Comment by fonnesbeck** [comment]
Is this really a dead-end, @bwengals? Multitask GP would be a great addition.

**Pull request closed without merging**
