### PR TITLE
Increment release number to 3.1

### PR DESCRIPTION
**Pull request by fonnesbeck**
Ready for release.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Merged. Will tag this as the release.

**Comment by junpenglao** [comment]
I think we should keep the 3.1 branch for readthedocs, @twiecki @owlas?

**Comment by ColCarroll** [comment]
Just needs a tag, I believe (this was helpful for checking out v3.0 to
benchmark).

**Comment by fonnesbeck** [comment]
It's been tagged in master, after this branch was merged. You should be able to check it out by tag number (v3.1).

@junpenglao same thing there -- we should be able to use the tag for readthedocs.

**Comment by fonnesbeck** [comment]
```bash
$ git tag
v3.0
v3.0.rc1
v3.0.rc2
v3.0.rc3
v3.0.rc3_full
v3.0.rc4
v3.0.rc5
v3.0.rc6
v3.0alpha
v3.0beta
v3.0rc2
v3.1
v3.1.rc1
v3.1.rc2
v3.1.rc3
v3.1.rc4
```

That said, we can probably delete RC tags. I don't see much value in keeping them around.

**Comment by junpenglao** [comment]
Oh I see.
I think we can just keep the v3.0 and v3.1 tag for readthedocs.

**Comment by owlas** [comment]
Readthedocs will automatically point the `stable` docs to the most recent tag `v3.1.rc4`, which is the most important thing.

Could also have a separate branch `3.1.x` for example if you wanted to make changes later.

But I think being able to toggle between `stable` and `v3.0` will serve most users.

**Pull request merged**
