### PR TITLE
Update webpage

### PR DESCRIPTION
**Pull request by junpenglao**

### CODE REVIEW

**Comment by junpenglao** [comment]
@twiecki fix webpage http://pymc-devs.github.io/pymc3/notebooks/Diagnosing_biased_Inference_with_Divergences.html

**Comment by twiecki** [comment]
Wait, this is on the gh-page, you need to fix the source file.

**Comment by twiecki** [comment]
gh-page gets overwritten every time we update.

**Comment by junpenglao** [comment]
#2130

**Pull request merged**
