### PR TITLE
Bounded now works with array bounds

### PR DESCRIPTION
**Pull request by ColCarroll**
Addresses #1491 .  The sampling now runs, but produces nonsense results.  Could use another set of eyes on this!

https://gist.github.com/ColCarroll/f003b12bf52b8e3893e2222a9a5f28ab

is the current output.

### CODE REVIEW

**Comment by ferrine** [comment]
@ColCarroll is it possible to refactor `class Bound` to function `Bound` so that it will return a `type` object but not instance of `class Bound`?

**Comment by springcoil** [comment]
LGTM after the advice from @ferrine is taken on board.

**Comment by ColCarroll** [comment]
@ferrine i'm not sure what you mean by a `type` object.

**Comment by ferrine** [comment]
@ColCarroll  it is a class, not instance

**Comment by ColCarroll** [comment]
I'm still not sure what you mean -- do you have an example of your envisioned API?  (or feel free to grab this branch and fix it!)

**Comment by ferrine** [comment]
@ColCarroll the following check should pass:  `issubclass(Bonded(Normal), Distribution)`

**Comment by ColCarroll** [comment]
ah, thank you!

**Comment by twiecki** [comment]
Does it still provide nonsense results?

**Comment by ColCarroll** [comment]
Yeah, it still provides nonsense results.

**Comment by springcoil** [comment]
Do we merge anyway?

**Comment by ColCarroll** [comment]
I'd be happy with a merge, since it doesn't appear to create any new bugs
(and contains some improvements).  It seems like the nonsense results are a
separate problem, and someone else may have more bandwidth to fix that.

**Pull request merged**
