### PR TITLE
Remove GLM submodule in v4

### PR DESCRIPTION
**Pull request by farhanreynaldo**
This PR closes https://github.com/pymc-devs/pymc3/issues/4681, which remove GLM submodule and its test, in favor to Bambi.

### CODE REVIEW

**Comment by ricardoV94** [comment]
Does something need to be changed in the docs templates?

**Comment by farhanreynaldo** [comment]
> Does something need to be changed in the docs templates?

Should I remove the `docs/source/api/glm.rst` and the glm line in `docs/source/api.rst`?

**Comment by OriolAbril** [comment]
> Should I remove the docs/source/api/glm.rst and the glm line in docs/source/api.rst?

I would do something like we do with ArviZ, not completely removing this from the documentation but instead leave only 1-2 sentences and a link to bambi. Example from stats "module": https://docs.pymc.io/api/stats.html, here there would be no aliases, but it could still be useful to have the link to bambi there somehow like we do in the first paragraph in stats.

**Review by twiecki — DISMISSED** [review]

**Comment by twiecki** [comment]
Definitely needs a line in the release notes for v4.

**Comment by farhanreynaldo** [comment]
> Definitely needs a line in the release notes for v4.

Should I add something like this here?

```
## PyMC3 vNext (4.0.0)
### Breaking Changes
- ⚠ Theano-PyMC has been replaced with Aesara, so all external references to `theano`, `tt`, and `pymc3.theanof` need to be replaced with `aesara`, `at`, and `pymc3.aesaraf` (see [4471](https://github.com/pymc-devs/pymc3/pull/4471)).
- ArviZ `plots` and `stats` *wrappers* were removed. The functions are now just available by their original names (see [#4549](https://github.com/pymc-devs/pymc3/pull/4471) and `3.11.2` release notes).
- GLM submodule is now delegated to Bambi library [#4682](https://github.com/pymc-devs/pymc3/pull/4682)
- ...
```

I am not actually confidence with the sentence.

**Comment by twiecki** [comment]
A bit clearer would be "The glm submodule has been removed, please use Bambi [link] instead."

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @farhanreynaldo!

**Pull request merged**
