### PR TITLE
Implement negative binomial family for GLM

### LINKED ISSUE #1688: Feature request: negative binomial distribution for glm
Hi,

I am wondering if you have plans to include negative binomial distribution in `glm.families`? To be specific, I meant as a new class in [here](https://github.com/pymc-devs/pymc3/blob/master/pymc3/glm/families.py). This distribution could be very useful when dealing with over-dispersed count data. Thanks.

### PR DESCRIPTION
**Pull request by jonathanhfriedman**
Resolves #1688 and adds a short example notebook. I'm not sure whether half-Cauchy is the best choice for the prior on alpha, but it seems to work fine.

### CODE REVIEW

**Comment by peadar-elevate** [comment]
I think this needs a rebase.

**Comment by peadar-elevate** [comment]
I think this needs a rebase

**Comment by springcoil** [comment]
I think this needs a rebase.

**Comment by twiecki** [comment]
Closing in favor of #1726.

**Pull request closed without merging**
