### PR TITLE
Fixes pickling bug when using Bounded distributions with njobs > 1

### PR DESCRIPTION
**Pull request by tyarkoni**
Consider this code:

```python
HalfFlat = pm.Bound(pm.Flat, lower=0)
model = pm.Model()

with model:
    a = HalfFlat('meh')
    pm.sample(1000, init=None, njobs=2)
```

This fails with a pickling error, whereas it runs fine if we set `njobs=1`. The reason is that the `Bounded` class definition internally imports the `transforms` module, which prevents pickling. Moving the import to the top of the module solves the problem.

### CODE REVIEW

**Comment by twiecki** [comment]
Good catch. I hope that wasn't there to avoid a circular import. We'll see what travis says.

**Comment by tyarkoni** [comment]
Oh, right. Didn't think about that, and it looks like the tests are indeed failing. I have to run, but I'll look at this again this evening and try to fix any import issues.

**Comment by junpenglao** [comment]
I ran into the same issue - what is the status on this?

**Comment by tyarkoni** [comment]
I believe this change solves the problem, though frankly it's kind of ugly, and the issue should probably be addressed by restructuring `distributions` to avoid the circular import (but I don't have time to look into that at the moment). The try/except block is there because pickling is attempted `njobs` times, so the `pop` will fail the second time through.

**Comment by tyarkoni** [comment]
Also, @twiecki, let me know if you want me to add a test for this (and if so, in what test module).

**Comment by twiecki** [comment]
Thanks @tyarkoni. The fix is quite ugly indeed. I'll try to take a look at the circular import.

**Comment by twiecki** [comment]
Closing in favor of #2007.

**Pull request closed without merging**
