### PR TITLE
Modify Logistic Regression Example

### PR DESCRIPTION
**Pull request by tomicapretto**
This pull request modifies the existing logistic regression example. 

This example uses the same dataset than the current example but, according to my opinion, improves the following:

* Proper usage of categorical variables: The previous example only uses numerical variables as predictors and/or treat categorical variables a numeric, which is not always possible or correct. Here we incorporate categorical variables with 2 or more levels as predictors and use dummy variables instead of assigning numbers to its levels.
* Exploratory plots: The previous example shows a pairplot and a heatmap. In this new example we see the distribution of all the potential predictors and the distribution of the response variable as a function of every predictor. 
* Estimated probability plots: This example adds more examples to plots shown in the current example where the probability of success is presented as a function of age and other explanatory variables.
* Odds-ratio plots: I added more plots related to odds ratios. In this case I show the odds ratio between categories of a categorical predictor.

### CODE REVIEW

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Thanks @tomicapretto, this is definitely an improvement!
I left some comments / questions below, mainly geared towards giving more context about the models and choices of variables.
Also, the watermark cell is missing at the end of the NB, and make sure to run `black_nbconvert` on the NB -- see [PyMC NB style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style)

**Comment by tomicapretto** [comment]
<p>You are right!, thanks!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>What do you mean with index variables? I'm not familiar with it.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<ul><li>Thanks, as you may have seen i have several English mistakes, I appreciate the correction.</li><li>The mode is placed on the left side and the long tail is on the right side, then it is skewed to the right (or positively skewed). <a href="https://en.wikipedia.org/wiki/Skewness#Introduction" target="_blank">https://en.wikipedia.org/wiki/Skewness#Introduction</a> may clarify.</li></ul>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>I'm going to add an introduction where I explain how I propose the different models (starting with a baseline model and adding terms to it).</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Ha ha, ok, thanks for clearing this up! I always mix this up :D</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Instead of having one indicator variable per category, you just have one index variable and each category has its level -- see chapter 5, section 5.3 of <em>Rethinking2</em> for instance (<a href="https://github.com/pymc-devs/resources/blob/master/Rethinking_2/Chp_05.ipynb" target="_blank">PyMC port</a>, see code 5.50)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Sounds perfect, thanks!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>Thank you, I got it. I thought it was something completely different, but they are equivalent. I think my election is due to a personal bias - I think the dummy approach is more explicit. The index approach makes me feel that someone could get confused and think you are replacing categories with numbers that are used as such, when actually numbers are just labels and no math is done with them. </p><p>I guess a good approach would be to use index variables but explaining the connection with the dummy setting and mentioning that the numbers of the index don't mean anything, just labels. Sounds good?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>If I use the default I have the following error:  Bad initial energy, check any log probabilities that are inf or -inf, nan or very small</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Yep, sounds good. With ArviZ <code>dims</code> and <code>coords</code> it's also easier to display the categories' names instead of the just the numbers now (I think Osvaldo can give you pointers on this). And setting priors is easier with index variables, compared to dummy ones. But don't feel obligated to do so if you really don't like it -- I just thought it could make for shorter data manipulations and easier-to-follow models.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Yeah, I'm not surprised about that, it's most probably because the priors are too wide. I'd either keep adapt_diag or set explicit priors.</p><p>Out of curiosity, which PyMC version are you running?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4015/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
What's the status of this? Still more work needed or can we merge @AlexAndorra?

**Comment by AlexAndorra** [comment]
I think there are still comments and changes to implement before it's ready to merge. Am I mistaken @tomicapretto ?

**Comment by tomicapretto** [comment]
> I think there are still comments and changes to implement before it's ready to merge. Am I mistaken @tomicapretto ?

Hi Alex, yes, you are right. I've not been on this PR the last days but it is something I'm definitely tackling within one or two days. Thank you for the patience.

**Comment by MarcoGorelli** [comment]
Hi @tomicapretto - is this still active?

**Comment by MarcoGorelli** [comment]
Closing as notebooks are being moved out of PyMC3 and into https://github.com/pymc-devs/pymc-examples , please open a pull request there if you're still interested in working on this

**Pull request closed without merging**
