### PR TITLE
Cosmetic fixes to getting started notebook.

### PR DESCRIPTION
**Pull request by rpgoldman**
There were some problems with the version on the PyMC3 docs site.
Fixed some warnings.  Tidied up some markup (some of which didn't seem to process properly on gh pages), and added a note explaining about pm.Deterministic

### CODE REVIEW

**Review by AlexAndorra — APPROVED** [review]
LGTM, thanks @rpgoldman ! I had just one small suggestion about `Deterministic`

**Comment by rpgoldman** [comment]
<p>You are quite right.  I have put that in, and will push it to the MR momentarily. Thanks for having a look!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4062/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>It's actually necessary here now.  The reason is that <code>az.summary()</code>  internally calls <code>az.from_pymc3()</code>  to build an <code>InferenceData</code>,  and that function needs information from the model in order to do the translation.  If you leave it out, you get a warning.</p><p>If you look at the version on the PyMC3 docs page, https://docs.pymc.io/notebooks/getting_started.html you will see the warning.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4062/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>See my response above: ArviZ now needs the model for <code>from_pymc3()</code>  (this is necessary to appropriately allocate random variables among the various groups in the <code>InferenceData</code>.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4062/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by fonnesbeck** [comment]
OK, cool. Did not realize that.

**Comment by fonnesbeck** [comment]
LGTM then.

**Comment by rpgoldman** [comment]
> OK, cool. Did not realize that.

Yes, originally ArviZ was using a sneaky pointer to the model that was stashed in an `_strace`, which made everyone very nervous, and wouldn't work when loading a saved trace.

**Pull request merged**
