### PR TITLE
Change default core number to at least 2

### PR DESCRIPTION
**Pull request by aseyboldt**
cc @fonnesbeck

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Suits me.

**Comment by twiecki** [comment]
The test failures look real. I think we might not be able to multiprocess on travis?

**Comment by fonnesbeck** [comment]
I would be surprised if multiprocessing code cannot be tested on Travis. Don't we already have multiprocessing tests?

**Comment by springcoil** [comment]
I had a look at those test failures, and none of them seemed related to multiprocessing. But they did look real. Am I missing something?

**Comment by twiecki** [comment]
Closing due to inactivity.

**Pull request closed without merging**
