### PR TITLE
Multitraces should iterate over samples from all chains

### LINKED ISSUE #2457: WAIC/LOO only consider last chain in a Multitrace
See [this gist](https://gist.github.com/AustinRochford/b2287e7e50544f60e8ac811d01dc2ce0) for a demonstration.  Of course, the WAIC values across difference chains should not be _too different_, if the sampling has been effective.  This may also affect other stat functions, I haven't checked yet.

@aseyboldt thoughts on what the correct behavior should be here?

### PR DESCRIPTION
**Pull request by AustinRochford**
Resolves #2457

### CODE REVIEW

**Comment by ferrine** [comment]
Does it affect [this](https://github.com/pymc-devs/pymc3/blob/master/pymc3/stats.py#L23) code somehow?

**Comment by junpenglao** [comment]
> Does it affect this code somehow?

I think it would.

**Comment by AustinRochford** [comment]
@ferrine it's not obvious to me that it will affect that code, but the tests will let us know for sure.  I certainly expect some to fail, and will also be adding a few new ones before merging.

**Comment by ferrine** [comment]
this line assumes old length https://github.com/pymc-devs/pymc3/blob/master/pymc3/variational/approximations.py#L311

**Comment by AustinRochford** [comment]
Thanks for the heads up, that one's a simple enough change, at least.  I'll wait to see how many other places there are that depend on the old `len`.  If there are many, I may need to take a different approach.

**Comment by AustinRochford** [comment]
Coverage decreased by ~40%

image

**Comment by aseyboldt** [comment]
Not sure what we should do here, all options I can see are a bit strange.

- We could keep the current behaviour (len and iter ignore all but the first chain), but add a method that returns an iterator over all samples
- Keep len as it is, but change iter to return all samples (the current PR). This kind of breaks common assumptions, usually `len(list(obj))` should match `len(obj)` for all iterables.
- Change both `len` and `iter` to return all samples

I think the first one might be a good compromise between reasonable behaviour and backward compatibility.

**Comment by AustinRochford** [comment]
@aseyboldt I agree. I mostly want to see which tests this approach breaks.  After trying the third option, which seems to break many parts of the code base, I'm inclined to go with the first, although it is a bit unsatisfying.

**Comment by twiecki** [comment]
Hm, yeah, first option seems the most realistic.

**Comment by ferrine** [comment]
I vote for the third

**Comment by aseyboldt** [comment]
Any updates on this? We still haven't decided which way we'd like to go, right?

**Comment by AustinRochford** [comment]
@aseyboldt this got lost in my vacation :|. I think we should go with the first option.  Will try to get a new PR up in the next few days.

**Comment by junpenglao** [comment]
@AustinRochford any progress? Would be great to fix this before 3.2 ;-)

**Comment by AustinRochford** [comment]
Yes it would.  Unfortunately no progress yet, but I'll see about putting something together tonight.

**Pull request closed without merging**
