### PR TITLE
Feature/dp mixture docs

### PR DESCRIPTION
**Pull request by mattKretschmer**
Fixing discrepancy in text-based model description and model definition in code. In first example, latex model description wasn't completely updated in PR #3724

### CODE REVIEW

**Review by eigenfoo — COMMENTED** [review]
Thanks @mattKretschmer! I'm just curious about the new divergences with the sampling with the `'advi'` init: it looks like this re-introduces the divergences from #3724.

```
There were 28 divergences after tuning. Increase `target_accept` or reparameterize. 
There were 17 divergences after tuning. Increase `target_accept` or reparameterize. 
There were 17 divergences after tuning. Increase `target_accept` or reparameterize. 
There were 38 divergences after tuning. Increase `target_accept` or reparameterize. 
```

I'm happy to merge this if this will be hard to fix, but I wonder if you have any special insight into why the divergences are cropping up again. Could it be the value of `target_accept`?

**Comment by mattKretschmer** [comment]
Hi @eigenfoo, thanks for reviewing! In #3724 I was able to lower, but not completely eliminate, the divergences for each of those samples. The screenshot you shared looks the same as what I've seen.

**Comment by ColCarroll** [comment]
I think this is good to go -- it wouldn't be bad to solve these divergences, but it seems like this is quite improved over the previous situation (which used Metropolis). I think we should merge, and deal with the divergences separately if there are volunteers.

Check out how bad it used to be!

image
image
image

**Comment by fonnesbeck** [comment]
Thanks, Matt!

**Pull request merged**
