### PR TITLE
Revert iterative nuts

### PR DESCRIPTION
**Pull request by twiecki**
https://github.com/pymc-devs/pymc3/issues/1420

### CODE REVIEW

**Review by springcoil — APPROVED** [review]
LGTM if this passes the tests

**Comment by springcoil** [comment]
Maybe @ColCarroll should look at this too - I never saw he was assigned.

**Comment by ColCarroll** [comment]
Spent some time yesterday trying to fix this, and it is complicated -- not sure when/if a fix will be available.

**Comment by twiecki** [comment]
@ColCarroll thanks, we can give it another try if/when you get it to work.

**Pull request merged**
