### PR TITLE
Deprecated Constant class

### LINKED ISSUE #2451: Can't create a Constant with float dtype
The pymc3.Constant distribution advertises itself as accepting both `int` and `float` values ([discrete.py#L553](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/discrete.py#L553)).

However the `Discrete` distribution base class enforces integer dtypes ([distribution.py#L129](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/distribution.py#L129))

This code sample also shows that while `theano.tensor.as_tensor_variable` correctly creates a float type tensor, the `Constant` distribution does not:

```python
import pymc3
import theano.tensor

with pymc3.Model() as pmodel:
    d = pymc3.Constant("k1", c=42.3)
    print(d.dtype)
    # >>> int64

t = theano.tensor.as_tensor_variable(42.3)
print(t.dtype)
# >>> float64
```

### PR DESCRIPTION
**Pull request by fonnesbeck**
Fixes #2451 

Also adds a bunch of newer distributions that are missing from the API docs.

### CODE REVIEW

**Comment by aseyboldt** [comment]
Hm. Having the dirac measure as a subclass of `Continuous` seems strange from a mathematical point of view. It doesn't have a density.
I can't even think of a use case for this distribution, couldn't we always use a constant (optionally wrapped in a deterministic) instead? Unless someone knows one, I'd rather deprecate it.

**Comment by fonnesbeck** [comment]
We've had this discussion in the past, but we can bring it up again. However, if someone wants to set a value of a constant to a floating point value they should be able to, and so it makes sense to move it here based on our taxonomy. Alternatively, we could have it not subclass from either Continuous or Discrete. 

Moving it to Continuous is the easiest.

**Comment by aseyboldt** [comment]
Wouldn't that mean that during auto assignment of step methods NUTS will try to sample from that?

**Comment by fonnesbeck** [comment]
Correct. I was on your side the last time the issue was brought up, but folks argued strongly in favor of keeping it. It apparently does get used, as evidenced by the issue.

**Comment by aseyboldt** [comment]
Well, then maybe it is best if it inherits from `Distribution` directly. That way it will at least not mess up step method assignment (I hope?). Although I wouldn't be surprised if we had some code that actually assumes that all distributions are either discrete or continuous.

**Comment by fonnesbeck** [comment]
We won't know until we try ...

**Comment by junpenglao** [comment]
> couldn't we always use a constant (optionally wrapped in a deterministic) instead? 

I agree. Is it possible to just internally take the constant and wrapped in a deterministic?

**Comment by twiecki** [comment]
Yeah, I don't recall the reasoning last time, but just because people are using it doesn't mean that there isn't a better way which we should support instead (i.e. a Deterministic with a float). I'm in favor of dropping it.

**Comment by fonnesbeck** [comment]
Ok, I will leave it where it is (Deterministic) and add a deprecation warning.

**Comment by fonnesbeck** [comment]
OK, after all that, we are just deprecating now.

**Comment by springcoil** [comment]
Is this ready to merge?

**Comment by fonnesbeck** [comment]
Please do, unless anyone objects

**Comment by springcoil** [comment]
Done.

**Comment by michaelosthege** [comment]
Hmmm. I'm the one who opened #2451 in the first place and now the deprecation of `Constant` is causing some real trouble for me.
Let me explain:
I'm building a package where a model is independent of the data. For sampling it, one takes a dataset, maps each instance (experiment) in the dataset to prior `Distributions` and then the package instantiates prior RVs and build the model (computation graph) for the dataset at hand.
To do this, I specify priors as `pymc3.Distribution` objects (eg. `pymc3.Normal.dist("ned", mu=1, sd=2)`) **outside of any model context**.

From that perspective, a `Constant` is a perfectly fine distribution!
But `pymc3.Deterministic` is a function, not a distribution. It can not exist outside of a model context. Which means one can no longer describe a constant distribution independent of a model context.

I was able to use `pymc3.Deterministic` by introducing some if/else in my code, but having the CompundStep skip constant RVs seems a much more elegant solution.

**Pull request merged**
