### PR TITLE
Update blackjax version to avoid TypeError on deprecated kwarg

### PR DESCRIPTION
**Pull request by ricardoV94**
## Description

Blackjax tests started failing from an issue that was solved in https://github.com/blackjax-devs/blackjax/pull/664

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7317.org.readthedocs.build/en/7317/

### CODE REVIEW

**Comment by ricardoV94** [comment]
It seems that the newer jaxlib which blackjax requires is not available yet on conda

**Review by junpenglao — APPROVED** [review]

**Comment by ricardoV94** [comment]
We may mark as xfail until we can install from conda

**Comment by twiecki** [comment]
Seems like jaxlib builds are broken currently. https://github.com/conda-forge/jaxlib-feedstock/issues/249

**Comment by ricardoV94** [comment]
I don't understand why did blackjax start failing if we had everything jax/jaxlib/blackjax pinned to a specific version?

Conda-forge still seems stuck at the old v0.4.23 version of jaxlib unfortunately

**Comment by ricardoV94** [comment]
Ah we only lower pinned it!

**Comment by ricardoV94** [comment]
Closing in favor of #7320

**Pull request closed without merging**
