### PR TITLE
Bug fixed for LKJCorr

### PR DESCRIPTION
**Pull request by junpenglao**
fixed issue #1751

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks, @junpenglao. https://github.com/pymc-devs/pymc3/pull/1753 fixes some additional type problems I found.

**Comment by junpenglao** [comment]
Cool, yeah I am not too sure of the transform ` n = tt.as_tensor_variable(n)`  doing so I just leave it there. Should I close this PR?

**Comment by twiecki** [comment]
Yep, sorry you're not getting the author credit for the fix.

**Comment by junpenglao** [comment]
lol, no problem - I will contribute something else in the future.

**Pull request closed without merging**
