### PR TITLE
Fix Minibatch deprecated warnings and improve several tests

### PR DESCRIPTION
**Pull request by danhphan**
This PR is used to:
- Fix Minibatch deprecated warnings in the issue #4664
- Simplify several tests for Minibatch in `TestMinibatch`
- Add a test for `get_data` function to improve test coverage of `data.py` a little bit

Let's me know if it need update anything. Many thanks

### CODE REVIEW

**Comment by danhphan** [comment]
Hi @michaelosthege @OriolAbril, please have a look. Thanks

**Comment by twiecki** [comment]
Looks like you have to rebase from main to get the scipy fix.

**Comment by danhphan** [comment]
Hi, thank you @twiecki, I have done `rebase` and rerun the test. It passed in my local machine, but not sure why not all the tests are passed here. 

Hi @ricardoV94, any suggestion mate?

**Comment by twiecki** [comment]
@danhphan Unfortunately looks like the rebase didn't work correctly. You could start a new branch from main and cherry-pick your commits on there.

**Comment by danhphan** [comment]
Hi yes, thanks @twiecki, I will create a new branch from the updated main. I am not sure how to do `cherry-pick` but will give it a try :)

**Comment by danhphan** [comment]
Hi @twiecki I have done the `cherry-pick` related commits, and submitted a new PR at #5513

How can we cancel this PR? Thank you :D

**Comment by twiecki** [comment]
Just close it :).

**Pull request closed without merging**
