### PR TITLE
Codecov reintroduce `after_n_builds`

### LINKED ISSUE #6660: Upload to codecov only once all_tests are run
### Description

Following #6654 we can now wait until all tests have run before uploading the coverage report to codecov.

This will avoid the premature bot message saying coverage has dropped that happens all the time as the initial partial coverage files are uploaded by each individual job.

PyTensor can probably be used as a template: https://github.com/pymc-devs/pytensor/blob/98de246293855def134b86b5af6599e74a44835b/.github/workflows/test.yml#L235-L262

### PR DESCRIPTION
**Pull request by ricardoV94**
## Related Issue

- [x] Closes #6660 

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Comment by ricardoV94** [comment]
Number of uploads confirmed in: https://app.codecov.io/gh/pymc-devs/pymc/commit/2092ea1a77afdc2dccbf6cd636a54a3991f04492

image

**Comment by ricardoV94** [comment]
Well code-cov got shy now

**Comment by ricardoV94** [comment]
One of the jabs failed to upload the coverage

**Comment by ricardoV94** [comment]
Here it is! This should be much less confusing for new contributors. Before it would start displaying a drop in coverage / failing test as the first runs get uploaded

**Review by maresb — APPROVED** [review]

**Pull request merged**
