### PR TITLE
Resolve Arviz redirect link in Pymc3 Plot page

### PR DESCRIPTION
**Pull request by CloudChaoszero**
## Description of your problem
* Resolve Arviz Hyperlink/directory error to correct directory (api) mentioned in #4319.
* ~Also deleted a blank line, at the end of the file.~

```
#4319 
Links on this page are broken. They should be changed to link to the correct arviz plotting documentation

https://docs.pymc.io/api/plots.html
```

The directory re-direct path originally goes to `https://arviz-devs.github.io/arviz/`. However, now it's `https://arviz-devs.github.io/arviz/api`,
 based on the following comparisons, respectively

### Example 1:  https://arviz-devs.github.io/arviz/

plot_trace: https://arviz-devs.github.io/arviz/generated/arviz.plot_trace.html

### Example 2: https://arviz-devs.github.io/arviz/api

plot_trace: https://arviz-devs.github.io/arviz/api/generated/arviz.plot_trace.html

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
I just tried building the docs locally with this change, and they work - thanks @CloudChaoszero !

EDIT
----
see below

**Comment by MarcoGorelli** [comment]
Actually, I just tried building the docs locally without this change, and the link to the ArviZ docs still works :thinking:

**Comment by CloudChaoszero** [comment]
@MarcoGorelli 

Hmm, that's interesting. The original links should not have worked, and with the change, it should have fixed the redirects.
> #4319 confirms the redirected links for certain functions reach an error.
____
I can check it out again sometime soon.
> I did a `make html` in the docs directory.

**Comment by CloudChaoszero** [comment]
[Updated w/o `>`]

Thanks @MarcoGorelli. I found the same thing (w/screenshot below). 
  * Mentioned it in [this comment ](https://github.com/pymc-devs/pymc3/issues/4319#issuecomment-745051004) of Issue 4319.

Do you think the docs should be re-built?
  *  Latest prod push in [arviz-dev](https://github.com/arviz-devs/arviz) was 2 days ago, but the changes are irrelevant to this prod issue haha
_______
If a re-built did work, should I close this PR?

**Comment by MarcoGorelli** [comment]
Yes, rebuilding the PyMC3 docs may indeed solve the issue

> If a re-built did work, should I close this PR?

Perhaps let's wait for the PyMC docs to be rebuilt?

---

Generic note - `>` on GitHub is usually used when quoting other's messages

**Comment by MarcoGorelli** [comment]
Hey @CloudChaoszero 

Looks like the links work fine with the latest version of the docs built, so I'm going to go ahead and close this. Thanks anyway for your PR, and there's lot's of other open issues you could work on if you like - any help would be much appreciated!

**Pull request closed without merging**
