### PR TITLE
ENH: Timeseries GARCH model

### PR DESCRIPTION
**Pull request by springcoil**
I added a model version of GARCH to PyMC3 - does this need any work?

It needs some documentation but it should work.

### CODE REVIEW

**Comment by springcoil** [comment]
Does this need a test guys @jsalvatier and @twiecki I couldn't find tests of the other distribution helper functions - perhaps one is not necessary...

**Comment by olafSmits** [comment]
Taken from my question [here](http://stackoverflow.com/questions/33725588/garch-model-in-pymc3-how-to-loop-over-random-variables). I didn't know what to set the self.mean parameter to (don't know what it is used for). I kinda guessed it.

**Comment by springcoil** [comment]
Olaf if you'd prefer I'll cancel this commit and just let you get a PR out of this.
BTW are you Joost Slingerlands old student - who I met at PyCon Ireland?

**Comment by olafSmits** [comment]
No it's ok, you can leave it up. And, yes that's me :)

**Comment by springcoil** [comment]
Ha - it's a small world. :) If you want to do an example notebook - that'd be great. Lots of people want the time series stuff - and even if you don't know what the various terms mean it's fine.

**Comment by twiecki** [comment]
@olafSmits Just the analytical mean of the distribution. In the case of the normal distribution it'd be `mu`. We don't use it internally but it's convenient for a user.

@springcoil This looks great. Do you want to change your previous example to use it? that way there'd be a basic check.

**Comment by olafSmits** [comment]
I'll see if I can cook up a new notebook. The priors I was using before didn't produce nice results, but I found some papers on this. 

It also might be interesting to work out the bayesGARCH package from R, which uses Studen-t innovations instead of Normal ones.

**Comment by springcoil** [comment]
Ok my previous example is changed to use it. Is that enough?

**Comment by twiecki** [comment]
Can't see the commit here?

**Comment by springcoil** [comment]
Let's close this one - and look at my lightspeed one 
it's all there.

**Pull request closed without merging**
