### PR TITLE
DOCS: Rugby Analytics commit

### PR DESCRIPTION
**Pull request by springcoil**
Updated the Rugby Analytics commit with the mkdocs.yml change and added in the rugby analytic forest plots.

### CODE REVIEW

**Comment by twiecki** [comment]
Looks great, thanks @springcoil!

**Comment by twiecki** [comment]
I'm not sure why, but it's not rendering correctly on http://pymc-devs.github.io/pymc3/rugby_analytics/.

**Comment by springcoil** [comment]
I dunno why this is either. It seems to be one part of the IPython file. I'll have a look some other time. Thanks though.

**Comment by springcoil** [comment]
Do we need to add anything to the IPython file to handle the Mathjax

**Comment by twiecki** [comment]
It works fine for other ones. Seems like some formatting issue though.

**Comment by twiecki** [comment]
Maybe looking at the resulting .md file is helpful.

**Pull request merged**
