### PR TITLE
Update notebook examples with new variational API

### PR DESCRIPTION
**Pull request by ferrine**
Moving to new variational API, linked with #1968 

- [x] lda-advi-aevb.ipynb
- [x] GLM-hierarchical-advi-minibatch.ipynb
- [x] GLM-hierarchical-ADVI.ipynb
- [x] gaussian-mixture-model-advi.ipynb
- [x] convolutional_vae_keras_advi.ipynb

### CODE REVIEW

**Comment by ferrine** [comment]
I found that normalizing loss can make convergence slower due to weaker gradients. I'll make it optional for user in a separate PR

**Comment by ferrine** [comment]
Previous callback stopped earlier for hierarchical model when convergence was not achieved. The new one did not stop at all though(remark: it stopped once).

**Comment by ferrine** [comment]
That's done. CC @taku-y, @twiecki

I've changed callback here. This change should be approved or disapproved. In case it's ok I'll revert that commit and change the callback in separate PR

**Comment by fonnesbeck** [comment]
Can you replace the `fit` method calls with function calls in the notebooks?

**Comment by twiecki** [comment]
Agreed. Moreover, the `partial` construct everywhere is not nice API, can't we pass an object, or optimizer_kwargs?

**Comment by ferrine** [comment]
@fonnesbeck `pm.fit` does not return elbo history. In case we want to access inference history we need inference object.

**Comment by twiecki** [comment]
@ferrine Couldn't we store that in the returned object, like we did before?

**Comment by ferrine** [comment]
@twiecki good point, but I don't think that's bad api. Since 2 optimizers can be passed in the future, there will be 2 more kwarg

**Comment by twiecki** [comment]
@ferrine Not bad, but not user-friendly I would argue. Can we not pass in `Optimizer(lrate=.5)`, must it be a class?

**Comment by ferrine** [comment]
@twiecki ofc we can but ideologically they'd be better distinguished

**Comment by twiecki** [comment]
@ferrine not sure I follow, distinguished to what?

**Comment by fonnesbeck** [comment]
I've said this before, but I feel pretty strongly about keeping the default interface consistent across fitting methods -- particularly in our examples.

**Comment by ferrine** [comment]
I think that `pm.fit` can return loss history additionally as a separate array object. I do not want to attach new attribute to approximation as loss history is not related with approximation itself.

```python
approx, losses = pm.fit(...)
```

What about optimizers. What about wrapping them in a classes?
Capital case `Adam` will represent a class that can be inited before call and lower case `adam` will remain functions as in Lasagne. So we will just add some lines below every definition

**Comment by twiecki** [comment]
@ferrine Why wouldn't the loss be part of the approximation? To me it makes sense.

I see now, I somehow thought we already used classes in updates.py, which is clearly wrong. So yes, turning optimizers into classes is the right approach here.

**Comment by ferrine** [comment]
@twiecki Approximation purpose is to store parameters and allow sampling. Inference purpose is to fit the approx. These two tasks differ a lot. The right design is to make objects serve one particular thing. Mixing inference with approximation violates this idea.

**Comment by twiecki** [comment]
@ferrine I think the loss history of an approximation can be coherently included in the approximation class. I do see your point, but the API trumps code purity in my opinion. I love the `pm.fit()` analog to `pm.sample()`, but having one function return two things and the other just one is incoherent.

**Comment by ferrine** [comment]
Can I introduce a lightweight wrapper over results so that they store both approximation and stats?

**Comment by twiecki** [comment]
@ferrine Definitely, how would you do that on a high level?

**Comment by ferrine** [comment]
I'll try. High level is needed. I always write some weird callbacks to have custom watch list of statistics. Adding `watch_list` as kwarg to fit will solve the problem and they will be returned with inference result. Later it will be possible to use step methods along with it.

**Comment by twiecki** [comment]
Sounds good. FWIW callbacks are usually frowned upon, look for callback hell.

**Comment by ferrine** [comment]
Rebased

**Comment by ferrine** [comment]
@twiecki following our discussion about VI stats, check out #2230

**Comment by ferrine** [comment]
Solved by #2171

**Pull request closed without merging**
