### PR TITLE
Enable RTD for v4

### PR DESCRIPTION
**Pull request by Sayam753**
Preview - https://pymc3-fork.readthedocs.io/en/rtd_on_v4

I think this will be useful to preview docs when we start working on implementing new wireframe.

### CODE REVIEW

**Review by OriolAbril — APPROVED** [review]
This is great, thanks! It will indeed be great for when we get to work on v4 docs and implementing GSoD ideas as well as helping documentation team members to see how their changes look like without having to build the docs themselves

How will urls/versions work though? Will docs be at pymc3.readthedocs.com/latest/? Will docs have the dropdown to change between v3 nd v4 docs like in your fork? Will the v3 v4 ids the same as in the fork or the branch names, something else?

**Comment by Sayam753** [comment]
> How will urls/versions work though?

- `pymc3.readthedocs.io` will track all the docs built on PyMC3's main branch
- `pymc3.readthedocs.io/en/v3` will track all the docs built on PyMC3's v3 branch 
- `pymc3.readthedocs.io/en/v3.11.3` will host v3.11.3 docs, then my idea is to close `pymc3.github.io/en/v3` if not required.

I have enabled RTD to build docs for each PR at my fork. Here is the demo PR https://github.com/Sayam753/pymc3/pull/1. One can see in completed checks, that RTD has built the docs [here](https://pymc3-fork--1.org.readthedocs.build/en/1/)

Following your ideas @OriolAbril, I want to configure PyMC3's RTD portal to preview docs at each PR. Right now, the [PyMC3's RTD builds](https://readthedocs.org/projects/pymc3/builds/) are failing for some reason. Just waiting for @twiecki to add me there, so as I can look why they are failing and configure some settings.

**Review by michaelosthege — APPROVED** [review]

**Comment by michaelosthege** [comment]
@Sayam753 wanna merge, or do you want to wait until Thomas added you to the RTD project?

**Comment by Sayam753** [comment]
Yes. Thomas added me to PyMC3's RTD portal. Will update everyone once there is some progress over there.

Thanks for the review.

**Pull request merged**
