### PR TITLE
Adding logcdf method to inverse gamma distribution

### PR DESCRIPTION
**Pull request by dfm**
Supersedes #3873 for paperwork reasons (sorry about the noise!). See more discussion in that thread.

Since this feature requires an update to Theano, it should not be merged until a (possible) future version of PyMC3 that migrates to a pymc-devs-supported version of Theano.

### CODE REVIEW

**Comment by twiecki** [comment]
Why the don't merge @michaelosthege ?

**Comment by fonnesbeck** [comment]
@dfm we are now running on Theano-PyMC, so is it possible to push this over the finish line?

**Comment by dfm** [comment]
Sure thing! I've fixed the merge conflicts so we'll see if CI passes now. Sorry that I forgot about this one!

**Comment by dfm** [comment]
It looks like there are precision issues when running at float32 so I marked the test as an `xfail`. If this isn't an acceptable solution, let me know. Otherwise, we should be good to go!

**Review by fonnesbeck — APPROVED** [review]
Looks pretty straightforward. Will merge when tests pass. Thanks!

**Comment by twiecki** [comment]
Needs a line in the release-notes.

**Review by twiecki — APPROVED** [review]

**Comment by canyon289** [comment]
@dfm Get a line in the release notes and this will get merged!

**Comment by Spaak** [comment]
Thanks @dfm!

**Comment by dfm** [comment]
whoops - sorry!

Thanks @Spaak, I totally forgot about this!

**Pull request merged**
