### PR TITLE
Minor cosmetic changes/fixes.

### PR DESCRIPTION
**Pull request by rpgoldman**
Clarified the docstring to bring it into compliance with what the function does.

### CODE REVIEW

**Comment by rpgoldman** [comment]
Actually, I stuffed a couple more mostly cosmetic changes into this PR, which I will rename.

**Comment by rpgoldman** [comment]
I'm not sure what's wrong with this PR -- it seems like somehow it has the contents of my earlier PR about graphviz, causing the travis checks to fail.  Marking this as WIP until I can figure out what's wrong here.

**Comment by rpgoldman** [comment]
@ferrine If this is ok, will you please just merge it? It's a trivial change, but having a more precise docstring is helpful...

**Comment by ColCarroll** [comment]
:+1: thanks!

**Pull request merged**
