### PR TITLE
changes sample_smc to allow starting points from `start` param

### PR DESCRIPTION
**Pull request by TStesco**
changes ```sample_smc``` to call ```_initial_population``` and generate starting points only if starting points are not provided in ```start``` param. This closes issue [#3061](https://github.com/pymc-devs/pymc3/issues/3061).

```
pytest --cov=pymc3 pymc3/tests/test_smc.py
...
============================ 3 passed in 338.45 seconds ============================```

### CODE REVIEW

**Comment by aloctavodia** [comment]
LGTM. It seems you need to update the values of https://github.com/pymc-devs/pymc3/blob/d829f560c3ee46a4d54a2790ede833ff8b5fd947/pymc3/tests/test_step.py#L126

Just use the values from https://github.com/pymc-devs/pymc3/blob/d829f560c3ee46a4d54a2790ede833ff8b5fd947/pymc3/tests/test_step.py#L217

**Comment by TStesco** [comment]
Okay - thanks for the tip, I'll get on it after work today. Curious, why does this PR change the test values when ```random_seed=1``` does not change? Or did these values already need to be updated?

**Comment by aloctavodia** [comment]
Great! I guess because now it is correctly using the provided start values

**Comment by TStesco** [comment]
Sounds good, I'll try running the model with ```start=None``` to double check before changing the ```master_samples[smc.SMC]``` reference.

**Comment by TStesco** [comment]
I found that running ```pymc3/tests/tesp_step.py``` gave a different result if ```start=None``` than ```[ 0.94245927,  0.04320349, ...]```. I moved the code block that sets ```step.population``` to where it was run previously and the results are now the same as before for when ```start=None``` or is not provided. 

I changed the reference value to the values for the case when ```start=[{'x':1.}, {'x':-1.}]``` and this should work for the time being (lets see what the full test suite says).

I'm not sure why the order of setting ```step.population``` appears to matter when ```_initial_population``` is used for ```start=None```. Sorry for the confusion, do you know why this might be?

**Comment by aloctavodia** [comment]
Not sure what is going on with the order, I will explore it later. I think this is almost ready to merge except that you need to rebase or close and open a new PR, as this PR has commits unrelated to your changes to SMC.

**Comment by TStesco** [comment]
Woopsie, reset to the current master and moved the changes into one commit. Let me know if I should change anything else. Thanks for the help!

**Comment by aloctavodia** [comment]
Thanks @TStesco!

**Pull request merged**
