### PR TITLE
Add Dask scheduler

### PR DESCRIPTION
**Pull request by davidbrochart**
This gives the possibility to distribute computations of the SMC sampler across a Dask distributed scheduler (locally or on a cluster).

### CODE REVIEW

**Comment by ericmjl** [comment]
Very nice! Dask is a great parallelization engine :smile:

**Comment by fonnesbeck** [comment]
Can you add a test for this?

**Comment by davidbrochart** [comment]
I'm trying to make it work on a cluster in Pangeo Binder (this is the only free cluster that I know of), but I have issues scaling the cluster up. I've asked for help on the Pangeo Gitter, I will let you know when it's fixed.

**Comment by ColCarroll** [comment]
Very cool! Just pinging @aloctavodia in case he wants to keep an eye on this.

**Comment by davidbrochart** [comment]
I have added a Dask setup on the local machine in the notebook, so that you can try it out.
- First, the performances are not good probably because Dask spends a lot of time moving data to the workers, and the model is too fast to run. I wanted to artificially slow down the model by inserting a `sleep` into the `two_gaussians` logp, but I have problems doing so (see my question [here](https://discourse.pymc.io/t/smc-example-with-arbitrary-function-as-model-likelihood/3249)).
- Second, the results of the inference are bad compared to the original notebook, and I don't understand why.

**Comment by fonnesbeck** [comment]
This looks pretty cool. I guess (1) is not surprising; you would only want to do this for expensive models. Maybe appropriate to choose an example with a bigger model (or larger dataset)?

**Comment by davidbrochart** [comment]
But anyway, having gradients in the model likelihood is useless here because the sampler uses Metropolis under the hood, so it would be good to have arbitrary functions in it (and it would allow me to insert a `sleep`). Any idea on [this issue](https://discourse.pymc.io/t/smc-example-with-arbitrary-function-as-model-likelihood/3249)?

**Comment by mrocklin** [comment]
If you have many small fast tasks you might want to consider Dask bag instead.  This also uses simpler machinery, and doesn't require the dask.distributed cluster.

https://docs.dask.org/en/latest/delayed-best-practices.html#avoid-too-many-tasks

If you want to test with the dask.distributed scheduler (which shouldn't be necessary if you're using bag, which will use a local process pool by default) then you should look here: 

https://distributed.dask.org/en/latest/develop.html#writing-tests

**Comment by aloctavodia** [comment]
Hi @davidbrochart thanks for working on this. I am not Dask expert but I will try to test this on a cluster with an expensive model. BTW I answered your question on discourse. Sorry for taking so long to check on this.

**Comment by davidbrochart** [comment]
Thanks a lot @aloctavodia, I saw your answer on discourse. It fixes the issue in the general case, but slows down the computation (+50%). And when using Dask.distributed, I get into issues where `two_gaussians` is not present on the workers: `distributed.core - ERROR - module '__main__' has no attribute 'two_gaussians'`.

**Comment by aloctavodia** [comment]
I guess that's the price of using `@theano.as_op` (theano is not able to apply some optimizations) using `math` instead of `numpy` for scalars, can helps, like `math.log(a)` instead of `np.log(a)`. Not sure about that dask error, but I bet i will have the same problem for my _expensive_ model because I also use a `@theano.as_op`

**Comment by davidbrochart** [comment]
Breaking down the decorator helps:
```python
# @theano.as_op([tt.dvector], [tt.dscalar])
def two_gaussians(x):
    log_like1 = - 0.5 * n * np.log(2 * np.pi) \
                - 0.5 * np.log(dsigma) \
                - 0.5 * (x - mu1).T.dot(isigma).dot(x - mu1)
    log_like2 = - 0.5 * n * np.log(2 * np.pi) \
                - 0.5 * np.log(dsigma) \
                - 0.5 * (x - mu2).T.dot(isigma).dot(x - mu2)
    return np.array(np.log(w1 * np.exp(log_like1) + w2 * np.exp(log_like2)))

two_gaussians_wrap = theano.as_op([tt.dvector], [tt.dscalar])(two_gaussians)

with pm.Model() as ATMIP_test:
    X = pm.Uniform('X',
                   shape=n,
                   lower=-2. * np.ones_like(mu1),
                   upper=2. * np.ones_like(mu1),
                   testval=-1. * np.ones_like(mu1))
    llk = pm.Potential('llk', two_gaussians_wrap(X))
```
But now Dask cannot pickle the Theano function: `TypeError: ('Could not serialize object of type Function.', '<theano.compile.function_module.Function object at 0x7ff62c0bb940>')`
I guess it's not pure Python, even though we tried to bypass Theano's compilator.

**Comment by junpenglao** [comment]
The recommended solution is to rewrite it into theano.

**Comment by davidbrochart** [comment]
I tried to "send the code" to the workers:
```python
def send_two_gaussians():
    global two_gaussians_wrap
    return two_gaussians_wrap
    
client.run(send_two_gaussians)
```
But I get a `PicklingError: Can't pickle as_op(), not the object at __main__.two_gaussians`. Strangely, pickling `two_gaussians` is almost empty:
```python
import pickle
pickle.dumps(two_gaussians)
# b'\x80\x03c__main__\ntwo_gaussians\nq\x00.'
```

**Comment by davidbrochart** [comment]
FYI, the bad inference quality was due to the fact that the Metropolis kernel uses random numbers, and so the function must be submitted to Dask with `pure=False`.

**Comment by davidbrochart** [comment]
You can try it out on the [Pangeo Binder](https://binder.pangeo.io/v2/gh/davidbrochart/pymc3/dask_smc) (open `notebooks/SMC2_gaussians.ipynb`). Unfortunately, you won't get any speed-up by running on the cluster, on the contrary (the model is not expensive enough here). As mentioned above, the model can't be pickled (and thus run through Dask) if decorated with `as_op`, so this PR is not that interesting any more...
FYI, I made @aloctavodia's SMC algorithm run in [my small MCMC library](https://github.com/davidbrochart/mcmc/blob/master/examples/example_smc.ipynb), which makes it possible to run any arbitrary model through Dask, because it doesn't involve Theano.

**Comment by aloctavodia** [comment]
Thanks @davidbrochart for working on this I will try to further explore this idea and also using MPI, unfortunately I will not have time to  work on this for at least a couple of weeks, but I will keep you and the rest posted about any update.

**Comment by twiecki** [comment]
I'm closing if it's not that interesting, feel free to re-open if you think we should merge this. It's really a bummer, very nice functionality - thanks for working on it.

**Pull request closed without merging**
