### PR TITLE
NFVI notebook improve

### PR DESCRIPTION
**Pull request by junpenglao**
* fix typo
* bound potential function so NUTS can sample properly
* add more examples for experiment.

### CODE REVIEW

**Comment by junpenglao** [comment]
@ferrine The NF is quite fun to play with but it currently still need some trial and error to make it work.

**Comment by ferrine** [comment]
I suggest to rewrite potential functions adding  to intractable ones `0.1*|z0|` that might work better than bounded potential

**Comment by junpenglao** [comment]
@ferrine just tried, the output is more or less the same compared to using bound.

**Comment by junpenglao** [comment]
@ferrine actually, after adding `0.1*|z0|` to the potential function, the NF does not return `inf` during optimisation. But plotting all the sample within the range [-5, 5], it's the same as using bound.

**Comment by ferrine** [comment]
You bound logp only there but not a variable. You need `pm.Bounded` there

**Comment by junpenglao** [comment]
@ferrine `pm.Bound` works on distribution, it would be complicated to do here.
~~I can change the code following your suggestion (i.e., adding `0.1*|z0|`) if you think that's easier to understand.~~
[EDIT] I will change the code to adding `0.1*|z0|` on the potential functions. Seems NF indeed work better.

**Comment by ferrine** [comment]
Looks great

**Pull request merged**
