### PR TITLE
Add Empirical example

### PR DESCRIPTION
**Pull request by ferrine**
#docathon!

### CODE REVIEW

**Comment by twiecki** [comment]
* "them do analysis " -> then
* "One of them was so-called Histogram that was later renamed with Empirical" no reason to mention things that weren't part of a release
* samplier -> sampler
* Hope I can ommit VI interface description here and focuse on Empirical. -> "For the interface description, see X. Here I will just focus on Emprical." or something along these lines, no reason to ask for permission from the reader
* "oun" -> "own"
* `approx.histogram` - shouldn't that be called `approx.trace`? I suppose that's a bit confusing because it's a shared rather than a Trace object but maybe we can find a more explanatory name like `samples`, or `trace_flat`.
* againg
* What's the point of doing Empirical from noise?

**Comment by ferrine** [comment]
Thanks, I'll take it all in account soon!
 
What about `approx.histogram` I think it is rather explanatory and moreover used internally only. I use a this name internally and in some cases use `histogram` as prefix. Changing name requires refactoring. Does it really worth it? 

BTW I like `samples` name but do not have enthusiasm to change this name convention. I still remember discussion where we discussed these things and renamed `Histogram` -> `Empirical` the main point was that `Empirical` is about what is the class and histogram is how samples are stored. From that point of view `samples` and also be confusing as there is again a convention `sample == dict` (taking point from trace gives a dict) but this sample is flattened. What about `trace_flat`, it can be either a trace and not a trace (particles) so that is not descriptive too. 
I hope we'll leave it as is.

**Comment by junpenglao** [comment]
This is ready to merge as well, @ferrine can you put it in the /docs/source/examples.rst under VI session for now?

**Comment by ferrine** [comment]
Yes, I was waiting for positive feedback before merge.

**Pull request merged**
