### PR TITLE
Fix for gp.cov.Stationary.square_dist

### PR DESCRIPTION
**Pull request by bwengals**
Attempts to fix the issue referenced in #1848.  Put a WIP tag because a test would be good, but I wasn't able to reproduce the described behavior.

### CODE REVIEW

**Comment by bwengals** [comment]
One of the builds failed due to travis HTTP error while installing packages.  Needs rebuild.

**Comment by fonnesbeck** [comment]
Yes, this has been happening for me as well. Might be a problem with conda.

**Comment by fonnesbeck** [comment]
This appears to need a rebase. Colin's commits are already in master.

**Comment by bwengals** [comment]
Hey @fonnesbeck, was having a hard time rebasing after having mistakenly pushed to here.  I closed this one and opened #1874.  Sorry, I know this isn't the best way to do this, trying to get clear  on rebasing/merging now...

**Comment by fonnesbeck** [comment]
Looks like you got it sorted out. Happens to me all the time.

**Pull request closed without merging**
