### PR TITLE
Move sampling code to a submodule

### PR DESCRIPTION
**Pull request by michaelosthege**
**What is this PR about?**
In #6257 we already wanted to do this, but had no good way to keep the `from pymc import sampling_jax` imports working.

Today I found a simple solution for this, so this PR moves all `*sampling*.py` files into a `sampling` submodule.

I also moved the tests accordingly.

⚠ The commits must not be squashed, otherwise the git history of `jax.py` would get messed-up. ⚠

You can check the diff commit-by-commit to see that I didn't actually change +721-680 lines...

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- None

## Bugfixes / New features
- None

## Docs / Maintenance
- All sampling related modules were moved into a new `pymc.sampling` submodule to facilitate further refactoring.

### CODE REVIEW

**Review by Armavica — COMMENTED** [review]
I only have two comments:
* There needs to be an empty `__init__.py` file inside `tests/sampling`
* There are a few places, mainly in the tests, where you import from `pm.sampling.mcmc` or `pm.sampling.forward` instead of just `pm.sampling`. This is not needed for the few items that are mentioned in `__all__` of these two submodules, because they are reimported in `pm.sampling`. But it works this way too, I didn't know if you actually wanted to be more precise, and I don't have a strong opinion on this question.

**Comment by michaelosthege** [comment]
thanks, @Armavica ! I'll add the init file.
For the import routes that I went with the exact ones because it makes refactoring a little easier.
IMO we should try to eventually arrive at a point where each submodule has an `__all__`-advertised public API and only those functions are used by other components. Once we get there I agree that we should import from the init files.

@ricardoV94 want to add something too before I make the "apply review feedback commit"?

**Comment by ricardoV94** [comment]
> @ricardoV94 want to add something too before I make the "apply review feedback commit"?

LGTM

**Comment by michaelosthege** [comment]
> LGTM, do you want a review already or still need to merge the suggestion?

I already added the `__init__.py` file, this is ready to review. You can even merge if you like it ;)

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
