### PR TITLE
Rectify return type hints in logprob module rewrites

### PR DESCRIPTION
**Pull request by AryanNanda17**
## Related Issue

- [x] Related to #6811

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] If you are a pro: each commit corresponds to a [relevant logical change]

## Type of change

- [x] Other (please specify): 
 ```Python3
def find_measurable_comparisons( 
     fgraph: FunctionGraph, node: Node 
 ) -> Optional[List[MeasurableComparison]]: 
```

Here, the return type hint is wrong. MeasurableComparision is an Op, but what is returned are TensorVariables whose node has that Op. This needs to be rectified for all the functions which intend to find a measurable op.

----
📚 Documentation preview 📚: https://pymc--7093.org.readthedocs.build/en/7093/

### CODE REVIEW

**Comment by AryanNanda17** [comment]
@larryshamalama please have a look at the pull request.

**Review by ricardoV94 — APPROVED** [review]
Looks good. Sorry for the delay in reviewing

**Comment by AryanNanda17** [comment]
@ricardoV94 , In this file:-
[pymc/pymc/logprob/tensor.py](https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/tensor.py#L200-L202)
```Python
 def find_measurable_stacks( 
     fgraph, node 
 ) -> Optional[List[Union[MeasurableMakeVector, MeasurableJoin]]]:
```
This went wrong. What is wrong here?

**Comment by ricardoV94** [comment]
> @ricardoV94 , In this file:- [pymc/pymc/logprob/tensor.py](https://github.com/pymc-devs/pymc/blob/f8b142a688d3e02883ba920ef23486197026b8bc/pymc/logprob/tensor.py#L200-L202)
> 
> ```python
>  def find_measurable_stacks( 
>      fgraph, node 
>  ) -> Optional[List[Union[TensorVariable, TensorVariable]]]:
> ```
> 
> This went wrong. What is wrong here?

The Union is not needed, since you have the same return type now

**Comment by AryanNanda17** [comment]
I updated it. 
Thanks!

**Comment by AryanNanda17** [comment]
Screenshot 2024-01-12 at 2 08 57 AM

Is this a formatting issue?
@ricardoV94

**Comment by AryanNanda17** [comment]
@ricardoV94 @larryshamalama Please look into the issue. I researched a lot during the past few days. But, did not get anything specific about the error here. 
Thanks

**Comment by ricardoV94** [comment]
@AryanNanda17 yes that's a formatting issue due to pre-commit. You can read about it in our contributing guides: https://www.pymc.io/projects/docs/en/latest/contributing/pr_tutorial.html

Check the `pre-commit` instructions specifically

**Comment by AryanNanda17** [comment]
@ricardoV94, I made the changes and now the precommits tests are passing. 
Screenshot 2024-01-31 at 12 32 57 AM

**Comment by AryanNanda17** [comment]
@ricardoV94 What is this error during mergeable check?

**Comment by larryshamalama** [comment]
> @ricardoV94 Why am I getting errors during mergeable check?

Hi @AryanNanda17, sorry about such delays in replying - I am pushing through graduate studies, which have been time-consuming. I will look more carefully at this afternoon or tomorrow.

Have you:
- Rebased with respect to main? Currently, I see that this branch has conflicts. This is probably due to the addition of commits to the main branch
- Applied pre-commit? Our linter and pre-commit configurations recently changed (#7901)

**Comment by larryshamalama** [comment]
Sounds good, do not hesitate to ping me in the new PR once you will have done so.

**Pull request closed without merging**
