### PR TITLE
Fix formatting in documentation of AR distribution parameters

### PR DESCRIPTION
**Pull request by daniel-saunders-phil**
**What is this PR about?**

Fixed a variety of docstring issues for the pm.AR distribution.

...

**Checklist**
+ [ ] Explain important implementation details 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## Bugfixes / New features
- ...

## Docs / Maintenance
- Fix formatting in documentation of AR distribution parameters

### CODE REVIEW

**Comment by reshamas** [comment]
#DataUmbrellaPyMCSprint

**Comment by cluhmann** [comment]
This looks good to me.  The only question I would have is about the "unnamed distribution" which seems correct, but there may be some other "docstring-official" way of specifying this.  Not sure.

**Comment by cluhmann** [comment]
And thank you for your contribution @daniel-saunders-phil !

**Comment by ricardoV94** [comment]
> This looks good to me.  The only question I would have is about the "unnamed distribution" which seems correct, but there may be some other "docstring-official" way of specifying this.  Not sure.

We should make one like tensor_like, but there isn't any right now. Do you want to open an issue to track that?

**Review by michaelosthege — APPROVED** [review]

**Comment by OriolAbril** [comment]
"unnamed distribution" should be `Distribution` which for now points to the API _section_ with all distributions, we could update it at any point to be a glossary term. The fact it is unnamed is not related to the _type_ but to a property some objects with this type have and that info should be described at the parameter description section (which is already done, so no changes needed here).

**Comment by cluhmann** [comment]
Yeah, I think a glossary term would be good, because I suspect that stating that this argument should be a "Distribution" is going to cause some confusion.  Chime in [here](https://github.com/pymc-devs/pymc/issues/6095).

**Pull request merged**
