### PR TITLE
WIP: Created deterministic decorator to replace Theano as_op

### PR DESCRIPTION
**Pull request by fonnesbeck**
Created `deterministic` alias for `as_op`, which is easier to remember and familiar for PyMC 2.3 users. One can then use:

``` python
@deterministic(itypes, otypes)
def func(args):
    ....
```

### CODE REVIEW

**Comment by twiecki** [comment]
Looks good to me.

**Comment by jsalvatier** [comment]
One thing that would make this more like pymc2 is if we inspected the defaults of the function we're wrapping and then used those as inputs automatically. That would have `deterministic` return an actual tensor, rather than a function. Seems kind of ugly to me, though.

**Comment by fonnesbeck** [comment]
I don't think specifying types is terribly onerous. I mainly wanted a shortcut for `theano.compile.ops.as_op` which is somewhat unfriendly. I suppose one could have a wrapper that first called the function to see what the output looked like, and set up the otypes with that information, it could be entirely automated.

**Comment by twiecki** [comment]
Yeah, that's possible but probably not the most pressing issue for now since it's only a small usability bonus. The alias here makes a lot of sense stand-alone for me.

**Comment by jsalvatier** [comment]
Sorry, I think you guys misunderstood me. I'm not talking about requiring or not requiring types, though that could be interesting and something I hadn't realized it was possible. 

I'm talking about the fact that `as_op` returns a Theano function, rather than a Theano value, which is different from what users might currently expect from `deterministic`.

**Comment by twiecki** [comment]
I think I would expect a `function` to get returned. What's the use-case where you think this would be confusing? https://github.com/pymc-devs/pymc3/blob/master/pymc3/examples/disaster_model_arbitrary_deterministic.py looks pretty good to me.

**Comment by fonnesbeck** [comment]
I think it's just the fact that you need to set up the function and wrap it in the theano decorator, then call the function again to get the object. This is in contrast to all other nodes (and arbitrary deterministics in PyMC 2) where once you set up the function and wrap it, you have your object, as far as the model is concerned. It May be possible to have a clever decorator that returns an object directly.

**Comment by twiecki** [comment]
So maybe we could do:

``` python
with Model() as model:
    # Prior for distribution of switchpoint location
    switchpoint = DiscreteUniform('switchpoint', lower=0, upper=years)
    # Priors for pre- and post-switch mean number of disasters
    early_mean = Exponential('early_mean', lam=1.)
    late_mean = Exponential('late_mean', lam=1.)

    @deterministic(inputs=[switchpoint, early_mean, late_mean], otypes=[t.dvector])
    def rate(switchpoint, early_mean, late_mean):
        ''' Concatenate Poisson means '''
        out = empty(years)
        out[:switchpoint] = early_mean
        out[switchpoint:] = late_mean
        return out
    disasters = Poisson('disasters', rate, observed=disasters_data)
```

Can we extract the theano dtype from the RV?

**Comment by springcoil** [comment]
One reason this might not be working is the syntax differences between python 2.7 and python 3.3. As I understand it there is no non local keyword in Python 2.7.

**Comment by twiecki** [comment]
Oh! That's probably it, can you fix that?

**Comment by springcoil** [comment]
I'll have a go!

**Comment by springcoil** [comment]
``` python
def outer():
  d = {'y' : 0}
  def inner():
    d['y'] += 1
    return d['y']
  return inner
```

 it's something like that. I'm having trouble retrieving Fonnesbecks PR - to edit it sadly.

**Comment by springcoil** [comment]
@fonnesbeck you want to add some simple 'if python < sys.version[3] then nonlocal stuff else the hack I showed above. https://technotroph.wordpress.com/2012/10/01/python-closures-and-the-python-2-7-nonlocal-solution/ is a decent reference.

**Comment by springcoil** [comment]
I pushed some changes, it's a bit 'hacky' let's see if it works. I think there are better ways to do this, but I wanted to see if it'd work and at least pass the tests.

**Comment by springcoil** [comment]
Ok so this is still not working. Does anyone have any suggestions on how to selectively import Python 2.7 functionality and Python 3.3 cc @twiecki and @fonnesbeck

**Comment by springcoil** [comment]
One reason why I think this isn't working is the from .model import *. This is causing nonlocal to be seen by python2.7 - Doesn't anyone have any idea of a solution that will handle the differing functionality in both 2.7 and 3.3. Do we use an if statement at import .model?

**Comment by twiecki** [comment]
We probably shouldn't `import *` at all.

**Comment by fonnesbeck** [comment]
Closing in favor of #1614

**Pull request closed without merging**
