### PR TITLE
Incremented version to 3.0.rc1

### PR DESCRIPTION
**Pull request by fonnesbeck**
Incremented version numbers for release candidate.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I replaced John with Thomas as maintainer contact.

**Comment by springcoil** [comment]
Does this need rebased.

**Comment by fonnesbeck** [comment]
I don't think so. I only created the branch about an hour ago.

**Comment by springcoil** [comment]
Ok I'll merge when it's through

**Comment by springcoil** [comment]
Awesome

**Comment by fonnesbeck** [comment]
Thanks. Will tag and release.

**Comment by twiecki** [comment]
:+1:

**Comment by twiecki** [comment]
Did you upload to pypi?

**Comment by springcoil** [comment]
I think @fonnesbeck is

**Comment by fonnesbeck** [comment]
Not yet. Hold tight.

**Pull request merged**
