### PR TITLE
[WIP] ENH: add variational gp model for classification

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
I have tried to add a Variational GP model from the paper [Mark N. Gibbs and David J.C. MacKay, Variational Gaussian Process Classifiers, 2000](https://ieeexplore.ieee.org/document/883477). Currently, I am facing some issues building the covariance matrix as it is failing to be a positive semi-definite! I have used all the equations from the paper (with inverse calculated using Cholesky decomposition and then solved with appropriate matrices). The equations I have tried to implement seem to be wrong although I am not able to find any mistakes myself. Can some of you have a look at this please? @bwengals  @aloctavodia  @fonnesbeck.

I will add tests and docs as soon as this is resolved. Also, this is draft as I am not so sure about this one.
 
Thank you!

### CODE REVIEW

**Comment by bwengals** [comment]
It's an interesting approach, but I'm not sure it makes sense to include this implementation in pymc3.  I kinda wish (now, not at the time) that the approximations hadn't been included, like FITC, VFE, DTC for a couple reasons.  

First is that PyMC is mostly focused on fully Bayesian models and inference results, and I'm not sure how you would interpret say, a marginal posterior distribution on a length scale parameter when the GP is approximated.  Or if the GP is part of a larger model with other parameters, how to interpret the other posteriors?

Second, there are other libraries like GPy, GPFlow, gpytorch and probably others now that are totally GP focused and let you build models using the latest and greatest variational approximations, where a first rate NUTS implementation isn't useful.  I think it makes sense for GPs in PyMC3 (and 4!) to fill the fully-Bayesian GP niche.

Thoughts @fonnesbeck @twiecki others?

**Comment by twiecki** [comment]
@bwengals So if in pymc3 one is using e.g. FITC you can't combine that with NUTS?

**Comment by bwengals** [comment]
@twiecki Nothing stops you, but I don't know if it makes a ton of sense.  If you're using an approximation you have a lot of data, so even finding the MAP will probably take a long time, much less NUTS.  And since it's an approximation, NUTS will give you samples from approximate posteriors for the unknown parameter.  Also you can't really quantify how close the approx is.

**Comment by fonnesbeck** [comment]
I agree that our focus is on fully-Bayesian models, though I will say that it is nice to have at least one approximation method available if needed, so that you can at least get an answer when a full GP becomes impractical, without switching software packages (or for purposes of comparison). It might be something to add to PyMC4 rather than here.

**Comment by tirthasheshpatel** [comment]
Agreed, @fonnesbeck and @bwengals! I am closing this for now. Will review some up-to-date GP approximation techniques and implement them in PyMC4.

**Pull request closed without merging**
