### PR TITLE
Update weibull_aft notebook

### PR DESCRIPTION
**Pull request by AmitKus**
1. Fixed: AttributeError: module 'statsmodels' has no attribute 'datasets'
2. Fixed: FutureWarnings
3. Updated the notebook to follow the consistent style (https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style)

### CODE REVIEW

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Thanks @AmitKus, this looks good! I just posted some comments below -- should be easy to address.
Tests are failing because of a Matplotlib issue, unrelated to your changes. Once #4023 is merged, you can rebase your current branch off master to take the changes into account and the tests should pass 😉

**Comment by AmitKus** [comment]
> Thanks @AmitKus, this looks good! I just posted some comments below -- should be easy to address.
> Tests are failing because of a Matplotlib issue, unrelated to your changes. Once #4023 is merged, you can rebase your current branch off master to take the changes into account and the tests should pass wink

Thanks @AlexAndorra for taking out time to review the changes. I made the changes you had suggested.

**Comment by AlexAndorra** [comment]
Thanks @AmitKus ! However, I don't think you rebased your branch -- you just picked up Robert's changes and integrated them into your PR. But these changes are already on the latest master. See what I mean?
I'm no git wizard, but I think [you need to rebase your PR](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request), i.e base it on the _latest_ version of master, not on the one you originally based it on. That way, the MPL issue will already be taken care of. Note that you _may_ have to revert your changes and add them back again but I'm not sure.
Sorry if this is confusing but you'll get the hang of it with time 😉

**Comment by AmitKus** [comment]
> Thanks @AmitKus ! However, I don't think you rebased your branch -- you just picked up Robert's changes and integrated them into your PR. But these changes are already on the latest master. See what I mean?
> I'm no git wizard, but I think [you need to rebase your PR](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request), i.e base it on the _latest_ version of master, not on the one you originally based it on. That way, the MPL issue will already be taken care of. Note that you _may_ have to revert your changes and add them back again but I'm not sure.
> Sorry if this is confusing but you'll get the hang of it with time wink

Thanks for your patience @AlexAndorra :)
I followed the link and rebased by PR. Hopefully this works!

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Well done @AmitKus, the git log looks all good now 👏 
This is almost ready -- just left a few comments to address before merging 😉

**Comment by AmitKus** [comment]
<p>Hi Alex, Looks like the default for tune and draws is 500, so made all the changes that you recommended except deleting draws and tune.</p><p> </p><p>Thanks,</p><p>Amit</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/4020/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Thanks @AmitKus! This is weird though, the new default is 1000 for both tune and draws. 
Which version of PyMC are you running? Can you post a screenshot of the progress bar when using the defaults please?

**Comment by AmitKus** [comment]
<p>Hey Alex, I just looked at the documentation for version 3.8 here: https://docs.pymc.io/api/inference.html</p><p>If this has changed in the recent version then I'll update the code to remove tune and draw.</p><p> </p><h2>Sampling<a href="https://docs.pymc.io/api/inference.html#module-pymc3.sampling" target="_blank">¶</a></h2><p><code>pymc3.sampling.sample</code>(<em>draws=500</em>, <em>step=None</em>, <em>init='auto'</em>, <em>n_init=200000</em>, <em>start=None</em>, <em>trace=None</em>, <em>chain_idx=0</em>, <em>chains=None</em>, <em>cores=None</em>, <em>tune=500</em>, <em>progressbar=True</em>, <em>model=None</em>, <em>random_seed=None</em>, <em>discard_tuned_samples=True</em>, <em>compute_convergence_checks=True</em>, <em>**kwargs</em>)<a href="https://docs.pymc.io/api/inference.html#pymc3.sampling.sample" target="_blank">¶</a></p><p> </p>

**Comment by AlexAndorra** [comment]
Aaaaah ok, I see the confusion! Docs are actually not up-to-date with the latest version of the code yet (we're still updating some notebooks, as this one, so that they appear on the website when we compile the docs).
So, when running this NB with 3.9.2, you should be able to just `pm.sample` and the defaults of `tune` and `draws` should be 1000 👌

**Comment by AmitKus** [comment]
> Aaaaah ok, I see the confusion! Docs are actually not up-to-date with the latest version of the code yet (we're still updating some notebooks, as this one, so that they appear on the website when we compile the docs).
> So, when running this NB with 3.9.2, you should be able to just `pm.sample` and the defaults of `tune` and `draws` should be 1000 ok_hand

I see. Made the changes to remove the tune and draws.

**Review by AlexAndorra — APPROVED** [review]
This is super nice now 🎉 Thanks for your help @AmitKus !

**Comment by AmitKus** [comment]
> This is super nice now tada Thanks for your help @AmitKus !

Great! Thanks for all the help @AlexAndorra

**Pull request merged**
