### PR TITLE
Rugby 2

### PR DESCRIPTION
**Pull request by springcoil**
Try again - any reason i can't automatically merge.

### CODE REVIEW

**Comment by twiecki** [comment]
That seems to have fixed it. Merged via https://github.com/pymc-devs/pymc3/commit/9dead24bece0d30acfb19b2922d8a7e9a4d5dd28. Thanks!

**Comment by springcoil** [comment]
Terrific :) :+1:

**Comment by twiecki** [comment]
What was the problem?

**Comment by springcoil** [comment]
I think it was the html tags in the markdown

**Pull request closed without merging**
