### PR TITLE
Update GP NBs to use standard notebook style

### PR DESCRIPTION
**Pull request by bwengals**
Updates the examples to use the standard notebook style, #3959, as outlined [here](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style).  

Should figure sizes / font sizes also be standardized? @michaelosthege @AlexAndorra.

### CODE REVIEW

**Review by AlexAndorra — COMMENTED** [review]
This is great, thanks for your help @bwengals !
LGTM, except for:
- Is it expected that the GP for classification example seems less able to recover the true f than in the earlier version of the NB? Would you consider the performance in the new version good enough?
- I'm not sure you ran `black_nbconvert` on the NB (see NB style Wiki)
- Oddly enough, `test_matrix_multiplication` is failing, but I don't see how that's related to the changes you did here 🤔

**Comment by michaelosthege** [comment]
Looks great! Can you add `assert all(r_hat < 1.03)` or similar after the samplings?

**Comment by bwengals** [comment]
@AlexAndorra I think the original problem was just easier, those variations around 0.5 were hard to pick up with the small data set.  I added more data and fixed the random seed so the results are better.  

Nope, totally forgot about black_nbconvert, thanks!  I'll see if that test still fails after fixing the other things.

@michaelosthege that's a good idea, will add that.

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Thanks @bwengals ! This is _almost_ ready, just added some comments below.

> I think the original problem was just easier, those variations around 0.5 were hard to pick up with the small data set. I added more data and fixed the random seed so the results are better.

Ow ok, thanks, that's good to know! You can even write a quick line about that in the NB if you feel like it -- always nice to highlight where a model could fail 🙂 

Regarding the tests: this has been fixed and merged, so if you merge master onto your branch, tests should pass now 😉

**Comment by bwengals** [comment]
<p>good call, will fix and rerun it</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3978/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>I reset it here because it's generating a new batch of fake data, it got a little confusing if I ran a few other cells before the new example.  Will add a note explaining this</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3978/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>fixed</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc3/pull/3978/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by AlexAndorra — APPROVED** [review]
Thanks @bwengals, this looks great now!
Just run `black_nbconvert` again (the new cells are not formatted) and merge master in your branch so that the tests pass, and then we're good to go 🎉

**Comment by michaelosthege** [comment]
@bwengals to fix the failing test:
```
git checkout master
git pull
git checkout gp-latent-nb-style-update
git merge master
```

**Comment by bwengals** [comment]
thanks @michaelosthege, much appreciated, pushed

Should I keep going with this PR for the other GP notebooks?  Or is 1 PR / 1 Notebook better?

**Comment by michaelosthege** [comment]
> thanks @michaelosthege, much appreciated, pushed
> 
> Should I keep going with this PR for the other GP notebooks? Or is 1 PR / 1 Notebook better?

I think multiple related NBs per PR are fine, but as this is done, let's merge it already

**Comment by bwengals** [comment]
@AlexAndorra whoops forgot about black again!  

OK that sounds good, next one I'll bundle the other GP NBs together.

**Pull request merged**
