### PR TITLE
Expand sampler-stats.ipynb example

### PR DESCRIPTION
**Pull request by junpenglao**
include model diagnose similar to case study example in [Stan](http://mc-stan.org/documentation/case-studies/divergences_and_bias.html)

### CODE REVIEW

**Comment by twiecki** [comment]
@junpenglao This is great, thanks for the port. I think it would be better to have it as a separate NB though which links to the stats one.

**Comment by junpenglao** [comment]
@twiecki No problem;-)

**Comment by fonnesbeck** [comment]
Thanks for this. Could you add some descriptive annotation to the notebook in markdown blocks? All of our notebook examples should be self-explanatory so that the user knows how to interpret the inputs and outputs of the model. This one in particular will be unfamiliar to many, so descriptive text will be helpful.

See some of the other notebooks for examples.

**Comment by twiecki** [comment]
Depending on the license of the STAN docs we can also copy&paste the text.

**Comment by twiecki** [comment]
CC-BY 4.0 license, so should be good.

**Comment by fonnesbeck** [comment]
Also, please add axis labels to all plots.

**Comment by junpenglao** [comment]
@fonnesbeck Sure.
BTW, is doing `step = pm.NUTS(k=.85)` the same as setting the `adapt_delta=0.85` in Stan? 
In a way, it is quite interesting that in `PyMC3`, the pathological samples from the trace is not necessary at the funnel (unlike Stan), and the sampler is generally doing a better job exploring the high curvature area even for a poorly parameterized model (at least in this example). I am not sure if this generalised to other models, but it might also mean that diagnosing biased inference is more difficult in `PyMC3`.

**Comment by fonnesbeck** [comment]
No, `adapt_delta` in pystan corresponds to `target_accept` in PyMC3.

`adapt_kappa` corresponds to `k`.

**Comment by fonnesbeck** [comment]
Looks good from here

**Comment by twiecki** [comment]
@junpenglao Looks great. Can you fix the pep8 issues in the model:
```
with pm.Model() as Centered_eight:
    mu = pm.Normal('mu',mu=0,sd=5)
    tau = pm.HalfCauchy('tau',beta=5)
    theta = pm.Normal('theta',mu=mu,sd=tau,shape = J)
    obs = pm.Normal('obs',mu=theta,sd=sigma,observed = y)
```

(spaces after `,` and no spaces around kwargs).

You can also link to my blog post on the same issue: http://twiecki.github.io/blog/2017/02/08/bayesian-hierchical-non-centered/

Good question regarding the divergences not being close to the funnel. @aseyboldt any ideas?

**Comment by twiecki** [comment]
Also, lets explicitly ask @betanalpha if he's fine with us porting his blog post.

**Comment by junpenglao** [comment]
Thanks for the patient answers I am complete newbie :-)
@twiecki Fixing the styling now. I already cited your post but will now make it more apparent.
Also, I am sending @betanalpha an email now.

**Comment by betanalpha** [comment]
The code in the case study is BSD (3 clause), the text is CC BY-NC 4.0.

**Comment by twiecki** [comment]
@junpenglao Did you change docs/source/notebooks/sampler-stats.ipynb? If not, should not show up in the diff.

**Comment by twiecki** [comment]
@junpenglao Also need to add this to `docs/source/examples.rst`, probably under how-to.

**Comment by fonnesbeck** [comment]
Just a picky thing: maybe use a Markdown quote block (`>`) for the direct quotes from Betancourt's paper/blog post. It will look better, and be more visually apparent that it is a quote.

**Comment by junpenglao** [comment]
> @junpenglao Did you change docs/source/notebooks/sampler-stats.ipynb? If not, should not show up in the diff.  

I did not - but ipynb picked up the change when I ran the notebook.

> @junpenglao Also need to add this to docs/source/examples.rst, probably under how-to.  

Cool.

> Just a picky thing: maybe use a Markdown quote block (>) for the direct quotes from Betancourt's paper/blog post. It will look better, and be more visually apparent that it is a quote.  

Done.

**Comment by twiecki** [comment]
Thanks for the great contribution @junpenglao.

**Pull request merged**
