### PR TITLE
Set start method to fork for MacOs ARM devices

### PR DESCRIPTION
**Pull request by bchen93**
**What is this PR about?**
Fixing an issue with use of parallel sampling on M1 Macs where sampling with more than 1 core results in broken pipe error (#5339). 

Changing multiprocessing context from forkserver to fork resolves this issue and does not seem to trigger issue (#3849) which was previously resolved by (#3919).
 

**Checklist**
+ [x] Explain important implementation details 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- None Noted
## Bugfixes / New features
Setting the default multiprocessing context to "fork" for ARM Macs, and "forkserver" for intel-based Macs.

## Docs / Maintenance
- ...

### CODE REVIEW

**Comment by ricardoV94** [comment]
Would it break stuff for older macOS?

**Comment by bchen93** [comment]
> Would it break stuff for older macOS?

I do not think so. I also tested on a 2016 Macbook Pro with i5 intel chip and it works with fork. 

*edit. Not sure about older operating systems, if that's what you were asking.

**Comment by bchen93** [comment]
After doing a little digging. Fork seemed to be the default start method for multiprocessing in MacOs (and still is for Unix) prior to python 3.8, after which they changed it to spawn (which does not work currently in pymc). There are some instances of fork crashing due to MacOs specific security features (after Os High Sierra (10.13). Which is [resolved](https://developer.apple.com/forums/thread/701358) by setting `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`. However, I haven't found it necessary to do this after changing the start method to fork in the pymc paralell_sampling.py script. 

The main reason for using spawn over fork is that it is [safer](https://stackoverflow.com/questions/64095876/multiprocessing-fork-vs-spawn), and it is currently the only method available to windows. 

I'm not sure if given the way that pymc uses multi-processing if the [dangers of using fork](https://www.reddit.com/r/programming/comments/vg3be2/fork_without_exec_is_dangerous_in_large_programs/) really apply. 

If not using fork, then I think there's a lot more work that needs to be done to make spawn/forkserver methods working on M1 Macs.

**Comment by ghost** [comment]
This seems like something users should be able to set to their liking. I'd be in favor of having a passable argument for `sample` that defaults to whatever is deemed to be safest or least likely to fail.

**Comment by bchen93** [comment]
Funnily enough, that is already possible in the pm.sample() method. It accepts an arg mp_ctx, which should be a multiprocessing context object. e.g. using the example model in #5339

```
import numpy as np
import pymc as pm
import arviz as az
import multiprocessing as mp

def build_model():
    data = np.loadtxt(
        pm.get_data("efron-morris-75-data.tsv"), delimiter="\t", skiprows=1, usecols=(2, 3)
    )

    atbats = pm.floatX(data[:, 0])
    hits = pm.floatX(data[:, 1])

    N = len(hits)

    with pm.Model() as model:
        phi = pm.Uniform("phi", lower=0.0, upper=1.0)
        pareto_dist = pm.Pareto.dist(alpha=1.0001, m=1.5)
        kappa = pm.Bound("kappa", pareto_dist, lower=1.0)
        thetas = pm.Beta("thetas", alpha=phi * kappa, beta=(1.0 - phi) * kappa, shape=N)
        ys = pm.Binomial("ys", n=atbats, p=thetas, observed=hits)
    return model

# %%
mp_ctx = mp.get_context('fork') # <--- Get fork, spawn, or forkserver context object
model = build_model()
with model:
    trace = pm.sample(1000, target_accept=0.99, mp_ctx = mp_ctx) <---Tell sampler to use this context

```

However, as it stands, anything run on M1 mac will not work without having to define the start method as fork. Would it be better to set the default start method for ARM macs as fork and for intel macs as forkserver as before?

So essentially changing the code in parallel_sampling.py to: 

```
        if mp_ctx is None or isinstance(mp_ctx, str):
            # Closes issue https://github.com/pymc-devs/pymc/issues/3849
            if platform.system() == "Darwin":
                if platform.processor() == 'arm':
                    mp_ctx = 'fork'
                else: 
                    mp_ctx = "forkserver"

```

**Comment by ricardoV94** [comment]
> However, as it stands, anything run on M1 mac will not work without having to define the start method as fork. Would it be better to set the default start method for ARM macs as fork and for intel macs as forkserver as before?
>
> So essentially changing the code in parallel_sampling.py to:

That sounds reasonable, we can always revert if that starts causing problems. Can we get some more M1 users to confirm that the model in the original issue indeed fails for everyone?

**Comment by twiecki** [comment]
@drbenvincent confirmed this fixed the same issue for him on a different model. I think we can merge this.

**Comment by ricardoV94** [comment]
We shouldn't merge this, but the default based on wether processor is arm or not mentioned in the last comment by the Op: https://github.com/pymc-devs/pymc/pull/6218#issuecomment-1283006746

**Comment by twiecki** [comment]
> We shouldn't merge this

Why not?

**Comment by bchen93** [comment]
> > We shouldn't merge this
> 
> Why not?

I believe @ricardoV94 wanted to change the then committed code s.t. the default for ARM Macs was specified as "fork" and and for intel Macs as "forkserver" (as it has been). I just committed the change to the code. So it can be checked/merged now if everyone is in agreement.

**Comment by ricardoV94** [comment]
@bchen93 Can you clean up the changelist in the top comment? It should mention in bugfixes what you did (use different default when on MacOS ARM). You can leave the other sections empty

We use those for the automatically generated release notes.

**Comment by bchen93** [comment]
> @bchen93 Can you clean up the changelist in the top comment? It should mention in bugfixes what you did (use different default when on MacOS ARM). You can leave the other sections empty
> 
> We use those for the automatically generated release notes.

Done!

**Comment by ricardoV94** [comment]
You seem to have caught unrelated changes in your PR

**Comment by bchen93** [comment]
> You seem to have caught unrelated changes in your PR

Sorry about that. I reverted the commits.

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @bchen93!

**Pull request merged**
