### PR TITLE
Unorphan the model transform doc page

### PR DESCRIPTION
**Pull request by Armavica**
## Description

This links the orphaned `model.transform` page to the `model` page.
Old: https://www.pymc.io/projects/docs/en/stable/api/model.html
New: https://pymcio--7544.org.readthedocs.build/projects/docs/en/7544/api/model.html

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7544.org.readthedocs.build/en/7544/

### CODE REVIEW

**Review by cluhmann — APPROVED** [review]
That looks like it does what it's supposed to. What was `model/conditioning`?

**Comment by Armavica** [comment]
It was the former name of the `transform.rst`: https://github.com/pymc-devs/pymc/commit/207821d3086412ac890989b3ea38580ca8b8d18b#diff-9b86228a64db07f9c0874c16d88007c423a5c1eea6182d62913e2aa9b94951ae

**Comment by cluhmann** [comment]
Ah, so @ricardoV94 was ultimately to blame. Figures.

**Comment by ricardoV94** [comment]
thanks 🙏

**Pull request merged**
