### PR TITLE
Add coveralls config to ignore examples directory.

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by aseyboldt** [comment]
Maybe this is not the common way of doing things, but I tend to find a coverage report of the tests useful. That way you can see if your tests are actually executed.

**Comment by twiecki** [comment]
@aseyboldt Fair, I do want to drop examples at least, we could easily run them but choose not to.

**Comment by ColCarroll** [comment]
Note you can also put coverage configuration in `setup.cfg` instead of a new file, using the prefix `[coverage:...]` (https://coverage.readthedocs.io/en/latest/config.html)

**Review by ColCarroll — APPROVED** [review]
looks good to merge

**Comment by twiecki** [comment]
image
Worth it!

**Pull request merged**
