### PR TITLE
Renamed StudentTpos to HalfStudentT

### PR DESCRIPTION
**Pull request by fonnesbeck**
This makes the naming consistent with other positive-truncated distributions

### CODE REVIEW

**Review by springcoil — COMMENTED** [review]
LGTM

**Comment by twiecki** [comment]
Should we add a `DepracationWarning`?

**Comment by springcoil** [comment]
Deprecation warning is a good one to add +1 for that.

**Review by springcoil — APPROVED** [review]
LGTM

**Pull request merged**
