### PR TITLE
Update pymc.LogNormal docsting

### PR DESCRIPTION
**Pull request by purna135**
Related to #5459 

This will update the docsting of [pymc.LogNormal](https://docs.pymc.io/en/latest/api/distributions/generated/pymc.LogNormal.html)

### CODE REVIEW

**Review by OriolAbril — COMMENTED** [review]
Can you add the close-figs context as shown in https://pymc-data-umbrella.xyz/en/latest/sprint/docstring_tutorial.html#section-independent-comments to the plot directive?

Also the short summary is not right. The first line should be the one line description of the distribution, then the note as part of the extended description.

**Comment by purna135** [comment]
> Can you add the close-figs context as shown in https://pymc-data-umbrella.xyz/en/latest/sprint/docstring_tutorial.html#section-independent-comments to the plot directive?
> 
> Also the short summary is not right. The first line should be the one line description of the distribution, then the note as part of the extended description.

Hi @OriolAbril, Please take a look at the adjustments I've made.
My other PRs are also missing `:context: close-figs`, should I also modify these PRs?

**Review by OriolAbril — APPROVED** [review]

**Comment by OriolAbril** [comment]
Yes, you should also update the other PRs

**Comment by purna135** [comment]
Sure, I will update them now

**Comment by purna135** [comment]
I think I should wait for review of those PRs so that I will do necessary changes and will add `:context: close-figs` in a single commit. This will save multiple CI runs.

what do you think ?

**Comment by purna135** [comment]
@OriolAbril, sd is still there in this PR; once it is decided whether sd should be removed or not, I will remove sd accordingly in my next PR.

**Pull request merged**
