### PR TITLE
Only set random seed on purpose

### LINKED ISSUE #1394: Random seed is set unexpectedly
There is a call in `_iter_sample` to set the random seed.  It is `None` by default, which reseeds the generator.  This can lead to unexpected behavior when users are trying to set a random seed themselves:

```
import numpy as np
import pymc3 as pm

for _ in range(2):
    np.random.seed(1)
    with pm.Model():
        pm.sample(1)
    print(np.random.random()) 
```

this will print two different numbers.  Changing a default value can be dangerous, so wanted to open an issue along with a pull request.

### PR DESCRIPTION
**Pull request by ColCarroll**
PR that fixes #1394 .  Included the sample script as a test case.  Also happy to remove the test case, because it is a little strange to test that something unexpected didn't happen.

### CODE REVIEW

**Comment by twiecki** [comment]
Does this change any behavior? I thought `seed(None)` was just a noop?

**Review by springcoil — COMMENTED** [review]
I think this is a fair contribution. I don't really understand the test case though - could you explain that to me?

**Comment by ColCarroll** [comment]
That would make sense, but it calls to `RandomState`, where "If seed is None, then RandomState will try to read data from /dev/urandom (or the Windows analogue) if available or seed from the clock otherwise." ([link](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState))

I double checked performance, and `_iter_sample` was written nicely, and only calls the random seed once (so it doesn't slow things down).

**Comment by twiecki** [comment]
Ah, gotcha.

**Comment by ColCarroll** [comment]
@springcoil I would expect that setting after explicitly setting a random seed, everything should be reproducible.  That means this loop should result in the same "random" number both times.  The test fails without this patch.

**Pull request merged**
