### PR TITLE
Fixed discrete index creation.

### PR DESCRIPTION
**Pull request by hvasbath**
Finally, the fix for issues: https://github.com/pymc-devs/pymc3/issues/1029, https://github.com/pymc-devs/pymc3/issues/1005
Rebased ;) Thx @springcoil , @twiecki  .

### CODE REVIEW

**Comment by twiecki** [comment]
Great! Can you add a test that fails with the old code but works with the new? Seems like you already have an example case. Also CC @fonnesbeck who looked over this the most.

**Comment by hvasbath** [comment]
At the moment this is my big bad complex model as example. Definitely cant add that ;) . But apparently @stonebig also found one. But I will try to simplify it. I think it is the combination of model variables of a scalar and a vector that fails with the old version.

**Comment by twiecki** [comment]
Ping @stonebig.

**Comment by fonnesbeck** [comment]
Thanks for the fix.

**Pull request merged**
