### PR TITLE
Setup alterations

### LINKED ISSUE #912: Add Patsy to setup.py
patsy is used inside glm/glm.py, so probably the best place to require this is within the install_reqs param within setup.py. Could someone do this?

### PR DESCRIPTION
**Pull request by springcoil**
I fixed [this](https://github.com/pymc-devs/pymc3/issues/912) problem in patsy. Just to avoid the installation errors which may be extra confusion for beginners.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
I get some Seaborn/MPL issues on 3.5:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/colors.py in to_rgb(self, arg)
    321                 raise ValueError(
--> 322                     'cannot convert argument to rgb sequence')
    323 

ValueError: cannot convert argument to rgb sequence

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/Users/fonnescj/anaconda3/lib/python3.5/site-packages/seaborn/palettes.py in color_palette(palette, n_colors, desat)
    184         palette = map(mpl.colors.colorConverter.to_rgb, palette)
--> 185         palette = _ColorPalette(palette)
    186     except ValueError:

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/matplotlib/colors.py in to_rgb(self, arg)
    327             raise ValueError(
--> 328                 'to_rgb: Invalid rgb arg "%s"\n%s' % (str(arg), exc))
    329             # Error messages could be improved by handling TypeError

ValueError: to_rgb: Invalid rgb arg "None"
cannot convert argument to rgb sequence

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-3-5c312646e2c7> in <module>()
     35 
     36 ## scatterplot the standardized data
---> 37 g = sns.FacetGrid(dfhoggs, size=8)
     38 _ = g.map(plt.errorbar, 'x', 'y', 'sigma_y', 'sigma_x', marker="o", ls='')
     39 _ = g.axes[0][0].set_ylim((-3,3))

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/seaborn/axisgrid.py in __init__(self, data, row, col, hue, col_wrap, sharex, sharey, size, aspect, palette, row_order, col_order, hue_order, hue_kws, dropna, legend_out, despine, margin_titles, xlim, ylim, subplot_kws, gridspec_kws)
    233             hue_names = utils.categorical_order(data[hue], hue_order)
    234 
--> 235         colors = self._get_palette(data, hue, hue_order, palette)
    236 
    237         # Set up the lists of names for the row and column facet variables

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/seaborn/axisgrid.py in _get_palette(self, data, hue, hue_order, palette)
    139         """Get a list of colors for the hue variable."""
    140         if hue is None:
--> 141             palette = color_palette(n_colors=1)
    142 
    143         else:

/Users/fonnescj/anaconda3/lib/python3.5/site-packages/seaborn/palettes.py in color_palette(palette, n_colors, desat)
    185         palette = _ColorPalette(palette)
    186     except ValueError:
--> 187         raise ValueError("Could not generate a palette for %s" % str(palette))
    188 
    189     return palette

ValueError: Could not generate a palette for <map object at 0x1093c90b8>
```

What version of these packages are you using?

**Comment by springcoil** [comment]
name: pymc3_examples
dependencies:
- certifi=14.05.14=py33_0
- freetype=2.5.5=0
- ipython=3.2.1=py33_0
- ipython-notebook=3.2.1=py33_0
- ipython-qtconsole=3.2.1=py33_0
- jinja2=2.8=py33_0
- jsonschema=2.4.0=py33_0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- markupsafe=0.23=py33_0
- matplotlib=1.4.3=np19py33_3
- mistune=0.7=py33_0
- numpy=1.9.2=py33_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py33_0
- pip=7.1.2=py33_0
- ptyprocess=0.4=py33_0
- pygments=2.0.2=py33_0
- pyparsing=2.0.3=py33_0
- pyqt=4.11.3=py33_0
- python=3.3.5=3
- python-dateutil=2.4.2=py33_0
- python.app=1.2=py33_4
- pytz=2015.7=py33_0
- pyzmq=14.7.0=py33_0
- qt=4.8.6=3
- readline=6.2=2
- scipy=0.16.0=np19py33_1
- seaborn=0.6.0=np19py33_0
- setuptools=19.1.1=py33_0
- sip=4.16.5=py33_0
- six=1.10.0=py33_0
- sqlite=3.8.4.1=1
- terminado=0.5=py33_0
- tk=8.5.18=0
- tornado=4.2.1=py33_0
- wheel=0.26.0=py33_1
- xz=5.0.5=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - appnope==0.1.0
  - decorator==4.0.6
  - enum34==1.1.2
  - gnureadline==6.3.3
  - ipykernel==4.2.1
  - ipython-genutils==0.1.0
  - ipywidgets==4.1.1
  - jupyter==1.0.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - nbconvert==4.1.0
  - nbformat==4.0.1
  - nose==1.3.7
  - notebook==4.0.6
  - path.py==8.1.2
  - patsy==0.4.1
  - pexpect==4.0.1
  - pickleshare==0.5
  - pymc3==3.0
  - qtconsole==4.1.1
  - simplegeneric==0.8.1
  - theano==0.7.0
  - traitlets==4.0.0

Is the output from my .yml file.

**Comment by springcoil** [comment]
I adjusted patsy a bit in the setup.py file.

**Comment by twiecki** [comment]
Your fork is still out-of-date.

**Pull request closed without merging**
