### PR TITLE
Clean up GLM doc

### PR DESCRIPTION
**Pull request by junpenglao**
* pm.glm.glm -> pm.glm.GLM.from_formula
* pm.glm.plot_posterior_predictive -> pm.plot_posterior_predictive_glm
* remove find_MAP and used default ADVI init

### CODE REVIEW

**Comment by junpenglao** [comment]
@twiecki I assigned you as you were working on this quite a lot before ;-)

**Comment by twiecki** [comment]
Looks great!

Can you delete the cell:
```
def f(x, y):
    print(x)
    print(y)
    
f(y=1, x=2)
```
in `GLM-robust-with-outlier-detection.ipynb`

Then `GLM-logistic.ipynb` also seems to have some exceptions in some cells, probably only needs to be rerun.

**Comment by junpenglao** [comment]
OK should be fine now. 
The only problem: in GLM-rolling-regression.ipynb the YahooDailyReader is currently broken (see https://github.com/pydata/pandas-datareader/issues/333 and https://github.com/pydata/pandas-datareader/issues/315). I did not rerun the notebook there.

**Comment by twiecki** [comment]
@junpenglao Did you try loading via Google? Interface is identical via pandas-datareader.

**Comment by junpenglao** [comment]
No as I never use Pandas-datareader. Trying now!

**Comment by ColCarroll** [comment]
that looks like a small file -- would it be better to download, check into `examples/data`, and read with `pd.read_csv(pm.read_data('stock_prices.csv'))`?

**Comment by twiecki** [comment]
@ColCarroll Good point.

**Comment by junpenglao** [comment]
@twiecki Using GoogleDailyReader there is no `'Adj Close'` (`prices.items -> Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')`), and the GDX data in `'Close'` are NaNs.

@ColCarroll I agree.

**Comment by twiecki** [comment]
This looks great, thanks!

**Comment by junpenglao** [comment]
Also, i find that Metropolis performs surprisingly well in GLM - in many cases out performs NUTS

**Comment by twiecki** [comment]
In low dimensional models?

**Comment by junpenglao** [comment]
yeah in GLM most model only has 2-3 hierarchies.

**Pull request merged**
