### PR TITLE
Rerun BEST and Euler-Maruyama

### PR DESCRIPTION
**Pull request by ColCarroll**
Updating some notebooks before release, focusing on those that haven't been updated in a while.  Euler-Maruyama used `%pylab inline`, which I have never seen before!

### CODE REVIEW

**Comment by fonnesbeck** [comment]
@ColCarroll I don't see an `inline` declaration anywhere in that notebook. Did you delete it?

**Comment by ColCarroll** [comment]
Yep - removed that call in favor of explicit `plt` and `np` calls. Also, [the link](http://docs.pymc.io/notebooks/Euler-Maruyama%20and%20SDEs.html) does not appear to be linked from the docs anywhere, though it looks very nice!

**Comment by fonnesbeck** [comment]
Wait, how do you get inline plots without either a `%matplotlib inline` or a `%pylab inline`?

**Comment by ColCarroll** [comment]
Hrm... now that you mentioned it, I haven't run that command in _months_.  Is it possible it is default on jupyter (lab?) now? It appears to be an open issue: https://github.com/ipython/ipython/issues/6424

**Comment by ColCarroll** [comment]
Closing - can rerun some more in the future.

**Pull request closed without merging**
