### PR TITLE
Fixed rugby_analytics.ipynb to run on Python 3.7.3 w/ PyMC3 3.8

### PR DESCRIPTION
**Pull request by kmcentush**
I was running through the example notebook and noticed that some aspects were no longer working in Python 3.7.3 and PyMC3 3.8.

Here's a list of the changes I made:
1. removed unused/confusing variables
2. updated bfmi and max_gr variables to properly format in the plot title string
3. changed pm.stats.quantile to np.quantile
4. reversed teams labels for forestplots (they were backwards)
5. properly normalized team placement percentages based on samples taken
6. updated the trace variable in "Covariate" to show that there is indeed no correlation; I found that the variable that was being plotted was highly correlated and confusing

Disclaimer: This is the first PR I've ever done on GitHub, so please let me know what I can do to help get this PR merged.

### CODE REVIEW

**Comment by ColCarroll** [comment]
This is great, thank you @kmcentush! 

I actually spent today working on porting this example to PyMC4, and it will be great to have a current implementation to compare to.

I'll merge this as soon as tests pass.

**Comment by eigenfoo** [comment]
@kmcentush thanks for doing this! For future reference, we recommend using our sister project [ArviZ](https://github.com/arviz-devs/arviz) for sampler statistics and visualizations, so perhaps a future PR could rework this notebook to use ArviZ. But this is still a great contribution!

P.S. congrats on your first PR to PyMC3!

**Comment by eigenfoo** [comment]
Looks like there was a test failure (Travis being picky again). Closing and reopening.

**Comment by eigenfoo** [comment]
Between both Travis runs, all test cases are passing! Merging now 😇

**Pull request merged**
