### PR TITLE
DOCS: AR(2) Example with Oil Data

### PR DESCRIPTION
**Pull request by springcoil**
I added a little Autoregressive model for oil price data. This could do with some more explanations but I felt it was a worthwhile snippet to add to the documentation. 
Can you all have a look @twiecki and @fonnesbeck so we can merge this in?

### CODE REVIEW

**Comment by springcoil** [comment]
Since this is just a document and makes no code changes I'll merge it in.

**Comment by springcoil** [comment]
Does something need to be done here @twiecki to get this onto the website?

**Comment by twiecki** [comment]
Yes, I'll have to compile it. Have you checked whether this recovers parameters on simulated data? I'm not totally convinced that the model is correct. Also, the title says it's ARMA but then later you say it's AR(2).

**Comment by springcoil** [comment]
Yeah you're right I'll restore that branch and do some edits to the title. Any suggestions on how to test it on simulated data - do i just generate things like you do for GLM?

**Comment by twiecki** [comment]
Right, exactly. Understanding the generating process also helps with formulating the model.

**Comment by springcoil** [comment]
Ok I'll have a look.

**Pull request merged**
