### PR TITLE
ENH: Added GARCH class and changed example (take 2)

### PR DESCRIPTION
**Pull request by springcoil**
Trying this again @twiecki 
@olafSmits  can you look at my code and tell me if I've correctly used the scan variable?
This is a fix of an earlier commit.

### CODE REVIEW

**Comment by olafSmits** [comment]
Hmm.. This won't work either I'm afraid! The problem is with the definition of `sd` / `sigma`. I actually have some code that might be working though... Shall I create another pull request?

**Comment by springcoil** [comment]
Please do!!

**Comment by springcoil** [comment]
Closed by https://github.com/pymc-devs/pymc3/pull/987

**Comment by springcoil** [comment]
Can anyone help me debug this? @twiecki @olafSmits

**Comment by springcoil** [comment]
Can anyone help me debug this? @twiecki @olafSmits resending out the alarm :)

**Comment by springcoil** [comment]
Can anyone help me debug this? I've some time free over the next two weeks.

**Comment by twiecki** [comment]
Maybe start by coding the generative process to have known parameters to recover.

**Comment by twiecki** [comment]
Closing due to inactivity, feel free to re-open when it's working.

**Pull request closed without merging**
