### PR TITLE
ReadMe doc updated

### LINKED ISSUE #7411: Include README example in docs homepage
### Description

https://github.com/pymc-devs/pymc?tab=readme-ov-file#linear-regression-example

⬇️

https://www.pymc.io/projects/docs/en/stable/learn.html

### PR DESCRIPTION
**Pull request by Adityajaiswal03**
## Description

Add the case study for plants growth in different enviroment

## Related Issue

- [x] Closes #7411 
- [ ] Related to #

## Checklist

- [ x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [x  Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Comment by Adityajaiswal03** [comment]
hi @ricardoV94,
I have raised a draft PR please review it and let me know for any changes.

**Comment by twiecki** [comment]
Sorry, I think this is the wrong place too. I was thinking of putting it on https://www.pymc.io/welcome.html which lives here: https://github.com/pymc-devs/pymc.io/blob/main/welcome.md

**Comment by Adityajaiswal03** [comment]
Okay @twiecki, I will add it to the specified file and raise a new PR.

**Comment by Adityajaiswal03** [comment]
@twiecki, could you kindly provide specific guidance on where to include it in the welcome file?

**Pull request closed without merging**
