### PR TITLE
Adding notebook with example of using a "black box" likelihood

### PR DESCRIPTION
**Pull request by mattpitkin**
This PR adds an [example notebook](http://mattpitkin.github.io/samplers-demo/pages/pymc3-blackbox-likelihood/) that describes creating a Theano Op for the "black box" likelihood function, including adding a `grad` method. This has been discussed on the [forum here](https://discourse.pymc.io/t/connecting-pymc3-to-external-code-help-with-understanding-theano-custom-ops/670).

The description probably still needs some tidying though! 

cc @junpenglao

### CODE REVIEW

**Comment by junpenglao** [comment]
Requested review from @aseyboldt and @ferrine who have more expert theano knowledge ;-)

**Review by ferrine — COMMENTED** [review]
Looks very good to me. There is nice motivation, somewhat simple solution (deserves a PR), and a kind warning that this might be a last resort method. 

What about the performance of logp_grad function? Could you please additionally profile them in the notebook?

**Comment by mattpitkin** [comment]
@ferrine At the end of the notebook I've added some tests that check that the gradient function I define is the same as that for the PyMC3 Normal distribution.

Would you like some profiling of the timings of the gradient function?

**Comment by junpenglao** [comment]
I think a sentence or two pointing to the possibility of doing profiling using http://docs.pymc.io/notebooks/profiling.html is enough. 
Also, small formatting nitpick: please follow https://github.com/pymc-devs/pymc3/issues/2834

**Comment by mattpitkin** [comment]
@junpenglao I've added profiling of the `logpt` function, which in my case also seems to profile the gradient, and included a link to the profiling notebook. I've also made some style changes and tried to adopt some of the formatting suggested in #2834. Should I remove the version info for everything other than PyMC3?

**Comment by junpenglao** [comment]
Looks great like this! Thanks a lot!

**Pull request merged**
