### PR TITLE
WIP notebooks cleanup

### PR DESCRIPTION
**Pull request by fonnesbeck**
Making sure all notebooks can run, and deleting poorly-maintained models.

Status:
- [ ] `discrete_find_MAP.ipynb` is broken, related to #1466 
- [ ] `cox_model` not generating correct results
- [ ] I cannot replicate the `NUTS_scaling_using_ADVI.ipynb` using current master. Broken for NUTS.

On my setup, the rest of the notebooks run as advertised. I've cleaned up a couple of them a little.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
The Cox survival notebook looks pretty sad next to Austin's survival notebook. I may have a go at moving whatever nuggets might be in the Cox notebook over to the newer one, and remove `cox_model.ipynb`.

**Comment by springcoil** [comment]
Ohh there's an error. However all sounds good to me. 
Leave the moving stuff from Cox to the survival notebook for version 3.0.1 :)

**Comment by fonnesbeck** [comment]
I notice that the Cox model notebook does not work. The ADVI estimates do not help the sampler at all, and the NUTS sampling is painfully slow.

Further comparison shows that the NUTS sampler gives different (wrong) values compared to Metropolis.

**Comment by springcoil** [comment]
Does anyone want to debug the Cox model? @AustinRochford maybe

**Comment by AustinRochford** [comment]
I can take a look at the Cox model, but not for a few days, as I will be traveling this weekend.

**Comment by twiecki** [comment]
This seems to have commits I made to master, does this need a rebase?

**Comment by fonnesbeck** [comment]
Those appeared after I rebased to master. Dunno.

**Comment by springcoil** [comment]
Maybe you need to edit manually your rebase - or something like that. I've had similar problems in the past no idea why they occur.

**Comment by fonnesbeck** [comment]
Closing in favor of #1535

**Pull request closed without merging**
