### PR TITLE
DOCS: Example added a cox model based on BUGS

### PR DESCRIPTION
**Pull request by springcoil**
I added a little example using Cox model from BUGS

### CODE REVIEW

**Comment by twiecki** [comment]
Not sure this has enough description to just drop in there with calls to `help(forestplot)`.

**Comment by springcoil** [comment]
Hi Thomas,
Yeah probably need some elaboration. Just wanted to put it down there as a
possible thing...

On Mon, Jul 11, 2016 at 9:54 AM, Thomas Wiecki notifications@github.com
wrote:

> Not sure this has enough description to just drop in there with calls to
> help(forestplot).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1231#issuecomment-231677556, or mute
> the thread
> https://github.com/notifications/unsubscribe/AA8DiLntY-Y_BxA4_bd1FETnY_zfXOcBks5qUgTOgaJpZM4JI7A5
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by fonnesbeck** [comment]
The estimates of beta should not all be zero, should they? Also, the optimization seems not to have converged.

A survival model wouldnt be bad, but it should be accompanied with a description of what survival modeling is trying to do, and what each piece of the model contributes.

More generally, we probably want to set some (informal) criteria regarding what gets added to the examples in the repo, and what gets added to the wiki. The former should probably be a small-ish subset of non-overlapping materials that are very well described and usable as teaching examples.

**Comment by springcoil** [comment]
Hey Chris,
Yeah this was a little hack I put together - I just wanted to get it up and
get some feedback on it.
I think there are some survival examples I could tile together.
Consider this a WIP until I get some proper time to cobble this together.

On Mon, Jul 11, 2016 at 4:26 PM, Chris Fonnesbeck notifications@github.com
wrote:

> The estimates of beta should not all be zero, should they? Also, the
> optimization seems not to have converged.
> 
> A survival model wouldnt be bad, but it should be accompanied with a
> description of what survival modeling is trying to do, and what each piece
> of the model contributes.
> 
> More generally, we probably want to set some (informal) criteria regarding
> what gets added to the examples in the repo, and what gets added to the
> wiki. The former should probably be a small-ish subset of non-overlapping
> materials that are very well described and usable as teaching examples.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1231#issuecomment-231768943, or mute
> the thread
> https://github.com/notifications/unsubscribe/AA8DiBHzcgO97uPUbdbN20EDKWqzG173ks5qUmCPgaJpZM4JI7A5
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by fonnesbeck** [comment]
Actually, this model is [already in the docs notebooks folder](https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/cox_model.ipynb).

**Comment by springcoil** [comment]
Cool then not needed

**Pull request closed without merging**
