### PR TITLE
Pin blackjax to lowest conda-compatible version in CI

### PR DESCRIPTION
**Pull request by ricardoV94**
## Description

~~Trying to understand why did blackjax tests start failing if we're pinning everything~~ We were only lower pinning blackjax

https://github.com/conda-forge/jaxlib-feedstock/issues/249

## Related Issue

- [x] Related to #7317 

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7320.org.readthedocs.build/en/7320/

### CODE REVIEW

**Comment by ricardoV94** [comment]
CI is fixed

**Review by junpenglao — APPROVED** [review]
newer version of JAX is still not on Conda? hmmmm...

**Comment by ricardoV94** [comment]
> newer version of JAX is still not on Conda? hmmmm...

For a while now, see @twiecki issue: https://github.com/conda-forge/jaxlib-feedstock/issues/249

**Review by twiecki — APPROVED** [review]

**Comment by ricardoV94** [comment]
@junpenglao you may want to lower pin jax/jaxlib version in blackjax, since it is no longer compatible with the old clip API

**Review by michaelosthege — APPROVED** [review]

**Pull request merged**
