### PR TITLE
Yet another fix for text floatX behavior

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
This is my third attempt at getting approval for fixing the text backend (and tests) on GPU platforms.  If we can't agree on one of them I'm switching to Stan :)

### CODE REVIEW

**Comment by twiecki** [comment]
I don't have specific issues with any of the fixes. But your point that the backend and model could well have different dtypes makes sense. Which is your favorite PR? :)

**Comment by kyleabeauchamp** [comment]
I'm happy with either.  The modified tests has the advantage of not touching the backend code (e.g. less chance to break anything), but this one has the advantage of building and formally testing round-tripping dtype invariance.  Up to you.

**Comment by kyleabeauchamp** [comment]
wait, py3k bug in the current one.

**Comment by kyleabeauchamp** [comment]
py27 bug, actually.  I'll fix it when I get home tonight.

**Comment by kyleabeauchamp** [comment]
OK fixed.

**Comment by kyleabeauchamp** [comment]
Choice of which PR to merge is your call.

**Comment by twiecki** [comment]
OK, this PR is exactly what I was getting at, thanks!

**Pull request merged**
