### PR TITLE
Convert docs to sphinx

### PR DESCRIPTION
**Pull request by twiecki**
- Removes `mkdocs`.
- Adds `nbsphinx` to include example notebooks.
- Allows generation of API docs.

### CODE REVIEW

**Comment by springcoil** [comment]
Awesome!

**Comment by springcoil** [comment]
I added https://github.com/pymc-devs/pymc3/pull/1124 this - because it needs numpydocs. I did a seperate commit for that. Might be worth retrying this when we get that merged into master.

**Comment by twiecki** [comment]
This is starting to shape up nicely, only problem is: https://github.com/spatialaudio/nbsphinx/issues/49

**Comment by twiecki** [comment]
OK, new docs can be checkout out here: http://pymc-devs.github.io/pymc3/ What do you think @fonnesbeck @springcoil?

**Comment by springcoil** [comment]
Awesome :)

**Comment by springcoil** [comment]
@twiecki - made a few changes and added in my Ipynb

**Comment by springcoil** [comment]
Hey @twiecki do you think it's alright to merge this in? Or do we need to fix some of the errors first?

**Comment by twiecki** [comment]
I want to get a pair of eyes from @fonnesbeck first.

**Comment by springcoil** [comment]
No problem :)

On Tue, May 24, 2016 at 10:46 AM, Thomas Wiecki notifications@github.com
wrote:

> I want to get a pair of eyes from @fonnesbeck
> https://github.com/fonnesbeck first.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1122#issuecomment-221219282

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by fonnesbeck** [comment]
Will take a peek today.

**Comment by fonnesbeck** [comment]
Should probably change/remove `howto_docs.md`

**Comment by fonnesbeck** [comment]
We've got some bad JSON in `Bayesian_LogReg.ipynb`:

```
Unreadable Notebook: /Users/fonnescj/Repositories/pymc3/docs/source/notebooks/Bayesian_LogReg.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\ncells: [\\n{\\ncell_type: "markdown",\\...',)
```

**Comment by twiecki** [comment]
@fonnesbeck fixed.

**Comment by fonnesbeck** [comment]
Looks nice. Might be an opportunity to thin out our notebooks a little. It they aren't documented well enough to be included in the docs' notebooks examples (e.g. categorical.ipynb, GHME2013.ipynb) we should probably remove them from the repository entirely. Some may be worth improving and cleaning up.

**Comment by twiecki** [comment]
@fonnesbeck Good point, removed those two.

**Comment by twiecki** [comment]
Good to merge?

**Comment by fonnesbeck** [comment]
I think so. Looks good.

**Pull request merged**
