### PR TITLE
Add Zenodo DOI badges and citation instructions

### PR DESCRIPTION
**Pull request by michaelosthege**
Zenodo DOIs are now created automatically.

@fonnesbeck I think you can log in there to specify further metadata

This PR adds the DOIs to the main readme. I'm not great with restructured text formatting; please just add/commit changes as you see fit.

### CODE REVIEW

**Review by OriolAbril — COMMENTED** [review]
Changes look good so far, we should also update the documentation home page and the "about pymc3" page.

https://github.com/pymc-devs/pymc3/blob/master/docs/source/index.rst#citing-pymc3

https://docs.pymc.io/about.html#citing-pymc3

**Comment by castelao** [comment]
> Zenodo DOIs are now created automatically.
> 
> @fonnesbeck I think you can log in there to specify further metadata

@michaelosthege & @fonnesbeck, you indeed can log in there to specify further metadata, or you can add a descriptor here as `.zenodo.json`. Check this https://github.com/castelao/inception for more details.

**Comment by michaelosthege** [comment]
Thanks for the info @castelao !
In my opinion we have too many files at the root level of the repo already. Therefore I would prefer to set the metadata in Zenodo. @fonnesbeck how do you want to proceed?

**Comment by fonnesbeck** [comment]
If the metadata is something that gets updated regularly (e.g. releases), then its best to have it in the repo, but if it is completely static then I agree it should be set on Zenodo. 

I did notice that you can keep track of citations in the metadata; if we wanted to do that, then it should be in the repo.

**Comment by fonnesbeck** [comment]
It looks like a pretty static file, except for contributors, which I doubt we want to try and keep up to date in the DOI metadata.

**Comment by castelao** [comment]
I believe that every release Zenodo creates a new DOI and fills only the basic metadata that it can guess. If that is correct, whatever metadata you edit manually at Zenodo would require to repeat that on every release.

If there is interest, it might be worth recording references (linking papers' DOIs) with related_identifiers[{"relation": "references", ...}], and contributors[{"type": "Sponsor", ...}] if any.

**Comment by michaelosthege** [comment]
> 
> 
> I believe that every release Zenodo creates a new DOI and fills only the basic metadata that it can guess. If that is correct, whatever metadata you edit manually at Zenodo would require to repeat that on every release.
> 
> If there is interest, it might be worth recording references (linking papers' DOIs) with related_identifiers[{"relation": "references", ...}], and contributors[{"type": "Sponsor", ...}] if any.

In my experience Zenodo associates the metadata with the whole project and replicates it for new releases. Only the list of contributors is gathered from the git history.

**Review by fonnesbeck — APPROVED** [review]

**Pull request merged**
