### PR TITLE
SMC change initialization

### PR DESCRIPTION
**Pull request by aloctavodia**
Unfortunately #2749 is not a general solution of #2742. The problem arise when asking for random samples for distributions that have other distributions as parents, for example the `z` variable in @junpenglao example (https://github.com/pymc-devs/pymc3/issues/2742#issuecomment-351090395). I am under the impression this problem have arisen before. 

This PR takes a different approach, instead of getting samples from the prior by using random methods of each distribution, it just sample from the prior using `metropolis`. It seems to work OK, so far but I will like to run more tests to ensure this is a good approach.

### CODE REVIEW

**Comment by junpenglao** [comment]
hmm, I am not sure this will actually work, as using metropolis is not the same as direct sampling from the prior

**Comment by aloctavodia** [comment]
Hi @junpenglao I also had may concerns at first but then I realize that to get proper samples using SMC, you only need to start from any easy to sample distribution that covers the entire solution space and then slowly move from this distribution to the posterior distribution. Starting from the prior is just one convenient choice. In other domains (like statistical mechanics) where priors are not explicit, methods similar to SMC start from a _high temperature_ that is equivalent to start from a _flatter_ distribution and then slowly _cool down_ the system.

The computation of the samples seems to be more or less insensitive to the details of the starting distribution, I use for example over-dispersed points. Contrary to this the computation of the  `marginal likelihood` seems to be much more sensitive to the starting choice, one of the assumptions in the computation of the `marginal likelihood` using SMC is that the normalizing constant of the samples from the first stage is 1. Also the `marginal likelihood` should be sensitive to how fast you move from the initial distribution to the posterior distribution... I have been trying to improve the computation of the  `marginal likelihood`, but is still very off for some models.

**Comment by junpenglao** [comment]
Thanks for the explanation!
also cc @hvasbath

**Comment by aloctavodia** [comment]
And we are back to initialize directly from the prior!!!

I also changed the way SMC auto-tune Metropolis proposal distribution. I basically follow the recommendations in [Transitional Markov Chain Monte Carlo Method for Bayesian Model Updating, Model Class Selection, and Model Averaging](https://ascelibrary.org/doi/abs/10.1061/%28ASCE%290733-9399%282007%29133%3A7%28816%29). Briefly, they recommend to multiply the _weighted covariance matrix_ (`calc_covariance()` inside SMC) by a scaling factor of 0.04. @hvasbath maybe can provide reasons against this change or correct me if I am doing something wrong about the tuning...

**Comment by hvasbath** [comment]
Hey guys! Thanks a lot for this explanation @aloctavodia ! I was totally unaware of these things as I am no statistician. I prefered to have the tuning adaptively based on the acceptance rate as it was already in the metropolis. Removing the adaptive scaling maybe better for some models but I found it was much better performing for my type of problems. Having the algorithm adaptively how it was, is from the Minson 2013 paper mentioned in the doc string. As I mentioned this implementation is not exactly the same as in the TMCMC paper. Just parts of it. So I would vote agains removing the adaptive scaling. If you dont want any adaptation simply set tune=False and set scaling=0.4 when you initialise the sampler .... But again if this interferes with calculating the evidence then we should discuss it further of course. SO for my problems the adaptive stepping is really important.

Ah cool I just saw that you worked on getting it working for transformed variables as well! Awesome! Good job!

**Comment by aloctavodia** [comment]
@hvasbath Thanks for the feedback I will go back with the tunning changes. It is very interesting that your models works better with the metropolis auto-tunning and worst with the weighed  covariance scaling, probably this, together with the results I am getting for the marginal likelihood are indications that there is room for improvement in the computations of the weights, I will work on this. Could you send me (maybe by e-mail) one of your models, I would like to have some real-world models beside my own to test SMC.

**Comment by hvasbath** [comment]
All my real world models are in my "beat" repository. In src/models.py, but I fear the coding there maybe a little unusual for you. Also you would need some data which I would have to send you. As it is a real world application you have quite some other dependencies. In the website there is a description how to install beat and its dependencies. If you want to try it. I fear I have no simpler example- sorry for that!

**Comment by aloctavodia** [comment]
Thanks @hvasbath. I will take a look at beat.

**Comment by hvasbath** [comment]
If I am not mistaken @junpenglao also had some real world applications which seemed much simpler to be implemented. Maybe you could do testing on one of his models as well in case getting beat to run takes too much time.

**Comment by junpenglao** [comment]
I have codes to compare mixed effect model (with simulation and real data) in https://github.com/junpenglao/GLMM-in-Python

**Pull request merged**
