### PR TITLE
ENH Allow passing of greek unicode symbols to specificy variable names.

### PR DESCRIPTION
**Pull request by twiecki**
Super simple hack of allowing specification of RVs using greek unicode characters:
image

Whoever named the Normal parameter `sd` instead of `sigma` deservers whatever is coming for him or her. Oh wait, that was me 😠 . Fixed in https://github.com/pymc-devs/pymc3/pull/3309.

### CODE REVIEW

**Comment by junpenglao** [comment]
Eh...... Sorry Thomas but I dont like this: it is difficult to type, so at the end of the days it is more for demonstration than any practical usage - there is a reason why ppl say "it is all greek to me"...

**Comment by twiecki** [comment]
Why hard to type? Just do `\theta` and hit tab in jupyter. @fonnesbeck and I use that all the time.

**Comment by junpenglao** [comment]
Let the Internet decide ;-)
https://twitter.com/junpenglao/status/1075021124889665537

**Comment by fonnesbeck** [comment]
I’d be happy with Greek being accepted, as long as its not the keyword in the function signature. What Thomas has proposed shouldn’t bother anyone who does not care for or know about Unicode Greek.

**Comment by twiecki** [comment]
yeah this is an issue where there is no internal or external agreement so I
think you'll just have to decide.

**Comment by twiecki** [comment]
Closing as we couldn't reach consensus.

**Pull request closed without merging**
