### PR TITLE
DOCS - Adding in explanation of counter intuitive behaviour of Logp

### PR DESCRIPTION
**Pull request by springcoil**
I've screwed up this branch - definitely don't merge yet. 
- Fixed now.

### CODE REVIEW

**Comment by springcoil** [comment]
@junpenglao I'm a bit confused about the documentation - do I submit the ipynb with the cells run or does someone else run them?

**Comment by junpenglao** [comment]
I think you should submit with the cell run, @twiecki?

**Comment by springcoil** [comment]
I'll submit with the cell run then.

**Review by junpenglao — APPROVED** [review]
LGTM.

**Comment by springcoil** [comment]
cc - https://github.com/pymc-devs/pymc3/issues/2489

**Comment by twiecki** [comment]
Definitely need the outputs.

**Comment by springcoil** [comment]
Thanks @twiecki I just ran it now. I wasn't sure if we did or not.

**Comment by twiecki** [comment]
LGTM.

**Comment by springcoil** [comment]
Going to merge it in now once the checks complete :)

**Comment by ferrine** [comment]
What about having fn cache that is cleaned after new var is added?

**Comment by springcoil** [comment]
Hmm that might work - do you have a toy example to illustrate?

**Comment by aseyboldt** [comment]
I think it is cleaner to return objects that encapsulate the functions. There is also other state to keep track of, for example the mapping between array space and dict space. When we add more variables, the meaning of an array changes. That is cleaner if it is all part of a separate object, that itself is immutable. It also makes it much easier to see where something is compiled, which makes tracking down errors or slowdown easier. Something like `model.logp_dlogp_function()`.

**Pull request merged**
