### PR TITLE
Add type hints to distribution parameters

### PR DESCRIPTION
**Pull request by iykat**
**What is this PR about?**
...Added type hints to distribution parameters
issue #5358
#DataUmbrellaPyMCSprint
@reshamas @cluhmann @SangamSwadiK 

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues (preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Documentation
- ... Updated some of the typings in the distribution parameter.

----
:books: Documentation preview :books:: https://pymc--6635.org.readthedocs.build/en/6635/

### CODE REVIEW

**Comment by reshamas** [comment]
#DataUmbrellaPyMCSprint

**Comment by cluhmann** [comment]
This looks good to me.  The one omission is `alpha=0.0` in the Wald distribution.  I suspect that it's also of type `Optional[DIST_PARAMETER_TYPES]` but default to `=1.0` rather than `=None`.

**Comment by iykat** [comment]
> This looks good to me. The one omission is `alpha=0.0` in the Wald distribution. I suspect that it's also of type `Optional[DIST_PARAMETER_TYPES]` but default to `=1.0` rather than `=None`.

Thank you for the feedback. I will make the necessary changes.

**Comment by iykat** [comment]
@cluhmann I have added more type hints to distribution parameters and typed the Wald distribution as you suggested.

**Review by cluhmann — APPROVED** [review]
Looks great to me. I am going to approve this to get the workflows working and then we can see where things are at.  Someone should sanity check the changes just to make sure I haven't missed anything before merging.

**Comment by cluhmann** [comment]
I lied (I'm not qualified). Can someone review so we can see how all the CI shakes out?

**Comment by reshamas** [comment]
Note:  This PR was submitted using Gitpod!

**Review by ricardoV94 — APPROVED** [review]

**Comment by cluhmann** [comment]
If I am reading the log correctly, this seems to be some plotting/Tcl error on windows?  Does that have anything to do with this PR?

**Comment by ricardoV94** [comment]
If it's the GP test it crops up now and then. No idea why

**Comment by cluhmann** [comment]
Ah. That seems to be it.

> def test_plot_gp_dist_warn_nan(self):

**Pull request merged**
