### PR TITLE
Fix #2577 and #2626

### LINKED ISSUE #2577: rendering error in Readme.rst
There seems to be some problem in the rendering, also the links are not working:
screenshot from 2017-09-19 11-35-14

### PR DESCRIPTION
**Pull request by Naereen**
This should fix the inconsistent rST markup in README.rst (see Fix #2577 and #2626).

At least it fixes the display on GitHub website, can anyone confirm that it will not break the links in the doc?

### CODE REVIEW

**Comment by Naereen** [comment]
(Note that if this syntax (simple relative links) don't work, I don't know any rST syntax that can be used to have both relative links on GitHub website and resolved references on the Sphinx doc...)

**Comment by fonnesbeck** [comment]
These look great -- thanks for the fix.

**Comment by Naereen** [comment]
Great! :smile:

**Comment by junpenglao** [comment]
Actually, this breaks the links on docs.pymc.io (see http://docs.pymc.io/#if-you-already-know-about-bayesian-statistics)
Also on the GitHub project page it links to 404.
Should we just replace it with the website link (e.g., http://docs.pymc.io/notebooks/api_quickstart)?

**Comment by Naereen** [comment]
@junpenglao Oh sorry.
Yes, do as you say, replace with hard coded links if it works. (that's my suggestion, not an order :wink: )

**Comment by junpenglao** [comment]
No problem - I will do that if nobody has a better solution.

**Comment by motatoes** [comment]
Yes I guess absolute links will fix it for both github and the docs site. These links are currently broken in the readme file and need updating:

- Getting started guide -> http://docs.pymc.io/notebooks/getting_started
- API quickstart guide -> http://docs.pymc.io/notebooks/api_quickstart
- PyMC3 tutorial -> http://docs.pymc.io/notebooks/getting_started

**Comment by twiecki** [comment]
@motatoes Want to make a PR?

**Comment by motatoes** [comment]
@twiecki Yes I'll do that now.

**Pull request merged**
