### PR TITLE
BUG Initialize adapt_full with a diagonal covariance matrix rather than ones.

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Review by eigenfoo — APPROVED** [review]
Oof, not sure how that slipped by me the first time! This looks good: will merge once tests pass.

**Comment by fonnesbeck** [comment]
Oops. Good catch.

**Comment by fonnesbeck** [comment]
Not sure if its a coincidence, but I've been getting sampling failures like this after updating:

```
ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `sigma_log__`.ravel()[0] is zero.
The derivative of RV `sigma_log__`.ravel()[1] is zero.
The derivative of RV `sigma_log__`.ravel()[2] is zero.
The derivative of RV `sigma_log__`.ravel()[3] is zero.
The derivative of RV `sigma_log__`.ravel()[4] is zero.
The derivative of RV `sigma_log__`.ravel()[5] is zero.
The derivative of RV `sigma_log__`.ravel()[6] is zero.
The derivative of RV `sigma_log__`.ravel()[7] is zero.
```

**Comment by twiecki** [comment]
Using this init?

**Comment by fonnesbeck** [comment]
Yeah, but now it seems to be happening for other init methods, so it must have been a coincidence. Please ignore.

**Comment by ColCarroll** [comment]
Still might want to init this like the `diagonal + jitter` (i.e., use the mean plus some random noise -- shoudl be a copy/paste)

**Comment by ColCarroll** [comment]
I can get to it later if no one else does!

**Comment by twiecki** [comment]
Great!

**Pull request merged**
