### PR TITLE
Don't broadcast in alltrue

### PR DESCRIPTION
**Pull request by AustinRochford**
Addresses #1449

### CODE REVIEW

**Comment by AustinRochford** [comment]
@twiecki `test_alltrue_shape` fails on the current master and passes on this branch

**Comment by twiecki** [comment]
Nice, looks simple (and logical) enough. I trust it wasn't as straightforward to derive at that solution though.

**Comment by AustinRochford** [comment]
It was pretty simple--the hardest part was getting the tests to pass locally (even on master).

**Comment by twiecki** [comment]
So even the geweke passes locally for you now?

**Comment by AustinRochford** [comment]
Yes, on Python 3.5 with the conda env created by `create_testenv.sh`.  Still does not pass on Python 2.7 locally, though.

**Comment by twiecki** [comment]
Travis at least didn't have a problem on 2.7.

**Pull request merged**
