### PR TITLE
Fixing bug when working with discrete and continuous variables using Metropolis step with blocked=True

### LINKED ISSUE #2916: Metropolis working with discrete and continuous variables
For the metropolis step when working with both continuous and discrete variables and when blocked='True' (so updating all parameters together) there is an error that the continous variables are of integer type. This is because in the metropolis script:

```python
        if self.any_discrete:
            if self.all_discrete:
                delta = np.round(delta, 0).astype('int64')
                q0 = q0.astype('int64')
                q = (q0 + delta).astype('int64')
            else:
                delta[self.discrete] = np.round(
                    delta[self.discrete], 0).astype('int64')
                q = (q0 + delta).astype('int64')
        else:
            q = floatX(q0 + delta)
```
     
q = (q0 + delta).astype('int64') transform the numpy vector containing all the variables into a vector that can contain only int. As you can not have different types of variables in a numpy vector 

I fixed my local version of the code with:
```python
        if self.any_discrete:
            if self.all_discrete:
                delta = np.round(delta, 0).astype('int64')
                q0 = q0.astype('int64')
                q = (q0 + delta).astype('int64')
            else:
                delta[self.discrete] = np.round(
                    delta[self.discrete], 0)
                q = (q0 + delta)
        else:
            q = floatX(q0 + delta)`
```
This should maybe be a pull request but I'm not that confident that my solution is the most efficient/elegant one.

### PR DESCRIPTION
**Pull request by charlotteburki**
fixed #2916

### CODE REVIEW

**Comment by ColCarroll** [comment]
This looks fine to me, but basically undoes #1550, which fixed a bug preventing PyMC3 from running on Windows.

Does anyone have a windows machine to try to run the [coal mining example](http://docs.pymc.io/notebooks/getting_started) with this change?  I did not read too carefully about the issue, but it looked possible that it got fixed on the theano side.

**Comment by charlotteburki** [comment]
I have tested it with a problem containing both continuous and discrete variables on windows. I can test tomorrow the coal mining example as well just to be sure.

**Comment by charlotteburki** [comment]
The coal mining example works. But it doesn't go through the 'if condition' I changed:


```python
        if self.any_discrete:
            if self.all_discrete:
                delta = np.round(delta, 0).astype('int64')
                q0 = q0.astype('int64')
                q = (q0 + delta).astype('int64')
            else:
                delta[self.discrete] = np.round(
                    delta[self.discrete], 0)
                q = (q0 + delta)
        else:
            q = floatX(q0 + delta)
```

It goes in the if self.all_discrete: condition. Because in the metropolis step all the variables are discrete. 

So it doesn't test the proposed modification.

**Comment by junpenglao** [comment]
Anybody else could think of a potential test case that might fail under windows?

**Comment by charlotteburki** [comment]
This is how I noticed the error, fixed it and tested the fix on windows.

https://github.com/charlotteburki/example

I made other modifications to the Metropolis function that shouldn't have any impact on the modification proposed here. All the supplementary changes that I made to the Metropolis function are written in the read me.

**Comment by ColCarroll** [comment]
Merging since existing tests pass, code looks good, and it looks like the original bug no longer exists. If we get bug reports from windows users on master, it will be easy enough to revert.
 
Thanks for taking that extra look, and congrats on first contribution!

**Pull request merged**
