### PR TITLE
Changed PytTensor import alias to pt

### LINKED ISSUE #7411: Include README example in docs homepage
### Description

https://github.com/pymc-devs/pymc?tab=readme-ov-file#linear-regression-example

⬇️

https://www.pymc.io/projects/docs/en/stable/learn.html

### PR DESCRIPTION
**Pull request by Krupakar-Reddy-S**
## Related Issue

- [ ] Closes #7411
- [ ] Related to #7446

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pymc--7449.org.readthedocs.build/en/7449/

### CODE REVIEW

**Comment by Krupakar-Reddy-S** [comment]
pre-commit.ci autofix

**Comment by Krupakar-Reddy-S** [comment]
@twiecki Still getting `Output ()` when model is trained, is this due to running online on Colab?
I will try locally.

**Comment by Krupakar-Reddy-S** [comment]
@twiecki now the output renders correctly.
Running it locally worked :)

**Comment by twiecki** [comment]
Looks great, any idea where the diff is so large?

**Comment by Krupakar-Reddy-S** [comment]
I had vcs issue with connecting to my remote branch, so had to delete `pymc_overview.ipynb` and replace it with the one i made chnages with ;(

**Comment by twiecki** [comment]
can you make a fresh branch and make only that single change?

**Pull request closed without merging**
