### PR TITLE
align minibatches

### PR DESCRIPTION
**Pull request by ferrine**
sometimes rngs are not aligned, so this function can help

### CODE REVIEW

**Comment by twiecki** [comment]
LGTM.

**Comment by gBokiau** [comment]
Hi guys,

I'm presuming that in the presence of multiple minibatches in a model, this would allow the same rows to be sampled at each iteration.

Any chance for a quick write up on how this might work?

In particular, is this supposed to be called during model definition, or as a callback of sorts?

**Comment by gBokiau** [comment]
From what I'm gathering this should best be called right before fitting, as model construction (again, purely guessing what I'm observing) might break alignments if some minibatches are used more than once and/or altered, dimshuffled or otherwise transformed in the model declaration.

**Comment by ferrine** [comment]
Yes, alignment should be done right before any action that involves them. No need to rerun notebook after occasional `minibatch. eval()`

**Pull request merged**
