### PR TITLE
Update radon example NB

### PR DESCRIPTION
**Pull request by AlexAndorra**
Finally got time to finish this PR 🍾 
I noticed [on Discourse](https://discourse.pymc.io/t/hierarchical-regression-models-for-ratings-data-2-by-2-within-subject-design/4206) that [the radon notebook](https://docs.pymc.io/notebooks/multilevel_modeling.html) is often used as an introduction to hierarchical models, but several questions were recurring so I thought it'd useful to:

- Update with new code and versions of PyMC and ArviZ
- Replace flat priors by weakly regularizing ones (both to encourage best practices and to preemptively answer Discourse questions)
- Add prior predictive checks
- Replace the section about varying-slopes only by a model including the covariance between varying slopes and varying intercepts
- Implement non-centered versions of the hierarchical models (this is necessary in this case to get rid of divergences + we often get questions about that, so this will hopefully be a useful ressource)
- Update and add graphs
- Do some miscellaneous changes

First PR on the main repo (🎉 ), so tell me if I forgot anything. And of course I'm available for any change.
Happy new year & PyMCheers 🖖

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Thanks for doing this! -- its definitely an upgrade.

A couple of notes:
- for didactic purposes, it might be best to separate sampling and posterior predictive sampling into tow different cells (at least for the first time it is presented)
- spelling: should be "envelope" (a noun) not "envelop" (a verb)
- its probably best to use `cores=2` rather than `chains=2` in calls to `sample`, as for some systems (e.g. Colab, some Chromebooks) the latter will result in sequential sampling of chains.
- add `plt.tight_layout()` call to multi-panel plots to make the labels more readable (at least the ones showing the county-wise estimates)
- why not use the symbol ρ rather than spelling out "Rho", since we use symbols for the other Greek letters?

**Comment by AlexAndorra** [comment]
Thanks Chris! 
I integrated all your points and I just had a small remaining question: I removed `chains=2` and didn't specify a number of `cores` (since I understood that parallel sampling is not possible on Windows), but now the fit is worse for complex models (starting from `varying_intercept_slope`): some divergences and the acceptance probability does not match the target. 
Do you know what could be the cause? (Running on Mac, 4 chains in 4 job)

**Comment by AlexAndorra** [comment]
Ok I think I figured it out: it needed a mix of increased tuning and higher target accept. Pushing the changes ;)

**Comment by aloctavodia** [comment]
Good to see you around @AlexAndorra, I just added a couple of super minor comments. I really like what you did with this notebook.

**Comment by AlexAndorra** [comment]
Ha ha thx Osvaldo, glad to be around too - the neighborhood is pretty cool 😉

**Pull request merged**
