### PR TITLE
DOC simplify line in getting_started notebook

### PR DESCRIPTION
**Pull request by MarcoGorelli**
First, thanks for this amazing library and for your great tutorials!

Reading through the _getting_ _started_ notebook, it took me longer than I'm proud to admit to figure out what was going on in this line, so I'm suggesting a slight simplification for the sake of readability

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Thanks @MarcoGorelli, this does look much simpler 😅 One question before approving: did you run this part of the NB to make sure it's giving back the same results?

**Comment by MarcoGorelli** [comment]
> Thanks @MarcoGorelli, this does look much simpler sweat_smile One question before approving: did you run this part of the NB to make sure it's giving back the same results?

Hey @AlexAndorra  - thanks, and yes, I did run it to check that the output stays the same.

General question about contributing changes to notebooks - should I make a change, restart and run the entire notebook and then push the entire thing, or is it preferable to keep the diff as small as possible and just stage the parts which changed?

**Comment by AlexAndorra** [comment]
I'd say it depends: when the NB is small, you might as well re-run it entirely, to give you a chance of discovering new changes that needs to be made. Here, the NB is quite long, so just re-running the appropriate bunch of cells is probably best. It seems that the plot wasn't re-generated though -- unless ReviewNB has a small glitch 🤔 
Also, you can take a look at the [style guide we enforce for NBs](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style) 😉

**Comment by MarcoGorelli** [comment]
> It seems that the plot wasn't re-generated though -- unless ReviewNB has a small glitch thinking

I don't know, but here's what I see if I open this PR in reviewnb:

image


> Also, you can take a look at the [style guide we enforce for NBs](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style) wink

Ah, nice, thanks! For the first point (sorted imports), it looks like it's encouraged, but is it checked anywhere as part of CI? In case it's useful to you, I have a command-line / pre-commit tool for this (https://github.com/nbQA-dev/nbQA), which allows you to run e.g.
```
nbqa isort docs/source/notebooks/Bayes_factor.ipynb --treat-comment-as-code "# %%" --lines-between-types=1 --check-only
```

**Comment by AlexAndorra** [comment]
> I don't know, but here's what I see if I open this PR in reviewnb

Yeah, I see the same, which is what's weird: when the graph has been re-generated, it is supposed to be surrounded by a green line. But if you tell me you reran this section of the NB I'll trust you and approve -- I'll wait a bit before merging, in case others have comments.

> For the first point (sorted imports), it looks like it's encouraged, but is it checked anywhere as part of CI? In case it's useful to you, I have a command-line / pre-commit tool for this

This is not checked in our CI pipelines but I think it'd definitely be great to do it! It looks like your tool can check imports and run Black, so we could enforce a big part of the style guide automatically 👌 Would you like to do a PR to set that up?

**Review by AlexAndorra — APPROVED** [review]

**Comment by MarcoGorelli** [comment]
> Would you like to do a PR to set that up?

Sure!

ps. I'm a huge fan of your podcast, thanks for your work!

**Comment by AlexAndorra** [comment]
> Sure!

Awesome, looking forward to it! Feel free to ask if you have questions.

> I'm a huge fan of your podcast, thanks for your work!

Ah thanks, really appreciate it! Funny to bump into listeners here 😆 #BayesianNetwork

**Pull request merged**
