### PR TITLE
Fix do/conditioning model docs

### LINKED ISSUE #6935: Put fgraph and conditioning model transforms inside model header in API Docs
image

These last two entries should be listed inside the Model entry.

`change_value_transforms` and `remove_value_transforms` should show in the sub-header as well:
image

And not only under Others:

image

Also the rendering of these code examples seems broken:

https://www.pymc.io/projects/docs/en/v5.8.2/api/model/transform/generated/pymc.model.transform.conditioning.change_value_transforms.html

https://www.pymc.io/projects/docs/en/v5.8.2/api/model/transform/generated/pymc.model.transform.conditioning.remove_value_transforms.html

### PR DESCRIPTION
**Pull request by juanitorduz**
Closes https://github.com/pymc-devs/pymc/issues/6935

- [x] Tested locally ✅ 

----
:books: Documentation preview :books:: https://pymc--6936.org.readthedocs.build/en/6936/

### CODE REVIEW

**Comment by juanitorduz** [comment]
https://github.com/pymc-devs/pymc/actions/runs/6365114498/job/17281883580 `mypy` ¯\\_(ツ)_/¯?

**Review by twiecki — APPROVED** [review]

**Comment by ricardoV94** [comment]
"Model" is not showing a dropdown arrow: 
image

Perhaps because it's centered around model/core.py?

**Comment by juanitorduz** [comment]
@ricardoV94 I think I fixed it in https://github.com/pymc-devs/pymc/pull/6936/commits/ec9a87478c680bfdc0dbb6c3df88575829028219 Let me know what you think :)

**Comment by ricardoV94** [comment]
Looks better but now there's a weird Model section under the outer Model drop down

**Comment by juanitorduz** [comment]
> Looks better but now there's a weird Model section under the outer Model drop down

Yeah ... but shall we name is as "Model  Core"?

**Comment by ricardoV94** [comment]
I think we only need a section for "create and inspect model" which includes the stuff in "core"

**Comment by juanitorduz** [comment]
ok https://github.com/pymc-devs/pymc/pull/6936/commits/91d29ce539b7c7ed2b15061906d355c97b834606 removed the redundant section. WDYT?

**Comment by ricardoV94** [comment]
We should have the Deterministics / Potential and set_data that used to be in Model/other in the model creation and inspection page.

Otherwise looks good to me

**Comment by juanitorduz** [comment]
Hopefully https://github.com/pymc-devs/pymc/pull/6936/commits/0103e1701ae81782e80a4d893e2b430aaf8b8023 will do

**Comment by ricardoV94** [comment]
> I think https://github.com/pymc-devs/pymc/pull/6936/commits/0103e1701ae81782e80a4d893e2b430aaf8b8023 should do it :)

I just *observed* that it *do*es :P

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Thanks @juanitorduz

**Pull request merged**
