### PR TITLE
Implement robust U-turn check

### PR DESCRIPTION
**Pull request by junpenglao**
Following the recent discussion on the Stan side: https://github.com/stan-dev/stan/pull/2800

### CODE REVIEW

**Comment by junpenglao** [comment]
Thanks to @aseyboldt's design, adding additional U turn check to pymc3 NUTS is actually pretty straightforward, because we are already saving the beginning and the end point of each tree trajectory.

**Comment by twiecki** [comment]
Looks like this needs a rebase.

**Comment by aseyboldt** [comment]
This looks good to me, I'd be in favor of merging.

**Review by aseyboldt — APPROVED** [review]

**Comment by ColCarroll** [comment]
+1 I'll also leave this here for us to keep an eye on :D 

https://pandas.pydata.org/speed/pymc3/

**Comment by twiecki** [comment]
👍

**Pull request merged**
