### PR TITLE
Add LKJ covariance prior example

### PR DESCRIPTION
**Pull request by AustinRochford**
@twiecki in response to https://twitter.com/twiecki/status/780770116871004161

### CODE REVIEW

**Comment by twiecki** [comment]
Fantastic, thanks @AustinRochford. I realized one thing, in https://github.com/pymc-devs/pymc3/pull/1398 we allow to pass `cov` directly to `MvNormal` which would make this example even more concise. Anyway, will have to merge that first.

**Review by springcoil — CHANGES_REQUESTED** [review]
Perhaps change this example based on the cov/ tau changes that Thomas Wiecki mentioned.

**Comment by twiecki** [comment]
Can you fix the headings? Title should be `# Title`, subtitles `## subtitle` etc. Also, feel free to add your author name and a link to your blog / twitter to the top if you want.

Typo: visuall -> visually

**Comment by twiecki** [comment]
Also `theano.tensor` should be imported as `tt`, not `T`.

**Comment by AustinRochford** [comment]
@twiecki @springcoil I think that should do it for the comments above.  Let me know if you have any others.

**Comment by twiecki** [comment]
:+1:

**Comment by twiecki** [comment]
http://pymc-devs.github.io/pymc3/notebooks/LKJ.html

**Pull request merged**
