### PR TITLE
Formatted 15 Files

### PR DESCRIPTION
**Pull request by Yash1256**
Issue #4109 Applying black command on 15 Files 

1. docs/source/conf.py
2. pymc3/gp/mean.py
3. docs/source/sphinxext/gallery_generator.py
4. pymc3/gp/util.py
5. pymc3/memoize.py
6. benchmarks/benchmarks/benchmarks.py
7. pymc3/model_graph.py
8. pymc3/ode/ode.py
9. pymc3/math.py
10. pymc3/ode/utils.py
11. pymc3/plots/posteriorplot.py
12. pymc3/gp/cov.py
13. pymc3/parallel_sampling.py
14. pymc3/tests/checks.py
15. pymc3/gp/gp.py

### CODE REVIEW

**Comment by Yash1256** [comment]
@MarcoGorelli Sir Please Review.

**Review by MarcoGorelli — APPROVED** [review]
Thanks @Yash1256 !

**Comment by Yash1256** [comment]
Thanks @MarcoGorelli Sir, Can I format rest of the files?

**Comment by MarcoGorelli** [comment]
That's fine with me!

**Comment by Yash1256** [comment]
@MarcoGorelli Sir Done!!!

**Comment by MarcoGorelli** [comment]
> @MarcoGorelli Sir Done!!!

Thanks - sorry, I meant it a separate pull request, 60 files all at once it pretty hard to review :rofl:
You have 3 commits here, could you open a separate pull request for each one? let me know if you want/need any help with that

**Comment by Yash1256** [comment]
Okk Sir.

**Comment by MarcoGorelli** [comment]
Hi @Yash1256 - the other 2 PRs you have open look correct, but this one still has 60 files committed - should this one be closed in favour of the other two?

**Comment by Yash1256** [comment]
Yes @MarcoGorelli Sir, I am Closing this PR.

**Comment by MarcoGorelli** [comment]
Hi @Yash1256 - it looks like we lost many of these files when you opened new PRs with just them, do you want to open a new PR to apply `black` to the leftover files from here?

**Comment by Yash1256** [comment]
Ok Sir I will open a new PR and apply formatting to the remainimg Files

**Pull request closed without merging**
