### PR TITLE
Rectify return type hints in logprob module rewrites 

### LINKED ISSUE #6811: Rectify Return type hint
### Description

Take a look at the code snippet below:
https://github.com/pymc-devs/pymc/blob/f67ff8bc22fcc72ead96eeeaef04173ed53650cb/pymc/logprob/binary.py#L42-L44

Here, the return type hint is wrong. ```MeasurableComparision``` is an ```Op```, but what is returned are ```TensorVariables``` whose node has that ```Op```.

This needs to be rectified for all the functions which intend to find a ```measurable op```.

CC @ricardoV94 @larryshamalama

### PR DESCRIPTION
**Pull request by AryanNanda17**
## Related Issue

- [x] Closes #6811

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change
- [x] Other (please specify):

The return type hint is wrong in many files. MeasurableComparision is an Op, but what is returned are TensorVariables whose node has that Op. This needs to be rectified for all the functions which intend to find a measurable op.

----
📚 Documentation preview 📚: https://pymc--7125.org.readthedocs.build/en/7125/

### CODE REVIEW

**Comment by AryanNanda17** [comment]
@larryshamalama and @ricardoV94 please look into this issue.

**Comment by AryanNanda17** [comment]
All the pre commits tests are passing:-
Screenshot 2024-02-02 at 1 59 55 AM

**Comment by AryanNanda17** [comment]
Screenshot 2024-02-02 at 2 24 46 PM
@larryshamalama and @ricardoV94 why did some tests failed.

It shows this file failed but I didn't even change this file.

**Comment by ricardoV94** [comment]
@AryanNanda17 this issue is already been worked by another contributor in https://github.com/pymc-devs/pymc/pull/7013

We will give priority to the first one as the contributor mentioned he still wants to work on it

**Comment by AryanNanda17** [comment]
@larryshamalama You could have told me this when I raised this issue #7093 but I kept working on it to figure out what was going wrong.

**Comment by ricardoV94** [comment]
Unfortunately, I missed the duplicated work when you opened that first PR. I am sorry.

The info about related PRs should show in the original issue, but I don't usually check if a PR is already linked when someone opens a new one.

**Comment by ricardoV94** [comment]
I see @larryshamalama mentioned an option of adding people as co-authors. We can also do that, specially since this PR is already complete it seems.

I'll check the unrelated failing test.
Could you update the title of the PR to the old one?

**Comment by ricardoV94** [comment]
It's failing elsewhere, not this PR's fault

**Comment by AryanNanda17** [comment]
@ricardoV94 and @larryshamalama thanks for looking into the issue. 
Let me know if any update is required.

**Review by larryshamalama — APPROVED** [review]

**Comment by larryshamalama** [comment]
We're looking into the failed test in #7136

**Pull request merged**
