### PR TITLE
Censored data and Weibull AFT model

### LINKED ISSUE #2899: Enhancement of Survival Analysis documentation
Just a quick remark/ placeholder.

Would it be possible to stick https://github.com/pymc-devs/pymc3/pull/1870 in a notebook, with the examples of survival analysis/ censoring like @fonnesbeck has done in the past.

### PR DESCRIPTION
**Pull request by eigenfoo**
Hello!

This PR closes #2899 and #2942 and adds two new notebooks to the examples:

1. `censored_data.ipynb`: porting #1870 to a notebook. I also took the liberty of touching up the explanations and visualizations there. Not sure if we now want to delete the original `.py` example file, but if we do, I'd be happy to do that.

2. `weibull_aft.ipynb`: I haven't gotten around to this yet, but as far as I can tell it's a basic Weibull AFT model ported from [here](https://github.com/junpenglao/Planet_Sakaar_Data_Science/blob/master/PyMC3QnA/discourse_1107.ipynb).

I'll probably finish up the Weibull AFT notebook sometime in the next few days; I'll ping when the PR is ready for review.

@junpenglao commented [here](https://github.com/pymc-devs/pymc3/pull/2942#issuecomment-383359239) about putting some notebooks under a new session and indexing them on the website. I'm not sure what that means, or how to go about doing it. Could someone give me some pointers? 😃 

I think the same comment also suggested adding @AustinRochford's [blog post on AFT models](https://austinrochford.com/posts/2017-10-02-bayes-param-survival.html) as an example notebook, but I'm not sure if we have the author's permission to do that. If we do, I'd be happy to tack that on to this PR (which would bring the number of new notebooks to three).

### CODE REVIEW

**Comment by junpenglao** [comment]
What I meant is to create a new session in https://github.com/pymc-devs/pymc3/blob/master/docs/source/examples.rst, the website will then build and automatically index the notebook correctly.
Maybe after the GLM session?

**Comment by junpenglao** [comment]
- There are some guideline about unifying the style of the docs, please have a look at this issue: https://github.com/pymc-devs/pymc3/issues/2834
- you can put `;` at the end of plotting command suppresses the text output: `pm.traceplot(trace);` that way you also dont need `plt.show()`
- you should use the default initialization and try to get rid of the divergence samples
- you dont need to implement the normal_lcdf and llcdf, you can import them from pymc3 after #3077 
- yes go ahead and remove `censored_data.py`
- more information/introduction is needed for weibull_aft notebook

**Comment by junpenglao** [comment]
Ah didnt realized this is WIP... :-p

**Comment by eigenfoo** [comment]
No worries! These commits should fix everything about `censored_data.ipynb`. Will get around to Weibull AFT tomorrow.

Still waiting to see if we can port the blog post as a notebook. If not, is it possible/permissible to link to the blog post from the docs? It's a valuable resource: I learnt a lot from it!

**Comment by AustinRochford** [comment]
@eigenfoo feel free to add my post!

**Review by AustinRochford — APPROVED** [review]

**Comment by AustinRochford** [comment]
I do appreciate you asking, but my posts are all CC BY-SA licensed so feel free to adapt, reuse, etc. in the future.
https://github.com/AustinRochford/blog-content

**Comment by AustinRochford** [comment]
Notebook looks good. My one comment would be that instead of a `Bernoulli` RV for for the censored times with all observed ones, it may be more idiomatic to use a `Potential`. Mathematically it _should_ be equivalent, and I probably should have done that in the first place. ;)

**Comment by eigenfoo** [comment]
@AustinRochford I'm a bit confused about the proper usage of `pm.Potential`. From [this thread on discourse](https://discourse.pymc.io/t/difference-between-densitydist-and-potential/307) it sounds like using `pm.Potential` is a bit of a hack, and you'd be better off if you can get by with supported distributions.

Personally speaking, I feel much more comfortable reading `pm.Bernoulli` and needing to figure out how the math works, rather than reading `pm.Potential` and needing to look up an obscure function (which doesn't appear to be well documented, but that's a separate issue). Unless it makes a difference in sampling, it seems to me that using well-known distributions would be more idiomatic... Could you please advise?

I think I'll change the implementations of all of the censored data models to whatever gets agreed on.

cc @junpenglao @aseyboldt

**Comment by junpenglao** [comment]
I agree with @AustinRochford, using a potential is clearer in this case as these values are not observed (but integrate over the tail of the distribution), which gives something like:
```python
y_cens = pm.Potential(
        'y_cens', suvival_func(y_std[cens], η[cens_], s))
    )
```
As you can see, using Bernoulli doesnt make it clearer, as you need explaination of why `observed=np.ones(cens.sum()` is needed.

**Comment by eigenfoo** [comment]
Deleting `censored_data.py` would make a broken link in the docs: I've pointed it to the `weibull_aft.ipynb` notebook.

I made a first pass through Weibull AFT notebook, but I'll probably want to take another look at it in the next few days before merging.

**Comment by junpenglao** [comment]
No problem, take your time. 
Also dont forget to add a line to the release note (maybe easier after 3.5 is released)

**Comment by twiecki** [comment]
@eigenfoo Looks great, make sure to keep the output cells in the NB.

**Comment by eigenfoo** [comment]
Ready for review/merge!

**Comment by junpenglao** [comment]
LGTM mostly, small reminder:
1, please add a line in the release note
2, in `bayes_param_survival_pymc3.ipynb` following @AustinRochford's comment you should replace `pm.Bernoulli` with `pm.Potential` for the censored observed.

**Comment by eigenfoo** [comment]
Ah right! Thanks for reminding me. These commits should do the trick.

**Comment by AustinRochford** [comment]
:shipit:

**Comment by twiecki** [comment]
Thanks @eigenfoo and congrats on your first PR!

**Comment by springcoil** [comment]
Awesome

**Comment by AustinRochford** [comment]
👏

**Pull request merged**
