### PR TITLE
Re-run putting workflow

### PR DESCRIPTION
**Pull request by MarcoGorelli**
use inferencedata and arviz-darkgrid

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
> /pre-commit-run

😄 that would require https://github.com/pymc-devs/pymc3/pull/4330 to be in first

Also, this PR passes the style checks so it wouldn't do anything anyway

**Comment by twiecki** [comment]
Yeah, just checking. It wouldn't comment or anything?

**Comment by MarcoGorelli** [comment]
Not currently, no, it just puts the 'rocket' and 'eyes' emojis (see above). You can see that it was triggered in the 'actions' tab https://github.com/pymc-devs/pymc3/actions

**Comment by twiecki** [comment]
Very cool!

**Comment by MarcoGorelli** [comment]
closing as this will go in pymc-examples

**Pull request closed without merging**
