### PR TITLE
SMC: work with transformed variables

### LINKED ISSUE #2742: sample_smc fails for models with transformed variables
Consider this minimal example:

```python
y = np.array([1, 2, 3])

with pm.Model() as model:
    sigma = pm.Uniform('sigma', 0, 10)
    yl = pm.Normal('likelihood', mu=y.mean(), sd=sigma, observed=y)
    trace = smc.sample_smc(n_steps=20, n_chains=1000, homepath='/tmp') 
```

This works fine with NUTS but fails with SMC. The error:
```
~/miniconda3/envs/base/lib/python3.6/site-packages/pymc3/step_methods/smc.py in <dictcomp>(.0)
    185         self.array_population = np.zeros(n_chains)
    186         for _ in range(self.n_chains):
--> 187             self.population.append(pm.Point({v.name: v.random() for v in vars}, model=model))
    188 
    189         self.chain_previous_lpoint = copy.deepcopy(self.population)

TypeError: 'NoneType' object is not callable
```

It works fine if the `Uniform` prior is replaced with a `Normal`--or for that matter, with any other non-bounded distribution. The problem seems to be that the loop over `vars` includes the transformed variables (in this case, `sigma_interval__`), so the `random()` call fails.

### PR DESCRIPTION
**Pull request by aloctavodia**
This resolves #2742.  Now SMC works with transformed, as well as not transformed variables. 
I also made some PEP8-related changes.

### CODE REVIEW

**Comment by ColCarroll** [comment]
Looks good to merge once tests pass!  One question, one comment:

Question: Would it be easy to add a test (or update the test to use a transformed variable?)

Comment: We allow 100 characters per line elsewhere in the project -- it looks like you were shooting for 80.  Eighty is fine with me, but feel free to let the code breathe a little more if you want!

**Comment by aloctavodia** [comment]
Hi @ColCarroll !

I am seeing many errors that I did not see locally :-( I will have to check that.
I did not know about the 100 limit, I will use it! 
I will update the test to use transformed variables.

**Comment by aloctavodia** [comment]
I think this is ready to merge, @ColCarroll?

**Comment by junpenglao** [comment]
Nice work, thanks!

**Pull request merged**
