### PR TITLE
Revert "Add numerically safe ordered probit distribution."

### PR DESCRIPTION
**Pull request by Spaak**
Reverts pymc-devs/pymc3#4232 . Although all tests were fine within this PR branch, we now have a failure on `master`, see https://github.com/pymc-devs/pymc3/runs/1562295314 .

Any input on how to avoid such issues would be very helpful :) @MarcoGorelli perhaps? For now I think reverting the merge is probably the best option? (Which is what this PR does.)

Ping @tohtsky as well, who wrote #4232 . (Not to assign blame! You could not have foreseen this, given the OK test status on the PR.)

### CODE REVIEW

**Comment by michaelosthege** [comment]
@Spaak I don't think we should revert. I had the same flaky test on #4214 but it went away after re-running the CI jobs.
So first just hit "re-run all jobs" on the master CI and it might turn green already.

**Comment by MarcoGorelli** [comment]
> So first just hit "re-run all jobs" on the master CI and it might turn green already.

Let's just make sure to leave some kind of comment/issue if we do this, flaky tests should be fixed eventually

**Comment by Spaak** [comment]
Re-running CI on master now, let's hope the test failure indeed proves flaky and goes away. I'll leave this PR open until we know.

**Comment by Spaak** [comment]
Yep, indeed CI on master is now all green. See #4323 for the issue about flaky tests.

**Pull request closed without merging**
