### PR TITLE
Adding hierarhical partial pooling example

### PR DESCRIPTION
**Pull request by usptact**
Credits:
http://mc-stan.org/documentation/case-studies/pool-binary-trials.html

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @usptact, that's very useful. Even cooler would be the model with a bit more description and plots in form of an ipython notebook, similar to what we have here: http://pymc-devs.github.io/pymc3/examples.html It will also get more recognition there. Let me know if you want to do that, otherwise I'm happy to merge this.

**Comment by usptact** [comment]
@twiecki Thanks! Definitely some informative plots (and debugging?) would be very useful. Would you point me to resources/examples where such plots are available? I would be happy to add them to the script.

**Comment by twiecki** [comment]
Maybe check out the examples in: https://github.com/pymc-devs/pymc3/tree/master/docs/source/notebooks

Use Jupyter Notebook to create a small tutorial on the model (does not have to be as detailed as the original of course).

**Comment by usptact** [comment]
@twiecki I've added the IPython notebook. As I am pretty new to Bayesian modeling and notebooks, please let me know what needs to be improved.

**Comment by usptact** [comment]
@twiecki Is there anything that prevents from merging in this notebook? I would be glad to improve it further.

**Comment by fonnesbeck** [comment]
We already have a few hierarchical examples. I'm not opposed to adding another as long as it brought something new to the example set. Let me have a look at it and see if I can offer any suggestions.

**Comment by usptact** [comment]
@fonnesbeck One, possible minor contribution, is demonstrating how to put lower/upper bounds on variables. I didn't find that in any of the examples and had to dig it out from documentation and source code.

**Comment by fonnesbeck** [comment]
@usptact Please check out [this revision](https://gist.github.com/fonnesbeck/08078792809cc29b522253957464d5b7) I've cleaned up the grammar and focused the narrative a bit, including providing the answer to the original question: what is the likely batting average of the 0-for-4 player. See what you think.

**Comment by usptact** [comment]
@fonnesbeck Great work! This reminds me countless iterations with my PhD advisor on papers and thesis! I love how you re-purposed the subject "what is performance for a 0 hits from 4 at-bats" player while keeping the application in context.
Thanks also for the plots, I was not certain what information to pull out and how to do it with matplotlib.

**Comment by fonnesbeck** [comment]
Great, why dont you download my Gist and drop it in as a replacement in your PR, then I can merge it.

**Comment by usptact** [comment]
@fonnesbeck I added the notebook to this pull request.

**Pull request merged**
