### PR TITLE
Revert "WIP robust interval transforms"

### PR DESCRIPTION
**Pull request by springcoil**
Reverts pymc-devs/pymc3#1430

### CODE REVIEW

**Comment by springcoil** [comment]
This should work right @fonnesbeck

**Comment by springcoil** [comment]
Was this supposed to be merged? CC @fonnesbeck

**Comment by twiecki** [comment]
I think he wanted it reverted, no?

**Comment by springcoil** [comment]
He said 'Dammit. Hit the merge button by accident. Can someone undo this? I am on a mobile device.' on that other one...

**Comment by springcoil** [comment]
Ohh I get it - I misunderstood the revert process :)

**Pull request merged**
