### PR TITLE
WIP travis sphinx commit

### PR DESCRIPTION
**Pull request by ColCarroll**
(see #2538 for history)

### CODE REVIEW

**Comment by junpenglao** [comment]
While you are at it, could you please also add pm.distributions.timeseries to distribution doc?

**Comment by ColCarroll** [comment]
Not till the docathon!

**Comment by junpenglao** [comment]
LOL fair point

**Comment by ColCarroll** [comment]
This is ready, though there's no way to prove that until we merge (and, indeed, there might be some futzing with environment variables yet).

I set everything up on my fork, and https://colcarroll.github.io/pymc3/ now exists, so I think there's a real chance that it *does* work.  The biggest untested bit is the `-c` flag on `travis-sphinx deploy`, which should write the proper CNAME file to the gh-pages branch.  

( @twiecki feel free to change authorship on this back to you -- my main contribution was screwing up the git history!)

**Comment by twiecki** [comment]
```
+++travis-sphinx deploy -c docs.pymc.io

Usage: travis-sphinx [options] {actions}


Options:

  -h, --help		See usage of script

  -s, --source		Source directory of sphinx docs, default is docs/source

  -o, --outdir		Directory to put html docs, default is target/doc/build

  -n, --nowarn		Do not error on warnings

  -b, --branches	Comma separated list of branches to build on

			default is =master

  -p, --pullrequests	Deploy on pull requests (not recommended)

Actions:

  build 		Build sphinx documentation, places docs in target/doc

  deploy		Deploy sphinx docs to travis branch by pulling from

			target/doc
```

I wonder if the `-c` syntax is for the upcoming(?) 2.0. Maybe we need to install from the source repo directly.

**Comment by ColCarroll** [comment]
@twiecki you were right -- fixed that, and now everything works, including `CNAME`.

**Pull request merged**
