### PR TITLE
Formatted 15 Files of test Dir

### PR DESCRIPTION
**Pull request by Yash1256**
Issue #4109 Applying Formatting on 15 Files of Test Dir.

1. pymc3/tests/conftest.py
2. pymc3/tests/helpers.py
3. pymc3/tests/sampler_fixtures.py
4. pymc3/tests/models.py
5. pymc3/tests/test_distribution_defaults.py
6. pymc3/tests/test_data_container.py
7. pymc3/tests/test_dist_math.py
8. pymc3/tests/test_hdf5_backend.py
9. pymc3/tests/test_distributions_timeseries.py
10. pymc3/tests/test_memo.py
11. pymc3/tests/test_glm.py
12. pymc3/tests/test_hmc.py
13. pymc3/tests/test_missing.py
14. pymc3/tests/backend_fixtures.py
15. pymc3/distributions/continuous.py (This One From Distribution Dir.)

### CODE REVIEW

**Comment by Yash1256** [comment]
@MarcoGorelli Sir is it Right Now?

**Comment by MarcoGorelli** [comment]
Almost, the `pyupgrade` check is failing - can you do `pre-commit run`?

**Comment by Yash1256** [comment]
Done @MarcoGorelli Sir.

**Review by MarcoGorelli — APPROVED** [review]
nice, thanks!

**Review by AlexAndorra — APPROVED** [review]
All good, thanks @Yash1256 👌

**Pull request merged**
