### PR TITLE
Updated DEMetropolis warnings

### PR DESCRIPTION
**Pull request by michaelosthege**
+ removed general warning (#3718)
+ added warning when too few chains are set (#3719)
+ test for the warning

### CODE REVIEW

**Review by junpenglao — APPROVED** [review]

**Comment by junpenglao** [comment]
We also already have warning for number of chains here: https://github.com/pymc-devs/pymc3/blob/1c30a6f487afaeef73464a98320e35961b11873f/pymc3/step_methods/arraystep.py#L214-L216

**Comment by aloctavodia** [comment]
> We also already have warning for number of chains here:
> 
> https://github.com/pymc-devs/pymc3/blob/1c30a6f487afaeef73464a98320e35961b11873f/pymc3/step_methods/arraystep.py#L214-L216

Probably this warning should be removed in favour of the new one, because the later is more informative. Other than that this LGTM

**Comment by michaelosthege** [comment]
> > We also already have warning for number of chains here:
> > https://github.com/pymc-devs/pymc3/blob/1c30a6f487afaeef73464a98320e35961b11873f/pymc3/step_methods/arraystep.py#L214-L216
> 
> Probably this warning should be removed in favour of the new one, because the later is more informative. Other than that this LGTM

No that's not possible: With less than 2 other chains, `DEMetropolis` can not work (`ValueError`, because no chains to sample a vector from), but with `2 < n_chains <= n_dims` it does work, but it's really not recommended (`UserWarning`)
>What happens if N ≤ d? Because N points lie in an N − 1
dimensional space, all proposals (2) will lie in this reduced
space when e = 0. Therefore convergence of DE-MC would
rely on e, which would take a long time if its variance is small.

(from [ter Braak (2006)](https://doi.org/10.1007/s11222-006-8769-1))

**Comment by aloctavodia** [comment]
> > > We also already have warning for number of chains here:
> > > https://github.com/pymc-devs/pymc3/blob/1c30a6f487afaeef73464a98320e35961b11873f/pymc3/step_methods/arraystep.py#L214-L216
> > 
> > 
> > Probably this warning should be removed in favour of the new one, because the later is more informative. Other than that this LGTM
> 
> No that's not possible: With less than 2 other chains, `DEMetropolis` can not work (`ValueError`, because no chains to sample a vector from), but with `2 < n_chains <= n_dims` it does work, but it's really not recommended (`UserWarning`)
> 
> > What happens if N ≤ d? Because N points lie in an N − 1
> > dimensional space, all proposals (2) will lie in this reduced
> > space when e = 0. Therefore convergence of DE-MC would
> > rely on e, which would take a long time if its variance is small.
> 
> (from [ter Braak (2006)](https://doi.org/10.1007/s11222-006-8769-1))

You are right! What about making the error message more explicit?

**Comment by michaelosthege** [comment]
> > > > We also already have warning for number of chains here:
> > > > https://github.com/pymc-devs/pymc3/blob/1c30a6f487afaeef73464a98320e35961b11873f/pymc3/step_methods/arraystep.py#L214-L216
> > > 
> > > 
> > > Probably this warning should be removed in favour of the new one, because the later is more informative. Other than that this LGTM
> > 
> > 
> > No that's not possible: With less than 2 other chains, `DEMetropolis` can not work (`ValueError`, because no chains to sample a vector from), but with `2 < n_chains <= n_dims` it does work, but it's really not recommended (`UserWarning`)
> > > What happens if N ≤ d? Because N points lie in an N − 1
> > > dimensional space, all proposals (2) will lie in this reduced
> > > space when e = 0. Therefore convergence of DE-MC would
> > > rely on e, which would take a long time if its variance is small.
> > 
> > 
> > (from [ter Braak (2006)](https://doi.org/10.1007/s11222-006-8769-1))
> 
> You are right! What about making the error message more explicit?

Actually, it was possible to raise even earlier in the call tree.
I still kept the original check even though it should never trigger as long as `pm.sample` is used.

Also tried to write more informative messages. Is it what you had in mind?

**Review by aloctavodia — APPROVED** [review]
LGTM!

**Pull request merged**
