### PR TITLE
Add multi-output support to GP Latent

### LINKED ISSUE #7152: ENH: Extend `gp.Latent` to allow for multiple outputs
### Context for the issue:

Currently `gp.Latent` can only handle a single GP observation, so `f ~ GP(0, k(x, x'))`.  It should be generalized to allow `f_i ~ GP(0, k(x, x'))`, which is multiple observations of the same GP.  

It "should" be pretty straightforward to extend all the GP implementations to handle this case, but it's probably most important for `gp.Latent`.

### PR DESCRIPTION
**Pull request by AlexAndorra**
Porting over #7226 as it got staled a few months ago. 
Ported the changes from @hchen19 and also added `dims` support to `gp.Latent.prior`. Ready for review 🍾 

Closes #7152

----
📚 Documentation preview 📚: https://pymc--7471.org.readthedocs.build/en/7471/

### CODE REVIEW

**Comment by bwengals** [comment]
looks good!  not sure whats up with the unrelated test failures.  Would it be possible to add @hchen19 as an author in the commit? [ Looks like its pretty easy here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

**Comment by hchen19** [comment]
@bwengals and @AlexAndorra , thanks for the suggestions and reviews of this PR. I think the test fails might come from the changes of `logprob` and `logcdf` in the commit 48a8b6b4e110ab8b9cef904605196e556dbd2157

**Comment by AlexAndorra** [comment]
> Would it be possible to add @hchen19 as an author in the commit? Looks like its pretty easy here.

You're my hero @bwengals , that's what I was looking for 🥳 
Will push this ASAP, and then you can approve the PR

**Comment by AlexAndorra** [comment]
@bwengals I think that one is good to go 🍾 
I added @hchen19 as co-author and fixed a typo in `hsgp.prior` where we weren't removing the first basis coeff when the user provided a combination of `drop_first` and `centered` parametrization

**Review by bwengals — APPROVED** [review]

**Comment by Armavica** [comment]
@AlexAndorra Just to let you know that it didn't work, you added a `>` character instead of a new line. It's visible on the github history where you are the only author:

image

For comparison, a commit with several authors:

image

**Comment by bwengals** [comment]
Again, thanks for your work on this @hchen19!  My fault for not merging your branch when you were finished.

**Comment by bwengals** [comment]
And of course I approved and merged it without refreshing the tab and seeing your comment @Armavica.  Sorry guys that probably makes it a bit harder to fix.  Is there any issue with ammending the commit?

**Comment by Armavica** [comment]
I commented one hour after you merged, so you couldn't have seen it :) Amending the commit would require to exceptionally lift the force-push protection of the main branch, since it's still the last commit I would say it's not too bad, but I don't know if it already has been done and we should probably ask someone else than me

**Pull request merged**
