### PR TITLE
bugfix for glm poisson plus new example poisson reg

### PR DESCRIPTION
**Pull request by jonsedar**
bugfix for https://github.com/pymc-devs/pymc3/issues/1100

plus new example Notebook for poisson regression

### CODE REVIEW

**Comment by Volodymyrk** [comment]
@jonsedar  I spent hours this weekend trying to find an example of poisson regression in pymc3! Thanks a lot!

**Comment by springcoil** [comment]
@jonsedar - actually there's two commits there - I think it's good practice (and @fonnesbeck or @twiecki will confirm) to rebase that and submit it in one commit.

**Comment by jonsedar** [comment]
I'd love to, no idea how to do that, any pointers?

EDIT: found [this](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history), seems doable if arcane (git certainly wasn't named by mistake, was it now). I'd be happy to give it a try but I also faffed around deleting my fork so that I could have a simple clean repo to add to. Now I see you've closed the revert PR, so is everything basically back to as it was after you merged my PR?

**Comment by springcoil** [comment]
This might work

git reset HEAD~1
git add -A
git commit --amend

On Sun, May 15, 2016 at 11:10 PM, Jonathan Sedar notifications@github.com
wrote:

> I'd love to, no idea how to do that, any pointers?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1102#issuecomment-219313860

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
Or on your branch - do just this.

git fetch upstream
git rebase -i upstream/master
git push -f origin/master

On Sun, May 15, 2016 at 11:17 PM, Peadar Coyle peadarcoyle@googlemail.com
wrote:

> This might work
> 
> git reset HEAD~1
> git add -A
> git commit --amend
> 
> On Sun, May 15, 2016 at 11:10 PM, Jonathan Sedar <notifications@github.com
> 
> > wrote:
> > 
> > I'd love to, no idea how to do that, any pointers?
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > https://github.com/pymc-devs/pymc3/pull/1102#issuecomment-219313860
> 
> ## 
> 
> Peadar Coyle
> Skype: springcoilarch
> www.twitter.com/springcoil
> peadarcoyle.wordpress.com

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
But consider that just for reference - there's no point undoing this commit and reverting since it's a small one in my opinion :)

**Comment by jonsedar** [comment]
Urg, as soon as git gets complicated it gets _seriously_ complicated. 

If you want to back out the original PR, go for it - otherwise I'll note for future...

**Comment by springcoil** [comment]
Yeah I know - I find Git a pain :)

Just note it for the future. I think it's fine to merge :)

On Sun, May 15, 2016 at 11:22 PM, Jonathan Sedar notifications@github.com
wrote:

> Urg, as soon as git gets complicated it gets _seriously_ complicated.
> 
> If you want to back out the original PR, go for it - otherwise I'll note
> for future...
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1102#issuecomment-219314421

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by jonsedar** [comment]
@Volodymyrk I did the same search a couple of weeks ago, there's strangely not many examples floating around in pymc2 and stan either.

Except, now that I see it, this stackoverflow thread from a certain @springcoil ;) http://stackoverflow.com/questions/30798447/porting-pymc2-code-to-pymc3-hierarchical-model-for-sports-analytics

**Comment by springcoil** [comment]
Ha :+1:

On Sun, May 15, 2016 at 11:27 PM, Jonathan Sedar notifications@github.com
wrote:

> @Volodymyrk https://github.com/Volodymyrk I did the same search a
> couple of weeks ago, there's strangely not many examples floating around in
> pymc2 and stan either.
> 
> Except, now that I see it, this stackoverflow thread from a certain
> @springcoil https://github.com/springcoil ;)
> http://stackoverflow.com/questions/30798447/porting-pymc2-code-to-pymc3-hierarchical-model-for-sports-analytics
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/1102#issuecomment-219314746

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by twiecki** [comment]
Thanks @jonsedar!

**Pull request merged**
