### PR TITLE
ENH Normalizing flows

### PR DESCRIPTION
**Pull request by taku-y**
This PR add normalizing flows for ADVI. Still WIP. #1438

### CODE REVIEW

**Comment by springcoil** [comment]
Hi Taku,
I agree this is a WIP, but it's good to get the code here so people can think about it. 

For tests, I'm not sure. I'll have a think and try to come up with something. Any suggestions from @AustinRochford or @twiecki @fonnesbeck on how we would approach testing?

**Comment by springcoil** [comment]
Seems this is passing, but do you want to wait until you have a good idea on the tests first.
Does this depend upon #1499 ?

**Comment by taku-y** [comment]
Hi Peadar,
Yes, I need to rebase code to #1499. And I come up with a model whose latent variables should be correlated thus NF shold be better than the meanfield approximation. It may require some time for me.

**Comment by springcoil** [comment]
That's fine, I'll be happy to review it when it's ready.

**Comment by springcoil** [comment]
Just for general discussion https://arxiv.org/pdf/1611.06585v1.pdf is an interesting paper.

**Comment by springcoil** [comment]
Have your recent changes @taku-y made this more likely to be worked on? Or are you still depending on some API changes?

**Comment by taku-y** [comment]
@springcoil There was no progress recently. I want to refactor advi with the code of @ferrine. If doing so, the implementation of normalizing flow should be modified. I want to postpone implementing NF after the refactoring. 

And I want to think about the interface to represent transformations. By combining and transforming two or more RVs, variational posterior become more accurate. What I want to thinking is how to specify combinations of RVs in the API. This is an issue of API design.

**Comment by ferrine** [comment]
Do we need a kind of flexible util for constructing variational approximations? This can be done in my future advi refactoring.

UPD:
The main point is that it should take a model as input and return variational replacements as output with holding all the parameters. Inside this black box we'll need then just switch the methods for constructing that replacements

## Input
* model
* type of approximation (e.g. mean field)
## Output
* replacements in graph for free random variables, theta
* shared variables used for training, phi
* q(theta|phi)
* inverse mapping (inp: latent variables point, out: variables in latent space that were used for generating replacements) maybe

Then all ELBO maximization methods will become similar

**Comment by ferrine** [comment]
This how I see this stuff (see [replacements.py](https://github.com/ferrine/pymc3/blob/refactor_advi/pymc3/variational/replacements.py) in my branch). I'm sure that this generalisation can be easily extended for SVGD or Normalizing Flows.

**Comment by twiecki** [comment]
@ferrine I think such a generalization would be very useful.

**Comment by springcoil** [comment]
@ferrine I think your generalization looks useful. Have you opened a PR yet?

**Comment by ferrine** [comment]
I'm thinking if there is a better design. Do you have any thoughts?

**Comment by springcoil** [comment]
I've a bit of an aversion to the `global_dict` but I'm not sure of a better solution. I suspect there's better ways of doing this design, but I think what you've presented is sufficient. I'm most interested in seeing the new functionality used rather than pursuing platonic ideals :)

**Comment by springcoil** [comment]
Any update on this @ferrine ?

**Comment by ferrine** [comment]
Yes, see #1600. But I have strange issues with tests

**Comment by springcoil** [comment]
@taku-y I think that @ferrines work will soon be merged - so looks like you'll have some fun refactoring this to use the new API.

**Comment by springcoil** [comment]
How's this looking guys - @ferrine and @taku-y

**Comment by ferrine** [comment]
@springcoil I'm planning to implement Flows with OPVI in summer as a part of my GSoC. [Here](https://github.com/pymc-devs/pymc3/pull/1961) OPVI proved to be highly flexible even for exotic VI algorithms.

**Pull request closed without merging**
