### PR TITLE
DOCS: Added numpydoc to the requirements.txt file

### PR DESCRIPTION
**Pull request by springcoil**
I noticed that a pull request by Thomas was failing. Just added numpydoc to the requirements file.

### CODE REVIEW

**Comment by springcoil** [comment]
So this is just a timeout error - so shall we merge it in and close this. @fonnesbeck do you think this is ok?

**Comment by twiecki** [comment]
Shouldn't this PR be onto the `sphinx` branch?

**Comment by springcoil** [comment]
Yeah it should probably. I'll redo it.

**Comment by twiecki** [comment]
I added it manually, thanks.

**Pull request closed without merging**
