### PR TITLE
Added package_data information to setup.py

### LINKED ISSUE #1339: missing requirements.txt
I'm trying to kickstart a conda package for pymc3 (and I'm happy to be the recipe maintainer for it as well). However, it looks like requirements.txt isn't distributed with the source distribution, making the conda skeleton build process error out. Here's the full error message I'm receiving.

``` bash
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    with open('requirements.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
$PYTHONPATH = /var/folders/4d/5h2mymgs27q1sk0828h4wyh00000gn/T/tmpy2d8bhaoconda_skeleton_pymc3-3.0rc1.tar.gz/pymc3-3.0rc1
Error: command failed: /Users/ericmjl/anaconda/envs/_build_placehold_placehold_placehold_placehold_plac/bin/python setup.py install
```

### PR DESCRIPTION
**Pull request by fonnesbeck**
Allows non-Python files to be added without needing a MANIFEST

Fixes #1339

### CODE REVIEW

**Comment by twiecki** [comment]
This does look a bit cleaner than the MANIFEST.in file, happy to go ahead with this. (Sorry, saw this one too late).

**Comment by springcoil** [comment]
Does this need a merge? I think it's ready to go in.

**Comment by springcoil** [comment]
Looks like that needs a rebase or something. There's a lot in this PR.

**Comment by fonnesbeck** [comment]
This is after a rebase.

**Comment by twiecki** [comment]
LGTM.

**Comment by springcoil** [comment]
Sorry @fonnesbeck I read the old commit not the new one :)

**Pull request merged**
