### PR TITLE
Upgrade nbqa, add config options for black

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Ahead of #4095

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
@AlexAndorra it seems to me that `black_nbconvert` doesn't respect the line length from `pyproject.toml`, e.g. if we have
```python
    average_disasters[i] = np.mean(np.where(idx, trace["early_rate"], trace["late_rate"]))
```
(90 characters long) it'll reformat it to
```python
    average_disasters[i] = np.mean(
        np.where(idx, trace["early_rate"], trace["late_rate"])
    )
```

Is that OK, or would you prefer to use the line length from pyproject.toml? (the latter is what I've gone for in this PR)

**Comment by AlexAndorra** [comment]
Yeah it should use the line length from pyproject.toml IMO

**Review by AlexAndorra — APPROVED** [review]
LGTM, thanks @MarcoGorelli !
Does this mean people should use `nbqa` to blacken NBs now, instead of `black_nbconvert`?

**Comment by MarcoGorelli** [comment]
> Does this mean people should use nbqa to blacken NBs now, instead of black_nbconvert?

If you want pyproject.toml configs to be respected, then I think that would be better - I'll update the wiki if you want this

**Comment by AlexAndorra** [comment]
Ok, let's do that then! Indeed, thanks for updating the wiki 😉 
I'll wait to merge this PR, as I think you may have picked up some of these changes in #4136 -- will merge once that's cleared

**Comment by AlexAndorra** [comment]
@MarcoGorelli, since this is merged now, do you mind [updating the NB style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style) with the changes please?

**Comment by MarcoGorelli** [comment]
Hey @AlexAndorra - sorry for the delay, I've updated the wiki

**Comment by AlexAndorra** [comment]
Perfect, thanks a lot @MarcoGorelli !
"This step will eventually be merged in with step 2" --> exciting 😉

**Pull request merged**
