### PR TITLE
Arbitrary deterministic function added.

### PR DESCRIPTION
**Pull request by mcavallaro**
This example is now consistent with the documentation (Case study 2: Coal mining disasters). The rate function is has been written using the @as_op decorator. It's definition is essentially as in the equivalent PyMC2 example.

### CODE REVIEW

**Review by springcoil — APPROVED** [review]

**Comment by twiecki** [comment]
Why should we want that?

**Comment by mcavallaro** [comment]
@twiecki Just as an example of the usage of @as_op. The current version is not consistent with the [doc](http://pymc-devs.github.io/pymc3/notebooks/getting_started.html#Arbitrary-deterministics) and the docstring. I agree that it's just a minor fix.

**Comment by twiecki** [comment]
Can we instead do a second version of this that we call `..._theano_op.py`?

**Comment by mcavallaro** [comment]
Sure, similarly to the [pymc2 repo](https://github.com/pymc-devs/pymc/tree/master/pymc/examples), I'd say to include one file `disaster_model.py` with the standard example and a file `disaster_model_theano_op.py` with the as_op decorator.  The link in the [doc](http://pymc-devs.github.io/pymc3/notebooks/getting_started.html#Arbitrary-deterministics) needs to be changed too, as it has the old name.

**Comment by twiecki** [comment]
Not sure where the conflicts are coming from but seems like you need to rebase.

**Comment by mcavallaro** [comment]
OK, it seems that there are no conflicts, not anymore

**Comment by twiecki** [comment]
Thanks @mcavallaro!

**Comment by mcavallaro** [comment]
You're welcome, thanks for the package!

**Pull request merged**
