### PR TITLE
Changed optimiser to use updates.py

### PR DESCRIPTION
**Pull request by bhargavvader**
With regard to #1784 .
Uses the adagrad optimiser from `updates.py`.

### CODE REVIEW

**Comment by twiecki** [comment]
pymc3/variational/advi.py:5: [W0611(unused-import), ] Unused OrderedDict imported from collections

**Comment by bhargavvader** [comment]
@twiecki , the tests related to ADVI fail with a value mismatch.
```
(mismatch 100.0%)
 x: array(-4.264022381777658)
 y: array(-4.992972238089946)
```
This is for both the mini batch and normal ADVI. Could the difference in the default optimiser cause such a difference? And how would I go about fixing something like this?

**Comment by twiecki** [comment]
Interesting, seems like we either fixed a bug or introduced one here.

**Comment by twiecki** [comment]
It seems like convergence to the true mean is definitely slower with this implementation and completely off for standard deviations. The main difference in implementation I can see between these two versions is that our own implementation implemented a window (default len = 10) over which to aggregate the gradients over. Not sure if that could be the cause here. @taku-y any ideas?

**Comment by twiecki** [comment]
@bhargavvader Ideas about fixing: Comparing both versions closely inside of a debugger (e.g. pdb++) and seeing where the differences start occurring.

**Comment by twiecki** [comment]
@ferrine You used the new updates.py, did you encounter any problems with those implementations?

**Comment by ferrine** [comment]
I've lowered tolerance in the beginning, need to review later again

**Comment by ferrine** [comment]
I've just tested this setup - OK, optimizer adam
```python
np.testing.assert_allclose(np.mean(trace['mu']), mu_post, rtol=0.1)
np.testing.assert_allclose(np.std(trace['mu']), np.sqrt(1. / d), rtol=0.2)
```

**Comment by taku-y** [comment]
@twiecki My concern is the error message showed 100% mismatch. It does not seem to be caused by any numerical problem.

**Comment by twiecki** [comment]
@taku-y I share your concern. Do you think the window could be responsible?

**Comment by taku-y** [comment]
I think the interface of optimizers doesn't match with advi function. Need to check the code for making the problem clear.

**Comment by bhargavvader** [comment]
Closing this PR for now - it's going to need some more poking around to see the exact reason it isn't reproducing the results of the older optimizer, and I am caught up with work for the next few weeks. Will get back to it the moment I make some time.

**Pull request closed without merging**
