### PR TITLE
Switch `run_mypy.py` from pass-listing to fail-listing

### PR DESCRIPTION
**Pull request by michaelosthege**
This PR inverts the `run_mypy.py` script from a list of known PASSING to a list of known FAILING source files.

This list is shorter (🥳) and can be read as a TODO-list for which files need attention.

**Checklist**
+ [x] Explain important implementation details 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- None

## Bugfixes / New features
- None

## Docs / Maintenance
- The `run_mypy.py` script now uses a list of known _failing_ source files.

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Review by maresb — APPROVED** [review]

**Comment by maresb** [comment]
I'm very curious: how does the execution time of `run_mypy.py` differ from that of a single invocation of `mypy` on the codebase?

The reason I'm asking is that we currently do a for loop, iterating over all the `.py` files. I suspect that starting and stopping the `mypy` process carries a lot of overhead. Perhaps there's some better way? It'd be really nice to be able to run mypy in the local pre-commit.

**Comment by ricardoV94** [comment]
Do you mind investigating?

**Comment by michaelosthege** [comment]
There's only one mypy invocation in `run_mypy.py`. check the subprocess call at the bottom of the script

**Comment by maresb** [comment]
Ah, yes, thanks @michaelosthege! Sorry, I was confused.

**Pull request merged**
