### PR TITLE
Add Binary Gibbs Metropolis sampler for mixture models.

### PR DESCRIPTION
**Pull request by twiecki**
This is mainly to start a discussion. It's pretty simple to change Metropolis to ever only update a single dimension.

### CODE REVIEW

**Comment by jsalvatier** [comment]
What are the main use cases for this? 

Are there any important special cases of analytical gibbs samplers that we want to support?

**Comment by hvasbath** [comment]
I am a little confused here. The way as it is implemented at the moment is exactly Gibbs sampling already. The Metropolis initialisation returns a step object for each RV, which are merged into a compound step. Then this is called by _iter_sample and will recursively execute each step.methods[:].step by changing only the variable it contains keeping the others fixed.
This is actually something which I would suggest to make clear in the name or tutorial or DOC or whatever. Because, this is not a regular Metropolis-Hastings where you would actually change all the variables per iteration. Or am I missing something here?

**Comment by twiecki** [comment]
@eigenblutwurst You're correct but that only works for 1-D variables. If you have a vector-RV (e.g. with shape) it'll still assign just one step-method.

**Comment by hvasbath** [comment]
Thats right, but if you have for example two vectors.
a = Uniform('a', shape=7)
b = Uniform('b',shape=5)
It will still create a step for a and a step for b. Instead of one step for a and b together.
So you will run your model twice instead of just once.
Just found the blocked class. Would that change if I would set blocked=False?

**Comment by twiecki** [comment]
Yes, that would change. This PR would cause each individual item of `a` and `b` to get updated individually.

**Comment by hvasbath** [comment]
Ah ok. Thanks now I get it. But thats not what I want. I want to update a and b at the same time in the same forward model. So ultimately I would have only one step method for both variables. 
Is there already a flag for this somewhere?
I couldnt find it. I guess I would need to write a seperate step method?

**Comment by twiecki** [comment]
Then set `blocked=False` if you're using Slice or Metropolis.

**Comment by hvasbath** [comment]
Thanks thats exactly what I want. Sorry I missunderstood your last comment. But, however,
there is a small bug in arraystep.py BlockedStep line 50.

if not blocked and len(vars) > 1

it has to become

if blocked and len(vars) > 1

Otherwise it will always block the variables. 
The default_blocked = False for the Metropolis class. So it shouldnt be creating the compound step per default. But it does. And blocked=False has no effect. 
Update: I guess it is just a point of view problem. So I have to put blocked=True without changing this line if I want just one step. Sorry for spaming.

**Comment by hvasbath** [comment]
I think this is an important feature and would be nice to have in the help. This also avoids confusion and stupid questions from users that consume your time ;) .

**Comment by twiecki** [comment]
The best way to get started with git is to get started :), your help would be appreciated!

**Comment by twiecki** [comment]
@fonnesbeck I ended up taking two different approaches here. I added a gibbs option to `Metropolis` that only updates one dimension each time `astep` is called, and a separate `BinaryGibbsMetropolis` that updates all dimensiones once each time `astep` is called. Any thoughts?

**Comment by fonnesbeck** [comment]
What's not clear to me is what makes this Gibbs; we are not sampling from the full conditionals (that's Gibbs, strictly speaking) -- we are still proposing and accepting/rejecting. You are really looking at an element-wise sampling scheme (rather than block updating), correct?

**Comment by twiecki** [comment]
Technically, Gibbs doesn't tell you how to sample from the conditional (i.e. doesn't have to be direct from the conditional but can be done via e.g. Metropolis or Slice -- then often called Metropolis/Slice within Gibbs).

**Comment by springcoil** [comment]
Plus one to encourage @eigenblutwurst to get started

On Tue, Feb 16, 2016 at 5:18 PM, Chris Fonnesbeck notifications@github.com
wrote:

> What's not clear to me is what makes this Gibbs; we are not sampling from
> the full conditionals (that's Gibbs, strictly speaking) -- we are still
> proposing and accepting/rejecting. You are really looking at an
> element-wise sampling scheme (rather than block updating), correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pymc-devs/pymc3/pull/799#issuecomment-184751414.

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by fonnesbeck** [comment]
OK, cool. I though Metropolis-within-Gibbs was just dropping in Metropolis for the variables that you couldn't use Gibbs for.

Anyhow, regarding the code -- your  proposal for `metropolis` only seems to update one element per iteration. Will there be a full sweep through all the elements within every iteration of sampling?

**Comment by fonnesbeck** [comment]
Won't just specifying `blocked=False` for `metropolis` do what you want?

**Comment by twiecki** [comment]
In this case it wouldn't (see also above). For example, a binary vector RV will still be block-updated because it's a single RV.

**Comment by twiecki** [comment]
> Anyhow, regarding the code -- your proposal for metropolis only seems to update one element per iteration. Will there be a full sweep through all the elements within every iteration of sampling?

Yes, that's right. It'd be more efficient to do a full sweep each time. Really this PR is most useful for the Binary case so maybe I'll remove the Metropolis option for now.

**Comment by hvasbath** [comment]
@springcoil sorry I dont really get what you are referring too? For me this question was resolved and nothing needs to be done, because as @fonnesbeck  mentioned already blocked=False/True does what I need. To update every single element of a vector within each iteration is what @twiecki implemented now I guess. Which would be even less suitable for my problem at least, as I have 450 variables which means 450 forward calculations to get one iteration done. But for models with only few variables this could be quite useful.

**Comment by springcoil** [comment]
I agree with you. No need for a PR now.

**Comment by twiecki** [comment]
OK, I think this should be ready to merge. CC @fonnesbeck @springcoil @jsalvatier

**Comment by springcoil** [comment]
I did a quick review on this and I say :shipit: :) I hope it was ok to merge this.

**Pull request merged**
