### PR TITLE
Optimized logpt computation

### LINKED ISSUE #2948: Theano does not sample from HalfCauchy and Lognormal together
Theano does not sample from a very simple model.

I have purged the theano cache, reinstalled theano/pymc3 to no avail.
I always get an error relating to dimension mis-match. I don't understand.

The model runs fine if I leave out `nu` or `sigma`. Both together just results in the error message below.

    import theano
    theano.compile.DebugMode = True
    print(theano.__version__)
    print(pm.__version__)

    ndim = 3
    with pm.Model() as model:
        sigma = pm.Lognormal('sigma', np.zeros(ndim), np.ones(ndim), shape=ndim)  # variance for the correlation matrix
        nu = pm.HalfCauchy('nu', beta=10) 
        pm.sample(10)

Answer:

    1.0.1
    3.4.1

    ValueError: Input dimension mis-match. (input[0].shape[0] = 3, input[1].shape[0] = 1)
    Apply node that caused the error: Elemwise{Composite{((-i0) + i1 + i2)}}(Elemwise{Composite{log(exp(i0))}}.0, TensorConstant{(1,) of -1.0}, TensorConstant{(1,) of 1.0})
    Toposort index: 8
    Inputs types: [TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, (True,))]
    Inputs shapes: [(3,), (1,), (1,)]
    Inputs strides: [(8,), (8,), (8,)]
    Inputs values: [array([-0.0915752 ,  0.1090227 , -0.38337466]), array([-1.]), array([ 1.])]
    Outputs clients: [[IncSubtensor{InplaceInc;int64:int64:}(Alloc.0, (d__logp/dsigma_log__), Constant{1}, Constant{4})]]
    
    HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
    HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

## Versions and main components

* PyMC3 Version: 3.4.1
* Theano Version: 1.0.1
* Python Version: 3.6.5
* Operating system: Scientific Linux  3.10.0-514.el7.x86_64
* How did you install PyMC3: (conda/pip):
`pip install git+https://github.com/pymc-devs/pymc3.git`

### PR DESCRIPTION
**Pull request by junpenglao**
I change the logpt computation in #2949 to fix  #2948, however, it slows down the speed as some graph optimization is turned off (those optimization is originally cause the error in #2948). I am trying with a differen approach here.
@colcarroll

### CODE REVIEW

**Comment by ColCarroll** [comment]
I don't quite understand the problem: it looks like you are trying a more explicit loop to give the compiler a better chance of optimizing?  I guess I also don't understand what caused the edge case in the first place, and whether it is ok to let that fail (that is the failing test)

**Comment by junpenglao** [comment]
Thanks for having a look @ColCarroll.
So the error is a bit difficult to trace down as it happens (i suspect) in the graph optimization. In that particular edge case (edge because it only doest work with `sd` being a vector in logNormal distribution, other distribution works fine), if you set the `ValueGradientFunction` to compile in python (`mode='FAST_COMPILE'`) it works fine. My initial fix is to set the logpt computation to the older way, but seems in effect it skip the optimization in the step of the logpt computation step (that's why no more error in the edge case). So now what I am trying to do is be more explicit at these similar edge case and compile a function that turns off the C optimization.
What do you think?

**Comment by twiecki** [comment]
Seems like a theano bug, no?

**Comment by junpenglao** [comment]
@twiecki not sure, I cannot really pin down where exactly is the error yet... compiling a theano function using pm.Lognormal.dist().logp()+... etc works without problem

**Comment by ColCarroll** [comment]
Ran the `asv` benchmarks locally, and this gets the hierarchical model running quicker again (160 ES/S vs 138 ES/S).  Agree that it would be nice to understand more about why this happened, but I wanted 14% of my time back!

**Comment by junpenglao** [comment]
So, this PR makes me quite paranoid so I did a bit more digging. 
Turns out doing `logp = tt.add(*map(tt.sum, factors))` is actually slightly faster in terms of raw speed, as the graph is smaller, but surprisingly in practice (I tested a few other models that I am working on) doing `logp = tt.sum([tt.sum(factor) for factor in factors])` seems to be numerically more stable (hence the higher `effective sample size / sampling time` ratio in the benchmark). 

All the output is in the folder below if you would like to test on your own model https://github.com/junpenglao/Planet_Sakaar_Data_Science/tree/master/Miscellaneous/theano_graph_optim

**Pull request merged**
