### PR TITLE
Allow use of DiscreteUniform distribution for CategoricalGibbsMetropolis step method.

### PR DESCRIPTION
**Pull request by helmutsimon**
The CategoricalGibbsMetropolis step method is the default for the Categorical distribution. The Metropolis step method may not work for Categorical in some circumstances, e,.g. as part of compound distribution. However, CategoricalGibbsMetropolis currently can only be used with Categorical or Bernoulli distributions.

For some models it is necessary to use a DiscreteUniform distribution rather than Categorical, as the k parameter can be very large. It would be useful if the CategoricalGibbsMetropolis step method could also be used for DiscreteUniform distributions, which are after all a special case of Categorical.

### CODE REVIEW

**Comment by junpenglao** [comment]
The file is under the wrong directory - you should modify the one under https://github.com/pymc-devs/pymc3/tree/master/pymc3/step_methods

**Review by junpenglao — CHANGES_REQUESTED** [review]
The file is under the wrong directory - you should modify the one under https://github.com/pymc-devs/pymc3/tree/master/pymc3/step_methods

**Comment by twiecki** [comment]
Ping @helmutsimon

**Comment by helmutsimon** [comment]
Resubmitting new and corrected pull request.

**Pull request closed without merging**
