### PR TITLE
Bugfix multinomial vector

### LINKED ISSUE #1477: Multinomial likelihood bug with multiple observations
I think there is a bug in the `Multinomial` log likelihood when there are multiple observations.  Here is a simple illustration:

``` python
import numpy as np
import pymc3 as pm
import scipy as sp
```

``` python
def multinomial_logp(x, n, p):
    return sp.special.gammaln(n + 1) - sp.special.gammaln(x + 1).sum() + (x * np.log(p)).sum()
```

``` python
N = 5
P = np.array([0.3, 0.7])
```

``` python
with pm.Model() as model:
    x = pm.Multinomial('x', N, P, shape=2)
```

``` python
x_single = np.array([2, 3])
```

``` python
model.logp({'x': x_single})
```

```
array(-1.175385291855191)
```

``` python
multinomial_logp(x_single, N, P)
```

```
-1.1753853474740241
```

``` python
x_many = np.array([[2, 3],
                   [1, 4]])
```

``` python
with pm.Model() as model_many:
    x = pm.Multinomial('x', N, P, shape=(2, 2))
```

``` python
model_many.logp({'x': x_many})
```

```
array(-1.3211512777668837)
```

``` python
sum(multinomial_logp(x, N, P) for x in x_many)
```

```
-2.1966200151207897
```

The problem appears to be [aggregating to `x_sum`](https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py#L303-L309) _before_ calculating `factln`.

### PR DESCRIPTION
**Pull request by AustinRochford**
Resolves #1477

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks! I think @fonnesbeck touched that code last.

**Comment by AustinRochford** [comment]
Yes, I would definitely like @fonnesbeck's opinion before merging.

**Comment by AustinRochford** [comment]
This change will also make it possible to extend (in another PR) the `Multinomial` likelihood to accept vectors for `n` and row-stochastic matrices for `p`, which is useful/necessary for models like LDA.

**Comment by fonnesbeck** [comment]
Yes, this looks right to me. Thanks for fixing.

**Pull request merged**
