### PR TITLE
Add CDF methods to continuous distributions

### PR DESCRIPTION
**Pull request by fonnesbeck**
This PR is mostly work by @domenzain that implements log-CDF methods to the continuous distributions. This merges the collaborative feature branch into master.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Unfortunately, my beta log-CDF appears not to be very precise.

**Comment by domenzain** [comment]
Maybe we should close #2048, since the commits are here anyhow.
I'll give refining this beta log CDF a go during the week.

**Comment by domenzain** [comment]
My bad, I hadn't refreshed my browser tab...

**Comment by fonnesbeck** [comment]
Closing in favor of #2688

**Pull request closed without merging**
