### PR TITLE
delete c=trace.close() in iter_sample()

### PR DESCRIPTION
**Pull request by hvasbath**
fixes issue as discussed here: https://github.com/pymc-devs/pymc3/issues/1816

### CODE REVIEW

**Comment by twiecki** [comment]
I wonder why this if-clause exists: https://github.com/hvasbath/pymc3/blob/0dadf3fcc5c7725df76a589b5097467a3eb48ff4/pymc3/sampling.py#L198 In the case of no progressbar we would not close the trace, which makes no sense to me.

**Comment by hvasbath** [comment]
Why was this changed actually in the first place? Was there some memory leak somewhere? For me it worked perfectly fine the way it was.

**Comment by aseyboldt** [comment]
That was me. This shouldn't close the trace, but the progress bar. `tqdm` spins up a thread to monitor the progress, and if close is not called that thread will keep running (and it seems it sometimes prints strange things to the notebook). If the iterator is exhausted, it is closed automatically. Closing it twice doesn't hurt it.

**Comment by hvasbath** [comment]
No it is not about closing the tqdm bar, it is about closing the trace twice, which hurts if it is a Text trace. I dont know about the others ...

**Comment by aseyboldt** [comment]
I was talking about the line 198, that @twiecki mentioned. Or what do you mean?

**Comment by hvasbath** [comment]
Ah sorry. I am talking about line 201. And line 198 has nothing to do about closing the trace- thats right. And this is executed also only once- so no problem there anyways.

**Comment by aseyboldt** [comment]
no problem.

**Comment by twiecki** [comment]
I got confused, this closes the progressbar, not the trace, sorry for the confusion.

@hvasbath Where was the other place where the trace gets closed?

**Comment by hvasbath** [comment]
The one in iter_sample() which is being deleted in the PR and the close at line 201 in the _sample function.

**Comment by twiecki** [comment]
Thanks @hvasbath!

**Pull request merged**
