### PR TITLE
Update hierarchical partial pooling notebook

### PR DESCRIPTION
**Pull request by aseyboldt**
I fixed another notebook. Then I noticed that it hadn't been broken in the first place.
Still, I improved mixing by switching around the parametrization a bit and updated the api usage.

### CODE REVIEW

**Comment by aseyboldt** [comment]
CC @ColCarroll That was yours, right?

**Comment by fonnesbeck** [comment]
A nitpick, but I would move the paragraph-long comment in cell 3 out into its own markdown cell. You can even break down the model specification into 2 `with` blocks to help step through the model construction.

**Comment by ColCarroll** [comment]
Not mine -- I think this was @usptact.  I did an API fix and some proofreading though.  Looks fine to me!

**Comment by usptact** [comment]
Yes, I created this notebook. Is there something I need to change?

**Comment by ColCarroll** [comment]
I don't think so, just wanted to let you know it is still useful!

**Comment by usptact** [comment]
@ColCarroll Thanks! It would be much more difficult without help of @twiecki and @fonnesbeck !

Currently I work more with Infer.NET (due to the platform) but I check out regularly what are you guys doing with PyMC3!

Cheers!

**Comment by fonnesbeck** [comment]
Thanks again @usptact

**Comment by junpenglao** [comment]
This is ready to merge right? @aseyboldt

**Comment by aseyboldt** [comment]
Now it is. I moved the long comment into a paragraph.

**Pull request merged**
