### PR TITLE
update references to py3.6

### PR DESCRIPTION
**Pull request by OriolAbril**
Couple of very minor updates after #3992

### CODE REVIEW

**Review by AlexAndorra — COMMENTED** [review]
Thanks @OriolAbril, LGTM 👌 
Travis seems to still test on py36 though 🤔 : "`ERROR: Package 'pymc3' requires a different Python: 3.6.10 not in '>=3.7'`"

**Comment by OriolAbril** [comment]
Oh, this is bad then, I though this was already taken care of, I'll look into it.

**Comment by OriolAbril** [comment]
This seems to be the issue: https://travis-ci.org/github/pymc-devs/pymc3/jobs/704960222#L271 which comes from https://github.com/pymc-devs/pymc3/blob/master/scripts/create_testenv.sh#L25, if someone wants to take over it will be welcome, otherwise I'll dive in whenever I have time.

**Comment by aseyboldt** [comment]
This seems to be because of the travis cache.
We don't really call the code that creates a new environment, but instead use a cached version of it. I'll delete the cache on travis, then we can try again.

**Review by AlexAndorra — APPROVED** [review]
All good now, thanks @OriolAbril and @aseyboldt ! Merging 🎉

**Comment by OriolAbril** [comment]
Thanks @aseyboldt!

**Pull request merged**
