### PR TITLE
WIP add distribution for Euler-Maruyama scheme for SDEs

### PR DESCRIPTION
**Pull request by maedoc**
First commit toward an SDE scheme, feedback welcome
- Where to put tests?
- How much to test?
- Any particular criteria for a demo notebook?

### CODE REVIEW

**Comment by twiecki** [comment]
Tests live here: https://github.com/pymc-devs/pymc3/tree/master/pymc3/tests We don't have tests for RandomWalk it seems so we can't place the bar too high. Anything to test it's working, perhaps a simple parameter recovery.

You can check out the tutorial on the stochastic random walk. It would be good to have it be instructive for people who are not familiar with it but want to learn.

**Comment by twiecki** [comment]
@maedoc I think we can merge this with a good example NB. Anything else you need help with?

**Comment by maedoc** [comment]
@twiecki on vacation right now, hence the lack of activity: I'll finish up once I'm back.

**Comment by twiecki** [comment]
Ah, no worries, enjoy your vaca!

**Comment by springcoil** [comment]
:+1: for this too. I studied this stuff in Grad school so I was glad to see it :)

**Comment by springcoil** [comment]
Any update on this @maedoc ?

**Comment by maedoc** [comment]
@springcoil no, I haven't had time to pick this back up, and I can't put a timeline on it right now. If you'd like to have a go, free free. 😄

**Comment by springcoil** [comment]
@twiecki All we need is an example NB for this I guess for this to merge - I think it's a fairly useful example to have. I might have some stuff from grad school on my harddrive somewhere.

**Comment by springcoil** [comment]
Can we merge this and add an example afterwards? What do you think @twiecki @maedoc

**Comment by twiecki** [comment]
That's probably fine.

**Comment by springcoil** [comment]
I was testing this today https://gist.github.com/springcoil/2b46700e4322339a475b86645c33ddc7 and got errors. Has anyone seen errors like this before?

**Pull request merged**
