### PR TITLE
Explode plots.py into separate directory

### PR DESCRIPTION
**Pull request by ColCarroll**
Followup to #1815.  I think there's a lot more tidying someone could do here, but this is a first step.  

I tried my best to only move functions around, but I think there are one or two places I made a small change.  This should not change any functionality.

### CODE REVIEW

**Comment by twiecki** [comment]
Why do you think it's better to break this out? Just less wieldy plots.py?

**Comment by ColCarroll** [comment]
Yeah - there are a lot of changes that are easier to reason about in smaller files.  I think the plots utilities had just outgrown a single file.

**Comment by twiecki** [comment]
I agree.

**Comment by fonnesbeck** [comment]
@ColCarroll I noticed that the bottom element of the `forestplot` is now getting overplotted on the x-axis. Could this have been due to this commit? Hadn't seen it previously.

**Comment by ColCarroll** [comment]
That is quite likely.  It should be line 260 in plots/forestplot.py, but
I'm away from my computer for a few days.

**Comment by fonnesbeck** [comment]
Wow. You know the line without having the code in front of you? Impressive.

**Comment by ferrine** [comment]
Setup script needs changes, doesn't it?

**Comment by ferrine** [comment]
Why we don't use `find_packages()`? Can anybody explain it to me? There is good documentation, it can fit our needs for sure.

**Comment by twiecki** [comment]
@ferrine Didn't you have a PR that implemented that? I had to revert it because it didn't work.

**Comment by twiecki** [comment]
https://github.com/pymc-devs/pymc3/commit/7a6bde3294c2c00117e835f1e698349dfcfe2b6a https://github.com/pymc-devs/pymc3/commit/893997f3d0bfb76f5c9a7d1eda447590a70e9b65

**Comment by ferrine** [comment]
Yes, I remember. I don't know why it didn't work. But it can fit our needs with a bit more efforts I think.

**Pull request merged**
