### PR TITLE
Fixed random() method of NegativeBinomial

### PR DESCRIPTION
**Pull request by Volodymyrk**
scale = 1/beta, where beta=alpha/mu

### CODE REVIEW

**Comment by Volodymyrk** [comment]
notebook to check NB distribution on simple synthetic data
[simple negative-binomial pymc3 fix.ipynb.zip](https://github.com/pymc-devs/pymc3/files/380260/simple.negative-binomial.pymc3.fix.ipynb.zip)

**Comment by fonnesbeck** [comment]
I would have thought `test_distributions_random` would have caught this if the scale was wrong.

**Comment by Volodymyrk** [comment]
I am not as familiar with the codebase, so definitely worth checking..
But I was struggling to figure out why I couldn't fit NB-based model, only to figure out that synthetic data produced by pymc3 was different from one produced by scipy.stats. And assuming naming is consistent, scale = 1/Beta

**Comment by twiecki** [comment]
Hm, yeah we should look into why the unittest didn't catch that. This is a valid fix nonetheless though.

**Comment by twiecki** [comment]
Thanks @Volodymyrk.

**Pull request merged**
