### PR TITLE
Add notebook with flows

### PR DESCRIPTION
**Pull request by ferrine**

### CODE REVIEW

**Comment by springcoil** [comment]
Looks great @ferrine - just a little nitpick, but it's `approximation` not `Appriximation` (the fifth cell)

**Comment by ferrine** [comment]
thanks

**Comment by twiecki** [comment]
@ferrine Can you add a title with `#` and make sure all sub-headings are at least `##`? Otherwise it will mess up the docs. Also, can you add this to `docs/sources/examples.rst`?

**Comment by ferrine** [comment]
Sure

**Pull request merged**
