### PR TITLE
add black formatter to pre-commit

### LINKED ISSUE #4109: Apply black formatter
xref https://github.com/pymc-devs/pymc3/pull/4108#issuecomment-694462527

Reviewing PRs which change code _and_ change formatting can be tricky, so my suggestion is to apply `black` to batches of 10-15 files at a time, merge those in, and then add `black` to `.pre-commit-config.yaml`.

This would make for a good beginner-friendly issue. Make sure you're using `black` version 20.8b1 for this.

See  #4110 for an example of how to open a PR for this

EDIT
----

have removed the list of files as it looks like existing PRs might be enough to close this off. Please see #4095 for a similar issue to tackle

EDIT2
----

As of 2020-10-08, existing PRs should be enough to address all files. To close this issue, a pre-commit hook should be added

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #4109 (!)

### CODE REVIEW

**Review by AlexAndorra — APPROVED** [review]
Awesome, thanks @MarcoGorelli !

**Comment by MarcoGorelli** [comment]
No worries! At this point the wiki should probably also have a "Python code style" section, seeing as this and `pyupgrade` are checked during CI...I'll put something together later

**Comment by AlexAndorra** [comment]
Ah right, good point 👌 Tell me when you've added the new section / updated the existing ones and I'll read it 😉

**Comment by MarcoGorelli** [comment]
> Ah right, good point ok_hand Tell me when you've added the new section / updated the existing ones and I'll read it wink

Sure, here's a first draft https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style

**Comment by AlexAndorra** [comment]
That's perfect, thanks @MarcoGorelli 👌 
Also, I think this means step 3 of the [NB style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style) can be merged with step 2 now, can't it?

**Comment by MarcoGorelli** [comment]
> That's perfect, thanks @MarcoGorelli ok_hand

Thanks!

> Also, I think this means step 3 of the [NB style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style) can be merged with step 2 now, can't it?

Not yet, no - currently `.pre-commit-config.yaml` has `black`, but not yet `nbqa-black`, there's still some notebooks left to clean up (else CI will always fail :smile: )

**Pull request merged**
