### PR TITLE
Fix typo in Notebook

### LINKED ISSUE #2069: Wrong module in getting started document
In http://pymc-devs.github.io/pymc3/notebooks/getting_started.html, it reads "Here is what the simulated data look like. We use the `pylab` module from the plotting library matplotlib."

I believe this should read 

"Here is what the simulated data look like. We use the `plt` module from the plotting library matplotlib."

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes #2069

### CODE REVIEW

**Comment by twiecki** [comment]
I could have sworn we fixed that already.

**Comment by ColCarroll** [comment]
Almost!
https://github.com/pymc-devs/pymc3/pull/2075

**Comment by twiecki** [comment]
Oh, right.

**Comment by bhargavvader** [comment]
Thanks for getting this @souravsingh !

**Pull request merged**
