### PR TITLE
Model comparison waic with standard error plot

### PR DESCRIPTION
**Pull request by aloctavodia**
I add a plot showing the WAIC estimates and its standard error (errorbar/forestplot-like plot). Maybe in the future I could add an improved version of this plot to the plots already available with PyMC3.

### CODE REVIEW

**Comment by aloctavodia** [comment]
Closes #1443

**Review by springcoil — CHANGES_REQUESTED** [review]
Could you add another warning for 0.7? I think being over 0.7 is also interesting information...

**Comment by aloctavodia** [comment]
Sorry about that. I fix it.

**Review by springcoil — APPROVED** [review]
LGTM

**Pull request merged**
