### PR TITLE
Renamed `model.recompute_initial_point` to `model.compute_initial_point` 

### PR DESCRIPTION
**Pull request by Vaibhav-Chopra-GT**
Closes #5360
+ [x] what are the (breaking) changes that this PR makes?

Renamed `model.recompute_initial_point` to `model.compute_initial_point` throughout the codebase.

+ [x] [linting/style checks have been run](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Python-Code-Style)
+ [ ] [consider adding/updating relevant example notebooks](https://github.com/pymc-devs/pymc-examples)
+ [ ] right before it's ready to merge, mention the PR in the RELEASE-NOTES.md

### CODE REVIEW

**Comment by canyon289** [comment]
Thanks for contribution! Ive approved CI run so you can see the checks

**Comment by Vaibhav-Chopra-GT** [comment]
Thanks @canyon289! Could you please approve them once more? I have fixed the failing tests now!

**Comment by canyon289** [comment]
Thank you for the contribution and fixing tests! Can you add a release note as well?

 Are you planning on updating the notebooks? No obligation just keeping track of things.

**Review by michaelosthege — APPROVED** [review]
Looking good. We don't need a release notes entry, because the entire method is new in `v4`.

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @Vaibhav-Chopra-GT!

**Comment by Vaibhav-Chopra-GT** [comment]
Thanks for merging! I do plan on updating the example notebooks!

**Pull request merged**
