### PR TITLE
Bump aesara to 2.7.8.

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by twiecki** [comment]
Blocked by #6002.

**Comment by michaelosthege** [comment]
> Blocked by #6002.

I don't think so. The `pre-commit` job succeeds, so there are no regressions in terms of which PyMC source files pass the type checks.

That being said, it's still a valuable contribution to fix the type errors one by one.

**Comment by twiecki** [comment]
@michaelosthege I pushed the change that breaks pre-commit: `1 files unexpectedly failed:
pymc/util.py`

**Comment by canyon289** [comment]
Tagging myself so I get notified of status updates. Very excited for this @canyon289

**Comment by canyon289** [comment]
@michaelosthege what do you think of just updating the mypy ignores and merging this? All other tests are passing and this is blocking inclusion of PyMC in colab which would be a big unlock for aesara, aeppl, and pymc

**Comment by twiecki** [comment]
I ignored `utils.py` for now.

**Review by michaelosthege — CHANGES_REQUESTED** [review]
@canyon289 @twiecki it is literally **a single error** in `utils.py`.
Instead of ignoring `utils.py` please just fix this one error!
```
pymc/util.py:241: error: Key expression in dictionary comprehension has incompatible type "Hashable"; expected type "str"
```

The whole purpose of having this pre-commit type check is to safeguard against regressions. Adding files to the ignore-list just because of a single line remoevs the safeguard for these files.

**Comment by twiecki** [comment]
@michaelosthege Unfortunately I don't know anything about types, do you know how to fix it?

**Comment by michaelosthege** [comment]
The problem that mypy is making us aware of is that `xarray.Dataset` keys are not always a `str`:

image

I'm opening a PR into this branch..

**Review by michaelosthege — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks for the help @michaelosthege!

**Comment by canyon289** [comment]
Thank you!

**Pull request merged**
