### PR TITLE
Update Aesara version and unpin numpy

### LINKED ISSUE #5321: Upgrade Aesara and NumPy upper version limits
Aesara is currently pinned and can't be updated to the latest version until https://github.com/aesara-devs/aesara/issues/707 is fixed.

That means we also don't get the NumPy 1.22 compatibility fix until we can upgrade.

Until that Aesara upgrade we'll want to pin  `numpy<1.22.0` and keep this issue open until we can upgrade Aesara *and* remove the NumPy version pin.

*For stability, we should still pin Aesara at the minor, or even the patch version.*

### PR DESCRIPTION
**Pull request by twiecki**
Closes https://github.com/pymc-devs/pymc/issues/5321.
Reverts temporary https://github.com/pymc-devs/pymc/pull/5332.

### CODE REVIEW

**Comment by ricardoV94** [comment]
Any idea what's wrong with the conda setup?

**Comment by twiecki** [comment]
I think I was just too fast before conda-forge had aesara packages up.

**Comment by twiecki** [comment]
```
pymc/tests/test_distributions.py:1943: 
519
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
520
pymc/tests/test_distributions.py:705: in check_logp
521
    model, param_vars = build_model(pymc_dist, domain, paramdomains, extra_args)
522
pymc/tests/test_distributions.py:282: in build_model
523
    distfam(
524
pymc/distributions/distribution.py:255: in __new__
525
    rv_out, dims, observed, resize_shape = _make_rv_and_resize_shape(
526
pymc/distributions/distribution.py:154: in _make_rv_and_resize_shape
527
    rv_out = cls.dist(*args, **kwargs)
528
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
529

530
cls = <class 'pymc.distributions.multivariate.MatrixNormal'>, mu = mu
531
rowcov = rowcov, rowchol = None, colcov = colcov, colchol = None, args = ()
532
kwargs = {'rng': RandomStateSharedVariable(<RandomState(MT19937) at 0x7FEA3124F340>)}
533
cholesky = <aesara.tensor.slinalg.Cholesky object at 0x7fea305062e0>
534
rowchol_cov = Cholesky{lower=True, destructive=False, on_error='raise'}.0
535
colchol_cov = Cholesky{lower=True, destructive=False, on_error='raise'}.0
536
dist_shape = (Subtensor{int64}.0, Subtensor{int64}.0)
537

538
    @classmethod
539
    def dist(
540
        cls,
541
        mu,
542
        rowcov=None,
543
        rowchol=None,
544
        colcov=None,
545
        colchol=None,
546
        *args,
547
        **kwargs,
548
    ):
549
    
550
        cholesky = Cholesky(lower=True, on_error="raise")
551
    
552
        if kwargs.get("size", None) is not None:
553
            raise NotImplementedError("MatrixNormal doesn't support size argument")
554
    
555
        if "shape" in kwargs:
556
            kwargs.pop("shape")
557
            warnings.warn(
558
                "The shape argument in MatrixNormal is deprecated and will be ignored."
559
                "MatrixNormal automatically derives the shape"
560
                "from row and column matrix dimensions.",
561
                FutureWarning,
562
            )
563
    
564
        # Among-row matrices
565
        if len([i for i in [rowcov, rowchol] if i is not None]) != 1:
566
            raise ValueError(
567
                "Incompatible parameterization. Specify exactly one of rowcov, or rowchol."
568
            )
569
        if rowcov is not None:
570
            if rowcov.ndim != 2:
571
                raise ValueError("rowcov must be two dimensional.")
572
            rowchol_cov = cholesky(rowcov)
573
        else:
574
            if rowchol.ndim != 2:
575
                raise ValueError("rowchol must be two dimensional.")
576
            rowchol_cov = at.as_tensor_variable(rowchol)
577
    
578
        # Among-column matrices
579
        if len([i for i in [colcov, colchol] if i is not None]) != 1:
580
            raise ValueError(
581
                "Incompatible parameterization. Specify exactly one of colcov, or colchol."
582
            )
583
        if colcov is not None:
584
            colcov = at.as_tensor_variable(colcov)
585
            if colcov.ndim != 2:
586
                raise ValueError("colcov must be two dimensional.")
587
            colchol_cov = cholesky(colcov)
588
        else:
589
            if colchol.ndim != 2:
590
                raise ValueError("colchol must be two dimensional.")
591
            colchol_cov = at.as_tensor_variable(colchol)
592
    
593
        dist_shape = (rowchol_cov.shape[0], colchol_cov.shape[0])
594
    
595
        # Broadcasting mu
596
>       mu = at.extra_ops.broadcast_to(a=mu, shape=dist_shape)
597
E       TypeError: broadcast_to() got an unexpected keyword argument 'a'
598

599
pymc/distributions/multivariate.py:1745: TypeError
```

**Comment by twiecki** [comment]
```
pymc/tests/test_ode.py::TestDiffEqModel::test_op_equality PASSED         [ 44%]
896
/home/runner/work/_temp/25769632-011a-4256-95b2-edae057d3830.sh: line 2:  7587 Killed                  python -m pytest -vv --cov=pymc --cov-append --cov-report=xml --cov-report term --durations=50 $TEST_SUBSET
897
pymc/tests/test_ode.py::TestDiffEqModel::test_scalar_ode_1_param 
```

**Comment by twiecki** [comment]
Not sure why this stalls out, it passes locally. Any idea @ricardoV94 @michaelosthege ?

**Comment by ricardoV94** [comment]
> Not sure why this stalls out, it passes locally. Any idea @ricardoV94 @michaelosthege ?

Are you testing with the latest Aesara? It fails locally for me. I think I know where the problem is...

**Comment by twiecki** [comment]
Alright, I wasn't. What's the problem?

**Comment by ricardoV94** [comment]
> Alright, I wasn't. What's the problem?

Still trying to pin it down. Those ODE Ops are super hackish xD

**Comment by ricardoV94** [comment]
I think there is a broken cyclical optimization on the Aesara side

**Comment by ricardoV94** [comment]
Yup, found it.

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
