### PR TITLE
Update Aesara dependency

### PR DESCRIPTION
**Pull request by michaelosthege**
Another update to Aesara and aeppl.

I believe @aseyboldt and @ricardoV94 can add commits to fix the CI ?

## Major / Breaking Changes
- None

## Bugfixes / New features
- None

## Docs / Maintenance
- Updated to Aesara 2.8.8

### CODE REVIEW

**Comment by ricardoV94** [comment]
No point in updating Aeppl dependency given #6334

**Comment by michaelosthege** [comment]
> No point in updating Aeppl dependency given #6334

I didn't know if there were going to be incompatibilities and updated just in case.

Do you have commits ready to cherry pick onto this branch to fix the CI ?

**Comment by ricardoV94** [comment]
> > No point in updating Aeppl dependency given #6334
> 
> I didn't know if there were going to be incompatibilities and updated just in case.
> 
> Do you have commits ready to cherry pick onto this branch to fix the CI ?

I am not sure I follow. I will push the fixes for that other PR and after that there is no Aeppl dependency anymore. So no point in updating it. Or were you asking something else?

**Comment by michaelosthege** [comment]
I'm asking about the Aesara-induced failures here. You mentioned that there exists a branch with fixes?

**Comment by ricardoV94** [comment]
Ah. One of the failures is addressed here: https://github.com/pymc-devs/pymc/pull/6306

I'll have a look tomorrow

**Comment by michaelosthege** [comment]
I rebased onto the branch from #6334 to see if there will be more ToDos.

**Comment by michaelosthege** [comment]
@aseyboldt unless I missed something, all remaining failures have something to do with unnamed variables and `SpecifyShape`. Is this related to your changes?

**Review by michaelosthege — COMMENTED** [review]
LGTM

**Comment by aseyboldt** [comment]
Sorry, just saw this, but that commit was the one :-)
LGTM

**Comment by ricardoV94** [comment]
Just one sec, cleaning a bit the `create_value_var`...

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
