### PR TITLE
Added a benchmark for marginalized mixture model distributions

### PR DESCRIPTION
**Pull request by springcoil**
I added based on comments in #2638 a Marginalized mixture model. 

Let me know if i broke anything.

### CODE REVIEW

**Comment by ColCarroll** [comment]
Sorry I just got to looking at this -- it looks great, and glad to test more model types.  I think it might be more useful to do most of our testing around effective samples per second.  See https://github.com/pymc-devs/pymc3/pull/2647 for how to do this -- mostly: 

- change the method name to `track_foo` instead of `time_foo`, 
- add your own timer around the call to `sample`
- return effective samples per second

**Comment by springcoil** [comment]
@ColCarroll Let me know what you think of this. I made changes based on your advice. Do I need to wait for #2647 to merge first?

**Comment by ColCarroll** [comment]
Needs to fix a merge conflict now, but other than that, good to go!

**Comment by springcoil** [comment]
The merge conflict seems fixed - so I'll merge this :)

**Pull request merged**
