### PR TITLE
shape problem when sampling

### PR DESCRIPTION
**Pull request by ferrine**
When constructing neural networks I met a problem that when I generate samples for initial values I get unexpected shape for tensor.

For example for random variable with shape (1, 1) (needed for matmul) yields a sample (1,). In general all samples seem to be [squeesed](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.squeeze.html#numpy-squeeze), I do not know how to hotfix it.

I've added a test suite to reproduce the problem

### CODE REVIEW

**Comment by twiecki** [comment]
So this is implementing a failing test to highlight the problem?

**Comment by ferrine** [comment]
Not only, I also want some discussion about the solution because 28 failing tests is not what I expected.

Suppose we have a dist with shape `a` and we want samples with size `b`. Shape or size can be represented as a tuple, e.g. `(,)` - scalar, `(1,)` 1d vector with one element and so on.
Am I right to expect shape like `tuple(list(b) + list(a))`?

**Comment by twiecki** [comment]
Yes, that's what I would expect. This is all about the random sampling PPC code, right?

**Comment by ferrine** [comment]
It was about instance method of random variable - `random`.

**Comment by ferrine** [comment]
BTW, bug is fixed and I can merge. Do you see any problem in the proposed solution?

**Comment by twiecki** [comment]
I think this looks good!

**Comment by twiecki** [comment]
should we merge this into 3.1?

**Comment by ferrine** [comment]
I also wanted to tidy up the code (see [commit](https://github.com/ferrine/pymc3/commit/b0b1803eb1a9842af5c8c602e793df72da0b6735)) after fix. So 3.1 will be better for that purpose.

**Comment by twiecki** [comment]
:+1:

**Pull request merged**
