### PR TITLE
kde plot added kwargs

### PR DESCRIPTION
**Pull request by hvasbath**

### CODE REVIEW

**Review by ColCarroll — COMMENTED** [review]
Looks good to me, but `cmap=None` can turn into a kwarg.

**Review by ColCarroll — APPROVED** [review]
LGTM -- I _think_ setting `extent` in `kde2plot_op` is funny.  That is, I think (but haven't checked) it is being set to be what it would be anyways, and it will definitely throw a `TypeError` if a user tries to pass `extent` kwargs.  I also think that that's an edge case if you'd rather not fix it now, and you might just add an issue to fix later.

**Comment by hvasbath** [comment]
Yeah I was not so sure about it, as it was initially coded by someone else, maybe that developer had something in mind...?

**Comment by ColCarroll** [comment]
Yeah, and it is helpful to keep commits small-ish.  I opened #1507 to double check this (I can after work, unless you want to get to it first).  I could imagine setting it is non-trivial (there's some `ravel`ing going on), but there should at least be a manual override.

**Pull request merged**
