### PR TITLE
make HalfStudenT parameters consistent with those from StudentTdistribution

### PR DESCRIPTION
**Pull request by aloctavodia**
Introduce changes following discussion in #2666

### CODE REVIEW

**Comment by fonnesbeck** [comment]
We ought to deprecate `beta` rather than just remove it, as this will cause breakage. You can check for it in the `kwargs` and use it, if present (with a warning).

**Comment by aloctavodia** [comment]
I think we don't need the deprecation warning. I recently introduce the beta parameter in #2666, so this should fix the breakages.

**Comment by fonnesbeck** [comment]
That's fair enough. As long as it was introduced after the 3.2 release it should not be a problem.

**Comment by aloctavodia** [comment]
That`s right, the change has less than 2 weeks.

**Pull request merged**
