### PR TITLE
Update pr_tutorial.md

### PR DESCRIPTION
**Pull request by juanitorduz**
Make the python version consistent on the PR tutorial, which seems to be `py38`.

### CODE REVIEW

**Comment by canyon289** [comment]
I hesitate to change this to be a version number down. Where is the other source that is at 3.8? Can that be upversioned?

**Comment by canyon289** [comment]
Apologies closed by accident but question remains

**Comment by juanitorduz** [comment]
Sorry for the lack of description. The conflict IMO is with line 48 (see below), where the python version is 3.8

image

**Comment by canyon289** [comment]
Ah great catch. lets change the ones below then to go to python 3.9. What would that take?

**Comment by juanitorduz** [comment]
Suggested change added in https://github.com/pymc-devs/pymc/pull/5724/commits/9f5f7fc03a8f0f2c68a1faeec347e6b9394b98f6 :)

**Review by twiecki — APPROVED** [review]

**Pull request merged**
