### PR TITLE
raise an error when model has discrete vars

### PR DESCRIPTION
**Pull request by ferrine**
Following #2907, now raising an error with informative message when model has discrete variables

### CODE REVIEW

**Comment by twiecki** [comment]
```
==================================== ERRORS ====================================
__________ ERROR collecting pymc3/tests/test_variational_inference.py __________
../../../miniconda2/lib/python2.7/site-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../miniconda2/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/travis/build/pymc-devs/pymc3/pymc3/tests/test_variational_inference.py", line 844
E   SyntaxError: Non-ASCII character '\xce' in file /home/travis/build/pymc-devs/pymc3/pymc3/tests/test_variational_inference.py on line 844, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by ColCarroll** [comment]
Thanks!

**Comment by ferrine** [comment]
Do you think we need a release note for this?

**Comment by fonnesbeck** [comment]
I don't think its critical, no.

**Pull request merged**
