### PR TITLE
forestplot: support multiple traces

### PR DESCRIPTION
**Pull request by aloctavodia**
Sometimes is useful to visually compare the results/posterior for different models. One option to achieve this task is to make a forestplot for all variables in all models. This PR modifies `forestplot` to support either a trace or a list of traces, a new keyword `models` can be used to pass the names of the models

This is an example of a forestplot for several models:
multi_forestplot
 
model `m0` does not have a beta parameter, contrary to models `m1` and `m2`. Additionally, the beta parameter for  `m2`has `shape=2`.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
It would be cool to do something to make the models stand out, such as colorize the labels by model. Conversely, I wonder if you could create shading bands to isolate the same parameters.

**Comment by aloctavodia** [comment]
I agree, the plot is too _flat_. I will try to do something to make the models stand out... maybe a color per-model and also the "shading-bands"

**Comment by aloctavodia** [comment]
Shading bands are used to help visualize groups of parameters (only when more than one trace is passed).

multi_forestplot_cb_00

Additionally, by setting `colors='cycle'`, we get a different color per model

multi_forestplot_cb_01

Previous plots were done with the style I generally use, i.e. `plt.style.use(['seaborn-colorblind', 'seaborn-darkgrid'])`. This is how the first plot looks with the default matplotlib style.

multi_forestplot_default

**Comment by junpenglao** [comment]
WOW this is really nice!

**Comment by fonnesbeck** [comment]
Yeah, that's exactly what I had in mind. Nice work.

**Comment by aloctavodia** [comment]
Should I also add this to the release-notes?

**Comment by aloctavodia** [comment]
Is this ready to _squash and merge_ or maybe more work is needed?

**Comment by junpenglao** [comment]
This is really a nitpick but is it possible to adjust the shadow to more in the middle between two errorbars?

**Comment by aloctavodia** [comment]
No nitpicking at all @junpenglao! This is how it looks with your suggestion.
multi_forestplot_default

**Comment by junpenglao** [comment]
Thanks @aloctavodia !

**Pull request merged**
