### PR TITLE
Fix examples in docs of mixture.py, bound.py and continuous.py 

### LINKED ISSUE #2806: Example code in Mixture docs does not display correctly
http://docs.pymc.io/api/distributions/mixture.html
PR: https://github.com/pymc-devs/pymc3/pull/2799
cc @ericmjl

### PR DESCRIPTION
**Pull request by sharanry**
Fixes #2806

### CODE REVIEW

**Comment by ColCarroll** [comment]
You need a single blank line after `.. code-block:: python` (I have been mucking around with rst a lot).

**Comment by ColCarroll** [comment]
Looks good to me (travis doesn't build docs on PRs) – will merge later today. If you get a chance, you might build the docs locally:
```
$ cd pymc3 && git checkout mixtureDocs
$ pip install -r requirements.txt
$ pip install -r requirements-dev.txt
$ cd docs/source
$ make html
$ open _build/html/api/distributions/continuous.html
```
Then post a screenshot if it looks ok?

**Comment by sharanry** [comment]
@ColCarroll Looks like it is okay.
pymc31
pymc32

**Comment by ColCarroll** [comment]
Thanks, @sharanry !

**Pull request merged**
