### PR TITLE
WIP: Convert zero-inflated distributions to Mixture subclasses

### PR DESCRIPTION
**Pull request by fonnesbeck**
Replaces #2231, which I messed up.

### CODE REVIEW

**Comment by AustinRochford** [comment]
The `test_scalar_shape` errors would seem to be due to the use of `size` [here](https://github.com/pymc-devs/pymc3/blob/6b038a995533751872c9a1de733a7d5cd5112e2e/pymc3/distributions/mixture.py#L141).

**Comment by AustinRochford** [comment]
I will continue working through the other sampling errors when I get the chance this week; the `nan` for the total probability of `ZeroInflatedBinomial` is still puzzling to me.

**Comment by AustinRochford** [comment]
I will continue working through the other sampling errors when I get the chance this week; the `nan` for the total probability of `ZeroInflatedBinomial` is still puzzling to me.

**Comment by fonnesbeck** [comment]
If it doesnt work out we can always pull the plug and go back to the zero-inflated subclasses of `Discrete`. Less elegant, but they passed the tests with flying colors.

**Comment by AustinRochford** [comment]
@fonnesbeck yes, I was thinking that it makes sense to put ZIB in the old way.  I understand the problem now and think I can refactor `Mixture` to make it easier to change in the future, but it will take a while

**Comment by fonnesbeck** [comment]
OK, I will change this to a WIP and create a PR with the working zero-inflated classes. We can target this for post-3.1.

**Comment by twiecki** [comment]
Closing because of age. Feel free to reopen if you want to fix this up.

**Pull request closed without merging**
