### PR TITLE
black codestyle

### PR DESCRIPTION
**Pull request by ferrine**
With this tool code looks much prettier. This is the first preview commit, we should integrate this with CI if it is all good

### CODE REVIEW

**Comment by ferrine** [comment]
I have concerns about that as some PRs are in progress and will be affected by changes.

**Comment by twiecki** [comment]
I agree that this looks much better. Seemed like you used an older commit, however.

I think this could be a good time for this, I don't think there are many active WIP commits, mainly #3214

**Comment by ferrine** [comment]
Yes, things changed in a week and I did not `git pull`. Any more opinions?

**Comment by ferrine** [comment]
I got issues with rebase and just recreated the branch, I suppose same issues will be with ongoing PRs

**Comment by ferrine** [comment]
We can wait until #3214 and then do the refactoring not to make a mess. Another option is trying to rebase it on top of this branch to check if it can be done with little pain

**Comment by canyon289** [comment]
Copy paste from slack

Black is used in ArviZ

Its mostly good, but when its bad, I think its pretty bad
it is consistent though

**Comment by springcoil** [comment]
How does one use this?

**Comment by fonnesbeck** [comment]
It does look better on the whole. I don't think we need to enforce this every time someone commits code, but perhaps run it prior to releases?

**Comment by ColCarroll** [comment]
It is pretty quick as a first check on CI: we run 
```
python -m black -l 100 --check arviz/
```
which takes 0.1s on my machine. Running on PyMC3, it takes 7s, but it is finding actual errors. To change the code, you leave out the `--check` flag.

I find the biggest benefit for a project is fewer nitpicking formatting requests - within seconds of making a PR, you're reminded to run black on your own code and resubmit. The biggest benefit for me is that most editors (vim or VS code) will run it automatically on save, and I'm not even thinking about line length or making shorter variable names.

Note that it does not replace pylint or pydocstyle, but it conforms to both.

**Comment by ferrine** [comment]
As I remember pycodestyle is less restrictive and thus less consistent

Oh, misread, pydocstyle?

**Comment by canyon289** [comment]
> It is pretty quick as a first check on CI: we run
> 
> ```
> python -m black -l 100 --check arviz/
> ```

> 
> Note that it does not replace pylint or pydocstyle, but it conforms to both.

You can also just run `black --check arviz/` and it'll automatically pick up 100 line length from a settings file, and black has a bash entry point. Exactly the same as above, just save some keystrokes

**Comment by canyon289** [comment]
> As I remember pycodestyle is less restrictive and thus less consistent
> 
> Oh, misread, pydocstyle?

pydocstyle checks to make sure docs are in correct format which black doesn't do.
pylint checks for unused imports, or variables, which is useful as well.

All three work well together!

**Comment by aseyboldt** [comment]
I don't think I really like this idea. This touches most of the code in pymc3, so a simple `git blame` will never show much useful information after we merge this. I agree that the formatting looks nice (mostly, sometimes I prefer the original), but in my opinion it really isn't worth it. If we write new code, by all means use black, same if we mostly rewrite a file. But touching everything just to make it look a bit more pretty seems a bit extreme to me.

**Comment by twiecki** [comment]
As always, @aseyboldt makes a pretty compelling case and from the likes on his comment it seems like there is critical mass in agreement, so I'm closing this.

**Comment by ferrine** [comment]
Yes, that was a very fair point

**Pull request closed without merging**
